### ISSUE TITLE
Russian(?) text in character creation after installing RPU

### ISSUE THREAD

**Issue by Taberone** [BGforgeNet/Fallout2_Restoration_Project#10]
![image](https://user-images.githubusercontent.com/9733597/62437547-87eb4c00-b6f8-11e9-8343-0eab56eda78d.png)

Clean install. Restoration Project installed first, then RPU. I do not think this is intended to appear in the main menu, especially since I'm on the English version. 

![image](https://user-images.githubusercontent.com/9733597/62437587-b23d0980-b6f8-11e9-85f4-d2dc1b891618.png)

Using "rpu_v6.zip" from Releases.

**Comment by burner1024** [comment]
You're right, one more packaging artefact (hard to extract the components separately from the 2.3.3 installer). Fixed now.
