### ISSUE TITLE
Loading a save in Den Residential

### ISSUE THREAD

**Issue by dlpnd** [BGforgeNet/Fallout2_Restoration_Project#100]
### What happened
Saving a game in Den Residential (During a fight with Laura and the Metzgers guards that are having a party in Den Residential)
And then attempting to load it, the game freezes.

In the save attached, tell Laura that you are ready, you will be teleported to Den Residential, attempt to save, and then load, the game will crash.

### What you expected to happen
The game should load

### Screenshot
N/A

### Savegame
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6379267/SLOT04.zip)

**Comment by burner1024** [comment]
Right, freezes with 
```
LOADSAVE: ** Error reading load function #11 data! **
LOADSAVE: Load function #11 data size read: 28 bytes.
```
It's an engine thing. I think it was supposed to be fixed for a while now, but apparently not in all cases.

@NovaRain @FakelsHub please take a look.

**Comment by FakelsHub** [comment]
Кажется это проблема скриптов этой все банды.
Вычищайте лог от любых Error'ов на этой карте, тогда можно будет разбираться если не поможет правка скриптов.

**Comment by FakelsHub** [comment]
Особое подозрение вызывает вот это **Error: attempt to Create critter in load/save-game: scripts\dcdealer.int!**
Если будешь чинить скрипты используй версию 4.1.6  для того чтобы не было мертвого подвисания игры.

**Comment by burner1024** [comment]
Почистил ошибки, бесполезно.
Да и по идее в любом случае крэш или зависание это проблема движка. Если функция в каком-то режиме это вызывает, то еще надо чинить или на крайний случай вообще запретить ее вызов в этом режиме.

> используй версию 4.1.6

А эта вообще не может загрузить сохранения: `LOADSAVE: ** Error reading load function #3 data! **`

**Comment by FakelsHub** [comment]
> (edit: если сделать "clear combat info" через F12SE, то грузится.)

да, там какая-то хрень с построением боевого списка, функция движка не может найти какого-то криттера/ров на карте, и поэтому происходит ошибка.
я еще думал как пропустить этот кусок данных. а тут уже есть решение.

> А эта вообще не может загрузить сохранения:

у меня грузила, но не зависало, табличку показывало что "не может загрузить сохранение".

**Comment by FakelsHub** [comment]
Сделал "clear combat info" и как предполагал до этого на карте нет NPC(банды дилера) которые должны быть в бою, в общем скриптовая проблема.

**Comment by burner1024** [comment]
А их и не было наверное. Они вроде при первом посещении появляются.

Сделал другой тест. Не стал говорить с Ларой. Просто прошел ногами в ту же зону. Сохранился. Эта новая сохраненка загружается при первом запуске игры нормально. А при попытке повторной загрузки (без перезапуска игры), - крэшит.

**Comment by FakelsHub** [comment]
Я так понимаю что это в RP добавленная лока? И это так наскриптили что это крашится теперь.

**Comment by FakelsHub** [comment]
Я там тесты на карте поделал эти нпс почемуто встали в состояние невидимости и переместились на второй уровень карты. Сделать их видимыми нельзя.
Шото глюкануло там конкретно что не разбаться.

**Comment by burner1024** [comment]
Уровень по идее у них всегда должен быть текущий, т.е. они следуют за игроком. А насчет невидимости неясно, вроде ничего такого в скрипте у них нет.

Вот дамп вылета, на всякий случай:
![Captura de pantalla de 2021-05-03 23-37-27](https://user-images.githubusercontent.com/1279852/116905270-f44a0500-ac68-11eb-9e75-6bdd86597e54.png)

```
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x01124597).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:01124597 ESP:0031fbe0 EBP:0031fc28 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000000 EBX:00010054 ECX:00000012 EDX:0031fc04
 ESI:0031fd14 EDI:00000000
Stack dump:
0x0031fbe0:  0031fc04 0031fc00 0031fc08 00000000
0x0031fbf0:  0031fd14 00000c0a 0031fc14 6edab70c
0x0031fc00:  00000000 00000000 00000000 021473a8
0x0031fc10:  0031fd14 00000000 00008000 00010054
0x0031fc20:  0031fd14 80000012 00008000 6edabdc7
0x0031fc30:  01124540 00010054 00008000 00000000
Backtrace:
=>0 0x01124597 EntryPoint+0xffffffff() in ddraw (0x0031fc28)
  1 0x6edabdc7 EntryPoint+0xffffffff() in user32 (0x00008000)
  2 0x6edae3f3 EntryPoint+0xffffffff() in user32 (0x6edb6e68)
  3 0x6ed69c41 EntryPoint+0xffffffff() in user32 (0x0031fd88)
0x01124597 EntryPoint+0xffffffff in ddraw: movl	0x0(%eax),%ecx
Modules:
Module	Address			Debug info	Name (48 modules)
PE	  400000-  6f0000	Export          fallout2
PE	  6f0000-  b74000	Deferred        ole32
PE	 10e0000- 11c8000	Export          ddraw
PE	 11d0000- 1437000	Deferred        d3dx9_31
PE	 1440000- 1688000	Deferred        msvcrt
PE	 22d0000- 2752000	Deferred        comctl32
PE	 2e70000- 2ef4000	Deferred        mmdevapi
PE	 3770000- 3793000	Deferred        msacm32
PE	 3a50000- 3e04000	Deferred        quartz
PE	 4030000- 40d2000	Deferred        devenum
PE	10000000-10077000	Deferred        f2_res
PE	61740000-61828000	Deferred        advapi32
PE	62b80000-62b8c000	Deferred        api-ms-win-core-localization-l1-2-1
PE	62fc0000-631f2000	Deferred        rpcrt4
PE	63480000-6349c000	Deferred        version
PE	63bc0000-63c02000	Deferred        shcore
PE	64a40000-64b5e000	Deferred        shlwapi
PE	64ec0000-652a7000	Deferred        oleaut32
PE	65bc0000-65bda000	Deferred        midimap
PE	67840000-6784e000	Deferred        psapi
PE	67c80000-67de9000	Deferred        d3d9
PE	682c0000-6844c000	Deferred        dsound
PE	68500000-6864b000	Deferred        combase
PE	68700000-6878e000	Deferred        uxtheme
PE	6a040000-6a0a3000	Deferred        msacm32
PE	6a400000-6a571000	Deferred        winmm
PE	6ac80000-6ac8b000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6bb00000-6bb6b000	Deferred        msvfw32
PE	6bc00000-6bca1000	Deferred        sechost
PE	6bcc0000-6be9c000	Deferred        setupapi
PE	6c0c0000-6c10d000	Deferred        msdmo
PE	6c9c0000-6cf41000	Deferred        gdi32
PE	6de80000-6de8c000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6ed00000-6f392000	Dwarf           user32
PE	70b40000-70df2000	Deferred        ucrtbase
PE	71200000-71248000	Deferred        imm32
PE	73350000-73354000	Deferred        winegstreamer
PE	7a840000-7a844000	Deferred        opengl32
PE	7b000000-7b30c000	Deferred        kernelbase
PE	7b3b0000-7b3b3000	Deferred        winepulse
PE	7b600000-7b928000	Deferred        kernel32
PE	7bc00000-7bedf000	Deferred        ntdll
PE	7c0b0000-7c0bb000	Deferred        dinput
PE	7c5a0000-7c5a3000	Deferred        winealsa
PE	7c5e0000-7c5e3000	Deferred        avicap32
PE	7c630000-7cf07000	Deferred        shell32
PE	7e2a0000-7e2a4000	Deferred        winex11
PE	7e390000-7e394000	Deferred        wined3d
Threads:
process  tid      prio (all id:s are in hex)
00000020 (D) C:\games\fallout2\fallout2.exe
	00000024    0 <==
	00000104    0
	00000108   15
	0000010c    0
	00000110   15
	0000011c    0
	00000120    0
	00000124    0
	00000128    0
	0000012c    0
	00000130    0
	00000134    0
	00000150    0
	00000154    0
	00000160    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000005c    0
	00000074    0
	0000008c    0
	000000b4    0
	000000e0    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	00000060    0
00000064 explorer.exe
	00000068    0
	000000c0    0
	000000cc    0
	000000d0    0
0000006c plugplay.exe
	00000070    0
	00000078    0
	0000007c    0
	00000080    0
	0000009c    0
00000084 winedevice.exe
	00000088    0
	00000090    0
	00000094    0
	00000098    0
	000000a4    0
	000000a8    0
000000ac svchost.exe
	000000b0    0
	000000b8    0
	000000bc    0
000000c4 conhost.exe
	000000c8    0
000000d8 rpcss.exe
	000000dc    0
	000000e8    0
	000000ec    0
	000000f0    0
	000000f4    0
	000000f8    0
System information:
    Wine build: wine-6.0
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.8.0-50-generic

```

**Comment by FakelsHub** [comment]
У меня нет никакого крэша.

**Comment by burner1024** [comment]
Как тестируешь?

**Comment by FakelsHub** [comment]
Пешком пришел, сохранил, загрузил, загрузил, загрузил и т.д.

**Comment by FakelsHub** [comment]
Set to 1 to enable the mood argument of start_gdialog script function to be available for talking heads
;Set to 1 to enable the mood argument of start_gdialog script function for talking heads

> Почистил ошибки, бесполезно.
> Если функция в каком-то режиме такое вызывает, то ее надо чинить или на крайний случай вообще запретить ее вызов в этом режиме.

Ну то проблема скриптов отсутствует функция game_is_loading (точно не помню как она пишется) в map_enter_

**Comment by burner1024** [comment]
@dlpnd could you try not talking to Lara, just walk to residential, then save, load that save, and load it again?

**Comment by dlpnd** [comment]
@burner1024 

I have:

1. Loaded Save in Slot 4
2. Walked to Residential
3. Manually Saved
4. Loaded
5. Loaded Again

No crash

**Comment by FakelsHub** [comment]
Я и на оригинале проверял.

Он писал о каком-то crash'e которого теперь нет?)

**Comment by burner1024** [comment]
У него тоже не вопроизводится. Почему-то только у меня вылет при второй загрузке.

**Comment by burner1024** [comment]
I'm out of my depth here. Opened an issue in sfall repo. Don't know what else to do.
