### ISSUE TITLE
add torrent link

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Restoration_Project#101]
Github releases are slow to download, see if we can publish to torrent as well and add magnet links. Probably there should be a GH action for that?

**Comment by egornovivan** [comment]
Can easier to make a gdisk mirror?

**Comment by Felipefpl** [comment]
> Github releases are slow to download, see if we can publish to torrent as well and add magnet links. Probably there should be a GH action for that?

Not a bad idea although i'd rather see google drive/megaupload links for that.

**Comment by burner1024** [comment]
I don't see a scenario in which gdrive would be better than github. (Not to mention it requires a google account, which is in turn subject to limits, etc)
Torrent, on the other hand, is all around better. Although unfortunately, I don't see a gh action for that.

**Comment by Felipefpl** [comment]
> I don't see a scenario in which gdrive would be better than github. (Not to mention it requires a google account, which is in turn subject to limits, etc)

indeed there may be limits but the advantage is the download speed that is most of times HIGH. :)

**Comment by burner1024** [comment]
Ah... too lazy now. Maybe later.
