### ISSUE TITLE
Sierra Army Depot Crash

### ISSUE THREAD

**Issue by ACiDxCHRiST** [BGforgeNet/Fallout2_Restoration_Project#103]
### What happened
Move 1 square southwest or step on elevator to the west and go to level 2 and the game crashes

### What you expected to happen
Not crash

### Screenshot
![Sierra Army Depot Crash](https://user-images.githubusercontent.com/32944637/120906633-b56ced80-c620-11eb-99e3-5630b0ffdf17.jpg)

### Savegame
[SLOT108.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6603303/SLOT108.zip)

### Mods
RPU v20
fo2tweaks v12.5
InventoryFilter v2.0.0

**Comment by burner1024** [comment]
Huh, you got to Sierra so fast? v20 was just released.
I can reproduce the crash, but it's not immediately obvious what't the issue. It does work for me with sfall 4.2.9 as opposed to 4.3. For the time being, you can use that.
@FakelsHub @NovaRain any idea?

**Comment by ACiDxCHRiST** [comment]
[SLOT109.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6603375/SLOT109.zip)

Here is another savegame at the same point that does NOT crash. There differences between them are:

SLOT108
I arrived at Sierra Army Depot for the first time and killed all the minigun turrets, looted all the bodies and containers then entered the inside

SLOT109
I arrived at Sierra Army Depot for the first time and did the bare minimum to get inside (Looted Howitzer shell, loaded it and fired it at door), then I ran inside. I did not loot any bodies or items. I did not kill any of the minigun turrets.

**Comment by FakelsHub** [comment]
sfall ver?

**Comment by ACiDxCHRiST** [comment]
> sfall ver?

4.3

**Comment by ACiDxCHRiST** [comment]
> [SLOT109.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6603375/SLOT109.zip)
> 
> Here is another savegame at the same point that does NOT crash. There differences between them are:
> 
> SLOT108
> I arrived at Sierra Army Depot for the first time and killed all the minigun turrets, looted all the bodies and containers then entered the inside
> 
> SLOT109
> I arrived at Sierra Army Depot for the first time and did the bare minimum to get inside (Looted Howitzer shell, loaded it and fired it at door), then I ran inside. I did not loot any bodies or items. I did not kill any of the minigun turrets.

Actually, SLOT109 will crash if you run out the door to the right.

**Comment by FakelsHub** [comment]
I've already decided. wait for the fixed version of sfall.
