### ISSUE TITLE
Healing Bess

### ISSUE THREAD

**Issue by zDragoNzz** [BGforgeNet/Fallout2_Restoration_Project#105]
Trying to heal Bess using a doctor's bag will "heal the disabilities" but she won't get up, and if you try again it says she's healthy, trying to use actual doctor skill even with enough skill will fail if you used a doctor bag before.

**Comment by burner1024** [comment]
Screenshot, savegame, other modes, their versions

**Comment by zDragoNzz** [comment]
I've moved past this point and i usually only have 2 save files so i would have to replay the game until that point, as for the mods, everything is latest version.

RPU v21
Fo2Tweaks v12.6
Inventory Filter v2.0.0

**Comment by burner1024** [comment]
That's too bad. Next time, make sure to make a separate save for each bug.
Do you use healing revision from FO2tweaks?

**Comment by zDragoNzz** [comment]
Yes i use the healing revision.
Next time i spot a bug i'll make a save for it and send it here, thank you anyways.

**Comment by zDragoNzz** [comment]
So, i was doing some tests and the only actual bug is that the doctor's bag doesn't work on her even though the console says "Disabilities Healed" but even if you use the doctor bag you can still heal her using the skill alone.
![image_2021-06-26_182111](https://user-images.githubusercontent.com/76008661/123525998-488ec580-d6ab-11eb-9933-90ddb3c12f4a.png)


[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6720703/SLOT10.zip)

**Comment by burner1024** [comment]
In my tests, even without healing revision, doctor's bag didn't work. Now it should work in both cases.
