### ISSUE TITLE
No Corpses in Klamath Canyon for the yellow reactor keycard 

### ISSUE THREAD

**Issue by yellowcardt** [BGforgeNet/Fallout2_Restoration_Project#106]
Hi Guys,

its my first time i report an issue on Github so, pls be considerate with me *smile*.
as the title says, the 2 corpses for the yellow reactor keycard are missing. 
i haven't played any further and i think, it's going to cause some more problems later...

- I use the steam version of Fallout 2
- also, the german ones
- and the v21 of the RPU
- Inventory Cleaner with newest ddraw.dll (not that from Inventory Cleaner. Not sure but, i think its a older one in the package)

In the past with the old RP and, in the german version of Fallout 2, we also need to install the "Bloodpatch" from neuRomancer (https://fallout-files.de/index.php?c=details&f_id=112&Itemid=100032) to showing up the corpses. Because of violence. it overwrite the "Critters" Files.
Now, the problem is, the critters files are all in one file i gues (the old path whas: Data/art/critters/files) and so i cant install that easily the bloodpatch.

anyone knows, how to solve my Problem? :-/

Some other informations:
- win 10
- Fallout 2 1.02d (from the start menue)
- RP 2.3.3u21 (from the start menue)
- SFall 4.3.0.1 (from the start menue)

**Comment by yellowcardt** [comment]
![Screenshot 2021-07-16 174845](https://user-images.githubusercontent.com/81216661/125980179-3537f55f-37eb-41e4-a26c-4f8c69029d12.png)
![Screenshot 2021-07-16 174802](https://user-images.githubusercontent.com/81216661/125980201-722a4381-8375-43a7-a11a-4fca6b2894fb.png)

**Comment by burner1024** [comment]
Did you start a new game on v21 or using a save from older version?
Attach the save, please.

**Comment by yellowcardt** [comment]
yea, with an new game. 
and here the savefile
[slot01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6833143/slot01.zip)

**Comment by burner1024** [comment]
Here's me loading your save:
![Captura de pantalla de 2021-07-17 04-26-39](https://user-images.githubusercontent.com/1279852/126010159-d42d855d-6478-4f84-aef3-e26c811f98c6.png)

What the hell is Inventory Cleaner, by the way?

**Comment by yellowcardt** [comment]
Sorry, i mean "Inventory filter" ^^
uhm. yeah... its because ive got a censored steam version i gues. :-/
allready tried a fresh install with just RPU (and without Inventory filter), but same results.

**Comment by burner1024** [comment]
I'm not aware of any corpse censoring.
Could you try an English version?

**Comment by Lexx2k** [comment]
The bodies have "bloody" death animations set. In the german version, all gore has been cut out and only the normal bleeding out remains in the game. Also the german fallout2.exe file is modified to always have a low violence level set.

Now if you use the german version and install a mod that replaces the fallout2.exe (like the RPU does), the gore level is suddenly set to higher than low. If you now enter areas like the Klamath canyon, the game won't find the gore animations and crash. To get around this crash, you have to manually set the gore level back to low / none.

**Comment by yellowcardt** [comment]
yeah. with a fresh installation of Fallout 2 in english and RPU in english it works, i can see the corpses

**Comment by Lexx2k** [comment]
Personally I would just ship the gore animations with the RPU and be done with it. The file size will be ~30mb bigger, but who gives a fuck. I've also added all this shit into ettu and nobody even noticed.

**Comment by burner1024** [comment]
Craptastic. I suggested that sfall either displays a placeholder animation or prints an error message to display, but none was implemented, so playing sharades now.

> Personally I would just ship the gore animations with the RPU and be done with it.

Sure, that's what I want to do, just need to figure out which ones are needed. All death anims except fall_back/fall_front? Do you have a link to commit?

**Comment by Lexx2k** [comment]
Just download the bloodpatch from [here](http://www.fallout-files.de//dl/1209663371_Fallout1u2-Bloodpatch.rar). It has all the graphics. The website might throw some error because of the certificate ... just ignore that, I can't fix it. In a couple months the website will be gone.

**Comment by yellowcardt** [comment]
I would like to thank you in advance for your helpfulness. thats great. :)

**Comment by burner1024** [comment]
@yellowcardt well, I guess you can use the bloodpatch for now, and I'll look into fixing this for the next version.

**Comment by yellowcardt** [comment]
Ok, but... mh... what have i to do now?
Install RPU, then the Bloodpatch (with the .exe)?
Or first Bloodpatch (with the .exe), then RPU? 
Or just take some files and copy it ... wherever ^^

**Comment by burner1024** [comment]
RPU, then bloodpatch

**Comment by yellowcardt** [comment]
it works :) thanks a lot guys.

**Comment by burner1024** [comment]
> The file size will be ~30mb bigger, but who gives a fuck. I've also added all this shit into ettu and nobody even noticed.

Small change for EtTu/RPU, but UPU went from 50 to 90Mb :(. Well, I guess we'll just bite the bullet.

**Comment by burner1024** [comment]
ok, next version will inlcude this
