### ISSUE TITLE
Black Screen after after repeatedly visiting Umbra Tribe (Primitive Tribe)

### ISSUE THREAD

**Issue by yellowcardt** [BGforgeNet/Fallout2_Restoration_Project#108]
### What happened
Hi,
after doing some quests on the Map: Umbra Tribe (Primitive Tribe) and leaving, i´ll come back and the Map is fully Black.
I can move around, but dont see my Car (its a solo game, so no more companions) and, by testing: i cant go to the tribe village by moving to the green area by remembering where about it is.
Also try to Close the Game, or reinstall it. I´ve got 2 Savegames attached: 
SLOT17 is like im allready in the black map-thing, 
and the SLOT20 one step before i reentering the Map

### What you expected to happen
The correcly working Map (it starts in the Forest with full of Scorpions)

### Screenshot
![Screenshot 2021-07-21 135217](https://user-images.githubusercontent.com/81216661/126484942-30eed094-7131-44a5-a64e-3afdb45afe86.png)
![image](https://user-images.githubusercontent.com/81216661/126486030-8aa36fe6-4d32-44b7-aaf0-bc0adcfc2b28.png)

### Savegame
[SLOT17.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6855431/SLOT17.zip)
[SLOT20.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6855484/SLOT20.zip)

**Comment by burner1024** [comment]
So in save 2, after re-entering, you see black, right?

**Comment by yellowcardt** [comment]
yes right

**Comment by burner1024** [comment]
I can't reproduce. Attach [debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/debug.md), all ini and cfg files (rpu.ini, fallout2.cfg, hires config, etc), and ddraw.dll too.

**Comment by yellowcardt** [comment]
[files.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6856921/files.zip)

**Comment by yellowcardt** [comment]
I fix it by myself to get my car back with help from this guide:
https://steamcommunity.com/sharedfiles/filedetails/?id=1131357688
But, the Problem with this black screen after revisiting this location will probably still be there.

**Comment by egornovivan** [comment]
have you used Fallout 2 SaveEditor before? It can cause unpredictable bugs.

**Comment by yellowcardt** [comment]
no, first time

**Comment by egornovivan** [comment]
You forgot to attach cfg and ini files

**Comment by yellowcardt** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/108#issuecomment-884280647
here are the config files in this post.

**Comment by burner1024** [comment]
Which game version you have? Steam? GoG? Which language (downloaded distro, not RPU itself, I see it's German).

**Comment by yellowcardt** [comment]
German, Steam and, the game version you can see on the first post (the second picture).
plus useing Bloodpatch for Gore Animations (see last issue) .
whats distro?

**Comment by burner1024** [comment]
Huh... I can reproduce on German version from GoG. I wonder if this is one more "hello" from German censors...

**Comment by yellowcardt** [comment]
in any case, I would not be surprised ^^
but, after lit research i found some discuss about this topic:
https://www.nma-fallout.com/threads/f2-black-screen-when-entering-primitive-tribe.199673/
its not the same like my problem (because i can enter on first time, but not while a second time). ill tried the same stuff ("read only" permissions on that 2 folders) before i report this issue, but this dont works for me.

**Comment by burner1024** [comment]
Found it, a leftover from old localization package. Download [this](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/art/intrface/intrface.lst) file and drop it into `data/art/intrface/`, that should allow you to enter the area.
