### ISSUE TITLE
Sfall is missing highlighting items/containers

### ISSUE THREAD

**Issue by Elsarild** [BGforgeNet/Fallout2_Restoration_Project#11]
Not sure when it was removed, but the Sfall that is bundled with this update dosen't have the option to highlight items and/or containers.

It can be enabled by adding an older Sfall, but then the game warns you that you've overridden the ddraw.ini file. If you add the lines to the config file without installing Sfall as a standalone, it does nothing.

```
;A key (LShift) to press to toggle the highlighting of all items on the ground on the current map
ToggleItemHighlightsKey=42
;Also highlight containers and dead critters (untouched color, valid range: 3..228, but 4,8,16,32 reserved)
TurnHighlightContainers=106
```

I'd love to play it, but highlighting items is honestly so convenient I'm struggling to play without it.

**Comment by burner1024** [comment]
As far as I can tell, RP never had item highlighting bundled.
You can download the script manually from [sfall releases](https://github.com/phobos2077/sfall/releases).
Or, get an [expanded version](https://github.com/BGforgeNet/FO2tweaks#expanded-highlighting) from FO2tweaks.

**Comment by Elsarild** [comment]
Hmm, pretty sure I've had it, but maybe it was an older version of RP.

Regardless, thank you FO2Tweaks looks pretty neat, gonna give that a whirl :)
