### ISSUE TITLE
"Complete brahmin drive" in NCR does not start, savegame included

### ISSUE THREAD

**Issue by NKO55** [BGforgeNet/Fallout2_Restoration_Project#110]
![scr00001](https://user-images.githubusercontent.com/32250049/127542240-f0e01fa3-64c5-4edd-97d9-aa7e31c0137e.png)

### What happened
1. I went to NCR
2. talked to Duppo
3. got the "Complete brahmin drive" quest from him
4. walked outside the Westin's gate
5. waited till 08.00 AM next morning
6. caravan guy didn't show up
7. I exit the area and re-enter, caravan guy now stands in front of the Westin's Gate
8. I talk to the caravan guy, he asks if I'm the one to join the drive, I say yes
9. Dialogue window closes and nothing happens
10. I talk the caravan guy again, he says "You again? Get lost" or something similar
11. I exit the area and come back to the caravan guy, he asks again if I'll take the drive quest and I answer "yes"
12. Dialogue closes and nothing happens

### What you expected to happen
My party was supposed to be teleported to the caravan event right after the dialogue window closes.

### RP version
2.3.3.v21

### Savefile
DL: https://we.tl/t-yFmkyGwkPQ This save is right after accepting the mission from Duppo. You need to use Pipboy to wait untill next morning. The caravan guy won't shop up, you need re-enter the area first.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6902238/SLOT01.zip)

**Comment by burner1024** [comment]
please attach the save to the issue, so it won't get lost later

**Comment by NKO55** [comment]
> please attach the save to the issue, so it won't get lost later

Done!

**Comment by burner1024** [comment]
Is it a fresh RPU install or upgrade from RP?
Did you run this caravan once already?

**Comment by ViperDaimao** [comment]
I also just ran into this issue. Same version. Upgraded from RP. Never ran any caravans before.

**Comment by NKO55** [comment]
> Is it a fresh RPU install or upgrade from RP?
> Did you run this caravan once already?

Fresh install. The version of FO2 I am using is that from GOG. This is the first time in 10+ years since I've touched this game.

**Comment by burner1024** [comment]
Anyone has a save before talking to Duppo?

**Comment by ViperDaimao** [comment]
> Anyone has a save before talking to Duppo?
This should be before going into NCR
[SLOT16.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6911221/SLOT16.zip)

**Comment by burner1024** [comment]
Very strange, but in all these saves caravan status GVAR is already set to finished. Please share a couple of earlier saves.

**Comment by NKO55** [comment]
> Very strange, but in all these saves caravan status GVAR is already set to finished. Please share a couple of earlier saves.

Could it be that the first caravan drive taken sets some flags wrongly? In my case, the drive from Redding to NCR

**Comment by burner1024** [comment]
Not that I can see so far. Need more save to sample it at different points.

**Comment by egornovivan** [comment]
Another small bug with the caravan.  Sometimes the trip takes place without a chance meeting and the caravan is considered destroyed.

https://youtu.be/1DpzyRCTykg?t=283

**Comment by burner1024** [comment]
please report each bug separately, with saves

**Comment by ViperDaimao** [comment]
> Very strange, but in all these saves caravan status GVAR is already set to finished. Please share a couple of earlier saves.

What is the GVAR name? Is it GVAR_NCR_BRAHMN_QST? Could it have something to do with there being a second similar variable,  GVAR_NCR_BRAHMIN_QST?

**Comment by ViperDaimao** [comment]
[SLOT02-RP-beforeRPU.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6911605/SLOT02-RP-beforeRPU.zip)
This is an old save from before I upgraded to RPU, I was just running RP at the time.

**Comment by burner1024** [comment]
In this one it's not initialized, but it's quite early. Something after Redding, Vault City, Broken Hills? (can attach multiple ones).
It's `GVAR_NCR_CATTLE_DRIVE`

**Comment by burner1024** [comment]
no saves?

**Comment by burner1024** [comment]
Also, need opinions in #111

**Comment by ViperDaimao** [comment]
> In this one it's not initialized, but it's quite early. Something after Redding, Vault City, Broken Hills? (can attach multiple ones).
> It's `GVAR_NCR_CATTLE_DRIVE`

what should the value be? is there a fix on issue #111? Here's a save from right before I arrived in NCR, but the GVAR is still 40.
[Before_NCR.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949781/Before_NCR.zip)

**Comment by burner1024** [comment]
Specifically, bit 4 of `GVAR_NCR_CATTLE_DRIVE` should be unset.
There's more to the mix, though, and while it should be fixed in the next release, I think for this run the quest better be left out.
