### ISSUE TITLE
Некорректное имя файлов SFX звуков

### ISSUE THREAD

**Issue by FakelsHub** [BGforgeNet/Fallout2_Restoration_Project#113]
Вроде как движок спотыкается при попытке обработать имя данного файла, т.е. любой файл у которых есть знак %
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/1252cbb82afc9426e169a393c75517e73b04ea05/data/sound
/sfx/wa%1xxx1.acm

Вы пробовали игра не падает при попытке проиграть этот и другие звуки?

**Comment by egornovivan** [comment]
RPUv21 да вроде все норм
[wa%1xxx2.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7010358/wa.1xxx2.zip)
прописал в maps.txt в качестве амбиента wa%1xxx2

**Comment by FakelsHub** [comment]
В директории SFX.  У меня из-за них игра не грузится падает с ошибкой с новой опцией для SFX.
Интересует именно штатное воспроизведение а не подсовывание.

**Comment by FakelsHub** [comment]
> Где ты вообще нашел? wa%251xxx1.acm

Это лишние цифры допечатались, имелось ввиду wa%1xxx2

**Comment by egornovivan** [comment]
> wa%1xxx1

похоже битая acm или я хз что щас произошло 
[wa.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7010634/wa.zip)

**Comment by burner1024** [comment]
Непонятно, но по крайней мере acm2wav нормально ее конвертирует и получившийся wav играется.

**Comment by egornovivan** [comment]
>  acm2wav нормально ее конвертирует и получившийся wav играется.

так она и в игре проигрывается, скорей всего метадату не чистили перед созданием acm, вот и результат.

**Comment by burner1024** [comment]
Ну а если вычистить то не падает?

**Comment by egornovivan** [comment]
> Ну а если вычистить то не падает?

Все точно также после реконвертирования с очисткой метадаты. Но я sndlist.lst не переписывал, видимо в ту сторону надо копать.
Вот реконвертированная acm
[wa%1xxx1.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7010779/wa.1xxx1.zip)

**Comment by egornovivan** [comment]
> 
> 
> > Ну а если вычистить то не падает?
> 
> Все точно также после реконвертирования с очисткой метадаты. Но я sndlist.lst не переписывал, видимо в ту сторону надо копать.
> Вот реконвертированная acm
> [wa%1xxx1.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7010779/wa.1xxx1.zip)

**Comment by egornovivan** [comment]
> похоже битая acm или может гдето в sndlist.lst косяк или я хз что щас произошло
> [wa.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7010634/wa.zip)
> краш получил на выходе из игры
Сори это мой косяк с acm был, я чтото у себя тут напутал с ними и в итоге краш получил.

**Comment by FakelsHub** [comment]
Меня вообще интересует  - движок проигрывает/не проигрывает эти файлы (которые с % в имени файла) без крашей? а не конвертация то вав.

**Comment by egornovivan** [comment]
> Меня вообще интересует - движок проигрывает/не проигрывает эти файлы (которые с % в имени файла) без крашей? а не конвертация то вав.

На RPUv21 нормально проигрывается, вон на копье поставил звуки
[log.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7011002/log.zip)

**Comment by FakelsHub** [comment]
:1st_place_medal:  Молоток.

> Мне на гог версии стоит проверить?

нет
