### ISSUE TITLE
Cannot save after installation under Linux

### ISSUE THREAD

**Issue by SandroWissmann** [BGforgeNet/Fallout2_Restoration_Project#114]
So I downloaded Fallout 2 from steam and then patched it with the latest RPU with the instructions for Linux (I use Manjaro). Everything seems to work fine. It even can get started directly via steam.

But when I start the game and try to save I get an error that the game could not be saved. What could have been gone wrong?

I also tried patching the master.dat like linked here: https://www.nma-fallout.com/threads/fallout2-restoration-save-game-issue.191921/ but that also was not leading to any succes...

**Comment by SandroWissmann** [comment]
Never mind. I uninstalled all fallout 2 complete and installed everything the same again and now saving was working with RPU.

As a site note for linux you should maybe mention that in ddraw.ini you have to set 
ProcessorIdle=0  
SingleCore=0
Otherwise with wine / proton the game runs totally laggy.

**Comment by burner1024** [comment]
Glad you got it working.

>  Otherwise with wine / proton the game runs totally laggy.

It doesn't for me, so it must be specific to your system/configuration.
