### ISSUE TITLE
Possible bug with hitpoint animations?

### ISSUE THREAD

**Issue by GelgoogJager** [BGforgeNet/Fallout2_Restoration_Project#116]
### What happened
Just started the latest version of Restoration Patch, during Temple of Trials I noticed that when my character looses hitpoints, the numbers on the counter are **not** scroling down like in the original fallout. Is this a problem caused by video settings?
### What you expected to happen
Numbers for both hitpoints and armor class to scroll up or down when either increased or decreased

**Comment by burner1024** [comment]
What are they doing?

**Comment by NovaRain** [comment]
What's the value of `SpeedInterfaceCounterAnims` setting in your ddraw.ini?

**Comment by GelgoogJager** [comment]
It´s on 2, what setting should I choose to best emulate Fallout 1?*

*also thanks for pointing out this function, couldn´t find it in the settings :)

**Comment by NovaRain** [comment]
> 
> 
> It´s on 2, what setting should I choose to best emulate Fallout 1?*
> 
> *also thanks for pointing out this function, couldn´t find it in the settings :)

Just leaving it 0, there's no difference between FO1 and FO2 regarding the counter anim.

**Comment by GelgoogJager** [comment]
Ok, thanks a bunch 🥇
