### ISSUE TITLE
Possible jet addiction bug special removal?

### ISSUE THREAD

**Issue by GelgoogJager** [BGforgeNet/Fallout2_Restoration_Project#118]
### What happened
So this is my first time playing as a jet junkie in Fallout 2, one of the problems I´m curently facing is with my character jet addiction setting my strength to 1 (which along with small frame which set´s my carry weight to atrocious 10 pounds max!!!) and perception to 4 (can´t remember now). Now when I created my character my stats were following: 4 S, 6 P, 4 E, 6 C, 7 I, 8 A, 6 L and from traits I choose fast shot and small frame.
Now when my character got addicted to jet during withdrawal phase my strenght and perception were lowered by -1, but when I traveled to Vault City (after doing bunch of quests) I finaly noticed that my strength and perception are set to 1 and 4 which is realy screwing with my gameplay, and it doesn´t seem that traveling around the world map helps either.
So did I encounter some strange level up bug (where if you take jet during level up, it permanently lowers your stats), or I just simply don´t understand the withdrawal mechanics.

P.S. Also is Cassidy talking head not on by default, or is it just me?

Edit: Ok, I found out what happened, but it kind of upsets me, it looks like my jet addiction is bugged in the game. I used fallout 2 save editor to give myself jet antidote and after taking it when I´m in Vault city, the addiction tag doesn´t go away, it seems that the game still thinks I´m addicted, but no matter how manny of the serum I take, it simply doesn´t go away, this means that somewhere along my travels I got double addicted (?) and bugged myself out. I figure it must have happened sometimes before Modoc, because I tried the same method in Umbra Tribe, but this time the addiction got away.
Any ideas how to fix the correct addiction through save editor?
### What you expected to happen
Strength to be at 3 and perception at 5 when suffering from jet withdrawall

**Comment by FakelsHub** [comment]
Проблема была, в том, что после 7 дней (или раньше) для всех зависимостей наступает "день благодарения" и зависимость отступает, но не в случае с Jet, поле этого дня движок удалял статус "зависимости Jet" оставляя ее дебафы и GVAR зависимости в состоянии ON. Эта проблема появилась из-за изменения поиска зависимостей, антидот больше не мог найти событие зависимости к Jet которое было удалено выше по тексту (раньше до изменений "антидот" тупо смотрел на установленную GVAR и снимал всю зависимость).

До следующего релиза, излечится от зависимости можно двумя способами:
1. Использовать антидот пока не наступили негативные последствия от зависимости.
2. Если уже получили дебафы зависимости, то принять нескольких доз Jet (так чтобы игра присвоила еще одну псевдо-зависимость) после этого использовать антидот. При этом дебафы не снимутся поэтому правим только в редакторе.

**Comment by burner1024** [comment]
fixed upstream, will ship when next sfall lis ready
