### ISSUE TITLE
Cassidy not having a talking head?

### ISSUE THREAD

**Issue by Orklord** [BGforgeNet/Fallout2_Restoration_Project#119]
### What happened
I was playing Fallout 2 with RPU v22 installed and everything had been going fine until reaching Vault City and when going to recruit Cassidy, he didn't have a talking head.
### What you expected to happen
I expected Cassidy to have a talking head.
### Screenshot
![image](https://user-images.githubusercontent.com/89825430/131439553-8c00c96c-1003-4bd3-b89e-8bedb07ad7bb.png)

### Savegame
[SLOT26.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7081109/SLOT26.zip)

**Comment by burner1024** [comment]
Unzip this into `data/scripts`, delete `mods/rpu_cassidy_voice.dat`
[vccasidy.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7084668/vccasidy.int.zip)

**Comment by Orklord** [comment]
That fixed it. Thanks!

**Comment by r1yoko** [comment]
> 将其解压到`data/scripts`, 删除`mods/rpu_cassidy_voice.dat`
> [vccasidy.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7084668/vccasidy.int.zip)

hi I would like to ask, the game with the treatment needle in battle will be ejected. The current version of RPU22 and the previous version will also pop up with the treatment needle. How can I solve this problem?

**Comment by burner1024** [comment]
Do you mean you have a crash? Post a new issue, guide is [here](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md).

**Comment by pwrfstlsbn** [comment]
Hello, I am having trouble finding mods/rpu_cassidy_voice.dat. Where do I go?

**Comment by burner1024** [comment]
why do you want to find it?
