### ISSUE TITLE
I would like to ask, the game with the treatment needle in battle will be ejected.

### ISSUE THREAD

**Issue by r1yoko** [BGforgeNet/Fallout2_Restoration_Project#120]
### What happened
I would like to ask, the game with the treatment needle in battle will be ejected. The current version of RPU22 and the previous version will also pop up with the treatment needle. How can I solve this problem?
### Savegame
[savegame.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7109524/savegame.zip)

**Comment by r1yoko** [comment]
the game pops up to show this problem
the instruction at 004197e8 referenced memory at 610a3288
the memory could not be read from
Click on OK to terminate the application

**Comment by r1yoko** [comment]
before this battle archive, I have never used the battle archive or read the archive during the battle. Just upload the problem this time, save the archive in this battle

**Comment by burner1024** [comment]
I cannot reproduce the crash.
Can you reproduce it and attach `debug.log` file?

**Comment by r1yoko** [comment]
> 我无法重现崩溃。
> 你能复制它并附上`debug.log`文件吗？

[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7110261/debug.log)

**Comment by r1yoko** [comment]
> 我无法重现崩溃。
> 你能复制它并附上`debug.log`文件吗？

thanks

**Comment by burner1024** [comment]
I can't see a crash in the log...

**Comment by r1yoko** [comment]
> I can't see a crash in the log...

thanks you

**Comment by FakelsHub** [comment]
> I can't see a crash in the log...

и не увидишь, там креш с art связан, или просто в силу бага в каком-то другом месте решило глюкануть с доступом к арту.

**Comment by burner1024** [comment]
Ну и хз что с этим делать, воспроизвести я тоже не могу.

**Comment by FakelsHub** [comment]
Что такое с китайского "treatment needle"??? :-)

**Comment by burner1024** [comment]
судя по всему стимпак

**Comment by NovaRain** [comment]
That's how "stimpak" got translated literally in the localized version, "treatment/healing/cure" needles.

**Comment by FakelsHub** [comment]
Exactly, acupuncture is the traditional methods of China. ))

**Comment by r1yoko** [comment]
> Ну и хз что с этим делать, воспроизвести я тоже не могу.

In other PCs, the treatment needles are also used in wars, that is, what you call "stimpak" is still wrong: P

**Comment by egornovivan** [comment]
Maybe the bug is hidden in the Chinese version of the game?  Winiepooh replaced the stimpacks with needles and broke something as a result?

**Comment by r1yoko** [comment]
> Maybe the bug is hidden in the Chinese version of the game? Winnie the Pooh replaced the stimpacks with needles and broke something as a result?
> 
> ![7jPAwLM - Imgur](https://user-images.githubusercontent.com/60801856/132954976-5b15baba-6f11-41d1-8e3d-d9527eb781cf.png)

maybe, but I’m not in Chinese, English version

**Comment by egornovivan** [comment]
> English version

Gog / Steam or another version?

**Comment by r1yoko** [comment]
> > English version
> 
> Gog / Steam or another version?

Other version

**Comment by egornovivan** [comment]
> Other version

We need a clean copy of this version, you can pack it into an archive and upload it here or somewhere on mediafire.com ?

**Comment by r1yoko** [comment]
> > Other version
> 
> We need a clean copy of this version, you can pack it into an archive and upload it here or somewhere on mediafire.com ?
> 
> Well, can you tell us more about where you got this version of the game from?

I also downloaded it, because I bought gog and steam, I can only zip the game, there is no pure version. Upload to MEGA if needed

**Comment by egornovivan** [comment]
> I can only zip the game, there is no pure version. Upload to MEGA if needed

Upload it, and we'll see what's wrong with it

**Comment by r1yoko** [comment]
> > I can only zip the game, there is no pure version. Upload to MEGA if needed
> 
> Upload it, and we'll see what's wrong with it

OK
https://www.mediafire.com/file/opieb5mt9ewr2gb/Fallout2.rar/file

**Comment by egornovivan** [comment]
> OK

You can try the gog version
`https://mega.nz/file/xx5CnBLb#NVVH5-M6sChoYoybS0fMS2fYSl8N85bbBPWO_nOpRI8`


(I will delete both links later)

**Comment by egornovivan** [comment]
@FakelsHub Внятный лог на такие Васянские случаи можно прикрутить? Или оно не стоит потраченного времени?

**Comment by FakelsHub** [comment]
Не смотрел на "Васянство". Но пусть разбираются те кто там что-то нахимичил.

**Comment by egornovivan** [comment]
Hmm, it looks like an uncensored CD version of the game, but why it crashed is not clear to me

**Comment by burner1024** [comment]
can you reproduce the crash?

**Comment by burner1024** [comment]
Ok, let's just write this off as a one-off. If you manage to find a reproducible use case, feel free to add info.
