### ISSUE TITLE
Cassidy Talking Head Problem

### ISSUE THREAD

**Issue by Vikktor14** [BGforgeNet/Fallout2_Restoration_Project#121]
### What happened
Ok so I got this problem, I downloaded Restoration Project Updated (The updated latest release V22) Went to Vault City and when I talk to Cassidy, his talking head does not appear, there is a way to fix this?. I went to my Mods file from Fallout 2 RPU and has this lines

[main]
; mutant armor for Marcus
marcus_armor=1
; kevlar armor for Dogmeat
dogmeat_armor=1
; smoking animation
smoking=1
; new look for Lenny
lenny_new_look=1
; use unique vault boxer model when figthing in the ring
vault_boxer=1

Something here is missing? I have
Cassidy_head.dat
cassidy_voice_joey_bracken_hq.dat
rpu_cassidy_voice.dat

**Comment by burner1024** [comment]
https://bgforge.net/2021/09/01/rpu-v23
