### ISSUE TITLE
RPU - is not a valid win32 application

### ISSUE THREAD

**Issue by vorob1** [BGforgeNet/Fallout2_Restoration_Project#122]
It's not compatible with windows xp?

**Comment by vorob1** [comment]
Downloaded zip version and it's working. Wish game with all updated is fully compatible with xp :)

**Comment by burner1024** [comment]
Game is compatible, I'm not sure why installer isn't, it's probably innosetup thing.
Note that zip version requires running [rpu-install.bat](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/release/rpu-install.bat) (or you can perform the same steps manually).

**Comment by FakelsHub** [comment]
> I'm not sure why installer isn't, it's probably innosetup thing.
Innosetup-5.5.9 последняя с поддержкой winXP (даунгрейднись)

**Comment by egornovivan** [comment]
> Innosetup-5.5.9 последняя с поддержкой winXP (даунгрейднись)

А потом на новых системах будем ловить баги, там в старых версиях даже юникод не поддерживается

**Comment by FakelsHub** [comment]
На каких новых Windows12 - 20?
Uniкоды в старых есть.

**Comment by burner1024** [comment]
Я думаю возможности ручной установки достаточно на текущий момент.

**Comment by vorob1** [comment]
В зип архиве нет батника rpu-install. Мне точно нужно что-то дополнительно делать кроме как разжать архив в папку с чистым фолычем 2?

**Comment by burner1024** [comment]
Да я его недавно убрал из дистрибутива, думал уже не нужен будет. Сейчас обратно добавил.
Надо запустить, да, либо руками то же самое сделать, батник простой, глянь его.

**Comment by egornovivan** [comment]
@vorob1 
[rpu-install.bat.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7148152/rpu-install.bat.zip)
