### ISSUE TITLE
Error: File not found: art\critters\masphnak.frm

### ISSUE THREAD

**Issue by ncromcr** [BGforgeNet/Fallout2_Restoration_Project#123]
Encountered these floaters, when they move, a couple of them generate Error: File not found: art\critters\masphnak.frm in the combat log. 

![image](https://user-images.githubusercontent.com/90653100/133155032-9b1c7b03-4800-4566-ad48-c189242f7690.png)

Saw one earlier too involving different creatures, but don't remember what they were or what the error was. Attached a savegame mid combat if that helps. I assume there's some mod I'm missing or something, but no idea what it might be. I'm running Steam's Fallout 2 (not the classic version) with the RP v23 and FO2tweaks.  
[savegame.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7157315/savegame.zip)

**Comment by egornovivan** [comment]
hmm, when testing caravans, I have not seen anything like this on Floaters

**Comment by FakelsHub** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/6a75393c3469f12fcbe437caf5c57c1a0b7b9e0a/extra/package/ddraw.ini#L19
Отключите sfall отладку или постояно будете видеь подобные Issue.

**Comment by ncromcr** [comment]
That did it, thanks. Dunno why it was toggled on, I didn't change it.
