### ISSUE TITLE
Game "freezes"/"gets stuck" when exiting conversation with Jackpot Jane.

### ISSUE THREAD

**Issue by ElvisNilsson** [BGforgeNet/Fallout2_Restoration_Project#124]
### What happened
Game "freezes"/"gets stuck" when exiting conversation with Jackpot Jane.

Steps to reproduce:
1. Boot save game "Buffy" attached below.
2. Zone north to the molerat fighting part of Redding.
3. Talk to Jackpot Jane and pick the "1" option until given the option to end the conversation with the "4" option.
4. Notice the game (and camera) getting stuck with only the option to move around the mouse cursor with it's arrow version out. No input are recognized. Only option left was to ctrl-alt-del and close the "Program" at which point tabbing back to the game showed the option to quit or no. Selecting no returns you to the state at the start of point "4". Selecting yes closes the game.

Screenshots in logical order from boot to freeze, didn't screenshot the actual freeze as the game no longer recognizes any more inputs.

Notice:
1. The camera "jumps" slightly to the right (as if trying to focus on a molerat fight, which isn't happening) just before the freeze.
2. Just starting the conversation and ending it (without going through the "1" options) DOESN'T produce the freeze.
3. Have played through the game fully once with these settings, this is my first issue.

### What you expected to happen
For the game to not get stuck ^^;

### Screenshot
![scr00000](https://user-images.githubusercontent.com/91654949/135400662-2d3a6137-1bd0-4676-92c8-f531235aff7a.jpg)
![scr00001](https://user-images.githubusercontent.com/91654949/135400669-08ae2f43-2fed-4
![scr00002](https://user-images.githubusercontent.com/91654949/135400675-7401b058-4587-4dff-8bf9-bc61c6a2bdf4.jpg)
89e-bf4d-1cf048594f2d.jpg)
![scr00003](https://user-images.githubusercontent.com/91654949/135400682-b87e1f6b-f472-4ddb-a46b-0ce2
![scr00005](https://user-images.githubusercontent.com/91654949/135400691-f048200b-4461-407d-92c1-5cfb2d4fb610.jpg)
037df08e.jpg)
![scr00006](https://user-images.githubusercontent.com/91654949/135400697-49cdb34e-45ff-4888-8f5f-f2ca9fb414ac.jpg)
![scr00012](https://user-images.githubusercontent.com/91654949/135400705-4d3eb733-a8a2-4b41-878f-a463db8b5c71.jpg)

### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7257253/SLOT01.zip)

**Comment by ElvisNilsson** [comment]
Notice (forgot this one):
4. The "draw" function in the game seems to keep working, cause during the freeze it doesn't have half the screen black as is customary when tabbing out and back in.

**Comment by burner1024** [comment]
I can reproduce.

**Comment by burner1024** [comment]
Try this (extract into data/scripts)
[rcjane.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7269592/rcjane.int.zip)

**Comment by ElvisNilsson** [comment]
Sorry, just uninstalled it like 2h ago, thx for the mod though, great overall ^^;
