### ISSUE TITLE
Vault City courtyard NPCs hostile if approached.

### ISSUE THREAD

**Issue by mz1193** [BGforgeNet/Fallout2_Restoration_Project#125]
### What happened

Vault City NPCs in the courtyard will instantly enter combat mode if approached too closely or clicked on. This happens across all characters I've tried. This only seems to affect the "peasant" NPCs. Guards, shopkeepers, etc. all act normally.

### What you expected to happen

I expect this to not happen unless Vault City has some reason to hate me, but it happens on the first visit regardless of companions brought.

**Comment by burner1024** [comment]
Save before first entering Vault City for the first time?

**Comment by zara1193** [comment]
> Save before first entering Vault City for the first time?

Right, sorry for not posting one. Attached is a save in the mountains right next to Vault City, prior to entering it for the first time. Thanks
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7295230/SLOT10.zip)
!

**Comment by zara1193** [comment]
> extract this into data/scripts [vccrtout.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7295840/vccrtout.int.zip)

Thanks so much!
