### ISSUE TITLE
Crash on attempt to clean fans in EPA Level 5 Violet

### ISSUE THREAD

**Issue by EPecherkin** [BGforgeNet/Fallout2_Restoration_Project#129]
### What happened

The game crashed when I tried to clean dirty Fans in EPA Level 5 Violet

Error

```
The instruction at 00484d3b referenced memory at 00000000
The memory could not be read from
Click on OK to terminate the application.
``` 

### What you expected to happen

Not to crash

### Screenshot

![image](https://user-images.githubusercontent.com/1036610/144132449-6d7829b0-12aa-49bd-86ad-d8e0433b1c0a.png)

### Savegame

[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7629050/SLOT01.zip)

### Debug Log

[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7629950/debug.log)

#### ddraw.ini and f2_res.ini

[ddraw.ini](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7629957/ddraw.txt)
[f2_res.ini](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7629960/f2_res.txt)

#### Additional info

I had another bug too. The character got Addicted to Jet. I found Jet antidote, used it and nothing happened. I bought another one - but it said "No effect". So, I used save editor to restore missing stats and continue walkthrough

**Comment by EPecherkin** [comment]
And it seems that I'm not the only one
https://www.reddit.com/r/classicfallout/comments/pe6h4m/crashing_in_the_epa_using_f2_restoration_project/hmowsm0/?context=3

**Comment by burner1024** [comment]
attach debug https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md

**Comment by EPecherkin** [comment]
@burner1024 Done

**Comment by burner1024** [comment]
What's your RPU version and language?
Jet thing is a known issue, you need to update sfall to get rid of it.

**Comment by EPecherkin** [comment]
I'm using the latest version, 24. I tried to use the latest sfall, but I constantly get the message that ddraw was changed and RPU might not work properly and I need to revert back

**Comment by burner1024** [comment]
Update ddraw.dll, don't replace ddraw.ini.
