### ISSUE TITLE
Changing sound options / preferences causes a crash

### ISSUE THREAD

**Issue by JohnnySixPistols** [BGforgeNet/Fallout2_Restoration_Project#133]
### What happened
Upon changing the volume of speech / music / effects / general in options / preferences the game crashes, producing a "divide by zero" or "memory" error.

I'm not using any other mods than this one.

The bug does not happen in Fallout 1 application.

**Comment by NovaRain** [comment]
If you get the error/crash when trying to mute the master volume, try setting FadeBackgroundMusic=0 in ddraw.ini.

**Comment by JohnnySixPistols** [comment]
> 

Thank you!!! That did the trick.
