### ISSUE TITLE
Is it intended that party members' weapons somehow count as me using a weapon when talking to NPCs?

### ISSUE THREAD

**Issue by Myrthian** [BGforgeNet/Fallout2_Restoration_Project#134]
- I'm on the latest v25
- I've had it happen multiple times now in e.g. Broken Hills or the weapons vendor in NCR bazaar that my PC has no weapon in his current item slot and yet NPCs refuse to talk to me with floaters that point towards me using a weapon in their presence, which obviously isn't the case
- So far I've worked around that by parking my party members somewhere and most of the times that works, but I somehow doubt that this interaction between my and other NPCs is intended

In this save the NPC bazaar weapons vendor refuses to talk to me with his "Put your weapons away" floater no matter what I do.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7920004/SLOT01.zip)

**Comment by Myrthian** [comment]
Completely leaving the map towards the overworld and coming back in does fix it in this instance, but it nevertheless seems like a bug.

**Comment by NovaRain** [comment]
Judging from [Steve's script](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/b2a700a242fdb5041746e100e32daf42782ed60f/scripts_src/brokhill/hcsteve.ssl#L210), it should be intended for him to have the entire party unarmed.
```pas
   else If_Party_Is_Armed then begin
      call Node008; // the floating message about being armed
   end
   else if (critter_is_armed(dude_obj)) then begin
      call Node008;
   end
```
As for Buster, his shop only opens after 8:00 AM, so he gives you the "Mr. .45" warning. You just need to wait a couple of hours.

**Comment by burner1024** [comment]
Yes, as far as I know it is intended.
It is the reason why [Party Orders](https://github.com/BGforgeNet/Fallout2_Party_Orders) has an order to holster weapons. (Included with RP, default key is H).

**Comment by Myrthian** [comment]
Ah. I didn't follow up on links for the additional mods included in RP.
Thanks.
