### ISSUE TITLE
Frequently can't save game + big black map once I leave the current map

### ISSUE THREAD

**Issue by Myrthian** [BGforgeNet/Fallout2_Restoration_Project#135]
- I'm nearing the end of the game and so far I've had at least ~15-20 crashes
- Every crash starts with not being able to save even though I can save in that area, sometimes with a general "You can't save" message, sometimes with an actual error dialog in which the name of the save/map name is listed
- Once I can't save and leave the current map via an exit grid I'm in a big map of nothing but black
- If I then alt-tab to Windows I get a memory allocation error or something like that, which I don't get when everything functions normally and alt-tabbing just ends Fallout with the process still being active

What logs do you need?

I did find #108, but I'm unsure if that's only in cases of black maps after being in Umbra Tribe maps, or generally applicable for my issue.

**Comment by NovaRain** [comment]
Try disabling `FadeBackgroundMusic` in ddraw.ini, or update sfall (ddraw.dll) to [4.3.3](https://github.com/phobos2077/sfall/releases/tag/v4.3.3).

**Comment by burner1024** [comment]
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md

**Comment by burner1024** [comment]
Not enough info.
Likely fixed upstream.
