### ISSUE TITLE
Vault 13 getting the GECK prompts Memory Error

### ISSUE THREAD

**Issue by thabisoram** [BGforgeNet/Fallout2_Restoration_Project#136]
After repairing the voice module for the computer in Vault 13, I go talk to the Deathclaw to get the GECK. Immediately after talking I get a Memory error "The instruction at x referenced memory at y, the memory could not be read from".

I've attached my save game to this
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7936390/SLOT01.zip)
.

**Comment by burner1024** [comment]
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md

**Comment by NovaRain** [comment]
Update your sfall (ddraw.dll) to [4.3.3](https://github.com/phobos2077/sfall/releases/tag/v4.3.3).

**Comment by burner1024** [comment]
Fixed upstream.
