### ISSUE TITLE
Minor bug with Marcus's floater dialogue

### ISSUE THREAD

**Issue by knsanchez0001** [BGforgeNet/Fallout2_Restoration_Project#137]
### What happened
Upon completing the quest to find the missing people in Broken Hills, Marcus emits the floater "I guess Francis was right about Jacob. That murderous bastard won't cause any more trouble in this town." That floater is only related to busting the anti-mutant conspiracy, and I hadn't even begun to start the anti-mutant quest chain.

This is repeatable by talking to Marcus about discovering what happened to the missing residents.

### What you expected to happen
To not see that floater with regards to finding the missing people.

### Savegame
[SLOT14.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/8009514/SLOT14.zip)

### Edit
I'm now wondering if this is actually a bug or just a weird quest design. Despite having a note that implicates Francis in the murders of the people underground, Jacob and Aileen are still framed for those murders.

**Comment by burner1024** [comment]
>  Jacob and Aileen are still framed for those murders

I think that's right. Marcus doesn't know about the note, he thinks it's Jacob, and he puts Jacob in jail.
From [walkthrough](https://lemmings19.github.io/fallout-2-walkthrough/#bh):
> The next step is to tell Marcus about the bodies. You should put this off until you've done quests 4 and 5 though, because Marcus will put Jacob away if he hasn't already done so.

As far as I can see, floater is correct from Marcus' viewpoint.
I'm open to discussion, but so far I don't think it's a bug.
