### ISSUE TITLE
[v25] Fight w/ Tyler's gang + script issue

### ISSUE THREAD

**Issue by agris-codes** [BGforgeNet/Fallout2_Restoration_Project#138]
Observed behavior: When you aid Lara in fighting Tyler's gang, and are teleported to the Den Residential map for the fight in the house: not all of Tyler's gang engages in the fight.  There is one of Tyler's guys in the bottom-right room of the house who does not aggro. So, you mop up everyone except him, combat ends, then it starts again a few moments later again when he engages. 

I'm going to be annoying and bundle a script bug in here as well because they occur together. When you defeat Tyler's gang in the same residential map and Lara tells you "good job, come by the church to get your reward" and dialogue closes, if you path away and back to her in short order, she will open a new dialogue and give you your reward - while you're still in the house. Then, when you approach her outside the church, her script kicks in again and gives you the reward again. The reward dialogue/script should be set to only fire on the map with the church.

Expected behavior: all of Tyler's men participate in the Den Residential fight at once, and Lara only rewards you once when you talk to her in front of the church. 

Other: the issue with one member of the gang not participating in the house fight was 100% reproducible. I ended up reloading the start of that fight over 5 times because a FoTweaks component causes a soft lock (I'll post on it soon). The gang member on the room off to the lower-right never participated in the initial fight during 5+ attempts.

**Comment by burner1024** [comment]
need save

**Comment by burner1024** [comment]
It is clear enough, however without a save it can't be verified, nor a fix (if any) can be tested.

**Comment by agris-codes** [comment]
Are of aware of how to get F12se working with the RPU? Being able to generate a new character and edit it would help me create a save.

**Comment by burner1024** [comment]
It should work, there's some warnings about sfallgv, but I think you should be safe to ignore those. Best check with the author, though.

**Comment by agris-codes** [comment]
I see you closed this, that’s fine. I’ll get around to generating a save, but it won’t be soon. I have a lot of bugs (and saves) to report to you from my recent completionist play through. It’s going to take a bit to format them into actionable feedback for you. 

I’ll put all of that in the NMA thread, I think it’s too much to swamp your git with 20+ issues. After our initial exchange here, I was more diligent in capturing saves for reproducibility.

**Comment by burner1024** [comment]
It is better to report the issues separately.
I don't read the thread.

**Comment by phobos2077** [comment]
I was able to reproduce the double reward issue. Maybe need to add check for the current map or something.

**Comment by agris-codes** [comment]
> Observed behavior: When you aid Lara in fighting Tyler's gang, and are teleported to the Den Residential map for the fight in the house: not all of Tyler's gang engages in the fight. There is one of Tyler's guys in the bottom-right room of the house who does not aggro. So, you mop up everyone except him, combat ends, then it starts again a few moments later again when he engages.
> 
> [....]
> 
> Expected behavior: all of Tyler's men participate in the Den Residential fight at once, and Lara only rewards you once when you talk to her in front of the church.
> 
> Other: the issue with one member of the gang not participating in the house fight was 100% reproducible. I ended up reloading the start of that fight over 5 times because a FoTweaks component causes a soft lock (I'll post on it soon). The gang member on the room off to the lower-right never participated in the initial fight during 5+ attempts.

If this is not reproducible it is likely due to the fact that I was using a non-default amount of path searching nodes. I didn't think of this when I submitted the report, but I've seen Lexx mention increasing the node count as a source of pathing and AI bugs, so I wanted to flag it.

**Comment by burner1024** [comment]
There's already an area check.
I relaxed the condition, so that on residential area she should just keep repeating "meet us back at the church".

As for oblivious guard, I'm not sure what's his deal. I think I also had that. Maybe can open the door and/or increase his Perception? Can't test without a save, though.
