### ISSUE TITLE
Game refuses to start with the Spanish translation

### ISSUE THREAD

**Issue by Renkoto** [BGforgeNet/Fallout2_Restoration_Project#139]
I installed everything correctly (i think) english version runs and seems to work fine, but setting up the spanish translation through fallout 2.cfg causes the game to crash. I was spend hours to find the problem.

- Mod version is v26
- I should note that I'm running it on Linux via Wine with the respective override (Wine version is 7.1 to be exact) i don't think it's a Wine thing.

I assume that the complete translations of the game are included in the mod since it's not specified at any time that the translations must be installed separately before so, the original and standalone version of the Spanish translation runs fine in Wine.

**Comment by burner1024** [comment]
Attach your config

**Comment by burner1024** [comment]
What's your base game, where'd you get the distro?
Did you select Spanish during installation? `mod/rpu_spanish.dat` is the localization package, do you have it?
Also include a screenshot and get [debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md).

**Comment by Renkoto** [comment]
> What's your base game, where'd you get the distro? Which language is the base game?
GOG Version, distro is OpenSUSE Tumbleweed. Base game language is English.

>  Did you select Spanish during RPU installation? mod/rpu_spanish.dat is the localization package, do you have it?

Yup. 
![imagen](https://user-images.githubusercontent.com/69415770/155907615-f9a29c1b-1845-437d-acd2-b7ed76b926da.png)

Game doesn't seem to leave a log file despite having debug mode enabled, i'm going to check something.

**Comment by burner1024** [comment]
I mean a screenshot of crash.
It really should leave a log. Re-check if you've set all settings correctly, specifically `DebugMode=2`.
