### ISSUE TITLE
Punk Girl playable character instead 3D gals models

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Restoration_Project#14]
I propose to replace non-fallout-like female playable characters (which are too stocky in my opinion) with great looking Punk Girl.
Punk Girl is included in recently released FALLOUT ET TU [NMA Thread](http://www.nma-fallout.com/threads/fallout-et-tu-alpha-release.218045/) which is based on Fallout 2 too, so it's easier to re-implement.

**Comment by burner1024** [comment]
Not going to _replace_ anything, but it could be added, although it might be better to move hero appearance into a separate repo, so it could be used with any setup with ease.

**Comment by burner1024** [comment]
Created a [separate repo](https://github.com/BGforgeNet/Fallout2_Hero_Appearance) for hero appearance, added punk girl.
While at it, are there any other character sets that could/should be added?
