### ISSUE TITLE
Request: Separate folder structure similar to F1to2

### ISSUE THREAD

**Issue by Dark-Jaguar** [BGforgeNet/Fallout2_Restoration_Project#141]
I was curious if the installation of this mod could be set such that it uses it's own folder structure and could thus be executed independantly of the "vanilla" Fallout 2 experience.  I've found I like having that option when it comes to Fallout Fixt and the Fallout 1 in 2 conversion, and think this would give players full freedom to play the game in whatever mood strikes them.

**Comment by burner1024** [comment]
Just duplicate the vanilla dir and install RPU into the duped dir.
