### ISSUE TITLE
Failed to open file. Too many open files

### ISSUE THREAD

**Issue by AdamChirnside** [BGforgeNet/Fallout2_Restoration_Project#142]
### What happened
Game gets stuck, throwing an error and otherwise being unable to take any game action.
Only seems to happen in the Den, so far, after moving between areas and talking to various NPCs.

### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/8308014/SLOT01.zip)

**Comment by NovaRain** [comment]
Did you get the error only after a long game session? Try setting `FadeBackgroundMusic=0` in ddraw.ini and see if that helps.

**Comment by AdamChirnside** [comment]
No it happens after even just 10-20 minutes, but seemingly only in the Den. sFall version is 4.3.3.1. I'll try that setting change as well, thanks.

**Comment by NovaRain** [comment]
If that happens again, it's better to upload the debug.log from your game folder.
You can also try this sfall test build with that option enabled (`=1`): [sfall4332-test.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/8308171/sfall4332-test.zip)

**Comment by AdamChirnside** [comment]
The workaround seems to be helping. I'm also noticing some severe performance drops in The Den which may be related?

**Comment by NovaRain** [comment]
> The workaround seems to be helping.

Could you also help to check the test build in my previous message? I'd like to know if the fix for that option works.

> I'm also noticing some severe performance drops in The Den which may be related?

I'm not sure because I didn't have any noticeable lag in The Den. Does the game lag only on a specific map (West/East/Residential) or all of them? What's the spec of your system?

**Comment by AdamChirnside** [comment]
I've just done some testing and it seems like the fix for the `FadeBackgroundMusic` option works.
Hard to say since it triggered somewhat randomly. 
Same for the performance issue I was having (only in the West map of Den).

My system is quite new compared to Fallout 2.. Is it demanding on modern hardware?

**Comment by NovaRain** [comment]
> 
> I've just done some testing and it seems like the fix for the `FadeBackgroundMusic` option works. Hard to say since it triggered somewhat randomly. Same for the performance issue I was having (only in the West map of Den).

OK, thanks. Would be nice if you can keep playing with the test build and option enabled for the whole game.
Please do report if the same open file error happens again.

> 
> My system is quite new compared to Fallout 2.. Is it demanding on modern hardware?

Supposedly it's not hardware demanding (the lowest spec I've tested is Pentium II), but some OS and driver settings might cause something.

**Comment by AdamChirnside** [comment]
It's back! When I was resolving the bar fight in Redding I got the dreaded "too many files" error again

[Here is the debug log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/8312299/debug.log)

**Comment by NovaRain** [comment]
Damn, OK, just disable the option for the time being. Hopefully the error won't happen again (might be a bigger issue if it does).

**Comment by burner1024** [comment]
I guess I'll disable the option by default.
