### ISSUE TITLE
Cant download anything

### ISSUE THREAD

**Issue by Nicolai744** [BGforgeNet/Fallout2_Restoration_Project#144]
Error when downloading the files, the message "Autorization required" pops up and make impossible to download the .exe or the .zip, tried several times, never worked.

**Comment by burner1024** [comment]
which file are you trying to download?

**Comment by Nicolai744** [comment]
> which file are you trying to download?

rpu_v.exe

**Comment by burner1024** [comment]
I mean exact url

**Comment by burner1024** [comment]
I'm not sure. Downloads fine for me. Maybe some Github issue.
Try another browser?

**Comment by Nicolai744** [comment]
Ok i will, i tried with 3 diferent browsers by now and idk what causes the issue

**Comment by Nicolai744** [comment]
It worked now, thanks. ^w^ im very excited to play fallout2 with the restoration proyect.
