### ISSUE TITLE
installed F2res the wrong way and now can not uninstall or get rid of files

### ISSUE THREAD

**Issue by EmmyOhMeOhMy** [BGforgeNet/Fallout2_Restoration_Project#145]
I installed and ran f2res in a way that made it so I could not get far into the game before an error message appeared saying the program is "running in compatibility mode" upon launch. There were other issues related to the installation, like sometimes the restoration project would not be running with the game (no rock behind the tribesman in the first scene), or a character with stats: S6P6E10C2I7A10L7 would start with -12 Barter instead of -2 and -2 Doctor instead of 12 or whatever its supposed to be. the game would not run consistently.
The issue I'm looking for help with, though, is that I can not uninstall and reinstall the game as Vanilla. Both the F2res mod and the sfall mod are still installed in the directory whenever I reinstall the game (even if I delete all the files prior to uninstalling), which means I can not just install the mod all over again in a different way.

**Comment by burner1024** [comment]
Both f2res and sfall are shipped with GoG distro, probably Steam too.

**Comment by EmmyOhMeOhMy** [comment]
> 

That is good to know, but it doesn't explain why there were some times when I ran it that the rock behind the tribesman in the first scene confirmed that I was playing F2res when examined, some times when the rock said some else about "Granite Inc." and other times where there was no rock at all. Also it doesn't explain how some times I end up with -12 Barter and other times I end up with -2.

**Comment by burner1024** [comment]
The rock shows RPU version, not hi-res nor sfall.
Once you delete game dir, there's nothing left of RPU.
If you have a reproducible case of a bug, then provide the steps.
If not, you could try to record a video.
