### ISSUE TITLE
Resolution of Game Screen Off

### ISSUE THREAD

**Issue by echasketch2010** [BGforgeNet/Fallout2_Restoration_Project#146]
Set the graphics in the ddraw.ini and f2_res.ini to my monitor size for fullscreen windowed using DX9. While the interface bar is the correct size, the actual screen for the game is smaller. I'm not sure what I'm missing here.
[FO2RPU_Resolution.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9034310/FO2RPU_Resolution.zip)

**Comment by NovaRain** [comment]
It's normal because the area of map edges for the temple entrance map is that size (not designed for 2K/4K resolution). If you want to see area beyond map edges, set `EDGE_CLIPPING_ON=0` in f2_res.ini.

**Comment by echasketch2010** [comment]
Thanks!
