### ISSUE TITLE
Bad fps in encounter

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Restoration_Project#147]
Had an encounter with farmers vs. geckos. Once the encounter was completed, the fps kept crashing down. See savegame:

[SLOT14.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9125442/SLOT14.zip)

Maybe some critter_proc going haywire? 

Note: I'm playing with pixotes new maps.

**Comment by burner1024** [comment]
> Had an encounter with farmers vs. geckos. Once the encounter was completed, the fps kept crashing down. See savegame:

I'm getting the same booted on v26.
`^^^^^^^^^` is spammed in debug.log. I vaguely rememeber something similar discussed in sfall issues, possibly related to sound? Can't find it.

> Note: I'm playing with pixotes new maps.

Cool, you're the designated tester then.

**Comment by Lexx2k** [comment]
> Cool, you're the designated tester then.

If you enter the cave in that savegame, you can see one of the chests being spawned inside new scenery.

**Comment by NovaRain** [comment]
Looks like some script keeps searching/loading protos. Every time more than 512 protos are loaded, the game prints a caret `^` in the log.

**Comment by burner1024** [comment]
Not sure how to find which script. Would it be hard to add some sfall debug option to replace the caret with actual script and proto file names/ids?

**Comment by burner1024** [comment]
1. Entering combat removes lag.
2. Removing improved mysterious stranger dat fixes this.

Not sure how it's relevant, given that you don't have the corresponding perk.
That component doesn't even have any scripts, only protos. Maybe one of them is corrupt? But then you'd have constant lag, not just on this map.
My money on some engine/sfall bug.

**Comment by NovaRain** [comment]
The cause is two of the protos for improved mysterious stranger: `00000270.pro` & `00000271.pro`, as they have incorrect PID (30/31 instead of 270/271) and clashes with the robbers using the _real_ PID 30/31 (tough thug).
Here's the fixed file: [rpu_improved_mysterious_stranger_fix.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9127642/rpu_improved_mysterious_stranger_fix.zip)

**Comment by burner1024** [comment]
Thanks!
