### ISSUE TITLE
Crash while exiting the Village outside of Vault City

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#149]
### What happened
I gave the firearms to the head of the Village outside of Vault City, then I massacred the Mole Rats while my party handled most of the inhabitants. After that, I return to my Highwayman. That’s when the game crashed.

### What you expected to happen
I expected to return to the world map like normal.

### Screenshot
![004f0021](https://user-images.githubusercontent.com/51846125/181698299-26e6cfa0-6d38-409f-ab28-1df630e576fa.png)

### Savegame
Where? [You never explained that!](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md) I can’t post my savegame if you don’t tell me where it’s stored!

**Comment by NovaRain** [comment]
Savegames are in `data\SAVEGAME\` folder.

**Comment by Anarcho-Bolshevik** [comment]
> Savegames are in `data\SAVEGAME\` folder.

![](https://user-images.githubusercontent.com/51846125/181701276-3ceb63f1-a196-4b7b-8306-dcb988e4a977.png)

**Comment by NovaRain** [comment]
Check your `C:\Users\<username>\AppData\Roaming\Fallout2\` directory. Generally it's not recommended to install old games under "Program Files".

**Comment by Anarcho-Bolshevik** [comment]
> Check your `C:\Users\<username>\AppData\Roaming\Fallout2\` directory. Generally it's not recommended to install old games under "Program Files".

![](https://user-images.githubusercontent.com/51846125/181702201-48fd9051-4bb5-402f-b4de-1d9144002607.png)

**Comment by NovaRain** [comment]
Yes, look inside of it. Or just search "SLOT##" folder names for your savegames.

**Comment by Anarcho-Bolshevik** [comment]
> Yes, look inside of it. Or just search "SLOT##" folder names for your savegames.

![](https://user-images.githubusercontent.com/51846125/181702962-454f2538-9481-491b-9e7b-8e49a5dbc1c0.png)

**Comment by burner1024** [comment]
I don't know, try system-wide search for `SAVEGAME`

**Comment by Anarcho-Bolshevik** [comment]
Never mind, I bypassed the problem by creating a SAVEGAME folder in _Fallout 2_'s data folder.

[Village crash.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9223660/Village.crash.zip)

**Comment by burner1024** [comment]
need crash debug.log too

**Comment by Anarcho-Bolshevik** [comment]
> need crash debug.log too

Where is that stored?

**Comment by burner1024** [comment]
game dir

**Comment by Anarcho-Bolshevik** [comment]
> game dir

You mean C:\Program Files (x86)\Fallout 2 ? It isn’t there. I modified ddraw.ini and fallout2.cfg and intentionally crashed the programme several times. It isn’t there.

[Here, these are the exact ddraw.ini and fallout2.cfg files that I used today.](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9224146/lorem.ipsum.zip)

**Comment by burner1024** [comment]
Your fallout2.cfg is awfully short.
How about you install another copy of F2 into, say, `C:\Games\Fallout2`, install RPU on top, then you can just copy the savegames and try to reproduce/find debug.log again.
Because you're having some very strange issues.

**Comment by Anarcho-Bolshevik** [comment]
[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9224724/debug.log)

**Comment by burner1024** [comment]
I could get a crash from this save. But not if you save after killing and load that save.
Strange heap messages in the log. @NovaRain they mean anything to you?

**Comment by NovaRain** [comment]
Not sure about the heap messages, but I'm more curious about the tons of "obj is NULL" as there are critter scripts that supposedly belong to NPCs in Vault 15 (Zeke & Dalia).

**Comment by burner1024** [comment]
yes, I noticed that too

**Comment by burner1024** [comment]
They aren't on the map.
What I find strange is that comes from `self_can_see_dude`. Since that's just `obj_can_see_obj(self_obj,dude_obj)`, and `dude_obj` always returns dude, I assume that `self_obj` is nul.
I went to V15 to check on Zeke, he is alive and well. Went back to village, same spam.
It appears that for some reason the engine didn't unload their scripts when leaving V15 and entering village.
Or maybe map ids somehow messed up internally, and scripts are loaded on the wrong map? But there's only Dalia and Zeke.

**Comment by Anarcho-Bolshevik** [comment]
I, Anarcho‐Bolshevik, do hereby solemnly swear that I neither used any cheats, nor any trainers, nor any editors for _Fallout 2: A Post Nuclear Role Playing Game_ ever since I reinstalled it this year. That is the truth, the hole truth, and nothing but the truth.

I acquired my latest copy of _Fallout 2_ from archive.org because my previous copy was no longer functional after several years of disuse. I completely uninstalled my old copy and installed this one into Program Files (x86) using the HUMONGOUS installation option. After reinstalling _Fallout 2_, I clicked the first link [here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/releases/tag/v26) and installed the RUP (including its QoL improvements) in English for the first time. That is the **only** unofficial programme that I installed.
![](https://user-images.githubusercontent.com/51846125/181903336-2229a933-8928-445c-8c3e-1885e6c22a74.png)
After installing the RUP, I beat this sequel once without any problems. Only when I started this new playthrough did I experience a crash.

**Comment by burner1024** [comment]
Well, for now, if you just save and load after slaughter, you should be able to use the Highwayman.
We'll continue looking into this.

**Comment by Anarcho-Bolshevik** [comment]
That can work. Sometimes exiting during combat can also work. But after exterminating all of the inhabitants and then saving, [I managed to produce this.](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9226425/lorem.ipsum.zip)

**Comment by burner1024** [comment]
Do you have a save prior to first entering the village?

**Comment by Anarcho-Bolshevik** [comment]
I’m afraid not. I overwrote it weeks ago.

**Comment by NovaRain** [comment]
I have one: [ToVillage.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9366323/ToVillage.zip)

**Comment by burner1024** [comment]
> I have one: [ToVillage.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9366323/ToVillage.zip)

This from RP or RPU? Can't load on RPU.

**Comment by NovaRain** [comment]
RPU with Pixote's updated maps.

**Comment by burner1024** [comment]
I tried to resave the map, doesn't change anything, so I guess it will have to be recreated.

**Comment by NovaRain** [comment]
> I tried to resave the map, doesn't change anything, so I guess it will have to be recreated.

I asked Pixote if he can recreate the map, we only need to add the scripts and do some misc work.

**Comment by burner1024** [comment]
OK, Pixote recreated the map, and @NovaRain provided script fixes. This should likely fix this issue, but you'd need a fresh playthrough to be sure.
