### ISSUE TITLE
Broken Hills ending bug

### ISSUE THREAD

**Issue by DrRamses** [BGforgeNet/Fallout2_Restoration_Project#150]
### What happened
I completed the quest "Find the missing people for Marcus" and put the anti-mutant conspiracy in jail. However, upon completing the game I received Ending C for Broken Hills (the race war ending).
### What you expected to happen
I was supposed to receive Ending B (the peaceful dispersion, i.e. the good ending), however this didn't play out. I tried looking for answers online, and found a thread with the same issue which seemed to imply that if you talk to Jacob the mod automatically treats it as though you sided with him. They also said something about being able to tell Marcus about Dr. Henry but I never saw the option in this updated version. https://www.nma-fallout.com/threads/fallout-2-restoration-project-2-1-2b-unofficial-expansion.193435/page-30
### Screenshot
![ezgif-4-747a524978](https://user-images.githubusercontent.com/111166135/184467904-53701192-38d0-4a72-9297-89f8a1115d57.jpg)

### Savegame
[ARDEAD.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9330757/ARDEAD.zip)

**Comment by DrRamses** [comment]
[ENCFITE.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9330780/ENCFITE.zip)
Here's the save right after beating Frank Horrigan for further reference.

**Comment by NovaRain** [comment]
If you already have Marcus joined your party, you need to take him back to Broken Hills to have the dialog option about Dr.Henry.

**Comment by DrRamses** [comment]
I'll do that & replay the oil rig to see if that changes anything, not looking forward to that electrical puzzle again.

**Comment by NovaRain** [comment]
Also, a savegame requires the whole "SLOT##" folder, individual .sav files have no use.

**Comment by DrRamses** [comment]
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9330834/SLOT01.zip)
My bad, I'm new to this.

**Comment by burner1024** [comment]
That's what the [guide](https://f2rp.bgforge.net/#bh) says

> You can now tell Marcus about the NCR scientist's mutant experiments. If you have already recruited him, you can still tell him about it as long as you are in Broken Hills. Marcus will thank you and tell you he'll never forget, other than that you get no XP or other reward. The caravan run to NCR will also get canceled for fear of poisoned goods. If you know about Dr Henry's experiment and don't tell Marcus, Broken Hills will get the racial wars ending.

**Comment by DrRamses** [comment]
I'm an idiot, my bad.

**Comment by burner1024** [comment]
I think you're a bit harsh on yourself =).
I didn't know that, and it's not obvious. Maybe the dialog can be improved. Need to take a look at that.

**Comment by burner1024** [comment]
OK, I think it doesn't make much sense.
1. If you never know about the serum, why would it any different from not telling Marcus? I think the endings should be the same in those cases, either both cause war, or neither.
2. How is someone in NCR developing serum cause a war in BH? Especially if _no one knows_ about it. Would make more sense the other way around.

So, I think the optimal solution is to have this dialog option to just disable the caravan, and maybe add a little XP reward to telling Marcus.

**Comment by burner1024** [comment]
Original quest design involved wiping all the mutants from Broken Hills somehow, which is why it affected the ending.
Now it has no effect on the ending, and telling Marcus provides a minor XP/karma reward.
