### ISSUE TITLE
Can I propose minor changes to the English dialogue?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#152]
I noticed that there are still quite a few punctuation errors ([like an extra parenthesis](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/dcaddct2.msg)) and even occasional spelling errors in the dialogues and monologues. Admittedly they are all pretty minor, and I am sure that you have higher priorities at hand, so I would prefer to propose (or make) these adjustments myself. It looks like you need to create a branch for data/text/english/dialog, though.

**Comment by burner1024** [comment]
You can propose, however note that incorrect spelling is not always a mistake, sometimes it's deliberate to convey the way of speaking.

**Comment by Anarcho-Bolshevik** [comment]
I’ll certainly keep that in mind… so, how do I submit my drafts?
