### ISSUE TITLE
Why does Dogmeat talk like a Hubologist?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#154]
### What happened

Usually when I pick up Dogmeat, his monologues in combat are based on the Khans’. I’ve noticed this since patch 1.02(!) but I’m assuming that this obvious peculiarity must have been intentional (for some reason) seeing as how it’s gone untouched for so long. However, I’ve noticed that sometime after I wiped out the Hubologist HQ, he now talks like a Hubologist in combat.

### What you expected to happen

I expected him to continue talking like a Khan (though I don’t think that he should be speaking at all).

### Screenshot

![imagen_2022-08-16_233154947](https://user-images.githubusercontent.com/51846125/185035165-c3592f81-9487-49ba-91b6-de3af43c1d04.png)

### Savegame

[oh god somebody please end my suffering already.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9356357/oh.god.somebody.please.end.my.suffering.already.zip)

**Comment by burner1024** [comment]
Whaaaat. What trickery is this.
I've never seen Dogmeat do that, presumably because I very rarely take him, but I can reproduce this.
And he doesn't even have any combat floats scripted...

**Comment by Anarcho-Bolshevik** [comment]
After you pick him up, you may have to progress through the story like normal for a bit before his monologues appear, but otherwise this peculiarity should be easy to trigger. Out of curiosity, I did a [couple](https://nma-fallout.com/search/143209150) of [searches](https://nma-fallout.com/search/143209347) to see if anybody else brought this up, but I found no relevant results. Nor could I find anything on the [_Fallout_ wiki](https://Fallout.fandom.com/wiki/Dogmeat_(Fallout)) mentioning this.

Honestly, for such an old and obvious glitch, it’s pretty hard to believe that nobody thought to report or even comment on it until now. That’s why I started wondering if it was intentional. I know that Dogmeat is one of the least accessible NPCs in _Fallout 2_, but twenty‐three years should be more than enough time for somebody to mention this online.

I’ll understand if you think that I must be playing some sort of prank on you; that sounds more probable to me than what I just described, too.

**Comment by NovaRain** [comment]
In your save, Dogmeat is using Elron(Hubologist) AI packet instead of his original one for some reason.

**Comment by Anarcho-Bolshevik** [comment]
Try taking Dogmeat to Vault 15 and clear out the Khans starting with Darion. I can do that myself, but it’ll take me longer.

**Comment by NovaRain** [comment]
The fastest way to check the case in your game:
1. Put this script: [gl_testkey.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9366853/gl_testkey.zip) in your `data\scripts\` folder.
2. Set `StartingMap=rndcafe.map` in ddraw.ini, start a new game to get Dogmeat right away.
3. Press V key with Dogmeat in your party to see the printed message.

**Comment by Anarcho-Bolshevik** [comment]
Gentlepeople, I have located the trigger. Here are your steps:

1. Recruit Dogmeat any way and any time you like
2. When conversing with him, click on COMBAT CONTROL
3. Set Dogmeat’s Disposition to either **Berserk** or **Aggressive**

That’s it.

**Comment by NovaRain** [comment]
Switching between his disposition settings causes his AI packet value to keep decreasing, other dog type companions or other party members don't have such issue, weird.

**Comment by NovaRain** [comment]
OK, the cause is the incorrect order of his AI packets. Here are the fixed files for RP repo:
[Dogmeat_AI_fix.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9367620/Dogmeat_AI_fix.zip)

Maybe also change the default AI packet number in his protos (00000342.pro-00000348.pro) because with the corrected order, now he's default to the unsettable "coward".

**Comment by burner1024** [comment]
Why does order even matter? Is it something hardcoded? I don't see `AI_PARTY_DOGMEAT` constants used anywhere.

**Comment by NovaRain** [comment]
The disposition presets for party members are [defined with constants](https://github.com/sfall-team/sfall/blob/master/sfall/FalloutEngine/Enums.h#L836).
When the player selects a new preset, the engine calls `ai_set_disposition(party_member_obj, disp)`, which has a calculation for new AI packet number like this:
`new_ai_packet = curr_packet_num - (disp - curr_disposition)`

So for Dogmeat's case, when you select "Berserk" (he's in Custom by default), it will be:
new_ai_packet = 167 - (4 - 0) = 163 (Tough Khan)
And further selection is just getting worse.

**Comment by burner1024** [comment]
Hmm but still not clear why crash.
I'm thinking about maybe 2-phasing the fix: force switch and lock Dogmeat to a single working AI packet, and next version release fixed files and re-enable packet selection.
But it seems that any changes to ai.txt cause crashes, even in saves that don't have Dogmeat for some reason.

**Comment by NovaRain** [comment]
> Hmm but still not clear why crash.

Not exactly sure, probably data block mismatch, because you can see "Missing AI Packet" in debug log if you use the "fixed" ai.txt to load existing saves.

> But it seems that any changes to ai.txt cause crashes, even in saves that don't have Dogmeat for some reason.

All party member protos are saved in the savegame, no matter one is in your party or not.

**Comment by burner1024** [comment]
Let's do that for the time being, and keep the full fix for when we break backwards compatibility anyway.
