### ISSUE TITLE
Inaccessible enemy in the Mountain Cavern

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#155]
### What happened

After clearing out a horde of Floaters on a random encounter, I went inside the cavern behind my party and cleared out nearly all of the creatures in there except one that spawned outside of the cavern’s boundaries. (This applies to Deathclaws, Radiscorpions, and likely other creatures, too.)

### What you expected to happen

Captain Obvious here to save the day: they should all be **within** the cavern’s boundaries, never _outside_ of them, thereby making them completely inaccessible.

### Screenshot
![wat](https://user-images.githubusercontent.com/51846125/185260389-32ecc161-409f-4aa6-9585-803c7d05b546.png)
![wut](https://user-images.githubusercontent.com/51846125/185260390-ab28a28d-d90f-415d-9923-e284d34738cc.png)

### Savegame
[Radiscorpion develops clever new battle tactic.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9366594/Radiscorpion.develops.clever.new.battle.tactic.zip)

**Comment by burner1024** [comment]
Critters are placed in a convoluted and not really secure way.
I think that the change should likely fix it, or at least make it happen less.
