### ISSUE TITLE
Why can’t I pick the Scrounger perk?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#156]
### What happened

Even though my character has a Luck of 10 and has advanced well beyond level 9, she can’t pick the [Scrounger](https://fallout.fandom.com/wiki/Scrounger_(Fallout)) perk.

### What you expected to happen

I was expecting it to become available at level 9. When I didn’t see it, I expected it to come later, but it never did. Did the wiki lie to me?

### Screenshot

![wut](https://user-images.githubusercontent.com/51846125/185281177-af463973-26c8-49ee-997a-64d496ce75b8.png)

### Savegame

[debug & save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9367214/debug.save.zip)

**Comment by NovaRain** [comment]
The [Scrounger](https://fallout.fandom.com/wiki/Scrounger_(Fallout)) perk is not available in Fallout 2, have you checked the manual instead of wiki?

**Comment by Anarcho-Bolshevik** [comment]
Ah, a false positive. All right, I’ll close this and correct the article.
