### ISSUE TITLE
Louisville Slugger Bugged

### ISSUE THREAD

**Issue by Nematocyst** [BGforgeNet/Fallout2_Restoration_Project#157]
### 
![image](https://user-images.githubusercontent.com/104546294/185696651-347d8dd3-8a3c-4f74-9ef3-f9887f89307c.png)
![image](https://user-images.githubusercontent.com/104546294/185696820-4f50b301-a0b7-4546-8e76-6bcab1dcdbba.png)

### Savegame

[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9384984/SLOT04.zip)

### Mods: Miria mod, NR Perkrate, Home Sweet Home, FO2 Tweaks, RPU latest version

**Comment by NovaRain** [comment]
It's normal because Sulik does not have the "club" weapon animation. NPCs cannot equip a weapon if they don't have the corresponding animation set.

**Comment by burner1024** [comment]
Correct, so unless new anims come long, this stays as is.
