### ISSUE TITLE
Game closing after first splash screen "Stand By"

### ISSUE THREAD

**Issue by LabAviator** [BGforgeNet/Fallout2_Restoration_Project#159]
### What happened
Installed a fresh copy of Fallout 2 from Steam. Installed the Fallout 2 Restoration Project Updated.
The game would crash on start up with the following message:

> Failure initializing input devices

Changed "BackgroundKeyboard=0" and "BackgroundMouse=0" to 1 respectively.
Now after the Fallout 2 launcher opens and clicking on "Play" the game starts in 800x600 resolution. The first splash screen with the "tribalised" power armor helmet and the text "Stand By" appears. The game exits, but the process "fallout2HR.exe" keeps running until manually ended.

### What you expected to happen
Expected the game to launch and play normally after a fresh install and the installation of Fallout 2 Restoration Project Updated.

### Screenshot
N/A
### Savegame
N/A

**Comment by burner1024** [comment]
What if you launch fallout2.exe?
