### ISSUE TITLE
rpu_rifle_animations.dat prevents npcs from equiping those rifles

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Restoration_Project#16]
With rpu_rifle_animations.dat in the ./mods directory npcs such as Cassidy and Vic will not equip weapons which use this animation. Probably because they don't have the animations for these weapons.
I don't know if it is possible to allow npcs to use their default animations? Otherwise it should probably be mentioned somewhere. My character didn't use rifles so I didn't even notice the new animation, just that Vic didn't want to equip a hunting rife for seemingly no reason.

Savegame with Cassidy, Vic, shotgun and a hunting rifle for testing.
[SLOT13.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3638855/SLOT13.zip)

Edit: Maybe also rpu_wakizashi_animations.dat? I haven't found any weapons which use this animation yet.

**Comment by burner1024** [comment]
> Probably because they don't have the animations for these weapons.
The animations are there, so I'm not sure what's the problem. I'll check this.

**Comment by burner1024** [comment]
Looks like all the files are [there](https://github.coam/BGforgeNet/Fallout2_Restoration_Project/tree/master/components/rifle_animations/art/critters). @Novarain, do you have any idea what could be the problem?

**Comment by NovaRain** [comment]
I didn't use RPU. My guess is you're using the default npcarmor.ini which doesn't specify extra weapon animation codes for Vic and Cassidy.

**Comment by burner1024** [comment]
Ah, it also needs customizing npcarmor.ini. Thanks, that's helpful.

**Comment by NovaRain** [comment]
As long as there are no weapon protos using new anim codes, leaving the settings shouldn't have any effect.

**Comment by burner1024** [comment]
Yes, adding the extra codes works.
Since you already ship `npcarmor.ini` with RP NPCs and adding the settings doesn't break anything, maybe change the defaults then?

**Comment by NovaRain** [comment]
Yes, I'll add those extra codes to default npcarmor.ini in next modderspack.

**Comment by burner1024** [comment]
Great, waiting for the next modderspack release then.
