### ISSUE TITLE
V.26: you have overwritten the rp ddraw ini

### ISSUE THREAD

**Issue by maks2491** [BGforgeNet/Fallout2_Restoration_Project#161]
### What happened
I download fallout 2 from steam, download RPU_v26, and I started a new game. I get a red text saying you have overwritten the rp ddraw ini. 

### What you expected to happen
I expected no issues with ddraw.ini

### Screenshot
See attached
### Savegame
No saved game, new player, new game, first time trying fall out 2. 

Thank you for all your hard work. Look forward to playing this mod and game.

![Fallout 2 ddraw](https://user-images.githubusercontent.com/80310414/195493138-c252747c-b715-444d-9ad9-fd57215391a0.png)

**Comment by burner1024** [comment]
Your screenshot shows that you run RP, not RPU.

**Comment by maks2491** [comment]
I install RPU_26 after i download the RP, but I guess it is not applying. How would I fix that?

**Comment by maks2491** [comment]
I uninstall RP form the game file and install RPU.26, it fixed it. I cannot wait to try this new game. Thank you so much!!!!
