### ISSUE TITLE
Car teleportation

### ISSUE THREAD

**Issue by ondrej-kuda** [BGforgeNet/Fallout2_Restoration_Project#162]
### What happened
Traveling with car & teleportation events
- When Sulik's sister if found, the story moves to the village and the car is parked at the entrance to the village location.
- When Johny is rescued from the Slag caves, the story moves to Modoc, but the car remains at Ghost farm. One has to go there on foot.

### What you expected to happen
I expected that the car is 'NPC' and should move with me.

**Comment by marstem** [comment]
Shouldn't we remember Brahmin drive from NCR here =)

**Comment by burner1024** [comment]
- It probably does make sense to move car from Ghost farm (likely it's not included in scripts because normally player doesn't have the car at that point)
- Brahmin drive is a different matter, it's explicitly on foot, or at least mounted, not on car, so no change is warranted there.
