### ISSUE TITLE
Typo: Child floating text

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#163]
### What happened
The floating text for generic children ([mcchild.msg](
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/mcchild.msg) and [kchild.smg](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/kchild.msg)) says

{183}{}{I bet you do to bathe.}

### What you expected to happen
I'm not sure what this floating text was supposed to be. I would have thought it was "I bet you don't bathe" but children's floating text for positive kharma characters is also says

{179}{}{You don't smell that bad.}

I mean kids say illogical things all the time but really any generic comment could be used as a replacement.

### Screenshot
I don't have a screenshot as I actually wrote this down for a playthrough I did a year ago and I don't have the save file anymore. However, I would imagine referencing the specific typo in github should be good enough though. 

### Savegame
See above

**Comment by burner1024** [comment]
Actually, `mcchild` says `I bet you do bathe`, which is what I think is correct.

**Comment by MarbledModulator** [comment]
good catch
