### ISSUE TITLE
Typo: Phoenix Armor Implants text (perks.msg)

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#164]
### What happened
[perks.msg](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/game/perk.msg) states

{1177}{}{You have inherent protection against energy attacks.}     # Phoenix Armor Implants
{1178}{}{You have extra inherent protection against energy attacks.}  # Phoenix Assault Enhancement

I think these also provide protection against fire

### What you expected to happen
Something like this

{1177}{}{You have inherent protection against energy attacks and flame attacks.}     # Phoenix Armor Implants
{1178}{}{You have extra inherent protection against energy attacks and flame attacks.}  # Phoenix Assault Enhancement

### Screenshot
I don't have a screenshot as I actually wrote this down for a playthrough I did a year ago and I don't have the save file anymore. However, I would imagine referencing the specific typo in github should be good enough though. 

### Savegame
See above

**Comment by burner1024** [comment]
Energy weapons being a separate category does add some ambiguity.
`energy attacks and flame attacks` seem overly verbose though, maybe just `thermal attacks`. That's how it's referred to in dialogs, anyway.

**Comment by MarbledModulator** [comment]
Whatever you think
