### ISSUE TITLE
Code error in John Bishop's script when asking "What's this guy's health like? Any illnesses?"

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#166]
### What happened
Unrelated to your mod, I was going through the game files looking for all the times "dude_iq" is called out and think I found a logic error.

John Bishop asks you to kill Roger Westin and Carlson. When he is telling you about each of these quests, the Chosen One can ask line 414 of [ncbishop.msg](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/ncbishop.msg) if he meets certain stat and skill requirements.
`{414}{}{What's this guy's health like? Any illnesses?}`

One of them requires dude_iq<7 and the other code requires dude_iq>=7. This doesn't make sense

762-763 of [ncbishop.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/newreno/ncbishop.ssl) says
```
   if ((dude_iq<7) or (has_skill(dude_obj, SKILL_DOCTOR)>50) or (has_skill(dude_obj,SKILL_FIRST_AID )>100)) then begin
      NOption(414, Node046, 004);
```
573-574 of [ncbishop.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/newreno/ncbishop.ssl) says
```
   if ((dude_iq>=7) and ((has_skill(dude_obj, SKILL_DOCTOR)>50) or (has_skill(dude_obj,SKILL_FIRST_AID )>100))) then begin
      NOption(414, Node026, 004);
```

### What you expected to happen

I think 762-763 of [ncbishop.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/newreno/ncbishop.ssl) should say
```
   if ((dude_iq>=7) or (has_skill(dude_obj, SKILL_DOCTOR)>50) or (has_skill(dude_obj,SKILL_FIRST_AID )>100)) then begin
      NOption(414, Node046, 004);
```

### Screenshot
I found this while browsing the code, not while playing the game so I don't have a screenshot or savegame.

### Savegame
I found this while browsing the code, not while playing the game so I don't have a screenshot or savegame.

**Comment by burner1024** [comment]
I agree, although first op should still be `and`, not `or`.

**Comment by MarbledModulator** [comment]
good catch
