### ISSUE TITLE
Buster's shop hours

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#167]
### What happened
Buster's shop hours are 08:01 to 23:59.

Line 118 of [scbuster.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/ncr/scbuster.ssl) says
`   if (time > 800 and time < 2400) then`

I would imagine store hours of 08:00 to 24:00 was intended. Stores in real life don't have hours of 08:01 to 23:59.

When I first played Fallout 2 many many years ago, I was really confused why his store wasn't open whenever you would use Pipboy timer to wait until the next day 08:00. Compounding this, if you talk to him at 08:00, he will attack you if you don't run away within 10 seconds. After I understood his store opens at 08:01, it was always a little annoying to then use the pipboy to wait another 10 minutes.

### What you expected to happen
Line 118 of [scbuster.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/ncr/scbuster.ssl) to say
`   if (time >= 800 and time <= 2400) then`

### Screenshot
I don't have a screenshot as I actually wrote this down for a playthrough I did a year ago and I don't have the save file anymore. However, I would imagine referencing the specific issue in github files should be good enough though.

### Savegame
I don't have a screenshot as I actually wrote this down for a playthrough I did a year ago and I don't have the save file anymore. However, I would imagine referencing the specific issue in github files should be good enough though.

**Comment by burner1024** [comment]
Makes sense to open at 8 sharp, waiting extra minute is an annoyance. I don't see much difference for closing hours.
