### ISSUE TITLE
Enhancement: Doctors healing NPCs and crippled limbs

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#168]
I was looking through some of the closed issues to see what enhancements you considered in-scope or out-of-scope and was interested by [closed issue 39](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/39)

You expressed possible interest in incorporating that change but closed the issue due to a lack of response.
> I think it could be RP material, but I'll need the full list of doctors with names and their behaviour and corresponding saves for all of them to make a decision and maybe implement it.

Per the request you made in [closed issue 39](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/39), I created a table that Iists all of the doctors and their services
https://fallout.fandom.com/wiki/Fallout_2_doctors#Locations_and_services

The only thing that differs between the Restoration patch and that table is that killap added restocking stores to Doc Johnson and Doc Jubilee.

I thought we could discuss my proposed changes before I get  the "corresponding saves" you requested. It's been two  years since [closed issue 39](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/39) and I wanted to check that you haven't changed your mind about this whole idea. I'll talk more about this at the end of my post but I'm happy to write the code if you agree with my proposed changes but don't want to do the work.

**Add "Heal NPCs" functionality to 5 doctors**
I don't really see any reason why the following doctors couldn't or wouldn't want to heal NPCs. It seems random that these doctors don't heal NPCs but [others do](https://fallout.fandom.com/wiki/Fallout_2_doctors#Locations_and_services). My guess is these level creators ran out of time or didn't realize other levels' creators decided to have their doctors heal NPCs.
- [Doc Jubilee](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/ncr/scdocjub.ssl)
- [Doc Jones]( https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/vault15/bcjones.ssl)
- [Joseph](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/vault13/ocjoseph.ssl)
- [Dr. Fung](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/sanfran/fcdrfung.ssl)
His dialogue has [unused dialogue references](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/text/english/dialog/fcdrfung.msg) to party healing
```
{106}{}{Yes. I need a doctor for my friend.}
{121}{}{A friend of mine needs to be healed.}
```
His script also references unimplemented party healing references `(If_Party_Has_Injured)` and `procedure NodeHealParty begin`
- [ACE](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/sanfran/fsface.ssl)

**Add "Fix crippled limbs" functionality to 2 doctors**
It seems random that the following doctors don't fix crippled limbs when less qualified facilities can fix crippled limbs. Though some characters reference why they can't fix crippled limbs in their .MSG's (Doc Jones says "I'm sorry, but I don't have the proper facilities to perform surgery" and Joseph says "I'm sorry, but I'm not a medical doctor and I can't perform surgery" for example), [Doc Johnson's dialogue](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/rcdrjohn.msg) and [Doc Jubilee's dialogue](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/text/english/dialog/scdocjub.msg) don't mention anything about crippled limbs.  
- [Doc Johnson](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/redding/rcdrjohn.ssl): He has an Auto-Doc, was trained at Vault City, and seems totally qualified to fix broken limbs
- [Doc Jubilee](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/ncr/scdocjub.ssl): If Gecko, Redding, and Broken Hills can handle broken limbs, I would imagine the main hospital in the NCR capital would offer this service. If you're unsure about Doc Jubilee's competency at this, it might be funny if he had a 50% chance of not fixing the limb and just causing damage or some other negative effect instead.

**Add "Remove radiation and poison" functionality to 1 doctor**
- Dr. Fung: This one is debatable but I thought it's worth mentioning. I think Dr. Fung is supposed to be the most knowledgeable doctor in the game. It seems like an oversight he can't remove radiation and poison, especially since he has a functioning Auto-Doc in his hospital.

I recognize I am proposing enhancements so its understandable if you think some or all of these are out of scope of the Restoration Project.

If you agree with the changes but dont' want to write the code, I can take a crack at creating the code if you would prefer. I've never actually made a Fallout 2 mod before but I'm very familiar with Fallout 2's .SSL files and .MSG files. I'll be able to write all the code but I am sure I will have questions and the final product will most likely have some mistakes. Not sure if that would just be more work for you than you just doing yourself.

Let me know what you think the above proposed changes.

**Comment by burner1024** [comment]
From strict PoV, the only restoration would be Dr. Fung.
Altogether, it's a minor convenience feature that doesn't make much difference. I'm not too interested in working on that, but if you want to send a pull, that's possible.
It's a pain to maintain different scripts for upu and rpu, so I suggest that you make minimal changes and gate the entire feature behind an ini setting.

**Comment by MarbledModulator** [comment]
Sure, will do. I'll start work on it this weekend.

**Comment by MarbledModulator** [comment]
Burner,
I don't think I'll be able to get to work on this anytime soon. I switched to Linux a while ago and haven't been able to get Fallout working on it yet. Maybe we should close this issue for now and can reopen it whenever I get everything working and the script updated?

**Comment by burner1024** [comment]
As you wish.
