### ISSUE TITLE
Female default character use new male animations for assault rifle burst

### ISSUE THREAD

**Issue by c0sm1k** [BGforgeNet/Fallout2_Restoration_Project#169]
### What happened

Default female model for player use new male animations for rifle when using burst mode with FN-FAL.

### What you expected to happen

female characters should use female animation only

### Screenshot

![Fallout 2 RPbug sc1](https://user-images.githubusercontent.com/118918737/203596120-878fa040-bb27-4dcf-a2fd-b0d6aa6b0034.png)
![Fallout 2 RPbug sc2 ](https://user-images.githubusercontent.com/118918737/203596141-8ec4ef2c-a338-4704-b6e1-6298250e6a6a.png)

### Savegame
[SaveGame SLOT32.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10077337/SaveGame.SLOT32.zip)

**Comment by burner1024** [comment]
Extract this into `data/art/critters`, should fix it.
[Uploading 1.zip…]()

**Comment by c0sm1k** [comment]
Thanks mate. Also i noticed that by default, keybinds are overlapping with party member mod. N key is used to change party member's ammo type while it also change your fire mode. Btw, i had hard time figuring out that the D key toggle burst mode for party members. Maybe a quick mention of this feature on mod description, or a reworked F1 screen, could prove it's helpfullness.  But it's only QOL, the mod is awesome. I'm glad ppl still showing love to this game. Keep up the good work.

**Comment by burner1024** [comment]
Not sure what do you mean by party member mod.
There's [party orders](https://github.com/BGforgeNet/Fallout2_Party_Orders). N is not used by default there.

**Comment by c0sm1k** [comment]
I'm sorry the comment was very inacurate.
Indeed party order use "B" key for (Dx code : 48) while it's also used by default to change weapon

party_orders.ini : 
; by phobos2077; switch ammo types (AP/JHP) key: B (48)
AmmoTypeOrderKey=48

**Comment by burner1024** [comment]
That one is [Ctrl-B](https://github.com/BGforgeNet/Fallout2_Party_Orders/blob/c6b5434305a60d56421716421af716e6810742d4/mods/party_orders.ini#L22).
You must've got yours from some other source or changed manually.

**Comment by c0sm1k** [comment]
Sorry, i'm dumb. I must have made the mistake when i remaped all keybinds, thinking it was overlapping.
