### ISSUE TITLE
Abbey dialog bug while repairing water pump

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Restoration_Project#17]
In the Abbey if I talk to the merchant by the water pump and then use the water pump I get a dialog box.

This dialog box seems bugged. None of the choices react when clicked. When I click on the second dialog option the pointer turns to 'use skill' pointer (as if you pressed 2). I can also still press escape and get the menu screen (which you normally don't get in dialog) although the middle portion is obscured by the dialog options.

I load a new game while in this dialog the dialog box stays visible in the loaded game. So the only option is to press escape and exit the game.

[SLOT36.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3658745/SLOT36.zip)
![loaded game](https://user-images.githubusercontent.com/3510562/65705272-666b6880-e088-11e9-917a-1d75b01f299d.png)
![menu](https://user-images.githubusercontent.com/3510562/65705209-45a31300-e088-11e9-8de9-ced63fe9482f.png)
![skillpointer](https://user-images.githubusercontent.com/3510562/65705210-45a31300-e088-11e9-8cb1-4b45abad5cca.png)

**Comment by burner1024** [comment]
That's really something strange. You have sfall 4.2 now, right?

**Comment by jvs3** [comment]
yes, sfall 4.2.  I've just also tested with v4.1.9.1 and that had the same result.

**Comment by burner1024** [comment]
Do you have a pre-Abbey save (not visited it yet)?

**Comment by jvs3** [comment]
This is in Vault city just before the first time visiting the Abbey.
[SLOT34.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3658945/SLOT34.zip)

**Comment by burner1024** [comment]
Unzip this into data/scripts.
[siptbox2.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3659097/siptbox2.int.zip)

**Comment by jvs3** [comment]
Now it works. Thanks!
