### ISSUE TITLE
Stop Brahmin raids does not complete

### ISSUE THREAD

**Issue by Walayimuna** [BGforgeNet/Fallout2_Restoration_Project#170]
### What happened
I accept the quest to stop the Brahmin raids.
Deathclaws enter the map, 
Deathclaws speak, 
Character is teleported to the mid-north area of the map
Character says 'talking deathclaws, that's weird'

And nothing happened, regardless of my outdoorsman skill, there is no option to follow the Deathclaws, the area north-east of the map remains blocked by stones, if I return to Westin or the Ranch Foreman, they ask if I finished the job, only option is No, and I can't return to the pastures, even if I try to do that by pressing 6 on NCR region map.

### Savegame
[SLOT208.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10174678/SLOT208.zip)

**Comment by Walayimuna** [comment]
I'll try that, thank you

**Comment by Walayimuna** [comment]
[zax_debug_2022-12-07_20-53-40.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10180971/zax_debug_2022-12-07_20-53-40.zip)

Is this what you need?

**Comment by burner1024** [comment]
Yes.
Upon loading your save, I have this message in PDA, do you see it too?
![Captura desde 2022-12-08 08-22-17](https://user-images.githubusercontent.com/1279852/206333021-2fd5350e-e8b4-42f6-957a-8be3609a9434.png)

**Comment by Walayimuna** [comment]
I do not

**Comment by Walayimuna** [comment]
https://drive.google.com/file/d/12e7DZayrP5k81BKMdnVG8TPpwu9YKRXj/view?usp=sharing

I can't upload the video here, it's too big, 26 MB

**Comment by burner1024** [comment]
This is strange. I don't see anything obviously wrong.

**Comment by Walayimuna** [comment]
The quest message does not appear for me on the video, I don't know why it is not recording full screen, I played the game twice and it happened both times, was the only quest in the entire game I could not finish

**Comment by Walayimuna** [comment]
Is there anything else I can do ?

**Comment by burner1024** [comment]
Do you have another PC you could try this save on?

**Comment by Walayimuna** [comment]
I do not =/

**Comment by burner1024** [comment]
[siexit.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10205049/siexit.int.zip)
Extract this into `data/scripts` and try the encounter again.
It's not a fix, just debug. Let's see what it prints on the pda.

**Comment by burner1024** [comment]
Feel free to add any new info.
