### ISSUE TITLE
NPC & solar scorcher

### ISSUE THREAD

**Issue by ondrej-kuda** [BGforgeNet/Fallout2_Restoration_Project#172]
### What happened
I gave Cassidy solar scorcher in the EPA. Cassidy repeatedly (~10 times each turn) tries to reload the gun during the combat with the robots.

### What you expected to happen
Give up when no ammo (sun) is available? And change the gun.

**Comment by burner1024** [comment]
Show screenshot, add savegame.

**Comment by NovaRain** [comment]
You need to update [sfall (ddraw.dll in the game folder)](https://sourceforge.net/projects/sfall/). The bug is fixed in 4.3.6.
