### ISSUE TITLE
kcsajag.ssl & cult of personality

### ISSUE THREAD

**Issue by MarbledModulator** [BGforgeNet/Fallout2_Restoration_Project#173]
### What happened
I was looking through the code to better understand how fallout 2 engine work and think I stumbled across an error.

Lines 47-49 of [kcsajag.ssl](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/scripts_src/klamath/kcsajag.ssl) say

> #define rep_check_pass ( \
>    (TOWN_REPUTATION > 5) or \
>    (TOWN_REPUTATION < -5 and dude_perk(PERK_cult_of_personality)) \

### What you expected to happen
I don't think that bit of code makes sense. I think
`(TOWN_REPUTATION < -5 and dude_perk(PERK_cult_of_personality)) \`
was intended to be
`(TOWN_REPUTATION > -5 and dude_perk(PERK_cult_of_personality)) \`

However I searched for PERK_cult_of_personality in the rest of the repository to understand how it is normally used and suggest the following resolution instead.

> #define rep_check_pass ( \
>    (TOWN_REPUTATION > 5) or \
>    (dude_perk(PERK_cult_of_personality)) \

 This matches how PERK_cult_of_personality is used in all of the other .SSL's I looked at (I only looked at a dozen or so though) and matches the in-game description of the perk. "Your reputation is always positive to people."

### Screenshot
N/A. Found while looking at the code on github.

### Savegame
N/A. Found while looking at the code on github.

**Comment by burner1024** [comment]
This check is good.
