### ISSUE TITLE
Killed Badger like AHS-7 wanted, can't proceed

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#175]
### What happened

I accepted AHS‐7’s mission to assassinate Badger. I gunned him down and some of the people near him. I returned to AHS‐7 and I can’t tell him that I assassinated the target.

### What you expected to happen

I expected there to be a new dialogue option with AHS‐7 after I killed Badger.

### Screenshot
(I don't see how a screenshot would help with this, but oh well.)
![piss in my skull](https://user-images.githubusercontent.com/51846125/209549597-a81bb65e-8b31-42aa-ba69-98e918c617d8.jpg)

### Savegame

[for Hubbel.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10303398/for.Hubbel.zip)
Don't worry about the combat; my scumbag packs a Bozar, the Sniper perk, scores of stimpaks and plenty of Jet. You can't lose.

ETA: 
[Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger a Snake a Snake.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10306816/Badger.Badger.Badger.Badger.Badger.Badger.Badger.Badger.Badger.Badger.Badger.a.Snake.a.Snake.zip)

(The debug logs are in these slots, by the way.)

**Comment by burner1024** [comment]
Attach a save from the second screenshot, after killing Badger.

**Comment by Anarcho-Bolshevik** [comment]
Check my post now.

**Comment by burner1024** [comment]
I can see the issue in the second save, but can't reproduce going from the first:
![Captura desde 2022-12-27 15-33-59](https://user-images.githubusercontent.com/1279852/209637748-6b50b034-e5db-41b3-af75-55e02d8e4fb7.png)

Try killing him 1-2 times again, see if it works then?

**Comment by Anarcho-Bolshevik** [comment]
[have you eliminated this Badger.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10307074/have.you.eliminated.this.Badger.zip) (debug log included in slot)

Still nothing. I gunned down Badger and his girlfriend twice and I still can’t tell AHS‐7 about it.

**Comment by burner1024** [comment]
Girlfriend is the problem.
To proceed, you can set `GVAR_SAN_FRAN_BADGER` to 128.

**Comment by burner1024** [comment]
Have to make a fix for it yet.

**Comment by Anarcho-Bolshevik** [comment]
Oopsie.

**Comment by burner1024** [comment]
The scripts set bit flags of the GVAR, but then check full value.
Proper fix would be to change the logic to check individual bit flags.
However, as this is a plot critical quest, and the fix requires multiple changes in various scripts, I'm wary to go all the way. That will require full San Francisco playthrough.

For now I implemented a workaround for this particular situation.
