### ISSUE TITLE
Entering Village for Vault City Quest shows black screen

### ISSUE THREAD

**Issue by dlpnd** [BGforgeNet/Fallout2_Restoration_Project#176]
### What happened
I'm using the build commit hash: [33eb3d9d80d6d7e041bff7246fc8ae66d7ce7bd4](https://github.com/BGforgeNet/Fallout2_Restoration_Project/commit/33eb3d9d80d6d7e041bff7246fc8ae66d7ce7bd4)

And the latest release of sfall: [4.3.7](https://github.com/sfall-team/sfall/releases/tag/v4.3.7)

I have accepted to scout a Village in Vault City. Upon entering the map, everything is black. Saving and loading on the map fails.

I have attached a save in Vault City. Go to exit zone, and walk to the Village up north.

I have also attached 2 debug files, one loading the save game, and failing, and one with entering the map from Vault City.

### What you expected to happen
It would load the map normally

### Screenshot
![image](https://user-images.githubusercontent.com/11916166/209590782-84317e42-e972-429a-b58b-1329038c8da0.png)

### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10305118/SLOT01.zip)
[debug_load_save_in_village.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10305131/debug_load_save_in_village.log)
[debug_entering_map_and_exiting.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10305132/debug_entering_map_and_exiting.log)

**Comment by burner1024** [comment]
Guess rebuilt map from #149 is not doing so great.
I can enter the village in v26, so to proceed you can download the vill.map file and drop it into `data/maps`.
@NovaRain any ideas?

**Comment by NovaRain** [comment]
The save works fine on my v27 beta as well. Can enter the village and see dead mole rats, save/load on the map also works.
Since the repo snapshot doesn't have compiled scripts, and the village fix has script files edited and renamed, I'd guess that might have something to do with this.

**Comment by burner1024** [comment]
OK, so master branch is not in consistent state right now. Should probably be playable other than this map, but not sure.

**Comment by dlpnd** [comment]
All good, I'll grab vill.mp from the v26 tag, thank you.
