### ISSUE TITLE
Curtis oblivious to somebody stealing Mr. Nixon

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#177]
### What happened

After the Chosen One gave the Mr. Nixon doll to Curtis and stole it, Curtis continued talking to his plaything like nothing happened.

### What you expected to happen

The most logical solution would be to return Curtis to his sad state.

### Screenshot

![Nix](https://user-images.githubusercontent.com/51846125/209638627-4d8a88d4-bf88-48cf-b4d1-7b341a5c7969.jpg)

### Savegame

[don’t gamble with our securities.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10307026/don.t.gamble.with.our.securities.zip)

(Debug log is in the slot.)

**Comment by burner1024** [comment]
It would be nice to have him to go between states as you steal and plant the doll, but that would require more extra code (karma adjustments and stuff), so I went for the simplest solution.
