### ISSUE TITLE
Strange dialogue option with Lil’ Jesus Mordino

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#178]
### What happened

My high INT and high CHA (courtesy of some Mentats) character tried to have a conversation with Lil’ Jesus Mordino, specifically by selecting the options 1, 2, and 1, in that order. After failing a speech check, a mysterious dialogue option called ‘Error’ appeared.

### What you expected to happen

You tell me.

### Screenshot
![Error](https://user-images.githubusercontent.com/51846125/209753740-13da4049-24ce-43dc-afd9-e67edff6ddaf.jpg)

### Savegame
[1-2-1.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10311951/1-2-1.zip)
(Debug log is in the slot.)

**Comment by NovaRain** [comment]
Already fixed in #140.
