### ISSUE TITLE
Why is Marcus silent during this dialogue?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#179]
### What happened

I asked Marcus ‘I need to talk to you about your gear’ and then asked him ‘I need to know what kind of weapons you can use.’ Although his response was perfectly legible, there was no audio to accompany it. (No mouth movements either.)

Is the audio file completely absent or is it just not playing?

### What you expected to happen

I was expecting to hear Michael Dorn reading out this line.

### Screenshot

![Marcus silent dialogue](https://user-images.githubusercontent.com/51846125/210132807-e6833d26-acc0-4507-9ae2-abbe1a62bd83.jpg)

### Savegame
[lorem ipsum.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10327158/lorem.ipsum.zip)

**Comment by burner1024** [comment]
Just search the [text](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/47498f3f7425602bcf4aa316addc616a6cf1cddd/data/text/english/dialog/hcmarcus.msg#L437)

```
# New Marcus dialog for new party structure, waiting for Vocs, from Phrases 81 and 79
{20000}{mcs81b}{Right.}
{20001}{}{Heh. I can use just about any big gun, like rocket launchers or miniguns,
 and the big energy weapons. I ain't bad with my fists, and I'm a hell of a shot with grenades. I don't
 wear armor. They just don't make it my size.}
```
20 years later, still waiting I guess.

If you find an unused voice line in game files, feel free to raise an issue.
