### ISSUE TITLE
Can you add a tombstone for Scott Bennie?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#180]
Normally I am against requesting Easter eggs (especially since _Fallout 2_ has too many as it is), but in this case I would say that it is important enough to merit consideration. [Scott](https://www.thegamer.com/scott-bennie-fallout-dogmeat-eulogy) [Bennie](https://boardgamegeek.com/boardgamedesigner/5640/scott-bennie) was somebody who provided additional design for _Fallout_, most notably the Mysterious Stranger perk and naming of Dogmeat, and he died yesteryear (March 30, 2022) from pneumonia. Many other real people have their own tombstones in _Fallout 2_, so this would fit in well. I would be very impressed if you gave him some recognition in your project.

Like I said, it is just an Easter egg, so I’ll understand if you have to decline, but since the intention behind this one is relatively serious I thought that suggesting it would be worth a shot anyway.

**Comment by burner1024** [comment]
Not interested in working on that, although not opposed to pull requests either.

**Comment by Anarcho-Bolshevik** [comment]
I can’t make pull requests now.
