### ISSUE TITLE
Slavers Hostile for no reason

### ISSUE THREAD

**Issue by WhyamIdoingthistomyselff** [BGforgeNet/Fallout2_Restoration_Project#181]
### What happened
Upon finishing "Help Lara attack Tyler's gang", slavers in the Den turn hostile for no reason. They aren't hostile after first stage of attack near the church but they turn hostile after second attack when you crash Tyler's party and kill him.

### What you expected to happen
They clearly shouldn't turn hostile as it never happened to me before using killap's 2.3.3 version.

### Screenshot
![blabla](https://user-images.githubusercontent.com/122760818/212587075-26c60914-b8d2-4c35-9f33-41c3965d45ec.jpg)

### Savegame
Non-hostile slavers
[Non-hostile.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10422147/Non-hostile.zip)

Hostile Slavers
[Hostile.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10422153/Hostile.zip)

**Comment by burner1024** [comment]
I can't reproduce. Try replaying the fight.

**Comment by WhyamIdoingthistomyselff** [comment]
> I can't reproduce. Try replaying the fight.

I did, a couple of times and it always triggers the slavers after i complete the quest. There is a prostitute at Tyler's party and maybe she triggers it somehow? I'm gonna try replaying the entirety of den area tomorrow and report back how it went.

**Comment by burner1024** [comment]
> There is a prostitute at Tyler's party 

did you hit her?

**Comment by WhyamIdoingthistomyselff** [comment]
> > There is a prostitute at Tyler's party
> 
> did you hit her?

I tried both without difference. She does have a red outline so AI probably considers her an enemy.

**Comment by WhyamIdoingthistomyselff** [comment]
Update:
Did the entire Den area anew and I'm still encountering the same issue.

**Comment by burner1024** [comment]
ok, good that you've found the root cause.
