### ISSUE TITLE
Vaultcity courtyard crash fallout2

### ISSUE THREAD

**Issue by Gorgragar** [BGforgeNet/Fallout2_Restoration_Project#182]
Vault city crashes. only place ive had crash. a person on nomutants used my save game and had no issue. when I do vanilla FO2 I dont get the crash.. I used ctrl R at title screen to pick a city and went to inner vault city. that worked. I went to vctyctyd.map and it crashed. again with the courtyard(beginning area of vault city)  it is a The instructions at 1000431c referenced memory at 00000000 The memory could not be read from" error I get when it crashes. if I turn off the sound and enter vaultcity it will crash with no error message.. I have uninstalled and reinstalled many time.. going in and getting rid of everything that says fallout2.  it seems to me to bed an error with that map specifically on my machine.  where are the maps read from? the rp installer should put everything in the right place Id assume since a person was able to load my save game and get into vault city.  if you have any ideas.. or maybe a vaultcity.sav file I can throw in to my save game file?  I am not savy on this stuff much.  Ive dont the check disc scan no errors on my hard drive. ram is fine also. have a radeon grphics card.   game is not in program files  I also used the save game editor after the fact and added vault city to  my found places.. went to it and it poped up  courtyard and the inner city.. I could go to the inner city but when I traveled to the courtyard it crashed again.  hopefully you can help me with this have been loving the RP patch a ton and want to continue.
 thank you for taking your time to look at this.
 
this is the crash report. if the zip didnt work had to renam it from .7z to .ZIP also a saved game.
Version=1
EventType=APPCRASH
EventTime=133192179235334957
ReportType=2
Consent=1
UploadTime=133192179243547660
ReportStatus=268435456
ReportIdentifier=8c3d25e7-d83d-4e95-8a7b-e4c80fc508cb
IntegratorReportIdentifier=649360c9-b385-463a-829d-afb717cac1c9
Wow64Host=34404
Wow64Guest=332
NsAppName=fallout2HR.exe
AppSessionGuid=000031d4-0001-0424-66b1-65969431d901
TargetAppId=W:0006d3e7cfd3bd6060ca8032ef257cf916bb0000ffff!0000f6eb5e7dd988699f510677e4ac3b03bfbc878f17!fallout2HR.exe
TargetAppVer=1998//12//12:00:56:02!0!fallout2HR.exe
BootId=4294967295
ServiceSplit=51707904
TargetAsId=941
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=ba14974b9ce6b67749684769d2a1e7d7
Response.BucketTable=1
Response.LegacyBucketId=73335221811
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=fallout2HR.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=3671bf22
Sig[3].Name=Fault Module Name
Sig[3].Value=fallout2HR.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=3671bf22
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000c5d09
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19045.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=2beb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=2beba6fb4680d73a8c78ca7c24ccdb46
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=e04d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=e04d98114ac1043a67f9e3e8b99335bc
UI[2]=C:\Fallout 2\fallout2HR.exe
LoadedModule[0]=C:\Fallout 2\fallout2HR.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[6]=C:\WINDOWS\System32\win32u.dll
LoadedModule[7]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[8]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[9]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[10]=C:\WINDOWS\System32\USER32.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[12]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[13]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[14]=C:\Fallout 2\f2_res.dll
LoadedModule[15]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[16]=C:\Fallout 2\DDRAW.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[18]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[19]=C:\WINDOWS\System32\sechost.dll
LoadedModule[20]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[21]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[22]=C:\WINDOWS\System32\combase.dll
LoadedModule[23]=C:\WINDOWS\System32\ole32.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[26]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[27]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\Wldp.dll
LoadedModule[29]=C:\Fallout 2\d3dx9_31.dll
LoadedModule[30]=C:\WINDOWS\system32\ddraw.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\DCIMAN32.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\DSOUND.DLL
LoadedModule[34]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\winmmbase.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\UMPDC.dll
LoadedModule[37]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[38]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[39]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[40]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[42]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[43]=C:\WINDOWS\System32\SHCORE.dll
LoadedModule[44]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[45]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[47]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[49]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[50]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[51]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\dcomp.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\dinput.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\HID.DLL
LoadedModule[56]=C:\WINDOWS\SYSTEM32\inputhost.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[59]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[60]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[62]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[63]=C:\WINDOWS\System32\MMDevApi.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
LoadedModule[65]=C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
LoadedModule[66]=C:\Windows\System32\Windows.UI.dll
LoadedModule[67]=C:\Windows\System32\WindowManagementAPI.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\avrt.dll
LoadedModule[70]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2211.5-0\x86\MpDetoursCopyAccelerator.dll
LoadedModule[71]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2211.5-0\x86\mpclient.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\gpapi.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\TextShaping.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=2486
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221984176
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.789.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32731
OsInfo[19].Key=svolsz
OsInfo[19].Value=465
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.2486.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[30].Value=E7366588-F2C5-4AC2-A608-3A0B9AE796D3.1
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=fallout2HR.exe
AppPath=C:\Fallout 2\fallout2HR.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=979071BE82B4CEEE9EB193C187ABA9BD
MetadataHash=327809580
### Savegame
[Report.ZIP](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10522100/Report.ZIP)
[SLOT08..ZIP](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10522102/SLOT08.ZIP)

**Comment by burner1024** [comment]
Try to collect a debug package with [ZAX](https://github.com/BGforgeNet/zax).

**Comment by Gorgragar** [comment]
[zax_debug_2023-01-27_14-28-02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10522473/zax_debug_2023-01-27_14-28-02.zip)
this work? sorry never used ZAX

**Comment by burner1024** [comment]
The save works for me.
Not sure if that matters, but you should launch fallout2.exe, not fallout2HR.exe.

**Comment by Gorgragar** [comment]
Tried using the fallout2launcher.exe  and the fallout2.exe both crash a vaultcity still.

**Comment by burner1024** [comment]
Which RPU version do you have installed?
Did you install updated maps, by chance?

**Comment by Gorgragar** [comment]
I have the v26 from here and no I didnt install updated maps just went with the RPu patch on here.

**Comment by burner1024** [comment]
Do you have another PC to try it on? See #171.

**Comment by Gorgragar** [comment]
Unfortunately I do not.  I have seen about maybe 5 people talk about this issue out of I dont know how many so I know this is a rare occurrence.

**Comment by burner1024** [comment]
I have nothing else to suggest at this time, unfortunately.

**Comment by Gorgragar** [comment]
I was thinking it was a long shot.  so no worries. Thank you for your time. If I do happen to find a solution I will let you know.
