### ISSUE TITLE
McClure holodisk Option missing

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Restoration_Project#184]
https://fallout.fandom.com/wiki/Optimize_the_powerplant#Quick_walkthrough

### What happened
`Persuade [McClure] to optimize the disk for you.` option missing from the game

### What you expected to happen
I told McClure I repaired the plant and that was it, no option described found anywhere

### Screenshot
![image](https://user-images.githubusercontent.com/1309656/217040180-37044843-7b4d-4b6e-b49f-50b4b0afa00e.png)

![image](https://user-images.githubusercontent.com/1309656/217040145-edf6cf34-917b-4bdd-8f1b-0b3a0faddcd2.png)

![image](https://user-images.githubusercontent.com/1309656/217040317-a6fe48c3-3718-4913-81b8-f1a6c23a201d.png)

### Savegame

Save after first saying I repaired the plant: [SLOT11.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10667451/SLOT11.zip)

Save right before first saying I repaired the plant: 
[SLOT17.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10667482/SLOT17.zip)

**Comment by burner1024** [comment]
Why do you think there should be such an option?

**Comment by Owyn** [comment]
Cuz the guide in the wiki I linked says so? 
![image](https://user-images.githubusercontent.com/1309656/217042766-57f25a2f-c626-4cc2-97f5-51a19d6b8fbb.png)

**Comment by burner1024** [comment]
Oh, I didn't see that expanding thing.
Looks like persuading way is only for non-citizens.

**Comment by Owyn** [comment]
> only for non-citizens.

I mean, that's exactly the quest which gives you the citezenship... I wasn't one before reporting I repaired the plant and right after he makes you one, but still you can't give him the disk

**Comment by burner1024** [comment]
Yes, someone dropped the ball here. Although I'm not sure there's anything to do about this. The line clearly goes
`Hmmm. Well, I cannot allow you access to the Vault, but I could optimize the reactor disk for you.`
