### ISSUE TITLE
some doors can't be opened with an item

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Restoration_Project#187]
### What happened
tried all kinds of lockpicks, a crowbar, a bomb - still "that does nothing" on some rare doors - they seem to be using wrong script or no script at all unlike most doors so the lockpickless-gameplay is inconsistent 

### What you expected to happen
opened door

### Screenshot
![image](https://user-images.githubusercontent.com/1309656/217916784-724f1441-cdef-4a62-9d60-e9ce0b001009.png)
this door,
also 4th level door on the left of the Sierra Depo,
also locked doors in slaver camp where Sulik's sister was kept

### Savegame
[SLOT18.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/10700844/SLOT18.zip)

**Comment by burner1024** [comment]
You'll need to provide saves for the rest.

**Comment by Owyn** [comment]
This also fixes crowbar use, right?

here's the door in Sierra
![image](https://user-images.githubusercontent.com/1309656/218077502-e2939620-41d4-465e-9bb5-655e4d82533b.png)
[SLOT12.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10706692/SLOT12.zip)

**Comment by burner1024** [comment]
It should.

> here's the door in Sierra

I can use electronic lockpick on it. What's the problem?

**Comment by Owyn** [comment]
> What's the problem?

Using the crowbar on it says "that does nothing" even thought I opened previous 3 floor doors that way and look at the description - " a rusty old lock " - how do you even use the electronic lockpick on it? xD

**Comment by burner1024** [comment]
This is what is says for me.
![Captura desde 2023-02-10 19-58-50](https://user-images.githubusercontent.com/1279852/218098304-35b7735f-fa23-451d-8218-7ff77e2b5a31.png)
Electronic lock can be old and rusty.

**Comment by Owyn** [comment]
I used binoculars action to see further for it to say that, anyway, that door is exactly the same as 3 other doors on other floors I opened with my crowbar so I expected it to work here too... 
I mean it's a role-playing game, locking off areas just to lock-pick masters is a bit off, that's why crowbar exists

**Comment by burner1024** [comment]
When using the crowbar, it says "you are too weak to bust the lock", first line in my screenshot.

**Comment by Owyn** [comment]
Are you sure? cuz it says "that does nothing" for me, even with strength 10 after buffout
![image](https://user-images.githubusercontent.com/1309656/218101895-b78a8d0e-532f-4955-96e5-39feb1d1b376.png)

**Comment by burner1024** [comment]
What do you mean, am I sure? I made a screenshot =).
In fact, I just busted it:
![Captura desde 2023-02-10 20-22-08](https://user-images.githubusercontent.com/1279852/218102637-25ec60a5-71e2-4981-82ca-5fda309e3cba.png)

The hotfix is only for the vault door.

**Comment by Owyn** [comment]
You have my mods and configs from the https://github.com/BGforgeNet/FO2tweaks/issues/96 , can you try with that? cuz I don't know what else are different in our games, I have latest steam F2 version...

**Comment by burner1024** [comment]
See if you can reptoduce on fresh v26.

**Comment by Owyn** [comment]
Is that a new version of v26? cuz I downloaded my v26 on feb2 but it says latest v26 is on feb 25 🤔 
![image](https://user-images.githubusercontent.com/1309656/218105641-b69b3ea3-c7a1-4437-bc42-4c1ae57caf1b.png)

**Comment by Owyn** [comment]
I tried to put a fresh v26 over my game, but even with fresh ddraw.ini config it still says "that does nothing", I don't know what's our difference 😢

**Comment by Owyn** [comment]
Here's my `wibaydr2.ssl` save editors says that door is using
https://pastebin.com/q1ptuU3Q
![image](https://user-images.githubusercontent.com/1309656/218133616-902d3db5-a9f5-4738-bfae-139fc5db2d9e.png)

is it the same as yours?

**Comment by burner1024** [comment]
There's some difference in the scripts processed with different preprocessors. I'll look into it.

**Comment by burner1024** [comment]
I can't reproduce the Sierra door issue.
The difference in scripts I mentioned earlier is short-circuit evaluation, and shouldn't affect functionality.
If you can reproduce on clean v28 without other mods, feel free to reopen.

However, I've come to think that probably doors with electronic locks shouldn't be opened by crowbars. I think I'll make that change.

**Comment by Owyn** [comment]
> However, I've come to think that probably doors with electronic locks shouldn't be opened by crowbars. I think I'll make that change.

Wouldn't that make taking lockpicking mandatory to progress and would kill the whole variativity and different paths of choice? (the strength build)

I've started this issue because I was sad that my strength build got blocked here on this unopening door

**Comment by burner1024** [comment]
Depending on how you look at it... Crowbar didn't work at all for 20 years. Did it make lockpicking mandatory for everyone?
And shortly after it's fixed, [here's](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/issues/101) already complaining that it made lockpicking useless.

I don't think that crowbar is supposed to work on all doors. Although if you're dead set on forcing your way through, doors can also be destroyed with explosives.

Maybe limit it to wooden doors... Not sure if there are any wooden doors with electronic locks -_-.

**Comment by Owyn** [comment]
> Maybe limit it to wooden doors

maybe make wooden doors require less strength and metal ones - more?

btw, in that complain they have the very same problem with the very same door not opening :D so it's not just me here

**Comment by burner1024** [comment]
They already require less.
Breezing through is from before the refactor, so if you couldn't do that, it means that it works fine.
And the same problem referred is also from before the refactor.
I guess no changes are necessary for now.
