### ISSUE TITLE
Appearance change machines do nothing?

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Restoration_Project#188]
### What happened
These three "do nothing" 

do I perhaps need "hero appearance mod" enabled? I have it off

### What you expected to happen
https://f2rp.bgforge.net/#epa said I can change appearance there

### Screenshot
![image](https://user-images.githubusercontent.com/1309656/218160750-af1dcabb-d8c1-4141-942d-8f35055522dd.png)

### Savegame
[SLOT15.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10709956/SLOT15.zip)

**Comment by NovaRain** [comment]
Yes, it requires the hero appearance mod enabled.
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/epa/epai37.ssl#L101
```cpp
   if (get_ini_setting("ddraw.ini|Misc|EnableHeroAppearanceMod") == 0) then begin
      display_msg(g_mstr(20000)); // generic.msg - {20000}{}{That does nothing.}
   end else begin
```

**Comment by Owyn** [comment]
Why does even changing the sex requires it tho?

**Comment by Owyn** [comment]
> I can't really think of a reason to have it disabled, do you have one?

Since I didn't need it and I wanted a classic experience with my hero's appearance
