### ISSUE TITLE
Depressed Mr Handy in EPA get's stuck and causes slowdown

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Restoration_Project#19]
The depressed Mr Handy on the maintenance level of the EPA gets stuck in place and causes the game to slowdown and stutter.

Game speed with robot:
![robot](https://user-images.githubusercontent.com/3510562/65839646-86608d80-e30f-11e9-8815-5e9d421b8637.gif)

Game speed without robot:
![no-robot](https://user-images.githubusercontent.com/3510562/65839595-ca06c780-e30e-11e9-9044-4d4078c27a43.gif)

Before entering maintenance level:
[SLOT54.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668107/SLOT54.zip)

Maintenance level:
[SLOT55.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668108/SLOT55.zip)

**Comment by jvs3** [comment]
The Mr Handy on the blue level by the hybernation tanks has the same problem.

Before entering blue level:
[SLOT60.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668221/SLOT60.zip)

Blue level hybernation tanks:
[SLOT61.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668222/SLOT61.zip)

**Comment by burner1024** [comment]
This was a bitch, but I got it finally. Not sure if perfect (might need to move event generation to `critter_p_proc`), but should be much better at least.

**Comment by giathai** [comment]
It might be better than originally, but it's still lagged as heck. 
The maintainance floor is compact so we can just get out and get in to see if Handy is stuck or not, if not, we run through to the next.
But the 7th floor is just weird. We did with the alien swarm just fine, no lag. But after disabling the forcefield and enter the hall, it start lagging. I just kill that Handy to solve the problem.

**Comment by burner1024** [comment]
[You know the drill](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/reporting.md).
