### ISSUE TITLE
Choice and options?

### ISSUE THREAD

**Issue by SCAR93** [BGforgeNet/Fallout2_Restoration_Project#190]
Hello
i love fallout 2
but your mod invalidate my choices and make playing impossible
however i like item highlight and better resolution support for OBS

could you include option to prevent your package from fixing valid ways to play the game
could you restore money in san francisco inventories? i don't wanna reload 500 times in the Den Gambling because you decided to make valid way to play impossible...
Is there a fix for random encounters to not appear on every step? or to modify how often they pop?
New Geckos in Gecko caves where you rescue guy see from kilometers and i can't pacifism
there is a lot "can't pacifism" "fixes" that turn this version inferior even to GOG basic for most of my playstyles

**Comment by burner1024** [comment]
Just play gog basic.
