### ISSUE TITLE
geckos pick up my thrown knives

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Restoration_Project#191]
### What happened
sneaky geckos trying to arm themselves 

### What you expected to happen
not yet another rise of the planet of the apes

### Screenshot
![image](https://user-images.githubusercontent.com/1309656/218553727-ffb6b124-b1d6-46ae-9fce-3da70b240a49.png)
![image](https://user-images.githubusercontent.com/1309656/218577776-7a704941-e67f-4cfd-8d7a-fa224131c188.png)

### Savegame
[SLOT19.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10725561/SLOT19.zip)

I also have these settings:
`AIBestWeaponFix=1`
`AIDrugUsePerfFix=1`

**Comment by burner1024** [comment]
I can't reproduce.
