### ISSUE TITLE
Robodog repair script

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Restoration_Project#193]
Not really a bug, just something probably worth pointing out. This condition is odd: https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/ncr/scrobo.ssl#L489

Determines the amount of times you can try to repair the robodog based on the players speech skill. Why? No idea. Maybe there are some deeper thoughts behind it, maybe not. Though it does feel a bit like the repair skill as a base would make more sense here.

**Comment by burner1024** [comment]
Yes this makes no sense. Changed to repair.
