### ISSUE TITLE
Restoration project remove peaceful resolution to stolen car problem...

### ISSUE THREAD

**Issue by SCARaw** [BGforgeNet/Fallout2_Restoration_Project#195]
![killap bad](https://user-images.githubusercontent.com/78019378/232332114-0dd3040d-958f-4b56-961c-f37a37471e08.png)
Before you even start:
i have Vanilla game installed right in the next folder
and i can convince This guy that i work for bishop and stealing his car was bad idea

here me and my 150 speech was forced to pay and no 500 or 750 option does not work at all
Why when you look at legit mechanic you must remove it?
for every restored option i meet at least 1 or 2 locked

i can't steal store in broken hills at night
i can't pickpocket people for money
i can't save and reload in combat
i can't sneak thru toxic caves with same stats as in vanilla...
can't walk up to shopkeeper inventory locker and get my money this way
can't walk beyond screen border
inventory filter mod works worse in this version

is there way to install exclusively restored dialogues and location and nothing related to this amazing "patches"?
i can assure you breaking to store in broken hills at night and stealing from it is intended mechanic
stealing money from shop too
telling chop shop guy i work for bishop too
there is a lot more of this, that i m unable to do what worked in default and i m very confused why is it the case?
you don't have to restrict gameplay...there is 0 value in this

**Comment by SCARaw** [comment]
also i could not convinced wishkey bob that he should pay for wiskey with that nickname, but i assume my stats on easy ware too low... 4 charisma with 3 perception worked in vanilla, in modded 6/6 can't do the job

**Comment by burner1024** [comment]
One problem per issue.
Issue template is there for a reason, follow it.

**Comment by SCARaw** [comment]
why option that i work for bishop is not avaible?

**Comment by burner1024** [comment]
I wouldn't know, since you didn't fill in the template.
