### ISSUE TITLE
Kama Sutra Master has no effect on Metzger (should allow having sex with him even if CH is below 6)

### ISSUE THREAD

**Issue by Hettikus** [BGforgeNet/Fallout2_Restoration_Project#199]
### What happened
Metzger does not want to have sex with my character

### What you expected to happen
Metzger was expected to have sex with my character with Kama Sutra Master perk

**Comment by NovaRain** [comment]
I'm not sure where you read that you can have sex with him regarding CH with the perk.
The requirement has been the same since vanilla.

**Comment by burner1024** [comment]
If you have evidence that it should work differently, feel free to add it.
