### ISSUE TITLE
Kitsune won't equip weapons and doesn't show armor

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Restoration_Project#20]
Kitsune (NPC from EPA) won't equip any weapons (small pistol, smg, rifle) and doesn't change appearance when wearing armor.

npcarmor.ini:
[npcarmor.ini.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668261/npcarmor.ini.txt)

Before opening the hibernation tanks:
[SLOT51.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668252/SLOT51.zip)

Outside EPA with Kitsune:
[SLOT52.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3668253/SLOT52.zip)

EDIT: Cat Jules equips all weapons but also doesn't show armor, so I'm not sure if these NPCs are supposed to show the armor they are wearing? npcarmor.ini does have different entries for some armor levels.

**Comment by burner1024** [comment]
I'm not so familiar with the script and the whole FID system, let's try summoning @NovaRain again.

**Comment by NovaRain** [comment]
I don't use RPU (don't really have the same motivation to replay the whole thing from start like helping killap few years ago) so the testing on NPC armor appearance script is done in UP with vanilla NPCs.

**Comment by burner1024** [comment]
I just thought you might have some tips what to check.

**Comment by NovaRain** [comment]
OK found it. They should use base PIDs but I set them with stage 1 PIDs. They should be:
```
[5]
PID=16777720
[6]
PID=16777718
```

**Comment by burner1024** [comment]
Awesome, thank you.
