### ISSUE TITLE
Salvatore Quest Ranesco "discount' is broken...

### ISSUE THREAD

**Issue by SCARaw** [BGforgeNet/Fallout2_Restoration_Project#200]
### 
![image](https://user-images.githubusercontent.com/78019378/236098779-4b427e85-212a-49aa-bc95-53a136398e12.png)
![image](https://user-images.githubusercontent.com/78019378/236098822-46b98532-8ad8-4029-a9d1-aab372561333.png)

**Comment by burner1024** [comment]
As usual, no saves, no justification. Sorry, you'll have to formulate issues more clearly.

**Comment by NovaRain** [comment]
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/up-changelog.txt#L265
> Discount modifier is no longer incorrectly applied with Renesco which allowed you to get all of his goods for $0

**Comment by SCARaw** [comment]
incorrectly? i think you misinterprets how gang operate 
OXhorn videos are more lore accurate than your fixes...
