### ISSUE TITLE
Version 2.7: any release date/ETA?

### ISSUE THREAD

**Issue by Wickez** [BGforgeNet/Fallout2_Restoration_Project#201]
Sorry this ain't a bug report, but I couldn't contact the current mod maintainer on any other platforms [I searched them there first, but I had to produce many posts before I could send PM/DM to other users], and GitHub doesn't support PM/DM anymore, so I'm opening this issue ticket with the question as in the title.

Thanks in advance!

**Comment by burner1024** [comment]
No.
