### ISSUE TITLE
dcaddict: error: attemmpting to use move_to in during loading

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/Fallout2_Restoration_Project#202]
### What happened

See this error spamming debug log during save load:
```dcaddict: error: attemmpting to use move_to in during loading```

Probably need to add check for loading.

**Comment by NovaRain** [comment]
The error log actually comes from "a check for loading":
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/headers/den.h#L1100
`CHECK_LEVEL` gets called in `map_enter_p_proc` for various NPCs in the Den and V15.

**Comment by NovaRain** [comment]
> Not sure. Is there any point in having this check/log? Do the corresponding scripts need to be fixed somehow? Or `move_to` resolves at a later point?

I don't think the log is needed, in the original RP 2.3.3 script source there's no logging in `CHECK_LEVEL` macro.
From the current macro, might just collapse the `IF` condition if the intention was to prevent `move_to` call during loading.
```cpp
#define CHECK_LEVEL \
   if ((is_loading_game == false) and (elevation(self_obj) != elevation(dude_obj))) then \
      move_to(self_obj, self_tile, elevation(dude_obj));
```
