### ISSUE TITLE
Hidden Wooz dialog with low INT character

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#204]
### What happened

I tried to converse with Wooz with my low INT character. At first I noticed nothing unusual, but clicking ‘REVIEW’ revealed some hidden dialogue.

### What you expected to happen

My guess is that the first line of dialog is supposed to be absent. (Either that, or the Chosen One was supposed to respond to it.)

### Screenshot

![scr00004](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/f4d56ec7-c179-461c-ae0a-278ab359bae7)

### Savegame

[insert title here.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11625833/insert.title.here.zip)

**Comment by burner1024** [comment]
Should be fixed now I guess.
