### ISSUE TITLE
Player name missing in conversation with Zaius

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#205]
### What happened

I had a conversation with Zaius through my low INT character. The problem is, she says “Me (name)!”

### What you expected to happen

I named her Hoof, so she was supposed to say ‘Me Hoof!’

### Screenshot

![scr00000](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/7dfbe344-7dda-49e9-9be9-88b83528bc89)

### Savegame

[nameless one.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11638484/nameless.one.zip)

**Comment by burner1024** [comment]
Should be fixed now.
