### ISSUE TITLE
Disabling Hi-Res patch makes camera/edge/scroll behavior to be broken

### ISSUE THREAD

**Issue by Dergash** [BGforgeNet/Fallout2_Restoration_Project#207]
### What happened

Disabling Hi-Res patch makes camera/edge/scroll behavior to be broken.

The most obvious example is the first locatin of Temple of Trials, you can't go pass the first room because the camera simply won't scroll hitting an invisible edge on the top of the screen.
Reproducible both when installing RPU_26 on original Fallout edition (taken from Internet Archive) and on GoG version.

### What you expected to happen

Camera should not be blocked and I should be able to scroll all the way to the door.

- Removing `Fallout2\mods\rpu.dat` fixes the issue, but most of the mod is gone
- Removing `ddraw.dll` also fixes the issue, but the whole mod is gone
- Enabling Hi-res also fixes the issue

Looks like RPU does some changes to the map edges that are tuned for hi-res patch which are not disabled when the hi-res patch itself is disabled.

### Screenshot

Srolling blocked with Hi Res disabled:
![bug1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/13132449/dec58d52-d09e-4d3b-8521-1192663857e8)

Scrolling is not blocked after removing `Fallout2\mods\rpu.dat`:
![bug1-expected](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/13132449/8d4974d3-a261-40fc-ba71-f96a6563fbd0)

### Savegame

[savegame.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11642721/savegame.zip)

**Comment by Lexx2k** [comment]
The HRP is an integral part of most Fo2 mods nowadays. You can't just disable it and expect things to work as usual. If you want to play in 640x480px resolution, just set the HRP to that.

**Comment by burner1024** [comment]
Is there any reason why you can't use hi-res patch in 640x480?

**Comment by burner1024** [comment]
I guess there isn't.
