### ISSUE TITLE
Broken Hills prison guard still talks after blowing up the mine

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#208]
### What happened

After accepting the quest to fix the mine’s air purifier, and just barely releasing the prisoners from Broken Hills (the security guard told me to get the hell out before I released them), I picked up the mine’s part from New Reno and did some quests while I was there. When I returned to the mine I installed the part, but then I detonated the mine’s air purifier also. So far, so good.

Then I returned to the Broken Hills jail and noticed that the security guard’s dialogue was still playing. Even stranger was when after I reloaded a save in the jail, the guard reappeared entirely.

### What you expected to happen

The jail should be silent and nobody in it should reappear after blowing up the mine’s air purifier.

### Screenshot

![0000](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/a527ae6f-4774-4384-b573-488fe64dc2f4)

### Savegame

[he’s back.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11687356/he.s.back.zip)

**Comment by burner1024** [comment]
Mutants go invisible after blowing up the purifier.
I think they still can be damaged by explosives and stuff, so a more correct solution would be to actually destroy them all.
For now I removed just this one mutant.
