### ISSUE TITLE
Why does Curtis sound so edgy during combat?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#209]
### What happened

Assaulting somebody else in Vault City’s courtyard provokes Curtis, which is fine, but his combat dialogue doesn’t fit his character.

### What you expected to happen

I expected him to talk like, for example, the children in Shady Sands.

### Screenshot

![scr00000](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/3ae0279f-6227-46fd-8e84-6fc83638a613)
![scr00004](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/76d6882a-5056-49e8-96a7-28bab6dc4654)
![scr00006](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/062efc26-08b3-4979-809f-e25650e80e4d)

### Savegame

[child with an attitude.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11709604/child.with.an.attitude.zip)

**Comment by burner1024** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/5cc9d8b4f202529d78a17fef569704549ee372d9/scripts_src/valtcity/vccurtis.ssl#L124C7-L124C7

> Tough kid. He throws rocks.

Apparently this is intentional -_-.
