### ISSUE TITLE
ecbox: invalid coordinates check for Zone4

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/Fallout2_Restoration_Project#211]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/6202d5c325699487b9940bb65265a3b8e16525e4/scripts_src/rndenctr/ecbox.ssl#L103C1-L103C1

Zone4 will never be used because the Y coordinates only go up to 1500.

**Comment by burner1024** [comment]
What do you suggest?

**Comment by phobos2077** [comment]
For my mod, I changed the line to: `INBOUNDS(350, 1400, 1100, 1500, val)`  - this covers the lower part of the land area. 
Need to take a look at the Zone4 contents though. Seems OK at first glance (plasma vs frag grenade, energy cells, etc) but this part of code probably was never used since the game came out :)

**Comment by burner1024** [comment]
It's not a guaranteed plasma grenade, just a 1% chance to get it. I'm sure it's fine at any stage.
