### ISSUE TITLE
[Modoc] Jo only gives discount once

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/Fallout2_Restoration_Project#212]
### What happened
After completing the Ghost Farm quest (the best solution), Jo says he'll give a discount. But it only applies immediately during the same dialog. If you talk afterwards, he will "forget" about it.

### What you expected to happen
Like most other character, `gdialog_set_barter_mod` must be called in `talk_p_proc` depending on quest status (or some lvar flag) so he actually keeps his word.

**Comment by phobos2077** [comment]
Fixed here: https://github.com/BGforgeNet/Fallout2_Restoration_Project/pull/197/commits/b2bca232cb39398683ee4e78cc7a83eb68377ae4

**Comment by burner1024** [comment]
Isn't it the same with Renesco? Why do you think it should be remembered?

**Comment by burner1024** [comment]
Makes sense.
