### ISSUE TITLE
Readme - dead link

### ISSUE THREAD

**Issue by auburncodingclub** [BGforgeNet/Fallout2_Restoration_Project#213]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/docs/rp-readme.txt
Walkthrough link be dead:  http://hem.bredband.net/darek1/f2rp_wt.htm

**Comment by burner1024** [comment]
Yes, I put it here https://f2rp.bgforge.net

**Comment by auburncodingclub** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/docs/rp-readme.txt

Still says this:

Q: I'm stuck on this one quest. Help me!
A: Morticia and others have compiled a detailed walkthrough for my work. You can access it here: http://hem.bredband.net/darek1/f2rp_wt.htm
