### ISSUE TITLE
NPC Crippled - I have no companion

### ISSUE THREAD

**Issue by Dartomic** [BGforgeNet/Fallout2_Restoration_Project#215]
### What happened
I am using the bald white guy character model. I went to the ghost town, and fell down the hole. The game shows that I am crippled, and that an NPC is crippled. The messages are displayed in two rectangles above the message section of the HUD at the bottom of the game screen. The letters are displayed in red. I have no companion NPC.

### What you expected to happen
I expected the game to just show a single message that says "Crippled" in the rectangle, instead of an additional rectangle that says "NPC CRIPPLED."

### Save File
[slot07.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12063084/slot07.zip)

**Comment by NovaRain** [comment]
The script that checks the cripple state of player and companions is bugged. Try this one: [gl_k_crippl.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12063091/gl_k_crippl.zip)

**Comment by Dartomic** [comment]
Oh thanks. I don't actually mind it doing that. I just figured it was a bug that should get reported. I kind of figured it had something to do with the character model, if what allows a different model is some kind of hack that uses something from the NPC code.

**Comment by burner1024** [comment]
Should be working now.
