### ISSUE TITLE
Question about radiation

### ISSUE THREAD

**Issue by gh0stwizard** [BGforgeNet/Fallout2_Restoration_Project#230]
I'm getting radiation everywhere, in Den, in Modoc, etc. I don't like this at all, this is not part of original game. Otherwise, there is zero explanation why nobody dying after 3 years. Each 3 days I getting 3 doses, so to get 1000 and die you need to live 3 years. This is not funny.

Is there a way to disable this or don't? What files and how I should change? Or may be I am missing something (don't eat this or that, etc)?

Thanks in advance.

**Comment by burner1024** [comment]
> Or may be I am missing something

You probably are. There is no general radiation code in RPU.

**Comment by phobos2077** [comment]
@gh0stwizard just curious, which other mods have you installed? EcCo has general radiation but it only triggers in Gecko and Broken Hills. Also you might got confused by eating Mutated Fruit - they give a small dose of radiation several hours after consuming.

**Comment by burner1024** [comment]
Some rats, geckos can irradiate. Walking around in toxic caves. Etc.

**Comment by gh0stwizard** [comment]
@phobos2077 Yes, it was because of Fruit. I've checked all items on wiki, it's only one which irradiates. The thing is that it does not work as described: 1 dose after 2h, then 1 dose after 8h. In my case I've got 3 doses after ~8h. May be it was because I've consumed many of them, idk. As of version: steam's one + RP last github's release.
Anyway, thank you very much. Have a nice day!

**Comment by phobos2077** [comment]
Yes, if you eat multiple drugs, their effects stack up to a certain maximum.
