### ISSUE TITLE
Typo in Umbra Tribe quest

### ISSUE THREAD

**Issue by markarce** [BGforgeNet/Fallout2_Restoration_Project#234]
### What happened

During Umbra Tribe quest to speak to the spirit. After speaking to the spirit, I talked to the new shaman about it. There's a typo in his dialogue:

"Thorg?! He was the shaman that I served as an apperceive under."

### What you expected to happen

I believe this should say "apprentice" instead.

### Screenshot
![Screen Shot 2023-09-01 at 10 15 29 AM](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/29787923/ac667947-3400-492c-ad10-060adbd8055b)

**Comment by burner1024** [comment]
Already fixed in development version, thanks.

**Comment by Anarcho-Bolshevik** [comment]
I found a few more:

{[280](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/33ef2668168d8b38eb38f714ddcd60f3f5f995f9/data/text/english/dialog/tribec1.msg#L88)}{}{**[**Gladly. [He looks into your eyes and grins wolfishly. Despite his scarred and rough appearance, he possesses a rugged handsomeness.]

{[400](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/33ef2668168d8b38eb38f714ddcd60f3f5f995f9/data/text/english/dialog/tribec11.msg#L22)}{}{Thanks for **helpin** Serin. He good warrior. You friend of tribe.}
