### ISSUE TITLE
Umbra village merchant deal crash

### ISSUE THREAD

**Issue by AXZIOM11** [BGforgeNet/Fallout2_Restoration_Project#236]
### What happened
Crashed in Umbra village merchant deal after inspecting the stimpacks to many times, about 8-9 times to be precise
crash text was: "Failed to open file. Too many open files"
i was trying to see if i could pass a perception roll when doing this but it seems like there isnt any rng involved here
would be nice to know in game that i cant find out that the stimpacks are blood without crashing or save scuming
### Savegame
[SLOT30.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12644104/SLOT30.zip)

**Comment by NovaRain** [comment]
If you're still playing older RPU, set `FadeBackgroundMusic=0` in ddraw.ini.

**Comment by AXZIOM11** [comment]
@NovaRain Thanks that fixed it, i turned that setting on manually when i setup the game, didn't know it was broken
