### ISSUE TITLE
RPU v27, Car disappears in Modoc after auto transferred from Ghost Farm

### ISSUE THREAD

**Issue by ericqzou** [BGforgeNet/Fallout2_Restoration_Project#237]
### What happened
Car is auto transferred with the player from Ghost Farm to Modoc when completing the Ghost Farm - Modoc main story. However once transferred back to Modoc, the car is there. As soon as Player enters another area of Modoc, like the Town Well or else, and get back to Main Street, the car is vanished for good.

However if the player just get into the car and start it, and then back to modoc, then the car will act normal again - staying in the main street area.
### What you expected to happen
Car does not vanish. I don't recall this in v26. I think it is be a new bug.
### Savegame
Slot 01 is the save that car is vanished.
Slot 02 is right before entering any other area of Modoc - hence triggering the car to vanish.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12664812/SLOT01.zip)
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12664814/SLOT02.zip)

**Comment by burner1024** [comment]
Extract [modmain.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12673833/modmain.int.zip) into `data/scripts`.
The fix should work, but please test it on a save made before returning to Modoc with Jonny.

**Comment by ericqzou** [comment]
I also first suspected that the car, when it was "vanished" from Modoc, then it will be in Ghost Farm, as NovaRain commented. However if I then go back to Ghost Farm on foot, the car is not there, that's why I said the car is vanished "for good". 

@burner1024 
I can try out your suggested solution later today, and upload the save here as you wanted.

**Comment by ericqzou** [comment]
@burner1024  Tried, the issue seems to be solved. I enter another area after being scripted back with Jonny, and the car is still in Main Street when I come back to Main Street.

Savegames attached as you asked.  Slot 01 is the moment right after being transferred back to Modoc with Jonny. Slot 02 is the moment right before departing from Ghost Farm
[SLOT.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12678001/SLOT.zip)

**Comment by burner1024** [comment]
Great, thanks!
