### ISSUE TITLE
RPU v27 Skynet combat settings issue

### ISSUE THREAD

**Issue by ericqzou** [BGforgeNet/Fallout2_Restoration_Project#238]
### What happened
Skynet combat settings are mixed up, and can not be saved - reset to messed up state after closing the dialogue

In addition to this I talked to NovaRain and he informed me that he coudn't find this issue on his installation, so I think I may better report it here and see.

### What you expected to happen
Settings shall be default skynet settings and can be saved after change.

### Screenshot
![Screenshot 2023-09-24 133054](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/14295735/44c0ddc8-2a5a-4753-a1e3-f6b270f7fe6d)

### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12708389/SLOT01.zip)

**Comment by NovaRain** [comment]
In your save, Skynet's AI packet is wrong (number 23, `AI_KAMAKAZI`, the correct range is 113-117), I have no idea how it turns out like that.

**Comment by burner1024** [comment]
Are you using any other mods?

**Comment by ericqzou** [comment]
I shall have only 1 mod and two extract scripts beside everything from RPU. sfall is from RPU package, didn't touch that.

1. FO2 Tweak
2. An old script from someone on NMA that makes dead body drop off armor, base on science and repair 
3. NovaRain's script that locks book reading to 5%-point. 

Sorry I didn't notice my email notification from github before. If you want me to upload more I shall be happy to.

**Comment by burner1024** [comment]
Similar to #154. I re-checked ai.txt and aipacket.h, everything appears to be in order.

**Comment by marstem** [comment]
I came to this issue a year+ ago, and with  help of Mr.Stalin @nuclear-city.com tried to find out rpu and even sfall scripts error. But looks like it is a MAP error, wrong ai  somewhere at original skynet location. But I'm not familiar with maps to find and fix it. 

Once the game is started it should be easily fixed for current party by just using ingame debugger - right after the skynet is joined, open current state with debugger, find our skynet as robobrain critter and set its ai packet to 117

**Comment by burner1024** [comment]
Do you have earlier saves? Can you check them for ai packet?

**Comment by NovaRain** [comment]
Some other findings:
AI packet value in Skynet's proto (00000079.pro) in your save is `AI_SECURITY_BOT` (31) instead of default `AI_PARTY_ROBOBRAIN_CUSTOM` (117) in its base proto in rpu.dat. The value in the proto shouldn't change for the disposition (berserk, aggressive, etc.) you select in the combat control panel. So something must go very wrong either in your game/save or from the script mods you're using. Obviously that old lootable armor mod is the no.1 suspect (fo2tweak shouldn, maybe attach it here for checking.

**Comment by ericqzou** [comment]
I have an earlier save but I am not sure if it is from this game or from the earlier one (the one I reported for the car vanishing issue). And in that save I haven't  yet recruited skynet.
[SLOT11.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12734489/SLOT11.zip)

The lootable armor script:
[Lootable Armor.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12734503/Lootable.Armor.zip)

I recall the only "settings" I changed, and may have an impact, compared to my previous play of RPU(must bed v24 and earlier) is that I noticed the option in FO2Tweaks:

; party npc level will match player level more closely

I changed it from 1 to 0 in the middle of the game play when I noticed it. So I am thinking either this or the lootable armor can be the cause.

**Comment by burner1024** [comment]
I don't see anything related in lootable armor script. Nor fo2tweaks one.
Is it a fresh v27 game or upgraded from v24?

**Comment by ericqzou** [comment]
It was a fresh v27 install.

Maybe it is not worth of your time to investigate anymore if it is just a random and one time error. I have already deleted the game since I am done with the play for this time. Seems like it needs more proactive and live debugging right before and while this is being triggered.

**Comment by ericqzou** [comment]
I didn't try skynet from another save. I actually just continue the game from the round that I detected skynet issue. The situations is such:

I didn't really "use" skynet as an active team member  except the fact that I got it late in the game and went to Mariposa Military Base to fight Melchior and his pets. It was during that fight I noticed skynet's combat settings issue. But it is just annoying in the way that skynet can't really be a combat partner in the way I wanted, nothing else in the game is effected by this. And any fight with this mis-configured skynet is totally doable. Skynet will just act like always has the "Charge !" command and keeps shooting. 

That's why if is not because of the Melchior fight I may not even notice the issue.

**Comment by burner1024** [comment]
Sorry, posted my comment in the wrong issue =/.

**Comment by burner1024** [comment]
The bot critter is created from terminal script:
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/8d6c7e8999cc0252f5208f5798d1de44899d90d4/scripts_src/sierra/wsterm3c.ssl#L166-L185

It is not saved in the initial map, and thus no errors should stem from it.

If anyone else stumbles upon this issue, please provide a save right before final Skynet assembly.

**Comment by DondeEstaTuHallPass** [comment]
I have the same issue. sfall 4.4.3.1.
save file is right before assembling(that is, putting all the parts to broken robot thingy) skynet.
[SLOT07.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15137568/SLOT07.zip)

**Comment by burner1024** [comment]
@DondeEstaTuHallPass 
Please attach a [ZAX](https://github.com/BGforgeNet/zax) debug package.

**Comment by NovaRain** [comment]
The cause is `epax.map` (EPA ground/utility/robot maintenance levels) because there's a brainbot that erroneously uses Skynet's proto, thus "sharing" data with it. If players enter `epax.map` before getting Skynet in SAD, Skynet's default AI packet will be changed to `AI_SECURITY_BOT` and triggers the issue.
