### ISSUE TITLE
Why is there no option to disable Cassidy talking head?

### ISSUE THREAD

**Issue by six6vi000** [BGforgeNet/Fallout2_Restoration_Project#239]
I found the other options I didnt want installed from RP (like Lenny animations) but I cant find any way to remove Cassidy's talking head. I really dont want this as I've seen videos of it in action & it just doesnt fit at all tbh.

**Comment by NovaRain** [comment]
To manually remove Cassidy's talking head, remove `cassidy_head.dat` and `cassidy_voice_*.dat` from your `mods` folder. If there is already a `mods_order.txt` in the folder, remove the filenames from its list as well.
But yes, I agree the installer should have more options to toggle some extra components, like how it was in the original RP 2.3.3.

**Comment by six6vi000** [comment]
> To manually remove Cassidy's talking head, remove `cassidy_head.dat` and `cassidy_voice_*.dat` from your `mods` folder. If there is already a `mods_order.txt` in the folder, remove the filenames from its list as well. But yes, I agree the installer should have more options to toggle some extra components, like how it was in the original RP 2.3.3: ![RP 2.3.3 installer](https://user-images.githubusercontent.com/8564973/270238025-2502a7fb-475b-41c3-b102-bf93ae451f67.png) (with less sub-options of course)

Thank you, I appreciate your help. While you're here, I have one other question: Is the walk speed fix the reason why my characters run speed is suddenly so fast? It's a full on sprint, essentially. I know theres the "speed adjustment" in ddraw.ini but that affects the games speed itself, it seems. I tested with a 1 AGI character first to make sure it wasnt a fallout 2 addition + tried 10 AGI in vanilla, and the speeds are drastically different. I assumed it must have been related to literal walking speed or perhaps the map travel, but clearly something has affected the run speed, too.

**Comment by NovaRain** [comment]
The walk speed fix is for other critters in the game, as the description in `upu.ini` said. And AG doesn't affect player's visually movement speed.

**Comment by burner1024** [comment]
FO2tweaks has an option to increase run speed, if have it installed.
