### ISSUE TITLE
Bugs about planting EPA experimental/corn seeds

### ISSUE THREAD

**Issue by NovaRain** [BGforgeNet/Fallout2_Restoration_Project#24]
The plant/corn from planting EPA seeds didn't show up in the game. I made fixes for them:
[rp_miscfix_nr.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3833990/rp_miscfix_nr.zip)

1. epai33.ssl: Two `if (cur_map_index == MAP_EPA_SUBLEVELS)` map checks are wrong, so the plant never shows up in the green level. It should be `if (cur_map_index == MAP_EPA_SUBLEVELS_1)`. For Arroyo village the plant/corn gets placed on the wrong elevation.

2. epas9.ssl: It checks a non-exist global variable (GVAR_EPA_SEEDS) for message 200, so the player never says that floating message. I changed it to check the new MVAR_Sprouted value.

Also a couple of misc fixes:

3. dcdealer.ssl: The drug dealer and his bodyguard don't receive/equip their weapons at the first time the player enters the Den Residential map.

4. ncslave.ssl: The male "loser" doesn't have "magic hands" frames (NMLOSRAL.frm). It's not really an issue for normal gameplay, but with newer sfall it'll cause the game interruption/forced crash when enabling DebugMode. This can also be applied to UP.

**Comment by burner1024** [comment]
Thank you, I applied all the fixes.
