### ISSUE TITLE
Game Crashes after killing all the guards during the "Help Lara attack Tyler's gang" quest (Among other crap)

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [BGforgeNet/Fallout2_Restoration_Project#246]
### "The instruction at 004a2b2f referenced memory at 00000078
The memory could not be read from
Click OK to terminate the application"

![Fallout2Crash](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/29a2e10e-9b4d-4ba2-a2f0-6bd498b16d1d)
Note: Not the exact code in the title but it's pretty much the exact same crash. It happened when I reached the Umbra Tribe.

![Fallout2Crash2](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/ac190d7d-b4e7-4dd5-8da4-19acdb0950bf)
Note: This one happened when I was doing the quest in the Umbra Tribe to bring peace to a girl who was murdered by Thorg. The shaman was doing the ritual and told her to find peace by going into the mists. As soon as she said she accepted, the game crashed with this exact error message. I'll include the debug But the save file is not accepted.

I've also experienced this bug in the Fallout 1 in 2 mod where the game crashes whenever I try to deliver pulse grenades to Sophia at the BoS which makes the quest incomplete and I can't talk to the guy who takes Item requisitions because he's angery that I kept the 'nades for meself. If anyone knows how to fix this bug, pls tell me. I am running the Fallout 2 Restoration Project Updated which comes with QoL mods, cut content added back in, and I even downloaded some mods from Nexus. But none of them, as far as I know, are tied to the quest in the title.
I hope you can help me.
ThatGuyFromReZero

PS: This same error also occurs during certain random encounters. Usually the random encounter with a red circle around the red lightning bolt.

PPS: The game also freezes **randomly** but sometimes, it feels like it freezes on **purpose**. For instance, I've encountered the old base from Fallout 1 that has been destroyed. Dogs wander around the place and the game freezes after a few seconds. Basically, once the game freezes, the music loops every 7 seconds. Even using CTRL+ALT+DEL doesn't close the game as I cannot access anything but the start-up menu. The only way to close it is to shut down the computer. But I did see that in the mini window of Task Manager, the application Fallout 2 is not responding. I need help with this so I don't start hating on such a good-ol' classic game from that era
Update: Now the game freezes whenever I get into any town with a lot of people.

Unfortunately, I ended up deleting the game entirely, reinstalling everything along with a mod to enhance the ACE Supercomputer, talking heads mod, and THAT (Talking Heads Actually Talk) mod. Plus, FO 2 Enhancements. So there is no Save Data to upload. I'll try and recreate the crashes again but keep in mind that it'll probably involve shutting my computer down a lot

Debug: [debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12891601/debug.log)

**Comment by burner1024** [comment]
Which mods did you have installed in the first setup?
Is that debug.log from a crash? Which in particular?

**Comment by ThatGuyFromReZero** [comment]
I'll list them here. Most of them came with the RPU. BTW, I also have FO2 Tweaks included as it was recommended I install them along with RPU. It's not on the mod list I'm posting but it is very much a mod I installed:
![FO2ModList](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/ce2d7fb3-8b38-4118-95c8-74cabedf410c)

**Comment by burner1024** [comment]
See if you can reproduce without talking heads, fo2 enhancements and ace mod, then share debug.log from a crash.

**Comment by ThatGuyFromReZero** [comment]
Coming right up

**Comment by ThatGuyFromReZero** [comment]
![Fallout2Crash3](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/df3e5411-694e-4749-9ad1-55fea8447aaf)
So I deleted the mods you said and went back into the game. Above is the new error that occurred after speaking to the spirit. Below that is the debug which modified in response to the most recent crash:
[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12907033/debug.log)

**Comment by burner1024** [comment]
You can zip the savegame to attach.

**Comment by ThatGuyFromReZero** [comment]
It says that I can't even send zips of save files.

**Comment by ThatGuyFromReZero** [comment]
Let me see if I can email it to you:

**Comment by ThatGuyFromReZero** [comment]
It still doesn't work
Let's try using our emails.

**Comment by ThatGuyFromReZero** [comment]
Ok. Maybe this crash is only exclusive to me. Try using the RPU with FO2tweaks and the mods I'm going to send you links of:
RP-THAT: https://www.nexusmods.com/fallout2/mods/67?tab=description
ACE-Supercomputer enhanced: https://www.nexusmods.com/fallout2/mods/38 (Note: Download the ACEenhanced1.1 file)
RPU-Talking Heads Addon: https://www.nexusmods.com/fallout2/mods/45

**Comment by khoitnm** [comment]
@ThatGuyFromReZero May I ask which RPU version are you using?
If it's the rpu_v28, then it will crash when having talking head <-- this cause crashing when meeting Kaga1. If I remove this mod, it won't crash anymore (we can easily reproduce it consistently by changing worldmap.txt to make KAGA1 encounter 99%.
To be more specific, the file cause error is `eckaga1.int` (I tested by removing this file only, and it won't crash anymore)

**Comment by GoatBoy-11** [comment]
Hi, I'm the author of the Talking Heads mod. I noticed there is no change in the Lara script from v26 so I'm unsure what the cause of the crash is. The only change I did was on the `start_gdialog` lines where I added the talking head and background.

I noticed both Lara and Kaga's crash occur when the `start_gdialog` line in a procedure different from `talk_p_proc`. The crash in Lara's case is when the `start_gdialog` command is used in `critter_p_proc` and in Kaga's case iis when his custom 'doSequence' command is called.

**Comment by ThatGuyFromReZero** [comment]
> @ThatGuyFromReZero Regarding to your comment about this: "This same error also occurs during certain random encounters. Usually the random encounter with a red circle around the red lightning bolt."
> 
> May I ask which RPU version are you using?
> 
> If it's the rpu_v28, then it will crash when having talking head and you meet Kaga (" random encounter with a red circle around the red lightning bolt"). If I remove this mod, it won't crash anymore (we can easily reproduce it consistently by changing worldmap.txt to make KAGA1 encounter 99%. To be more specific, the file cause error is `eckaga1.int` (I tested by removing this file only, and it won't crash anymore)

Well, the funny thing is that when I encountered Kaga, the game didn't crash, it only fast-forwarded the text. Other "Red Circle Encounters resulted in the game immediately crashing. I'm using version rpu_v28 as it's the latest.

**Comment by ThatGuyFromReZero** [comment]
@GoatBoy-11 Well, it crashes after killing all of Tyler's gang when I end combat unless I leave the area and come back before they're all dead. I never had any issues talking to Lara

**Comment by NovaRain** [comment]
> @GoatBoy-11 Well, it crashes after killing all of Tyler's gang when I end combat unless I leave the area and come back before they're all dead. I never had any issues talking to Lara

Actively talking to her is different from Lara initializing the dialogue by herself.
As for the crashes in your RPU v28 with mods, you can try replacing `ddraw.dll` with this one: [sfall_dev.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12974159/sfall_dev.zip)

**Comment by GoatBoy-11** [comment]
> > @GoatBoy-11 Well, it crashes after killing all of Tyler's gang when I end combat unless I leave the area and come back before they're all dead. I never had any issues talking to Lara
> 
> Actively talking to her is different from Lara initializing the dialogue by herself. As for the crashes in your RPU v28 with mods, you can try replacing `ddraw.dll` with this one: [sfall_dev.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12974159/sfall_dev.zip)

Thank you, that fixed the issue!

Is there a public place to download this? That way I can direct users signaling this issue.

**Comment by ThatGuyFromReZero** [comment]
Thanks! I'll see if that works!

**Comment by NovaRain** [comment]
> Thank you, that fixed the issue!
> 
> Is there a public place to download this? That way I can direct users signaling this issue.

The fix will be in next sfall release, for now you can tell people to grab the dev build above. AFAIK it doesn't need an account or something to download attached files.

**Comment by ThatGuyFromReZero** [comment]
I'm doing a fresh start. I have FO2 Tweaks with Unlimited Carry Weight enabled as well as starting at level 5 upon completing ToT, the version of ddraw.dll which @GoatBoy-11 recommended, ACE Enhanced and that's about it. I'm not getting the Talking Heads mod or THAT mod. If things go smoothly, I'll install those and see if I have any issues. If things don't go smoothly with my current game, I'll send a report.

**Comment by ThatGuyFromReZero** [comment]
It still crashes.  @NovaRain When do you expect the next sfall release to be done? I'll be willing to test it out so I can see if it has improved. BTW, the game never crashes to desktop or freezes with the music looping every 7 seconds when I'm in the Temple of Trials or when I'm traveling in the Map. It only happens if I'm in an area where I can move my character around

**Comment by NovaRain** [comment]
I don't see detail info about those (error messages, logs, possible saves to reproduce/trigger them, etc.), so I don't think new sfall would help solving your crashes.

**Comment by ThatGuyFromReZero** [comment]
I'll redownload RPU and start over. I'll also be using the FO2 Tweaks and
ACE Enhanced. I'll send the attached files via my email for you to look at.
I'll try and spend as much time on it as possible in order to gather plenty
of data. But how do I show the freezing which makes everything
inaccessible unless I shut down my entire PC?
ThatGuyFromReZero

**Comment by ThatGuyFromReZero** [comment]
Ok. No crashes or freezing so far but there are times when the music loops for some random reason. I'm going to take a riskier gamble and try recreating the Game Crashes after killing all the guards during the "Help Lara attack Tyler's gang" quest. I'll do two tests: One that's more or less Vanilla and another one with Talking Heads RP and the THAT mod. I wanna see what results I get and document them for future consideration. As for the looping music, I may be able to fix that if I download the Lossless Music mod.

**Comment by ThatGuyFromReZero** [comment]
No crashes or freezing to report. I'm now using Talking Heads RP and the THAT mod along with the [Restoration Project - Companion Expansion](https://www.nexusmods.com/fallout2/mods/70)
I was told on the Talking Heads RP discussion page to switch to a dev build of ddraw.dll right here: https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/12974159/sfall_dev.zip in order to prevent the CTD. I'm also hoping that the RP-CE will make Miria actually a worthwhile wife/companion so she's useful. No encounters with Kaga yet so I can't comment on that but I intend to do a full playthrough and push through as much of the game as possible. It'll probably take me a week or two for me to get through but I intend to do it and be a reliable test player for the RPU. I not only want this to succeed but my dream is for this to be available for purchase on Steam. The developers of these mods deserve all that and more. Fallout 2 Ultimate Edition. Sounds great to me.


@NovaRain  Once I confirm my problem has been fixed after all this trial and error, I propose making a new page with properly detailed installation instructions for these mods to ensure fewer crashes/freezes in the future and hopefully, garner more interest in the Classic Era Fallout. I have my best bud who has never touched Fallout all his life playing Fallout 1 in 2 and he says he's enjoying it so far. I want him to have the same experience with with Fallout 2 RPU.

**Comment by ThatGuyFromReZero** [comment]
Ok. So my game froze twice in Arroyo. Once when I went to go talk to the guy with a sharpened spear, I was suddenly minimized out of the game and straight to desktop. The music looped every seven seconds but I couldn't get back into the game and trying to close the program via Task Manager didn't work so I had to force a shut-down. The other time when I re-entered the Temple of Trials, the game froze and the music looped as per-usual freezing. The thing is, I feel as though the Talking Heads Addon is what's causing it, I can't totally prove it so it's just a theory for now. I'll push further on and let you all know what happens next

**Comment by ThatGuyFromReZero** [comment]
Dear @NovaRain I believe I’ve solved the mystery to the mysterious freezes and CTDs. It’s the Talking Heads Mod from Nexus. Even when I used the recommended DevBuild of ddraw as per the mod author’s instructions, the game still froze/CTD. I believe that the problem lies in the compatibility of the RPU mod and the Talking Heads mod. Unfortunately, I’m not sure where we go from here. I’m sorry for being an absolute pain to work with but I just want things to run smoothly. If you need me to run tests on future builds, I’ll gladly take it up.

**Comment by ThatGuyFromReZero** [comment]
So, I managed to figure out what the problem was after much trial-and-error. I'll be making more clear and concise guides in the future and maybe even considering bundling the mods I like into one bundle on NexusMods for a quick-and-easy installation.
Until I find more issues in the future, this Issue of Lara crashing/Game Freezing/Other Crap is officially Closed.
