### ISSUE TITLE
Game Crash when selecting body part in VATS

### ISSUE THREAD

**Issue by RyuAzuku** [BGforgeNet/Fallout2_Restoration_Project#247]
Game crashes when using VATS in combat. Consistent with using VATS but appears random in the amount of attacks/time it takes to cause the crash, sometimes it's the first few hits, most of the time it's 5 or so minutes into combat. Game crashes immediately after selecting a location to hit while in VATS.

~~Game does not crash in combat when NOT using VATS.~~

**_EDIT: with more testing I have found that just combat in general will cause my game to crash, specifically when an enemy dies._**

Current Location: 
Vault 15 fighting the Khan Leader and guards(but it can happen anywhere combat happens) 

**Steps I do to reproduce:**
1. Only attack using VATS(can still happen if you do a mix of VATS and non VATS combat, but will always crash when selecting a spot with VATS)
2. Swap between using gun/melee on a target(using one or the other exclusively can still cause the game to crash)
3. Continue this over and over again until you get a crash.

**Programs used:**
Current Restoration Project Build(v28)
Sfall Dev Build referenced in issue #246 by user NovaRain

**Mods used from Nexus:**
Talking Heads Mod (24 Aug 2023)
Talking Heads Actualy Talk (15 Jul 2023)
Classic Fallout GOD MODE Cheat File (09 Nov 2021) *loaded on character creation/not sure what program they used to create

**--Included debug.log and save file in ZIP format--**
[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/13047432/debug.log)
[SLOT05 Save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/13047459/SLOT05.Save.zip)

**Comment by burner1024** [comment]
Nothing in the log, and can't reproduce.
I think try older sfall: 4.3, 4.2, 4.1.

Also try pressing ctrl-c while on crash window, it should contain crash dump, if you're able to get it, please paste here.

**Comment by RyuAzuku** [comment]
Just the generic memory crash, not very verbose.

_---------------------------
Application Error: B:\SteamLibrary\steamapps\common\Fallout 2\fallout2HR.exe
---------------------------
The instruction at 004107b8 referenced memory at 06029074
The memory could not be read from

Click on OK to terminate the application
---------------------------
OK   
---------------------------_

I'll try an older version of sfall and see if that helps out.

**Comment by RyuAzuku** [comment]
I tried using different versions of sfall but I can no longer test anything since I cannot load my saves.

**Comment by burner1024** [comment]
OK, well, thanks for trying.

**Comment by NovaRain** [comment]
If the crash is always the memory address above (004107b8), it happens in `pick_death` engine function.
I'd suspect some `HOOK_DEATHANIM1`/`HOOK_DEATHANIM2` related script screwed up.

**Comment by RyuAzuku** [comment]
@NovaRain I haven't really payed attention to the addresses when the game crashes, give me a couple of minutes and I'll check it out.

**Comment by RyuAzuku** [comment]
@NovaRain alright update, the address in the crash is the same every time, and it still pops up even after removing the Talking Heads mod

**Comment by NovaRain** [comment]
Can't reproduce the crash here (w/o mods). What's the version of your Fallout2 game? (Steam/GOG/EPIC/etc. and the language)

**Comment by RyuAzuku** [comment]
most up to date steam version, and english

**Comment by RyuAzuku** [comment]
New things attempted:
1. New Save(same mods) made sure not to save during combat
2. Re-Installed Fallout 2/restoration project into new folder not in ProgramFilesx86(2 different saves one with same mods one without)
3. Tried running Fallout2HR.exe as administrator both in original copy/new copy of restorationproject

Still getting that crash with and without the mods/re-installed into a new area on my ssd, still getting the same crash.


**Thing to note that I forgot to mention, I did enable the infinite carryweight as well as autodoors in the f02tweaks.ini

**Comment by RyuAzuku** [comment]
Another Update:
the same exact crash CAN still happen outside of VATS combat, I had gotten so engrosed with testing this out with VATS that I didn't properly test non-vats combat enough. Given enough encounters OR a long enough fight this crash WILL still occur without VATS. I can play the game significantly longer without a crash though.

**Comment by burner1024** [comment]
Does it happen as someone dies, or there are other cases?

**Comment by RyuAzuku** [comment]
@burner1024 Actually yeah it's pretty much around the death of something. When in combat it's usually around a few times after hitting a dude when he's close to death. Also my initial post where I mentioned that it could happen at the first attack the testing was done on rats, which can die on a single hit.

Something to note though, in my testing I've gone through the Temple of Trials 4 times and never once got a crash even when targeting in VATs and while one-tapping nearly all enemies. All crashes on all saves happen in areas with more than 3-4 enemies at a time, though I haven't had enough time to test sparse encounters(1-2 enemies only besides temple of trials).

*Also I just realized that my last post may have been a little confusing. It's still only combat just not using VATS

**Comment by burner1024** [comment]
Please try with latest sfall. If still crashes, add new save and log and guide to reproduce.
