### ISSUE TITLE
Leveling Up

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [BGforgeNet/Fallout2_Restoration_Project#249]
This isn't so much an issue as it is more of a question of tweaking but, is it possible to alter the game so I can set the Level Cap from 24 to 40? In Fallout 1 in 2, I can go into the code and set up a custom leveling system. The default is this: 
;Uncomment and set a comma delimited list of numbers to use a custom XP table.
;Player's level is capped once the highest specified level is reached
XPTable=1000,3000,6000,10000,15000,21000,28000,36000,45000,55000,66000,78000,91000,105000,120000,136000,153000,171000,190000,210000

However, I changed it to this so I can reach Level 40. Pay attention to the changes and you'll see that I've altered it after 210000 so it starts earning XP in the opposite direction: XPTable=1000,3000,6000,10000,15000,21000,28000,36000,45000,55000,66000,78000,91000,105000,120000,136000,153000,171000,190000,210000,229000,247000,264000,280000,295000,309000,322000,334000,345000,355000,364000,372000,379000,385000,390000,394000,397000,399000,400000
I used a calculator to subtract 190000 from 210000 to reach 229000. I then added 180000 to 229000 and continued to do so, taking 1000 away every time I added to the point where you only need 1,000 XP to go from Level 39 to Level 40. Is it possible to do something similar with Fallout 2 RPU?

**Comment by burner1024** [comment]
It should work all the same. It's an sfall feature, not an RPU feature.
