### ISSUE TITLE
Incompatibility with Fallout 2 Save Editor

### ISSUE THREAD

**Issue by FalloutBruhMoments** [BGforgeNet/Fallout2_Restoration_Project#25]
Upon updating to v9 i was unable to use F2SE.
I get an access issue error, if not that it stops responding, but only on my saves that use v9, my other saves work fine in the save editor.
Please address this issue in the next version please.
![ggg](https://user-images.githubusercontent.com/57788573/68923641-e1244a80-07d2-11ea-8e20-340df6941684.PNG)

**Comment by burner1024** [comment]
1. F2SE is deprecated, please use F12SE.
2. If that doesn't help, attach the saves (both working and non-working, same location).
3. Also indicate exactly which F12SE version did you use. And sfall version.

**Comment by FalloutBruhMoments** [comment]
Downloaded F12SE and i get errors as well, newest version of both F12SE and sfall.
Just checked and my other saves get an error as well

Here is a save that works
[Savegame2.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3850750/Savegame2.zip)

Here is the save that i want to edit.
[Savegame.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3850730/Savegame.zip)

**Comment by FalloutBruhMoments** [comment]
I should note i had the same problem with v8 but it fixed on a clean install (kinda messed up installing i had an issue with ddraw overwriting as well) however i have performed several reinstallations of v9 to no avail, my saves work in game (loading/saving works without a hitch) it's just editing the saves themselves refuses to work.

**Comment by burner1024** [comment]
1. I do mean actual version numbers, not just "newest".
2. The saves load for me in the save editor, but there are some warnings and numbers are all screwed up.
3. That happens with both v8 and v9 for me.

![Captura de pantalla de 2019-11-15 17-20-18](https://user-images.githubusercontent.com/1279852/68936370-fb5b2a00-07cc-11ea-8a34-468dd6bbc3ba.png)

Conclusion: I think the best thing to do is to contact vad and ask him to check out your saves. As they work fine in game, it's likely some mixup with sfall mod load order.
