### ISSUE TITLE
Error: "The instruction at 004af4b0 referenced..." caused a crash at the mole rat mission

### ISSUE THREAD

**Issue by NKO55** [BGforgeNet/Fallout2_Restoration_Project#253]
### What happened
In the mole rat quest in Klamath, you encounter regular rats in the first underground level. I had already killed a bunch of rats, then continued to attack another one, when this error popped up and crashed the game. I tried to replicate the encounter afterwards but couldnt do so succesfully.

### Screenshot
![Screenshot 2023-12-04 221719](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/32250049/4c477604-d92a-4869-8fd8-4538fa82f991)

**Comment by burner1024** [comment]
Sorry, but without a reproducible case not much point in reporting a bug.
