### ISSUE TITLE
(IIP) Random Freezing

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [BGforgeNet/Fallout2_Restoration_Project#255]
This is an Issue-In-Progress. I'm tackling the Talking Heads Addon Mod along with THAT mod, Companion Expansion, and ACE Enhanced.
I'm starting over on a new game and seeing what kind of errors I'll encounter. I know that the team has been very helpful about sending debug logs to them but how do I show reports of the game freezing the same way I've done for debug logs?
I'm doing my best to figure out what's going on so we can make everyone's Fallout 2 RPU experience much better.

Update: So I was about to leave the temple for the next room and the game booted me to Desktop. Now the music is looping and the game can't be closed (It doesn't even show up on Task Manager. Figure that one out) and the only way to remedy this is by forcing shutdown. What do we do?
![Fallout2Crash5](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/6ed018a7-6aa9-4d9c-96d9-0d9b16efe220)
Edit: Should I add Talking Heads and THAT to the FO2 mod list or is that not required?

**Comment by burner1024** [comment]
Unless you can reproduce the issue without additional mods on top of RPU, there's really not much to do.

**Comment by ThatGuyFromReZero** [comment]
Understood. I'll try a run with only the Talking Heads mod and omit the rest. If it still causes the game to freeze/loop then I think this means that the Talking Heads Addon Mod is not compatible with RPU. (Which is ironic because the mod page itself states that in order for the Talking Heads Addon Mod to work, RPU must be installed first) After going on the Comment's page I noticed that Nova Rain said this "You might consider using a [slightly older version (F2-InventoryFilter_v2.0.2)](https://github.com/rotators/InventoryFilter) that is compatible with current RPU + talking heads mod setup." He was discussing this with [KSNiF85](https://www.nexusmods.com/fallout2/users/2254064). Maybe that might work. Dunno though.

**Comment by NovaRain** [comment]
You should consider posting issues on [Talking Heads mod discord](https://discord.gg/WgAfvVFdmb﻿) instead of RPU repo.

**Comment by ThatGuyFromReZero** [comment]
> You should consider posting issues on [Talking Heads mod discord](https://discord.gg/WgAfvVFdmb%EF%BB%BF) instead of RPU repo.

@NovaRain 
Very good sir. I've got the Talk Heads Addon mod along with THAT mod and placed their names into my mod_order file. I'll still join the Discord for more accurate troubleshooting. Wish me luck.

**Comment by ThatGuyFromReZero** [comment]
@burner1024 
Update: So I installed the mods again but this time, I put them on the mods_order list in a manner someone on Nexus suggested. No issues to report so far. If I make it to the Lara quest and am able to complete it without experiencing any issues/crashes/freezes along the way between my departure from Arroyo to the completion of Lara's quest in The Den, then I think we can close my issues. But I will still want to make a guide to be posted here for those who may stumble across similar issues when trying this out for the first time.

**Comment by ThatGuyFromReZero** [comment]
@burner1024 
So, I made it to Lara's quest without so much as a freeze or crash along the way. Then, as soon as I finished killing the final guard at the church, the game CTD with this error message:
![Fallout2LaraCrash](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/147804585/e2568ce6-a8e6-42d5-9b43-22935344c6ab)
Which version of sfall do I need for this problem again?

**Comment by ThatGuyFromReZero** [comment]
@burner1024 Hold the phone! I may have "unintentionally" fixed it!

**Comment by ThatGuyFromReZero** [comment]
@burner1024  So, I finished Lara's Quest. That CTD was somehow fixed when I installed that sfall file that GoatBoy11 pinned to the top. I was able to finish the quest with no trouble at all and without having to start a new game. I'm sure that there may be some other bugs in the future but for now, let's officially call this issue Closed.
I know I've been a VERY frustrating person to work with but I'm glad that after many trial-and-error runs, we fixed it. Now that I know what to do, I'll focus on making guides for clean installations. Maybe even go so far as to bundle the recommended mods together in one package.
For now though, you may close this issue.

**Comment by ThatGuyFromReZero** [comment]
Ok. This is awful of me to say this after having believed I fixed everything but... The game is still freezing. I made a new save after a clean install of RPU and almost as soon as I got to Klamath, the game froze again in the same manner I've been experiencing these past months whenever I use Talking Heads...
Please don't be mad at me. I'm dead set on making sure every last detail works properly.

**Comment by burner1024** [comment]
Maybe try UPU, and vanilla too.

**Comment by NovaRain** [comment]
That freezing reminds me of the "not responding" error on newer Windows. Try `EXTRA_WIN_MSG_CHECKS=1` in f2_res.ini.

**Comment by ThatGuyFromReZero** [comment]
Duly noted. Also got Nova Rain's message on trying EXTRA_WIN_MSG_CHECKS=1 in f2_res.ini. I'll see what happens but it may have to wait until the evening after I finish work.

**Comment by ThatGuyFromReZero** [comment]
I can send over the hardware I use. BTW, Nova Rain's tip didn't fix the problem:
16 GB RAM
RTX 3090
AMD Ryzen 9 3950x 16-core
x570 Tai Chi Motherboard
FireCuda 530 4TB SSD (That's where I keep all my games)
Samsung 1 TB SSD (I use that for my OS and other programs)

**Comment by ThatGuyFromReZero** [comment]
@burner1024  When you said Hardware issue, I decided to make sure the refresh htz of the game and monitor matched each other but the game still froze. However, someone on Discord suggested that the presence of FO2 Tweaks is causing conflict with the Talking Heads Addon. I'll try using Talking Heads Addon without FO2 Tweaks and see if the game behaves or not. For the record, I've used FO2 Tweaks with RPU, ACE, and Companion Expansion and never had any problems. If the game still freezes without FO2 Tweaks, then I'll close down this Issue and take it up with the Author of the Talking Heads Addon mod. If I have anything to report to the devs of RPU, You'll be the first to know.

PS: I've been careful that whenever I install FO2 Tweaks I install it correctly so that it doesn't overwrite the ddraw files as I was warned that those would cause issues.

**Comment by ThatGuyFromReZero** [comment]
@burner1024  Ok, played half an hour or so without FO2 Tweaks and not a single freeze to report. Possibly, FO2 Tweaks causes scripting issues with Talking Heads. Where do we go from here? Should I move this issue to GoatBoy11? Or to the FO2 Tweaks page? Let me know when you can and I'll respond as soon as I am able.

**Comment by ThatGuyFromReZero** [comment]
@burner1024  Ok, So I removed FO2 Tweaks, kept Talking Heads Addon, and started a new game. Got through the Temple, Arroyo, and the Guard the Brahmin quest with no issue. However, when I rested to heal up, I decided I'd head for the Military Base as the game usually froze there when I had THA in my files. Just as I headed for the Klamath exit grid, the game froze/looped again. FO2 Tweaks isn't the problem. I'll close the issue here and see if I can reach out to GoatBoy11. I'll also see if I can duplicate the results on other computers. Maybe you're right. Maybe it's a local hardware/software issue on my end.

**Comment by aud1cted** [comment]
I'm using Fo2 Tweaks, Talking Heads Addon (plus the "Talking Heads actually talk" mod) too and i'm having the exact same issue. Whenever i leave Arroyo heading Klamath, the first random encounter always results in crash (I'm assuming it's the first Kaga encounter, the game crashes instantly i cannot see which encounter it is). It's not a local hardware/software issue... This is not the first time we are playing this game.

![Screenshot_1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/117252312/4874baae-8563-4a02-b211-6ead323fb63d)

**Comment by ThatGuyFromReZero** [comment]
@aud1cted Try again but be sure to not overwrite the RPU ddraw.dll with the FO2 Tweaks ddraw.dll. Oh, and get this


In case of crashes during Lara's quest or instances where an NPC initializes dialogue with the player please do the following:

1) Download the most recent version of SFALL from [here](https://sourceforge.net/projects/sfall/).

2) Extract the contents in the main FO2 directory the and overwrite everything  ASIDE FROM "ddraw.ini".

The CTD isn't caused by the mod but by the current iteration of Sfall RPU v28 uses.

After you do that, try going to the military base. It always consistently froze there when I had the Talking Heads Addon.
