### ISSUE TITLE
Description falsely claims that I crippled enemy’s right arm

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#256]
### What happened

I critically hit somebody in her right arm, and the description told me that that crippled her arm. In reality, her arm was uncrippled.

### What you expected to happen

A different message should be used for this type of critical.

### Screenshot

![inconsistent](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/e459ed0e-e60b-4c0a-bab5-63e749f0cdf1)

### Savegame

It’s kind of pointless to provide a save for this, but oh well.

[do you condemn Hamas‽ do you condemn Hamas‽ do you condemn Hamas‽.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/13709387/do.you.condemn.Hamas.do.you.condemn.Hamas.do.you.condemn.Hamas.zip)

**Comment by burner1024** [comment]
Apparently there's some mismatched messages:
> [DSCD] \<novarain13\> OK, here's a list _I think_ the messages are incorrect, other humanoid/biped critter types seem OK:
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/game/combat.msg
```
Men right arm:
Message - 5014 (changed to 5010 as left arm crit?)
Failure - 5000 (changed to 5014 for actually crippled)

Women right arm:
Message - 5114 (changed to 5110 as left arm crit?)
Failure - 5100 (changed to 5114 for actually crippled)

Gecko right arm (using some messages from Men):
Message - 6702 (nothing wrong)
Failure - 5000 (changed to 5014 for actually crippled?)

Alien right arm (using some messages from Men):
Message - 6806 (nothing wrong)
Failure - 5000 (changed to 5014 for actually crippled?)

Giant ant right arm (using some messages from Men):
Message - 6906 (nothing wrong)
Failure - 5000 (changed to 5014 for actually crippled?)
```
> Note: If the target passes the stat check for the crit effects, "Message" will be shown. If fails and gets cripple effect applied, "Failure" will be used instead.

**Comment by burner1024** [comment]
Will be fixed in sfall.

**Comment by Anarcho-Bolshevik** [comment]
There seems to be a similar problem when critically hitting a Super Mutant in the right arm. The description claims that it struck his temple.
