### ISSUE TITLE
Kaga encounter consists of nobody

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#257]
### What happened

Heading south, the ‘special encounter’ icon flashed on the world map without leaving a spot, so I am presuming that it was supposed to be another encounter with Kaga. Nevertheless, looking around I realised that there was nobody in this encounter.

(I doubt that it matters, but earlier in the story when the map asked me if I wanted to encounter Kaga, I ignored it.)

### What you expected to happen

Kaga and a few raiders should have been around.

### Screenshot

![where are they](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/a885b820-702a-45d5-b4ab-cdd7209b405c)

### Savegame

[where’re you going get back here.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/13756185/where.re.you.going.get.back.here.zip)

**Comment by burner1024** [comment]
Not really sure how to debug it...

**Comment by burner1024** [comment]
I'm pretty sure it's Kaga, you can get the encounter ("A bunch of angry raiders') very fast if you load the save and drive around. One time I even managed to get an empty encounter too, on another map.
I thought something was wrong with the map, but I got a proper encounter on this one too.
Looking at `eckaga` scripts and `worldmap.txt` encounter, nothing too obvious.

I've added some debug. For now, I don't see what else can be done. If you hit this again, please enable and include `debug.log`.
