### ISSUE TITLE
Deathclaw spawned outside of the cave’s boundaries

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#258]
### What happened

After massacring all of the critters in a random encounter, I went inside and massacred all of the Lesser Deathclaws in the nearby cave except for one.

### What you expected to happen

I expected all of the Deathclaws to be within my line of sight.

### Screenshot

![sneaky](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/cba1962e-2adc-48f0-8613-dc91b65c1414)

### Savegame

[how did you get back there.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/13774108/how.did.you.get.back.there.zip)

**Comment by burner1024** [comment]
This is `cave3.map / cave03.ssl`. I moved the spawn point further away from the wall. Probably should fix it.
![Captura desde 2024-02-26 14-45-10](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/1279852/02d057ee-1a18-4110-9ee8-6d3242aaa09d)
