### ISSUE TITLE
Random freezes

### ISSUE THREAD

**Issue by mrkaga** [BGforgeNet/Fallout2_Restoration_Project#259]
I don't know if this mod or some other is the cause for crashes but will try anyway. Installed RPU and F02Tweaks and "Perk Every Level" mod. I also configured the .ini files accordingly. Everything worked until in Klamath the game began to freeze randomly.

Error code 1: The instruction at 779c40b3 referenced memory at 00000000. The memory could not be read from
Error code 2: The instruction at 779c406d referenced memory at 00072eca. The memory could not be read from

Thanks for answering.

**Comment by burner1024** [comment]
Try without perk mod. Also see #255.

**Comment by mrkaga** [comment]
Thanks, I will do that and I suppose that I need to start new game. Do I need to update the sfall from Github here as well?

Will repost when I play new game another day and if it crashes again.

**Comment by burner1024** [comment]
Probably shouldn't need a new game, but you can try.
Updating sfall may help, or may not.

**Comment by mrkaga** [comment]
One last question though. Does the error code not provide any hint what the crash cause was?

Someday I will give the game with mods one last chance before I give up and let it lay in dust :(

**Comment by aud1cted** [comment]
I assume you are also using Talking Heads mod as well? Because that was what causing the freezes in my case.

I don't use Perk Every Level mod, but i use Fo2 Tweaks and i'm certain it's not the culprit. Perk Every Level might be the issue in your case.

**Comment by burner1024** [comment]
You can also try another copy of the game with an older RPU version (v26, 25, etc), and see if that crashes/freezes as well. You would need to start new game in those, though.

**Comment by mrkaga** [comment]
Do you have any suggestion which versions I should test? Will do that someday when I have patience for trial & error. It's not like the game begins to crash instantly but after few hours in then it can start happen regularly.

Might quick save have something to do with it? Just a thought if I might avoid quick saving.

**Comment by burner1024** [comment]
27 is basically the same as 28. Maybe 26, 25.
But in fact I have little hope for it. All the later versions have minor changes, can't think of anything that would cause generic crashes or freezes without a reproducible case.

Maybe try just downgrading sfall: 4.3, 4.2, 4.1. Might be combination of settings and hardware that don't work well.

**Comment by aud1cted** [comment]
sfall 4.4.1 is definitely freezing the game with v28. Military Base area is the best section to reproduce the error. It almost immediately freezes once you get there.

**Comment by mrkaga** [comment]
> sfall 4.4.1 is definitely freezing the game with v28. Military Base area is the best section to reproduce the error. It almost immediately freezes once you get there.

Sounds "promising". So that's where I'm going to at start of the game and test someday soon.

**Comment by mrkaga** [comment]
Can't reproduce the crash in Military Base with the current installation versions (sfall 4.3.8). So created another character and left the temple ("W" key) and went to Klamath which led to crash almost instant.

So it seems to be a good spot for me testing different versions. There is something wrong in Klamath for me.

**Comment by aud1cted** [comment]
You are NOT copying the ddraw.dll file from the Fo2 tweaks mod right? Because it just occured to me that when i was modding the game i just copied the mods folder, not ddraw.dll.

I think that is your culprit.

**Comment by aud1cted** [comment]
I think what you need to do is this:

Backup your save game files, and do a clean install.
Install the RPU.
Begin a new game with a meele character and proceed quickly to the Klamath if it is crashing. Save while there.
Copy only the mods folder from Fo2tweaks, not ddraw.dll.
Place only the .int file to the scripts folder from PerkEveryLevel mod.
Load the new save you've created and check again.
Then use your old saves and check if the issue persists.

**Comment by mrkaga** [comment]
I think you might be right because I could not reproduce the crash in Klamath after running around 10 minutes, save, reload, etc. Thanks so much for noticing my bad mistake!

**Comment by burner1024** [comment]
So, uhm, do I understand correctly that you have freezes with sfall 4.4.1, but not 4.3.8?

**Comment by mrkaga** [comment]
It was 4.3.8. Because I also copied the ddraw.dll from F02Tweaks. Maybe that is what caused crashes in Klamath for me.

**Comment by burner1024** [comment]
So, then reverse? 4.3.8 has problems, and 4.4.1 doesn't?
Please clarify which versions work for you and which have problems (what problems?).

**Comment by mrkaga** [comment]
It's 4.4.0.1 which came from your installation. I avoided to copy the ddraw.dll from FO2Tweaks. I could not reproduce the crash in Klamath after testing different things there for like 15-20 minutes.

So maybe it was because of the ddraw.dll from F02Tweaks yeah.

**Comment by aud1cted** [comment]
It was definitely the ddraw.dll from the Fo2Tweaks because basically you are changing the sfall version when you are copying it. My freezes began after i've updated the sfall version to 4.4.1. I don't know which version of sfall comes with the Fo2Tweaks mod, but my experience with v28 goes like this:

4.4.0.1 ---> no freeze.
4.4.1 ---> freezes.

I didn't try any other sfall version.

**Comment by mrkaga** [comment]
Created character with 2 strength lol.. went to Navarro and grabbed the Advanced Power Armor so it gave me 6 strength enough for weapon. Also finished the quest there and got few sweet perks from the mod. Then I went to Klamath and completed all quests there and got none crash.

It was indeed the ddraw.dll from Fo2Tweaks as the culprit. Maybe you should consider to update that mod with better ddraw.dll.

**Comment by burner1024** [comment]
I guess not related to RPU then.
