### ISSUE TITLE
Modding weapon doesn't replenish ammo.

### ISSUE THREAD

**Issue by bloodaxis** [BGforgeNet/Fallout2_Restoration_Project#26]
I've managed to narrow this down to the RPU after trying to see if the culprit was my individual settings or fo2tweaks or any of the other mods I'm using, I'll attach a savefile right next to Eldridge with a non modified Hunting Rifle in the inventory that doesn't get full ammo when it's been modified. The save file is from a clean steam install with RPU version 9 installed on top. I checked known issues and the change logs of both RPU and the unofficial patch to see if it's an intended change but I couldn't find anything so I'm assuming it's a bug somewhere.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4022695/SLOT01.zip)

**Comment by burner1024** [comment]
That is an [intended change](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/312dc5aef9de22d1112064c5cf599b7632d7581f/scripts_src/headers/upgweap.h#L13), sorry. I'm pretty sure it's been in UP for a long time.
