### ISSUE TITLE
Do some companions not use vanilla weapon animations?

### ISSUE THREAD

**Issue by mrkaga** [BGforgeNet/Fallout2_Restoration_Project#261]
I read on the internet about some using Vic with energy weapons as Turbo Plasma Rifle or Gatling Laser. However in this he does not equip them so I added more weapon animations and now he can wear them.

Was there a mistake with gear animations different from the vanilla game?

**Comment by NovaRain** [comment]
> read on the internet about some using Vic with energy weapons as Turbo Plasma Rifle or Gatling Laser.

Vic does not have corresponding animations for those weapons in vanilla game. It was possible with old B-team mod because party members used the same animation as the player when in their armor appearances.

**Comment by burner1024** [comment]
He still can if you give him some full body armor; power or robes.
