### ISSUE TITLE
Game freezes when trying to install NavComp Chip or when heading to the submarine

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [BGforgeNet/Fallout2_Restoration_Project#262]
When I try to do either of those actions, the game freezes with the music looping every 7 seconds and the only way to get out of it is to shut down the PC. This is getting ridiculous... I can't complete the game now...

**Comment by burner1024** [comment]
maybe try on another pc

**Comment by ThatGuyFromReZero** [comment]
@burner1024 NVM, I found out what the problem was. The game engine seems to only cap at Level 99. Trying to go beyond Level 99 causes the game to lock up. Of course, anyone who uses the Subaru Leveling System will only be able to max out at 485100.
