### ISSUE TITLE
Changing game difficulty doesn't seems to be working. 

### ISSUE THREAD

**Issue by xsarq** [BGforgeNet/Fallout2_Restoration_Project#263]
### What happened

I started new game and set my game to normal. I exit Temple and went to talk to NPC that checks if your meele skills is greater than 36% and then offer training (Jordan). I tried to lower difficulty to temporary increase my meele skills to pass the checkpoint just like I did many times in the past but it did not work.

### What you expected to happen

Switching difficulty should modify skills. Hard should give - 10% and easy something like +10%? I dont remember exactly. After switching game difficulty the hit chance in combat did not move and skill points did not get switched - This looks like switching difficulty button doesn't work at all. 

### Screenshot
https://youtu.be/4XqnmrfLW7Q (be sure to turn off voice Im in work, next to few production machines sorry)

**Comment by xsarq** [comment]
Sfall 4.4.0.1
Rp 2.3.3 Version 28

**Comment by burner1024** [comment]
combat skills are not affected by difficulty
