### ISSUE TITLE
Crash  004a2b2f referenced memory at 00000078

### ISSUE THREAD

**Issue by Kevinelpevin** [BGforgeNet/Fallout2_Restoration_Project#264]
Hello there. 
The game crashes when I try to do Lara's mission, just after clearing the church and leaving the combat. The mods I have are Restoration project (latest version on github), restoration project heads and sfall
![Screenshot_1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/158741581/d4a70fda-288c-4804-a78d-edc220088320)
Thank you in advance

**Comment by NovaRain** [comment]
> restoration project heads

https://www.nexusmods.com/fallout2/mods/45?tab=posts
See the first sticky message.
