### ISSUE TITLE
RPU 28, Sfall 4.4.1, F2 1.02d – Crash upon entering Vault City (and a few other locations)

### ISSUE THREAD

**Issue by WWWFWWW** [BGforgeNet/Fallout2_Restoration_Project#265]
Installed F2 1.02d (GOG) > RPU > SFALL 4.4.1 as recommended in a few other posts. Added fo2tweaks v12.15, keeping the sfall's version of ddraw.dll (the latest, 11/2023) – as recommended from other bug reports here (as RPU would either crash or be bugged in the EPA levels without it).

Game crashes upon entering Vault City. Sfall log doesn't show anything amiss.

"An illegal instruction was executed at address 004f15a7"

Played around with disabling fo2tweaks in mods_order.txt (; should comment out a mod and disable it, right?), same crash.
Tried ddraw.dll from fo2tweaks (an older version from 3/2023), no difference, still a crash.

RPU 28 on its own without the latest sfall was bugged in EPA, crashing or "ghosting" in the lower EPA levels (elevators didn't work), but now it's the Vault City that's crashing.

mods_order.txt, autogenerated:

cassidy_head.dat
cassidy_voice_joey_bracken_hq.dat
f2_res.dat
fo2tweaks.dat
npc_armor.dat
party_orders.dat
rpu.dat
rpu_enhanced_worldmap.dat
rpu_extended_flamer.dat
rpu_improved_mysterious_stranger.dat
rpu_rifle_animations.dat
rpu_wakizashi_animations.dat

**Comment by NovaRain** [comment]
Try extracting this script to your `Data\scripts\` folder:
[vctyctyd-export.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14324628/vctyctyd-export.zip)

**Comment by WWWFWWW** [comment]
@NovaRain Thanks! That script did indeed work for Vault City, at least the initial two areas I tested (and a few other cities discoverable on map without any prerequisites like scripted encounters).

Unfortunately I still get the same crash when trying to access the Abbey north of it (both with the latest sfall and ddraw.dll, and RPU 28 original dlls, at least in my limited testing).

Although, debugging Fallout 2 and mods is pretty hard, with all the different version combinations of various libraries and ini files, especially given that each session needs manually going through the Temple of Trials at first if one wants to start with a clean state. 

Any idea what the issue could be or how could one make debugging any issue easier? It's hard to know if the crashes might be related to ddraw libs or ini changes – some of which are simply required to get the game to run on modern systems, or get to the tested areas quickly )like lowering random encounter rate to nearly zero, because otherwise one wouldn't get anywhere while testing without fighting endless encounters) – or which might be related to RPU/UPU things like map scripts?

How much of that is carried over with saves, i.e. can one make a testing save just _before_ e.g. entering the Abbey and try out different dll and ini configurations, or would that only introduce more variables into the mix?

Thanks!

**Comment by NovaRain** [comment]
Try these scripts: [scripts_fix.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14337340/scripts_fix.zip)

> Any idea what the issue could be

See https://github.com/BGforgeNet/Fallout2_Restoration_Project/pull/260

> can one make a testing save just before e.g. entering the Abbey and try out different dll and ini configurations, or would that only introduce more variables into the mix?

I'd just use `StartingMap` and `PipBoyAvailableAtGameStart` settings in ddraw.ini to make a new game start at the nearest location (e.g. Gecko) then go there. Or write my own test script to teleport me to the nearest location.

**Comment by WWWFWWW** [comment]
> Try these scripts: [scripts_fix.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14337340/scripts_fix.zip)

Aww, thanks!

I now see that you later added the other two compiled scripts (Abbey and NCR) from #260 as well, great! You just saved me a lot of effort trying to set up a VS dev environment just to compile sslc and the other two scripts from 260, which would have been a headache ;-)

Just checked and it seems it fixes the crash issue in VC, Abbey and the NCR, so this is welcome for Wine users on Mx Macs (I gather from 171 that the crash was solved on Windows).

Cheers!

**Comment by NovaRain** [comment]
> You just saved me a lot of effort trying to set up a VS dev environment just to compile sslc and the other two scripts from 260, which would have been a headache ;-)

You can grab the sslc (compile.exe) from [sfall modderspack](https://sourceforge.net/projects/sfall/files/).

**Comment by burner1024** [comment]
Merged #260.
