### ISSUE TITLE
Недоработка диалога в побочном квесте Аббатства

### ISSUE THREAD

**Issue by shahooey** [BGforgeNet/Fallout2_Restoration_Project#266]
### What happened
У брата Самуила можно взять квест на поиск человека, который раскапывает по ночам могилы (бедняк Том), при этом он упоминает, что сперва следует поговорить с фермером Питерсоном по данному поводу. В разговоре с Питерсоном тот предлагает, чтобы при встрече с этим Томом убедить его трудоустроиться на его ферму. После этого у ГГ есть выбор из трёх стандартных вариантов ответа в диалоге (скриншот №1) - принять во внимание данную идею, но сперва задать пару вопросов; принять во внимание данную идею и уйти; принять во внимание данную идею с использованием юмора (?). Проблема в том, что из всех данных ответов, лишь второй (выделен красным) ведёт к появлению в диалоге с Томом ветки с его вербовкой на ферму (скриншот №2, выделено красным).

Используется: ф2 из стима + RPU v28 (всё в русскоязычных версиях).
### What you expected to happen
Все три варианта ответа Питерсону должны давать возможность в диалоге с Томом трудоустроить его на ферму.
### Screenshot
![scrn1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/47d06369-c7ad-4714-92a8-02f580519313)
![scrn2](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/ada180c9-d26b-4f5e-ab72-d23a014ff12b)

### Savegame
[SLOT138.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14349118/SLOT138.zip)

**Comment by burner1024** [comment]
That's correct for options 1 and 2. I wasn't sure about option 3, but after reflecting a bit, I tend to agree.
