### ISSUE TITLE
Модель Сулика после расставания с ним в его племени

### ISSUE THREAD

**Issue by shahooey** [BGforgeNet/Fallout2_Restoration_Project#267]
### What happened
После завершения квеста по спасению сестры Сулика, будучи в племени, Сулик просит дать ему время попрощаться со всеми. Спустя сутки если начать с ним диалог, то он скажет, что готов путешествовать с ГГ дальше. Если в этот момент расстаться с ним, выбрав вариант ответа, что ему лучше остаться в племени рядом с сестрой (на скриншоте выделено красным), то все вещи из его инвентаря переносятся в инвентарь игрока, ВКЛЮЧАЯ экипированные оружие и броню. Однако модель Сулика не возвращается к дефолтному виду, сохраняя вид той брони, которая была перед передачей всех вещей.

Используется: ф2 из стима + RPU v28 (всё в русскоязычных версиях)
### What you expected to happen
Модель Сулика должна стать дефолтной после трансфера всех его вещей игроку.
### Screenshot
![scrn1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/e0c53b87-5c54-4d6e-a18b-e95272af3d72)

### Savegame
[SLOT139.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14378104/SLOT139.zip)

**Comment by NovaRain** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/250d3f5693a5ca50d2fcc9e6202c5271a3accc1c/scripts_src/klamath/kcsulik.ssl#L1941
This should work:
```js
inven_unwield(self_obj);
art_change_fid_num(self_obj, FID_NMWARR); // reset appearance
```
