### ISSUE TITLE
rpu-install.sh on MacOS/BSD requires slight tweaking

### ISSUE THREAD

**Issue by korri123** [BGforgeNet/Fallout2_Restoration_Project#27]
Currently you will get this message when running it on macOS:
`sed: 1: “…”: Invalid command code f`
Found a fix here: https://stackoverflow.com/questions/29081799/sed-1-invalid-command-code-f

I have also placed a command at the top that sets the current directory to the one of the sh file, so the file can simply be double clicked to be installed, instead of having to cd yourself to the directory and then running the sh file through terminal.

You can copy paste this fixed version:
```
#!/bin/bash
cd -- "$(dirname "$BASH_SOURCE")"
bdir="backup/rpu"
mkdir -p $bdir/data

if [[ -f patch000.dat ]]; then
  mv patch000.dat $bdir/
fi

# keep savegames, sound, character files
for i in $(ls data | grep -vi "^savegame$\|\.txt$\|\.gcd$\|^sound$"); do
  mv data/$i $bdir/data/
done

# sfall mods
mkdir -p data/scripts
scripts="
gl_ammomod.int
gl_highlighting.int
gl_npcarmor.int
gl_partycontrol.int
"
for f in $scripts; do
  mv $f data/scripts/
done

# old appearance mod in directories
if [[ -d appearance ]]; then
  for i in $(ls appearance); do
    if [[ -d $i ]]; then
      mv appearance/$i $bdir/
    fi
  done
fi

# sound path fix
rm -f camlrt.dll initool.exe
cp fallout2.cfg $bdir/
sed -i '' 's|music_path1=.*|music_path1=data\\sound\\music\\\r|' fallout2.cfg
sed -i '' 's|music_path2=.*|music_path2=sound\\music\\\r|' fallout2.cfg

echo "RPU installed. Backup is in $bdir."

```

I'd recommend making this file separate from the Linux file and having mac somewhere in the name. Instead of having a .sh file extension, I'd use .command as it is owned by terminal and not xcode by default (so you can simply double click the file to run it, no need to open the terminal yourself). I have tested this on macOS High Sierra and it works great.

**Comment by burner1024** [comment]
What's BASH_SOURCE line do?
I guess I can just symlink .sh to .command, to avoid duplication.

**Comment by burner1024** [comment]
Also, maybe you have gsed?

**Comment by korri123** [comment]
The BASH_SOURCE line comes from [this](https://stackoverflow.com/a/29710607/6741772), basically if you run the file by double clicking it by default the user's home directory will be used instead of the Fallout 2 directory, where all the files are

**Comment by korri123** [comment]
I'm not sure if the tweak I put in there is ideal for Linux, as it seems to work there fine. The tweak is only required for BSD/MacOS systems according to the StackOverflow link in the OP. Hence why I think another file would be preferable to symlink.

**Comment by korri123** [comment]
gsed is not provided by macOS by default, but sed however is. It works fine if you do the slight tweak above.

**Comment by burner1024** [comment]
OK I'll see if it works on both systems.

**Comment by korri123** [comment]
Great work, many thanks!
