### ISSUE TITLE
Доктор Эндрю путает устанавливаемый имплант в разговоре с ним

### ISSUE THREAD

**Issue by shahooey** [BGforgeNet/Fallout2_Restoration_Project#270]
### What happened
При определенной последовательности ответов в диалоге с доктором Эндрю про импланты он может перепутать устанавливаемый имплант. В ходе тестирования этой проблемы было выявлено 4 сценария, когда это может произойти (далее НУ - имплант Низкой Ударопрочности, ВУ - Высокой Ударопрочности, НТ - НизкоТемпературный, ВТ - ВысокоТемпературный):

1) установленные импланты отсутствуют
[расспросить про НУ] => [поставить НТ] - ожидается НТ, по факту персонаж получает НУ

2) при уже установленном НУ
[расспросить про ВУ] => [поставить НТ] - ожидается НТ, по факту персонаж получает ВУ

3) при уже установленном НТ
[расспросить про НУ] => [поставить ВТ] - ожидается ВТ, по факту персонаж получает НУ

4) при уже установленных НУ и НТ
[расспросить про ВУ] => [поставить ВТ] - ожидается ВТ, по факту персонаж получает ВУ

(!) В пунктах 2 и 4 необходимо спросить у доктора ВСЕ уточняющие вопросы про соответствующий имплант, и только потом поинтересоваться другим имплантом.

Пример ветки диалога на пункт 2 представлен на скриншоте.
Из всех трёх докторов, которые могут поставить импланты, подобная проблема есть только у доктора Эндрю.
Используется: ф2 из стима + RPU v28 (всё в русскоязычных версиях).
### What you expected to happen
Имплант должен соответствовать тому, который был выбран в диалоге.
### Screenshot
![scrn1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/2317aaad-334b-4366-b40a-32db0c6e2696)

### Savegame
[SLOT142.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14386852/SLOT142.zip)

**Comment by burner1024** [comment]
[vcandy.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14392492/vcandy.int.zip)
Drop this into `data/scripts`, should work.
