### ISSUE TITLE
Использование объекта вместо применения предмета из инвентаря на нём

### ISSUE THREAD

**Issue by shahooey** [BGforgeNet/Fallout2_Restoration_Project#271]
### What happened
Проще всего объяснить проблему на данных 3 примерах:

1) [скриншот №1] при использовании ядерных батарей на машине через контекстное меню, если в момент клика ЛКМ курсор находился на фоне модели машины, персонаж просто активирует машину для поездки. Если курсор находился на фоне багажника, то персонаж откроет багажник.

2) [скриншот №2] при использовании винта на Фрэнсисе в Брокен Хиллс, если курсор оказался на фоне модели Фрэнсиса (его модель выделена красной рамкой), то вместо применения винта на нём персонаж просто начнёт с ним диалог.

3) [скриншот №3] при использовании электронной отмычки на полках, если курсор оказался на фоне модели полок, то вместо оповещения о том, что данное действие ни к чему не приведет, персонаж откроет инвентарь этих полок.
### What you expected to happen
Результат применения предмета на объекте не должен зависеть от взаимного расположения курсора и модели этого объекта.
### Screenshot
![scrn1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/61465d43-7670-4c1e-ac29-59b60c71c75b)
![scrn2](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/af141c60-5937-4679-b38d-23626cf1d771)
![scrn3](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/160628467/27efdecb-78d2-4618-8806-912e1aa20685)

### Savegame
[SLOT150.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14394959/SLOT150.zip)
На данном сохранении можно протестировать проблему в случае с машиной.

**Comment by burner1024** [comment]
It's the engine. Can't help with that.
You may want to try and open an issue in [sfall](https://github.com/sfall-team/sfall) and/or [CE](https://github.com/alexbatalov/fallout2-ce) repos.

**Comment by NovaRain** [comment]
[sfall_use_inv_fix-test.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/14475545/sfall_use_inv_fix-test.zip)
I made a quick hack fix for the issue. Please help check/test this sfall dev build in game. At least the problems in your three examples shouldn't happen anymore.
