### ISSUE TITLE
Linux install script is self invalidating

### ISSUE THREAD

**Issue by DuendeInexistente** [BGforgeNet/Fallout2_Restoration_Project#273]
### What happened
Downloaded the zip, extracted to fallout 2 folder, ran install.sh. [This checks if upu.dat is in the mods folder](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/b2c5f9d72f14b97f8ba46e13328319680c0c5091/release/rpu-install.sh#L28). Because rpu includes upu.dat by default, the script cannot be run without modifying it.

**Comment by burner1024** [comment]
No it doesn't.
