### ISSUE TITLE
Kaspersky false positive, not a bug

### ISSUE THREAD

**Issue by S1lv3r2** [BGforgeNet/Fallout2_Restoration_Project#274]
### rpu_v28.exe detected as Trojan by Kasperky, I know this is not a bug but I have no idea how to solve this since the opentip (https://opentip.kaspersky.com) doesn't let you analyse the .exe because it's too big.

**Comment by burner1024** [comment]
It's likely reacting to bundled sfall.
As for tips to solve this, I suggest contacting Kaspersky.
