### ISSUE TITLE
rpu-install.sh keeps asking me to recursively lowercase the directory when I already have done so

### ISSUE THREAD

**Issue by Vitoria90** [BGforgeNet/Fallout2_Restoration_Project#277]
### What happened
I can't install the Linux version of RPU, on Ubuntu 22.04.4 LTS, because the install script keeps asking me to recursively lowercase the Fallout 2 directory after I have already done so.
I have tried both on the wine virtual C drive and also with the fallout 2 folder directly in the home folder.
### What you expected to happen
For it to install
### Screenshot
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/22651510/f9a7a840-c218-4d03-80a7-354ea1588ebd)
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/22651510/47ba98a6-5f4c-4e0e-b38e-c5fb2810fa74)
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/22651510/7505031d-caac-4565-948b-70281b6ebc7d)

### Savegame
not applicable

**Comment by burner1024** [comment]
Run `bash -x rpu-install.sh`, and you'll see the flow.

**Comment by Vitoria90** [comment]
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/22651510/61a1539a-39d0-41fa-b923-5832247307c6)

Here's the result of that

**Comment by burner1024** [comment]
Now you can see that `find . -name '[[:upper:]]*' .` finds something. Run that command to see what exactly.
