### ISSUE TITLE
World Map Crash Special Encounter

### ISSUE THREAD

**Issue by fakk3** [BGforgeNet/Fallout2_Restoration_Project#279]
### What happened

The game crashes every time on the first special encounter discovered on the main map (The game asks if I want to visit the location. I click yes and the game crashes to the desktop.). This happens every time I start a new game and leave Arroyo.

Regular desert encounters work normally.

I played the GOG version of the game with the restoration project v28 patch. No additional mods. Windows 11 as the main operating system.

### Screenshot
![f2crash](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/38753623/4b897b7c-a236-452d-bb22-b519045cacda)

**Comment by NovaRain** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/264
If you're using the talking heads addon, see the first sticky post.
https://www.nexusmods.com/fallout2/mods/45?tab=posts

**Comment by fakk3** [comment]
> #264 If you're using the talking heads addon, see the first sticky post. https://www.nexusmods.com/fallout2/mods/45?tab=posts

Yes, I use the talking heads mod. I noticed that after disabling this mod in mods_order.txt, the game did not crash. Interestingly, this happens the first time you meet Kaga.

**Comment by fakk3** [comment]
I actually uploaded the files suggested from the nexus website and everything works normally.
