### ISSUE TITLE
Gecko Ghoul Aggro Bug?

### ISSUE THREAD

**Issue by RatJuuntox** [BGforgeNet/Fallout2_Restoration_Project#280]
Second time in Gecko and some ghouls started aggroing to me when I tried to reach the reactor. Read on the forums that this was something that can be patched out by the UP, but im using RPU installation. Images show I don't have aggro in this part of town, but when I reach the shack by the Reactor i get aggro. I entered the Reactor to try to avoid them and was able to get to past the guards and to the supply requisition room. Though they also started to aggro once I opened the door. Tried reinstalling RPU, but I didn't see any difference.
![image12d](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/167795499/2fc6d7ec-08d6-4012-b229-c9c868c430b0)
![imagedw1](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/167795499/c01023de-04b4-4926-a671-532f4623d319)
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15065627/SLOT02.zip)

**Comment by burner1024** [comment]
Save crashes for me.
Do you use other mods?

**Comment by RatJuuntox** [comment]
I doubt it, After this I did a fresh install from GOG Galalxy and RPUv28. Not sure what could be causing the crash, Ill upload a save where I used a trainer to get to where I was faster. Though now im at Broken Hills. Ghouls still aggro and I maxed my stealth to solve the reactor problem peacefully.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15098230/SLOT01.zip)

**Comment by burner1024** [comment]
Upload a [ZAX](https://github.com/BGforgeNet/zax) debug.

**Comment by RatJuuntox** [comment]
[zax_debug_2024-04-25_09-20-52.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15112930/zax_debug_2024-04-25_09-20-52.zip)

**Comment by burner1024** [comment]
Are you running on windows or wine?

**Comment by RatJuuntox** [comment]
Windows

**Comment by burner1024** [comment]
And you'll need to start a new game.
But for a quick test, you can change `StartingMap` in ddraw.ini to `gecksetl.map`.

**Comment by RatJuuntox** [comment]
Yea, I noticed that. My old saves didn't work, but im thinking you are right. The Highwayman car doesnt load onto the map properly. Only the trunk is visible after repairing it.
