### ISSUE TITLE
[Not a bug report] Explosion animation added by RP

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [BGforgeNet/Fallout2_Restoration_Project#281]
As the title says, this isn't report, but rather a request.

RP seems to have changed the explosion animation to that of massive, long lasting blast smoke, as oppose to tiny, 5 frames-or-so explosion from the original. Is there any way to disable the newly added explosion animation?

**Comment by NovaRain** [comment]
Extract the following files from `art\misc\` from `master.dat`:
```
empxpld.frm
exp.frm
expa.frm
expb.frm
explodeb.frm
explodeg.frm
expp.frm
kpow1.frm
robtrock.frm
roktxpd.frm
rscorpbl.frm
```
And put them in your `data\art\misc\` directory.

**Comment by burner1024** [comment]
do you have screenshots?

**Comment by NovaRain** [comment]
Vanilla explosion (expa.frm):
![expa-orig](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/8564973/02034b02-3b59-42e7-a351-3d1e45afdbf1)
RP explosion (expa.frm):
![expa-rp](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/8564973/9c8ab4cc-f687-4049-9b1b-2075fe2973f3)
If memory serves, they are converted from Tactics, just like the removed Environmental Armor critter set.

**Comment by burner1024** [comment]
I like the second one. But yeah, we can separate it into a component.

**Comment by Lexx2k** [comment]
Problem is that the 2nd duplicated 6 or what times on every explosion, which makes it look bad. If it would play only once, the situation might be different.. but the way it is right now is just really terrible looking.

**Comment by phobos2077** [comment]
Wow, and I thought why these explosions look so bad for all these years. I don't even know how vanilla game looks anymore. Definitely needs to be optional.

**Comment by burner1024** [comment]
that makes sense

**Comment by DondeEstaTuHallPass** [comment]
Thank you for the answer. I was going to ask whether extracting those files would also 'revert' the new plasma grenade explosion from RP, and that seems to be the case.
