### ISSUE TITLE
Hakunin talking bug

### ISSUE THREAD

**Issue by Forio25** [BGforgeNet/Fallout2_Restoration_Project#284]
### What happened
After I've done temple of trials and talked to old-one, I can't talk with Hakunin, nothing happen when I clicked on him. Restoration Project is on newest version, didn't update sfall to newer version, no other mods installed. F2 is in polish language.

### What you expected to happen
Talk with Hakunin

### Savegame
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15137792/SLOT10.zip)

**Comment by burner1024** [comment]
Your save appear broken, doesn't load.
Make a debug package with [ZAX](https://github.com/BGforgeNet/zax), attach it here.

**Comment by Forio25** [comment]
[zax_debug_2024-04-27_15-01-10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15138246/zax_debug_2024-04-27_15-01-10.zip)

Here's package

**Comment by NovaRain** [comment]
The cause is probably the leftover file from the [old Polish translation pack](https://fallout-corner.pl/fallout-2/spolszczenie/) you installed (since you have `przelacz.bat`). If you have a `vault13.gam` in your `data\data\` directory, remove it and start a new game.

**Comment by Forio25** [comment]
Yes, I've a vault13.gam in data/data. Started a new game without this file and still have same problem. I will try clean install and use polish translation without a .bat file.

**Comment by Forio25** [comment]
> I'm not sure if you already know, but RPU has its own Polish translation pack.

I don't know, but when I install RPU game is in english and now ZAX didn't work... But I can talk with Hakunin now. So, something wrong with - as you said - old translation polish pack.

**Comment by Forio25** [comment]
With new translation is something wrong too :) Something wrong with translation and RPU :/ So, if RPU have already polish language how to change into it?

**Comment by NovaRain** [comment]
If you use the installer, there's a checkbox for the Polish translation.
Or download [rpu_v*_translation.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/releases), extract `rpu_polish.dat` to your "mods" folder, and add its filename to **mods_order.txt** like this:
```
party_orders.dat
rpu.dat
rpu_polish.dat
```

**Comment by Forio25** [comment]
Now everything working great :) I must download installer, because manual installation doesn't work. 
Thanks a lot for your patient and tell everything. It's time for a new level of adventure from past 👍
