### ISSUE TITLE
 Chad is skimming money quest crash.

### ISSUE THREAD

**Issue by Leannya** [BGforgeNet/Fallout2_Restoration_Project#285]
### What happened: 
The game crashes whenever I end checking the dresser at Chad's house.

### What you expected to happen
A conversation to pop up? Definitely not a crash.

### Screenshot

![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/136006985/88677ad9-d7ca-49ff-97d0-f21fba26f556)

![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/136006985/a4b6a057-ae89-4bb5-9d99-9a6b37110d48)

### Savegame

[SLOT29.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15140063/SLOT29.zip)

Oh right I forgot to mention I'm using the F2Tweaks, Talking Heads, Voiced Talking Heads mods as well.

**Comment by NovaRain** [comment]
> Talking Heads

https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/264
https://www.nexusmods.com/fallout2/mods/45?tab=posts
See the first sticky post.
