### ISSUE TITLE
Cassidy's voiceline cuts off w/ female character

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [BGforgeNet/Fallout2_Restoration_Project#287]
https://www.youtube.com/watch?v=Ry0fWJLQRfA

When asked for questions to Cassidy as a female character while having Myron in the party, Cassidy's voiceline sort of cuts off as he will not say all of his dialogue that are listed, but rather, what I assume only the additional dialogue variant added just for the female character.

Sorry for the link. I couldn't record his dialogue as a video under 10MB file size limit.

**Comment by burner1024** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/33ef2668168d8b38eb38f714ddcd60f3f5f995f9/scripts_src/valtcity/vccasidy.ssl#L891

It's a combined line.
Sound's there. I assume it's an engine issue.

**Comment by NovaRain** [comment]
Maybe combine the voice of Cas0302 and Cas0303 as the new Cas0303 (need a new lipsync)? i.e. msg 303 will be a full dialog line for female PC.
Or a more quick-n-dirty way: just make Cassidy say only msg 302 for both genders, at least it won't have cut-off or sound too awkward in this case.

**Comment by burner1024** [comment]
Probably should concatenate lines and wavs.
Lip files are generated automatically.

**Comment by burner1024** [comment]
Maybe keep split and just insert a `[Next] / ...` reply between them?

**Comment by burner1024** [comment]
@DondeEstaTuHallPass try this. msg into data/text/english, script into data/scripts.
I just inserted a `Next` between the lines for female.
[cassidy.zip](https://github.com/user-attachments/files/16028139/cassidy.zip)

**Comment by burner1024** [comment]
Too bad we don't have a save to test.
