### ISSUE TITLE
Avoiding shotgun wedding in Modoc causes party members to not follow the PC

### ISSUE THREAD

**Issue by H7dek7** [BGforgeNet/Fallout2_Restoration_Project#292]
It's my 30+ Fallout 2 playthrough and I wondered if I can avoid the shotgun wedding. It could be achieved, but strange things happen.

Steps to replicate:
1. Sneak. Plant an explosive to Grisham. Wait for him to explode. Unsneak.
2. Sleep with Miria. At this point Miria's uncle (don't remember his name) spawns above Grisham's corpse and the story goes the same as if Grisham was alive.
3. Repeat step 1, but with Miria's uncle. You have to set the time to 10 or 20 seconds to kill him before the story skips to the church. 

If you succeed, there's no wedding, you continue from Miria's room, but any follower you had at this point won't follow you in the location. They will spawn with you whenever you enter a location, but they won't move unless there's combat. The same applies to any new party member.

I think it's not a RPU bug or even a bug at all and it works as intended (no party members going inside Miria's room after sex and before wedding), but it would be nice if it somehow was "fixed".

EDIT: After another cutscene (Frank's conversation with Gunther in Vault 13) party members follow the PC again.

**Comment by burner1024** [comment]
A common sense solution would be to set Modoc hostile when Grisham dies, but that doesn't really add value.
I don't think there's anything to do here.
