### ISSUE TITLE
Missing Trunk

### ISSUE THREAD

**Issue by Talwin2134** [BGforgeNet/Fallout2_Restoration_Project#293]
### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/15409570/SLOT01.zip)

**Comment by burner1024** [comment]
Can you reproduce it with RPU v29?

**Comment by Talwin2134** [comment]
Is that an update for the version I have.

I will download and try.

**Comment by burner1024** [comment]
Make sure to save backups before any updates.
