### ISSUE TITLE
Steam Deck installation?

### ISSUE THREAD

**Issue by SPavuna** [BGforgeNet/Fallout2_Restoration_Project#297]
Has anyone tried to install this into a Steam Deck? I've been trying for a while now and I'm not successful. I'm following the Linux installation guide but nothing happens when I execute the rp-install.sh

**Comment by burner1024** [comment]
No idea. What's it run? Some custom Linux distro?

**Comment by SPavuna** [comment]
Yup, it's Valve's Linux distro SteamOS

**Comment by burner1024** [comment]
Run script with bash -x and see where it stops.

**Comment by SPavuna** [comment]
This comment has some more detailed instructions that I guess should work (they did for a few people in the comments). I guess unzipping with -LL is a good way to fix the lower case issue.

Maybe you can add this section (possibly making it a bit more specific and precise) as a new section for Steam Deck enthusiasts? Note that a lot of us are Linux noobs :D

https://www.reddit.com/r/SteamDeck/comments/ufwqsu/fallout_2_restoration_project_lowercase_game/is2hel0/

[https://github.com/BGforgeNet/Fallout2\_Restoration\_Project](https://github.com/BGforgeNet/Fallout2%5C_Restoration%5C_Project)
1. Download rpu_v*.zip from the latest release page. (Current one is [https://github.com/BGforgeNet/Fallout2\_Restoration\_Project/releases/tag/v26](https://github.com/BGforgeNet/Fallout2%5C_Restoration%5C_Project/releases/tag/v26) )
2. Download Fallout 2 on steam (Under "Compatibility" I have it checked to force a specific version which I set to Proton 6.3-8
3. Run Fallout 2 then close out of the game once you get to the title screen.
4. Open rpu_v* and dump the files into the Fallout 2 game folder, when prompted select "Replace All" (mine is /home/jak/HDD1/SteamLibrary/steamapps/common/Fallout 2) (Or right click Fallout 2 on steam, properties, local files, browse and that is the folder)
5. Back out once so you're in the ../steamapps/common folder and right click the Fallout 2 folder, select compress, and make it a .zip file.
6. Delete the Fallout 2 folder so that the only Fallout 2 in the folder is the .zip file.
7. Right click in the ../steamapps/common folder and open in terminal.
8. Type "unzip -LL Fallout\ 2.zip" (with no quotes)
9. When prompted to replace the fallout 2/f2_res_config.exe type no and press enter.
10. Now inside the newly unzipped fallout 2 folder right click and open in terminal, type "./rpu-install.sh" (without the quotes)
11. In ../common/fallout 2 right click on the ddraw.ini and open with a text editor.
Find the DamageFormula= line and change it to =1, =2, or =5 to apply the AP ammo fix depending on which version you want.
This isn't needed but the official mod page suggests it. I play with DamageFormula=1
12. On steam right click Fallout 2 and go to general and under launch options and paste WINEDLLOVERRIDES="ddraw.dll=n" %command%
13. Launch Fallout 2 and pray to God that everything works.
This was done on Manjaro. I haven't tested it on the steam deck but it should be similar enough because they're both arch based. Good luck my friend!

**Comment by SPavuna** [comment]
Yeah, but original game had uppercased files, right? The suggestion is to zip entire game folder and unpack it with -LL.

**Comment by burner1024** [comment]
Oh, I see. I guess it's one way to that.
I don't think this is a place for general OS education, though, so probably not going to include this longish guide.
I would accept a script to lowercase stuff, but it'd have to be crossplatform enough.
