### ISSUE TITLE
I can save or load a new game 

### ISSUE THREAD

**Issue by Ghetsumn** [BGforgeNet/Fallout2_Restoration_Project#302]
### What happened
After getting passed the instruction at 004a2b2f error I am now stuck with this new bug
### Screenshot
![Fallout 2 Screenshot 2024 07 04 - 19 12 35 84](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/174758457/00c58465-c030-4664-a812-c2888abc8b07)
![Fallout 2 Screenshot 2024 07 04 - 19 12 56 47](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/174758457/6deb5902-9c59-44f9-b6d4-6ebde4b2d04e)

**Comment by burner1024** [comment]
So where's the savegame?

**Comment by Ghetsumn** [comment]
Sorry for the wait I received this when using the save editor and here is one of the save files and i can't upload the savegame 
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/174758457/3bec5b5e-f976-4b07-843d-a23c6fa58912)
![image](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/174758457/b728f0f4-9653-49fe-ab2d-689f486ed1ba)

**Comment by Ghetsumn** [comment]
[GameRes_log.gz](https://github.com/user-attachments/files/16113673/GameRes_log.gz)
[SaveDat_log.gz](https://github.com/user-attachments/files/16113674/SaveDat_log.gz)
here are loggs from the save editor how do I enable the debug logger

**Comment by burner1024** [comment]
Zip the savegame directory and attach the archive.

**Comment by Ghetsumn** [comment]
[SLOT39.zip](https://github.com/user-attachments/files/16186155/SLOT39.zip)
here is the save file I took forever but here it is

**Comment by burner1024** [comment]
I can load your save just fine.
What you should next:
1. set up a separate fallout 2 instance (another directory)
2. install fresh RPU into that directory.
3. Try and load your savegame there.
4. If it works, then copy over your other mods and settings 1 by 1, see what causes the crash.

**Comment by Ghetsumn** [comment]
how do I run multiple instances?

**Comment by Ghetsumn** [comment]
I will try that and see what happens

**Comment by Ghetsumn** [comment]
nothing changed

**Comment by burner1024** [comment]
Did you try this exact savegame?
Then it's probably something about your machine.
Try gathering a debug package with [Zax](https://github.com/BGforgeNet/zax) and attach it here. (From the second, fresh RPU installation)

**Comment by Ghetsumn** [comment]
I deleted some file and it works now and the mods are intact

**Comment by burner1024** [comment]
OK, cool.
