### ISSUE TITLE
Local map Temple of trails

### ISSUE THREAD

**Issue by Slagar80** [BGforgeNet/Fallout2_Restoration_Project#303]
### What happened
When youre in the Temple of trials the pc can access the local map on the “pib boy” although he hasn’t one yet.
I know that’s already in vanilla so I don’t know if it needs to be fixed but already bothered me there since you logically can’t access other pib boy features 
### What you expected to happen
To not be able to access the local map in the temple if trials

**Comment by Lexx2k** [comment]
This is such a high level of nitpicking, nobody really cares about that.

**Comment by burner1024** [comment]
I don't think it's worth the trouble.
Although if you come up with a good solution and implementation, a pull request may be considered.

**Comment by Slagar80** [comment]
Yeah I totally get that, it’s really just nitpicking.
Btw. I choose for myself to play with the sfall setting to enable the pip boy at game start to head cannon that the chosen one has him already before the trial although the game pretty straightforward tells you that you’re not wearing one.
Makes sense for me since it’s a tribe of vault inhabitants descendants, you only get a vault suite cutscene after completing the trials, people in the village seem more interested in a canteen from vault 13 than you having a pip boy and the elder must obviously have one too to read the holodisc.
And also (I know this is way to meta) the complete interface like dialogue or character sheet or even the normal ui is build around using a pip boy.
But I absolutely understand your reasoning that no one probably will notice.
