### ISSUE TITLE
wipe_inventory deletes certain items intended to remain in stock

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/Fallout2_Restoration_Project#304]
### What happened
I tried `wipe_inventory=1` and it deleted the only instance of .223 Pistol available at New Reno arms dealer.

Some other observations:

1. The wipe-related code is in upu.h, the list of quest items to keep is hard-coded and doesn't have RP quest items.
2. It should be easier to extend quest items list. I guess you can define a macro for `move_critical_items` to "redirect" call to a different procedure with updated logic and different list, but maybe there's a better way.
3. `check_restock_item` should call a procedure. I think we're well beyond the point where we need to care about call performance... But this will make compiled code smaller and decompiles easier to work with.

### What you expected to happen
The pistol and other "unique" items like it must remain in stock regardless of `wipe_inventory` setting.

**Comment by phobos2077** [comment]
I have a set of work-arounds for the .223 Pistol specifically in EcCo that I can port over to RPU later.

**Comment by burner1024** [comment]
It's not a bug, as original has no wipe in the first place.
I don't care so much about items, either.
Probably can script one-off items with no restocking.

**Comment by burner1024** [comment]
RPU has wipe setting, which is not a bug.

**Comment by phobos2077** [comment]
> RPU has wipe setting, which is not a bug.

Are you trolling now? RPU has wipe setting, which is deletes items that aren't meant to be deleted. This is a bug.

**Comment by Wickez** [comment]
Two Russkies are now debating over an American franchise who's more "legit" in understanding it. xD

**Comment by burner1024** [comment]
I think what they actually were going for is make sure it's there the first time around.
Probably can add a small chance to restock, too.

**Comment by phobos2077** [comment]
> Two Russkies are now debating over an American franchise who's more "legit" in understanding it. xD

Feel free to add your non-Russkie expertise on this American franchise.
