### ISSUE TITLE
Question, not a bug: DAT file description

### ISSUE THREAD

**Issue by reseto** [BGforgeNet/Fallout2_Restoration_Project#307]
### What happened
I'm using https://github.com/efossvold/fallout2-save-editor as it's a nice visual piece of modern software. The downside is that it doesn't know about FRP save's new items. Is there a DAT description that could be used to extend this editor's capabilities?

### What you expected to happen
At least the editor could be "fixed" to modify the base stats without corrupting the entire save.
If possible, it would be nice to have the capability to change the number of items in the inventory.
And super advanced mode, ability to add all known items to the inventory.

### Screenshot
n/a

### Savegame
[SAVEGAME-1temple-2den.zip](https://github.com/user-attachments/files/16604624/SAVEGAME-1temple-2den.zip)

**Comment by burner1024** [comment]
Known item pids are [here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/headers/itempid.h).
It probably won't work anyway, as RPU uses sfall, loading dats from mods directory.
Items shoud be read from items.lst, not predefined.
