### ISSUE TITLE
Memory Could Not Be Written

### ISSUE THREAD

**Issue by cadencadet** [BGforgeNet/Fallout2_Restoration_Project#308]
In both a prior run in which I used saves during combat, and my new current one in which saving during combat is disabled, I have faced this same error when I attempt to fight the Dragon's goons in San Fran. Usually I can get through a couple or most of them but inevitably the game will stop responding randomly with this error. This is an issue I've also faced in a prior unmodded playthrough, however it would only occur if I tried to engage in combat in the Hubologist's headquarters, so methinks it may have something to do with engaging in combat in areas with lots of NPC's? The mods I have installed are SFALL, RPU, RPU TH, THAT, and FO2tweaks. I was hoping one of these would fix this crashing issue but idk. 

I expected the game not to crash every time I try to test my skills against the Dragon's guys.

![image](https://github.com/user-attachments/assets/4e640d9f-a4e4-4ea0-ba3a-28d05a15cad4)

[SLOT27.zip](https://github.com/user-attachments/files/16633414/SLOT27.zip)

**Comment by burner1024** [comment]
Can you reproduce it without talking heads mods?

**Comment by cadencadet** [comment]
> ented

Just tried doing the fight again and had no issues after removing 
talking_heads.dat
talking_heads_audio.dat
from the mods order text file. So maybe TH is the cause of this issue then?

**Comment by burner1024** [comment]
Likely.

**Comment by cadencadet** [comment]
Just had this same issue happen again with the boxing arena in New Reno. Beat a fighter and then right after fading to black to talk to Stuart, this memory error occurred again. 
Removing talking head fixed it, of course. I guess I'll post an issue under that mod then.

**Comment by burner1024** [comment]
If you manage to trace back to RPU after all, feel free to re-open.
