### ISSUE TITLE
Shi computer force field won't disable game breaking bug!

### ISSUE THREAD

**Issue by coldroll** [BGforgeNet/Fallout2_Restoration_Project#31]
So I'm near the end of Fallout 2 and I helped the shi against the hubolgists and they have excepted

d me and told me I can see the computer emperor and they give me the password to see the computer emperor. And they tell me the force field will be disabled but it doesn't seem to disable and now I can't refuel the tanker to get to the Poseidon oil rig. I've included my save file and a screenshot to show what I'm talking about. I'm using the last build of the restoration update patch before the latest one was released 3 days ago would updating the build solve this issue or not?

![shi computer force fieldglitchbmp](https://user-images.githubusercontent.com/43797773/72508645-490f0580-3803-11ea-8159-4f18ef1af215.jpg)

[Shi save file.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4070161/Shi.save.file.zip)

**Comment by burner1024** [comment]
Yes, [it will](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/29). You just need `mods/rpu.dat` from latest release.
