### ISSUE TITLE
Game crashes upon trying to enter New Reno

### ISSUE THREAD

**Issue by ewedusoft** [BGforgeNet/Fallout2_Restoration_Project#310]
### What happened
Moving into New Reno from the worldmap crashes to desktop immediately. I tried to start a new game and ran straight to New Reno, and the game still crashed. So: with or without the car, it doesn't matter, it'll CTD.
This happened on the latest version of the RPU at this point (v30, with sfall 4.4.4).

### What you expected to happen
Dudette, Cassidy and Sulik appear in New Reno.

### Screenshot
No error message was thrown up, so have this from the debug log file instead. Relevant bit in attached screenshot.
[debug.log](https://github.com/user-attachments/files/16980046/debug.log)
![image](https://github.com/user-attachments/assets/dcac7280-06da-4e69-9e14-855f381ccfb1)

### Savegame
[SLOT07.zip](https://github.com/user-attachments/files/16980032/SLOT07.zip)

**Comment by burner1024** [comment]
Can't reproduce.
Try collecting a debug package with [ZAX](https://github.com/BGforgeNet/zax), attach it here.

**Comment by ewedusoft** [comment]
Debug package: 
[zax_debug_2024-09-12_22-12-30.zip](https://github.com/user-attachments/files/16985543/zax_debug_2024-09-12_22-12-30.zip)

**Comment by burner1024** [comment]
Try without the extra mods - BozarSniper, CorpseDrop, RadscorpLimbs, SkipTempleTrial.

**Comment by ewedusoft** [comment]
That fixed it! But why... I recall seeing in an older version of either this or FO2Tweaks that those were recommended additional mods, but now I can't find them in the respective pages.

Either way, it works now, thank you!

**Comment by NovaRain** [comment]
The cause is "RadscorpLimbs" because it directly changes the limbs from the "misc" type to "weapon", and different proto types don't have the same filesize. Existing/pre-placed items on maps do not play nice with such changes.
