### ISSUE TITLE
Die from radiation

### ISSUE THREAD

**Issue by longtry** [BGforgeNet/Fallout2_Restoration_Project#311]

**Comment by NovaRain** [comment]
If the "radiated" in the character screen is highlighted in gray, that means you still have an impending radiation effect. When the radiation effect kicks in and one of your SPECIAL stats happens to be less than 1 (trait/drug effects included, in the character screen it only shows 1 as the minimum), the game will consider you dead.

The easiest solution is to use a save editor to temporarily raise all your SPECIAL stats to 10, wait/rest in game until radiation effects completely wear out, then revert your SPECIAL stats.

**Comment by longtry** [comment]
Wow, you're a sage; it was indeed gray. Do you consider the whole thing a bug or acceptable mechanism? Cause if it's the latter, editing SPECIAL could be seen as cheating. My MCs always has low EN & need Buffouts to do some types of physical activities, so this is always a threat if I'm to play a serious no-save game.

Do you happen to know the length of time between rad absorption and rad effect event? I'm thinking that if I check char scr often enough, I should be able to deal with rad before the curse comes. Or I could use yet another drug to raise my stats >1 as a last ditch effort.

**Comment by NovaRain** [comment]
> Do you happen to know the length of time between rad absorption and rad effect event?

Should be around 4-18 hours.
https://github.com/alexbatalov/fallout2-re/blob/main/src/game/critter.c#L495

**Comment by burner1024** [comment]
I think it's reasonable enough to be not considered a bug.
