### ISSUE TITLE
Russian voice acting does not work

### ISSUE THREAD

**Issue by Trapeciya** [BGforgeNet/Fallout2_Restoration_Project#312]
### What happened

Russian voice acting does not work.
I don't know how important this is, but I have a version of the game from Epic Games.

### What you expected to happen

Instead of English voice acting there should be Russian, since Russian translation was selected during installation.

### Screenshot
...
### Savegame
...

**Comment by NovaRain** [comment]
Check if `upu_russian_sound.dat` is in your "mods" folder, and `mods_order.txt` has a line with the filename.

**Comment by Trapeciya** [comment]
Yes, everything is there

![Desktop Screenshot 2024 09 24 - 15 14 23 99](https://github.com/user-attachments/assets/f8c86af8-bdc6-4fca-8146-cbfa5745f3a4)
![Desktop Screenshot 2024 09 24 - 15 14 05 30](https://github.com/user-attachments/assets/7a991fcc-44d7-4461-8e91-c555fc9fd80c)

**Comment by burner1024** [comment]
Try UPU (in another copy of the game).
