### ISSUE TITLE
No Dr. Jing in Steel palace

### ISSUE THREAD

**Issue by longtry** [BGforgeNet/Fallout2_Restoration_Project#313]
I played UPU and know that there's a dr Jing in a room south of the Shi base, who gives the hardening power armor quest. In RPU I never see this guy, despite playing a few times w/ different characters. He's not there, and not invisible I think, because the mouse doesn't reveal any possible interaction when I hover it over the place where he should be. Is this a bug or RPU has deleted this NPC?

**Comment by burner1024** [comment]
He should be there. Attach save.

**Comment by burner1024** [comment]
Check out [Inventory Filter](https://github.com/rotators/InventoryFilter).

**Comment by longtry** [comment]
Uh.. I already have Inv Filter mod; what I described is another thing altogether, focusing on party management.

**Comment by burner1024** [comment]
You will need a new mod for that, likely based on inventory filter.

**Comment by longtry** [comment]
I see. Could you advise where best to ask for a new mod?

**Comment by burner1024** [comment]
You will likely need to work on it yourself.
[NMA forums](https://www.nma-fallout.com/forums/fallout-general-modding.18/) may be of some help.

**Comment by longtry** [comment]
My appreciation. Now for something related to RPU, I believe. Have you thought about the possibility when, after MC successfully change their gender at EPA, they could marry another person in Modoc by having some new lines of dialogue about identity?

**Comment by burner1024** [comment]
Not really in RPU scope.
