### ISSUE TITLE
Crashing on attempt to enter Vault Village

### ISSUE THREAD

**Issue by ObfuscatedCoder** [BGforgeNet/Fallout2_Restoration_Project#314]
Every time I try to enter Vault Village (not Vault City, but the village whose rats the VC sgt wants me to eliminate), the game crashes (see screenshot). I'm using the Epic Games version as a base on an M3 Mac using Porting Kit to create a wrapper. https://github.com/BGforgeNet/Fallout2_Restoration_Project/pull/260#issue-2066357447 seems to mention the problem as an aside to the main issue of that thread; I believe the main issue of that thread was resolved, but not the aside, and I didn't see another mention of my problem. Anyway, I've attached a save file that should be located close to the village in question (saved after I tried to add fo2tweaks to see if I could bypass the issue; nope).

I've got zero modding experience and no clue how to fix this...any ideas? 

### Screenshot
<img width="1149" alt="Screenshot Vault Village" src="https://github.com/user-attachments/assets/ceaa0d8f-ff29-4155-8829-630dba3426e4">

### Savegame
[SLOT80.zip](https://github.com/user-attachments/files/17196088/SLOT80.zip)

**Comment by burner1024** [comment]
I can't reproduce.
Try collect a [ZAX](https://github.com/BGforgeNet/zax) debug package.

**Comment by ObfuscatedCoder** [comment]
Thanks for your attention to this! While waiting for PyPi to install Zax (I had difficulty getting the .exe to work with my wineskin; as I indicated, I don't really know what I'm doing), I finally saw crash.md and set up the logger. I've attached the log; it looks like it starts loading the map ("As you enter the small village, your nose is assaulted by the familiar stench of rodent....") before running into trouble after "gl_k_smoking: smoking enabled":

> Script Error: scripts\bientdr.int: op_obj_lock: obj is NULLScript Error: scripts\zimtldor.int: op_obj_unlock: obj is NULLScript Error: scripts\zimtldor.int: op_obj_unlock: obj is NULLScript Error: scripts\ziwoddor.int: op_obj_unlock: obj is NULLScript Error: scripts\ziwoddor.int: op_obj_unlock: obj is NULL
zicrtrnk: trunk: map_enter_p_proc

zicrtrnk:    Trunk_In_Party: start

zicrtrnk:    GVAR_CAR_PLACED_TILE == 0

zicrtrnk:   trying to hide trunk

zicrtrnk:    Trunk_In_Party: end
Script Error: scripts\bcdalia.int: op_elevation: obj is NULLScript Error: scripts\bcdalia.int: op_critter_add_trait: obj is NULLScript Error: scripts\bcdalia.int: op_critter_add_trait: obj is NULLScript Error: scripts\vcgenvil.int: op_tile_num: obj is NULLScript Error: scripts\vcgenvil.int: op_critter_add_trait: obj is NULLScript Error: scripts\bczeke.int: op_elevation: obj is NULLScript Error: scripts\bczeke.int: op_critter_add_trait: obj is NULLScript Error: scripts\bczeke.int: op_critter_add_trait: obj is NULLScript Error: scripts\vcgenvil.int: op_tile_num: obj is NULLScript Error: scripts\vcgenvil.int: op_critter_add_trait: obj is NULLScript Error: scripts\vcgenvil.int: op_tile_num: obj is NULLScript Error: scripts\vcgenvil.int: op_critter_add_trait: obj is NULLScript Error: scripts\vcconnar.int: op_critter_add_trait: obj is NULLScript Error: scripts\vcconnar.int: op_critter_attempt_placement: obj is NULL
Error during execution: 
Stack underflow short.
Current script: scripts\vcconnar.int, procedure map_enter_p_proc

[debug.log](https://github.com/user-attachments/files/17201875/debug.log)

**Comment by burner1024** [comment]
Did you get ZAX to work?

**Comment by ObfuscatedCoder** [comment]
Not really. Short version: I got Zax to load, but when I then used it to start the game it loaded the base version _without_ the Restoration Project mod, and I haven't been able to figure out why.

Long version: to play the version with the Restoration Project on my Mac, I downloaded F2 from Epic Games and followed the instructions on how to apply the mod. Initially I tried to play using the Fallout 2 Community Edition, but while that loaded the base game without issue, it ignored the mod. (That's probably irrelevant, but I mention it because Zax behaved similarly; see below.) I then used Porting Kit to generate a Wineskin wrapper "for the GOG version" but copied F2 (with mods applied) into the wrapper's drive_c; that basically worked. I also copied a save-game editor into the same drive_c, and when I set that same Wineskin app to open that .exe, it runs fine too. But that method doesn't seem to work with Zax: when I set the Wineskin app to open zax.exe and click "test run," it thinks for a bit, then I get a message saying that the program ran with no issue (even though the program didn't actually load for me). I did get Zax to seemingly run properly by opening it in Whisky, and when I selected the Fallout 2 folder in the aforementioned drive_c, it launched Fallout 2...but then, like the Fallout 2 Community Edition, the opening menu did not show the restoration project version number and it wouldn't load any of my saves (or indeed recognize the existence of any save past the 10th).

**Comment by burner1024** [comment]
You don't necessarily need to start the game from it, just collect the debug package.

**Comment by ObfuscatedCoder** [comment]
Ah, I think I understand Zax a little better now. Here (I hope) is a relevant debug package. Thanks for your patience on this! [zax_debug_2024-10-08_13-57-21.zip](https://github.com/user-attachments/files/17298054/zax_debug_2024-10-08_13-57-21.zip)

**Comment by burner1024** [comment]
Everything looks in order. Still can't reproduce, though.
[vcconnar.int.zip](https://github.com/user-attachments/files/17338326/vcconnar.int.zip)
Extract this into data/scripts and trigger the crash again. Let's see where it dies.

**Comment by ObfuscatedCoder** [comment]
Sure thing. As always, I appreciate the help!

[zax_debug_2024-10-11_03-12-02.zip](https://github.com/user-attachments/files/17339733/zax_debug_2024-10-11_03-12-02.zip)

**Comment by burner1024** [comment]
Just debug.log will suffice, the zax package is for the overall assesement.
How about this one
[vcconnar.int.zip](https://github.com/user-attachments/files/17340261/vcconnar.int.zip)

**Comment by ObfuscatedCoder** [comment]
Hey, it seems like that fixed it! The game loaded the village this time. It may be that some other crash will occur when I start completing the associated quests, but I wanted to thank you immediately.

I'm attaching the debug.log in case it'll provide any further useful details (like if you didn't expect it to fix the issue).

[debug.log](https://github.com/user-attachments/files/17340379/debug.log)
