### ISSUE TITLE
download problem :(

### ISSUE THREAD

**Issue by FallMaxModUser** [BGforgeNet/Fallout2_Restoration_Project#316]
I have a problem when trying to download the file because in the middle of the download it gives me "error requires authorization." Is there anything I can do?

**Comment by burner1024** [comment]
Try another browser?

**Comment by FallMaxModUser** [comment]
> Try another browser?

I tried it twice with two different browsers, I'll try another one and see how it goes.

**Comment by FallMaxModUser** [comment]
> Try another browser?

Ok, I tried it in Chrome, Opera and FireFox and nothing, I'm starting to believe that the problem has to do with my computer or some antivirus, although I searched on Google and the error is supposed to occur when the owner of the file does not give access to the download

**Comment by FallMaxModUser** [comment]
> Likely so.

By the way, I tried to download the file on my phone and it gave me the same error, I don't know how downloads work in git hub but at least this problem had never happened to me before. I also tried other browsers and at least this attempt went further than the previous ones, since I was close to downloading the file until access to it was denied

**Comment by burner1024** [comment]
Maybe the issue is with your internet provider?
No one have ever reported anything like this.

I can say, however, that next release will include torrent links.

**Comment by ThatGuyFromReZero** [comment]
> Maybe the issue is with your internet provider? No one has ever reported anything like this.
> 
> I can say, however, that the next release will include torrent links.

Hey man. It's me. ThatGuyFromReZero. Listen, I wanna ask you something and I can't cite it as an issue as it's more of an enhancement request rather than a Bug Report. Would you be willing to hear me out?

**Comment by burner1024** [comment]
You can open a new issue and we'll see.

**Comment by ThatGuyFromReZero** [comment]
> You can open a new issue and we'll see.

Gotcha
