### ISSUE TITLE
No V13 massacre?

### ISSUE THREAD

**Issue by longtry** [BGforgeNet/Fallout2_Restoration_Project#317]
### What happened
I fixed the computer & get 5000xp from Gruthar, but when I arrived months later, Horrigan still hadn't massacred the whole population there

### What you expected to happen
The massacre, so I can report to Tandi

### Screenshot
No need, I think

### Savegame
Uh.. where is the savegame folder? Can't find mine in Fo2\data\SAVEGAME

**Comment by burner1024** [comment]
> Uh.. where is the savegame folder? Can't find mine in Fo2\data\SAVEGAME

Must be there. Unless Windows put it into LocalData or whatever it's called.

**Comment by longtry** [comment]
No, but to achieve massacre w/o Horrigan, I then killed Gruthar (& his guard nearby), and the dialogue was opened in NCR.

In each SLOT0x folder inside SAVEGAME there are a whole lot of *.sav. Should I zip the whole folder, or you could point out which save file name corresponds to V13?

On another note, I'd like to take this chance to ask whether the perk Cult of Personality is working correctly in RPU, as opposed to vanilla's bug?

**Comment by burner1024** [comment]
Whole slot.
Cult should be working correctly.

**Comment by longtry** [comment]
Thx. I found out I accidentally overwrote the savegame w/ another character. Will play toward that point some time. Regarding Cult, do companions react to negative reps now? For example, Sulik is known to auto-leave when karma -101, Cassidy wouldn't join Slaver, or some others wouldn't go with Berserker. Are they all OK now w/ Cult?

**Comment by burner1024** [comment]
Slaver is a separate thing.
Other titles should work fine, if not, you can report that.

**Comment by burner1024** [comment]
No, not really, unless it's to bringing them in line with UPU.
