### ISSUE TITLE
IN gain doesn't feature into skill points?

### ISSUE THREAD

**Issue by longtry** [BGforgeNet/Fallout2_Restoration_Project#318]
### What happened
My IN is 9, and I chose option to talk at Kitty's, so it's now 10, right before I complete some quest to lv up. However, I still get only 18 points, despite character screen clearly shows IN 10.

### What you expected to happen
20 skills points, properly calculated based on current IN. Related question: if I refrain from opening char scr at SF for a few levels, and operate to increase IN. Would the (bonus) skill point increase appear when I open SPECIAL again?

### Screenshot
Not really applicable imo because it's a before-and-after process.

### Savegame
Can only provide the "after" save, if needed.

**Comment by burner1024** [comment]
You gain skill points upon leveling up. It's not retroactive.
