### ISSUE TITLE
Truncated ddraw.ini

### ISSUE THREAD

**Issue by darlinggj** [BGforgeNet/Fallout2_Restoration_Project#32]
Is ddraw.ini in RPU v10 supposed to be so much shorter and uncommented than in RPU v9 etc? Many options now seem to be missing; no mention of this in the v10 changelog; I also get the "You have overwitten the RP ddraw.ini etc" message on loading an old save or starting a new game (after having further installed EcCo 0.6.2 + FO2Tweaks 11.2 + sfall 4.2.2 except for its own ddraw.ini).

On Windows 10; did run batch file.

This is all of it in the v10 download:

[Main]
AllowSoundForFloats = 1
WorldMapSlots = 21

[Misc]
UseFileSystemOverride = 1
FemaleDialogMsgs = 2
NPCAutoLevel = 1
OverrideArtCacheSize = 1
ElevatorsFile = Elevators.ini
DisplayKarmaChanges = 1
PlayIdleAnimOnReload = 1
EnableHeroAppearanceMod = 1
AIDrugUsePerfFix = 1
ExtraSaveSlots = 1
KarmaFRMs = 128,146,129,125,152,127,147,134,176
KarmaPoints = -1000,-750,-500,-249,250,500,750,1000
SpeedInventoryPCRotation = 220
BoxBarColours = 11111
BoostScriptDialogLimit = 1
DontTurnOffSneakIfYouRun = 1
NumbersInDialogue = 1
WorldMapFontPatch = 1
PartyMemberExtraInfo = 1
VersionString = FALLOUT II 1.02d RP 2.3.3u10

**Comment by burner1024** [comment]
No, absolutely not. Although that shouldn't be an issue per se. Have you upgraded from RP 2.3.3?

**Comment by darlinggj** [comment]
No, skipped RP 2.3.3: Gog's FO2, then RPU v10, EcCo v0.6.2, FO2Tweaks v11.2, sfall v4.2.2 except for ddraw.ini.

Just now repeated with the new RPU v11, and ended up with a more sensible-looking ddraw.ini . But new game _still_ shows red message "You have overwritten the ddraw.ini file etc"; rock at Temple of Trials shows "2.3.3u11".

Also, I just noticed that sfall-mods.ini is duplicated in Fallout 2/ and Fallout 2/mods/. Could this be related? Which is correct?

**Comment by burner1024** [comment]
I cannot reproduce. Are you installing from scratch or upgrading? Linux of Windows?

**Comment by darlinggj** [comment]
From scratch, Windows 10. The vanilla install from Gog starts normally. After applying RPU v11 and running rpu-install.bat _only_ (not EcCo, FOTweaks or the latest sfall), not changing any of the .ini, and starting a new game, the red message shows immediately.

**Comment by burner1024** [comment]
How about this one?
[ddraw.ini.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4075586/ddraw.ini.zip)

**Comment by darlinggj** [comment]
Started new game, no more red warning. Cool. Will test more later.
