### ISSUE TITLE
(Not a Bug Report but an Enhancement Request) Romancible Kitsune?

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [BGforgeNet/Fallout2_Restoration_Project#320]
Listen, I like Kitsune. She's a great character and a wonderful party companion but it bugs me that she isn't romancible at all. The Companions Expansion Mods/CEM added new and vanilla characters to recruit and Angela Bishop is romancible. Basically, I was wondering if there is a mod or way to update the game's code so Kitsune can be romanced. But only when playing as a male. Similar to how Angela can only be romanced by a male.

Would the RPU devs be willing to do that or is it too much trouble to ask? I want to apologize to the devs for bothering them when installing the Talking Heads Addon Mod and THAT Mod started causing lots of issues on my end. I recently installed the updated RPU mod, THA and THAT mods, and I haven't had a single crash, freeze, hard-freeze-looping, CTD, or any other issues that previously plagued me. Thank you for all of your hard work and I hope you take my request into consideration if its possible.

Looking forward to hearing from you,
ThatGuyFromReZero

**Comment by burner1024** [comment]
It's a decent idea. However, I'm not interested in working on it. Maybe you could contact the authors of the CEM mod.
Or, write it yourself. It's reasonably easy to do.

**Comment by ThatGuyFromReZero** [comment]
> It's a decent idea. However, I'm not interested in working on it. Maybe you could contact the authors of the CEM mod. Or, write it yourself. It's reasonably easy to do.

Thanks. I'll do that
