### ISSUE TITLE
Slot jinxing not working

### ISSUE THREAD

**Issue by longtry** [BGforgeNet/Fallout2_Restoration_Project#321]
### What happened
I got the toaster to teach me jinxing technique, but every time I approach a machine in Reno, Redding, & everywhere, it just says something like "you look at the shining metal contraption", no playing options at all.

### What you expected to happen
I was able to jinx in all previous games; this run is the odd one out.

### Screenshot
Got the perk alright, but no use on site https://imgur.com/a/DC9FzMc

### Savegame
Can provide if needed.

**Comment by burner1024** [comment]
Jinxed perk has nothing to do with the ability to jinx slot machines. Just similar names.
Yes, attach the save.

**Comment by longtry** [comment]
I know, just that I happened to capture a scrshot for pariah dog. You can see that right below jinxed, slot jinxer is also listed in the perks area.

[slot 7 -11.zip](https://github.com/user-attachments/files/17529273/slot.7.-11.zip)
Looks like github has a size limit, so I can't upload all the SAVEGAME folder here. I guess the save in question lies between slots 7 & 11, so here it is. If you load one named "failed" in game, that's the latest with jinx bug.

**Comment by NovaRain** [comment]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/headers/command.h#L295
You must have Gambling skill >= 25% to play the slot machine, and you only have 20%.

**Comment by longtry** [comment]
Ah I see, the novelty of hard difficulty. Thx!

**Comment by longtry** [comment]
A little question. According to the code, is it possible to have 3 addictions at a time? I got mentats & buffout with just a few pops, but then I spent the whole psycho stocks (10-20) without being able to get 3rd addiction.

**Comment by burner1024** [comment]
I think there's no limit on addictions. And Jet gets you addicted on first use, doesn't it?
