### ISSUE TITLE
Enclave Ending Slide Appears AFTER Vagrants Ending Slide

### ISSUE THREAD

**Issue by apometta** [BGforgeNet/Fallout2_Restoration_Project#322]
### What happened

When looking at the ending slides, the vagrants ending slide appears 2nd last, with the last being the President Richardson slide.

### What you expected to happen

I expected the vagrants slide to be last.  This is very important - it affects the mood and tone of the ending right before the credits hit.  That ending slide was clearly written to go last.  I think, if this is working as intended, then at least an option should exist to disable the extra ending slides in one of the .ini files, but I couldn't find them if they do exist.

### Screenshot

Unnecessary.

### Savegame

[SLOT90.zip](https://github.com/user-attachments/files/17711059/SLOT90.zip)

There are >8 minutes left on the bomb timer, and Frank Horrigan is already dead, so you can just walk out and see the endings.

**Comment by apometta** [comment]
As a follow up:

 1. I was also using the FO2tweaks and Inventory Filter mods, but I assumed this to be from the added cut content.
 2. I hope the tone did not come off as rude, I greatly enjoyed playing with the mod.
 3. If the ordering is based on the wiki entries, then the Hubologist endings may also be affected.  It may be a subjective decision to decide where the ending slide belongs, since the others follow a set order, but I think any decision the mod authors decide is fine as long as it is known.  I could not find anything on the issues page.

**Comment by burner1024** [comment]
The order is here https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/data/endgame.txt
Same in UPU. I don't think it's ever been changed, was it?
Not sure which extra slides do you mean, too.

**Comment by apometta** [comment]
I was referring to the "President Richardson being forgotten" slides.  Not sure what the ordering was before - the last time I played was with Killap's original restoration patch, and I don't think that version added them.  But it seems someone committed a change to put the vagrants last (thank you!).

**Comment by apometta** [comment]
I don't know when the next release is, but making a data/data directory and putting that endings.txt in there fixed the issue, so this should be good.  Thanks!
