### ISSUE TITLE
Warning message "You have overwritten the rp ddraw.ini file! Revert back immediatly before it's too late" on Linux

### ISSUE THREAD

**Issue by saschati** [BGforgeNet/Fallout2_Restoration_Project#323]
Thank you for your work!

### What happened
I installed this update by rolling it to the fallout version in Steam, then I installed it as instructed except for the "Special Note" because it didn't work for me... but I found an instruction that made this update work on my system.

I used the installation steps from this thread ( https://steamcommunity.com/app/38410/discussions/0/4418676821640990568/ ) for the steam desk and after that the game started for me but I get **"You have overwritten the rp ddraw.ini file! Revert back immediatly before it's too late"**

I looked at the closed issues in this repository, but I'm not sure if they apply to my situation, I just performed the actions that were described in the topic, how can I find the logs of what exactly went wrong?

Thanks in advance, I hope there is some simple way to solve this problem(

My ddraw.ini file: [ddraw.zip](https://github.com/user-attachments/files/17757602/ddraw.zip)

### What you expected to happen
-

### Screenshot
![image](https://github.com/user-attachments/assets/22adae03-8965-47a3-876b-53f723bbf985)

### Savegame
-

**Comment by burner1024** [comment]
Your message is from old RP, not new RPU.
Either you installed both, or had leftovers from a previous attempt, or are launching the wrong game altogether.
I would wipe everything clean and install anew, double checking that it's actually the correct game.

**Comment by saschati** [comment]
Yes, you were right, Steam somehow cached the files I changed in the cloud and downloads them from them, I disabled synchronization with the cloud and reinstalled the game and after that the mod stopped issuing warnings.

Thank you again! Now I can enjoy your mod!
