### ISSUE TITLE
V10 Red 888 in San Fran has no items in stock

### ISSUE THREAD

**Issue by ericqzou** [BGforgeNet/Fallout2_Restoration_Project#33]
Dear Burner

I just tried V10 and when I reach San Fran I find Red 888 has nothing except fixed amount of money in stock. And it keeps in this way no matter how many days pass by. The Flying Dragon 8 and Jenna (merchant on the ship) seems to be fine refreshing their in stock items normally.

Eric
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4075602/SLOT01.zip)

**Comment by burner1024** [comment]
Did you upgrade or is it a fresh install, and you got to San Fran so quickly?

**Comment by ericqzou** [comment]
I copy contents from V10 in to FO2 (has V9) folder, run the .bat file, (and copy rewrite some ini files as I have pre-saved them)

And then I restarted a new game with a new char.

**Comment by ericqzou** [comment]
Actually when I saw the changelog yesterday, these two points really makes me wondering:

> Badger will stock Bozar and G11E.
> Badger will keep re-stocking after 7 years.

Is there any chance you come to mix between Badger and Red 888?

**Comment by burner1024** [comment]
I don't think so. Try this into `data/scripts` [figuntbl.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4075831/figuntbl.int.zip).

**Comment by ericqzou** [comment]
Red 888 restocks now after the int file.

Btw I saw you have compiled V11? I believe RPU can use old savings right? like if I just put V11 in to the folder but still load the game from saves saved during V10?

**Comment by burner1024** [comment]
In general, yes, but v11 only contains internal fixes/changes, and it looks like I'm going to have to put a v12 up soon, as some issues were identified.

**Comment by ericqzou** [comment]
Ok. Thank you for the quick fix, however.

**Comment by ericqzou** [comment]
Buerner, an update

So after the fix Red 888 restocks its items as usual, but I noticed that whatever I sold to him, they remains there with the exact amount I sold him. Now I have been selling stuff to him twice and they never got vanished when he refreshes his stock.

**Comment by burner1024** [comment]
I think that's how it's supposed to work?

**Comment by ericqzou** [comment]
Oh you mean if I want the normal behavior I will need to restart a new game after the quick fix?

I don't think it is normal that everything the dude sold to merchant remains right there with the exact amount in stock even after (several) refreshes. For example right now Red 888 has permanent 5 gold nuggets (among  all others like lockpicks, jackets) in the right table (the weapon and ammo table), which clearly shouldn't there be after refreshing the stock / restocking.

I have also never had this issue before. Only this time after the fix to Red 888. It is also only the Red 888 that keeps my sold items. Other merchants refresh their stock normally.

I took a quick look into the too many items bug, but I don't feel certain that it is related to the issue here?

**Comment by burner1024** [comment]
I think that's how it worked originally. Wiping inventory on restocking was [added by killap](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/ddad1a7bfd68152bf4cb10d8c60689cb657f577b/docs/up-changelog.txt#L843) to combat "too many items". Now that bug is fixed in sfall and this bandaid solution is no longer necessary.

It's probably been around so long that people don't even remember how it was anymore.

**Comment by ericqzou** [comment]
hahahahahaha ok. Thank you very much for explaining me and your patience

**Comment by Owyn** [comment]
> I don't think so. Try this into `data/scripts` [figuntbl.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4075831/figuntbl.int.zip).

thank you for the script,

I have noticed the same "problem" when playing,
there should really be at least an option to control this

**Comment by burner1024** [comment]
Which problem? Red888 never restocking?

**Comment by Owyn** [comment]
> Which problem? Red888 never restocking?

the problem of merchant stock being cluttered with items sold by the player

**Comment by Owyn** [comment]
Wait, I've been fooled, forum post says that the script actually doesn't help :-( any other solution?
![image](https://user-images.githubusercontent.com/1309656/216327326-1e105ecb-8a8b-49de-817a-cd4c75845a45.png)

**Comment by burner1024** [comment]
No, the attached script is a hotfix for the first issue.
