### ISSUE TITLE
"YOU HAVE OVERWRITTEN THE RP DDRAW.INI FILE" 

### ISSUE THREAD

**Issue by deadcombo** [BGforgeNet/Fallout2_Restoration_Project#34]
Hello, and thank you for your effort in maintaining Fallout 2!

I installed this yesterday, the latest v11 release, according to the instructions in the readme. I'm using the GOG version of Fallout 2, installed outside of the Program Files directory. I did perform a clean installation (more than one, actually).

I get the message as soon as I load or start a new game. It doesn't make a difference if I load the game I had going on with RP 2.3.3 and sfall 4.2.2, or if I start a fresh game.

I also tried with the v10 release, so it is likely to be an oversight on my end, but I'd still quite appreciate some help.

Thanks.
deadcombo

**Comment by burner1024** [comment]
Hi. No, it's an oversight on my part, sorry. I already released v12 to fix this. `WorldMapSlots` was put into a wrong section in `ddraw.ini`. You can set `WorldMapSlots=21` in `[Misc]` section manually to get rid of this. (But v12 also includes another fix for a merchant for San Fran, so you'll probably want to get it).
Ref #32.
