### ISSUE TITLE
font0.aaf

### ISSUE THREAD

**Issue by WannaCyp0r** [BGforgeNet/Fallout2_Restoration_Project#35]
Note: this file does not exist in upu.dat, so I report it here.

Seems font0.aaf included in rpu.dat cause copyright&version at main menu looks terrible, since use font0.aaf from original game(master.dat) fix the issue.

---font0.aaf from rpu
![font0 aaf from rpu](https://user-images.githubusercontent.com/48723581/75110620-4f4a9a00-566b-11ea-913a-39b3d642b204.png)

---font0.aaf from original game
![font0 aaf from original game](https://user-images.githubusercontent.com/48723581/75110618-4c4fa980-566b-11ea-964f-21106f262a17.png)

**Comment by burner1024** [comment]
You're right. Leftovers from original packaging still haunt. Will fix.
