### ISSUE TITLE
Dividing ammo issue

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#37]
In my game using the latest official RP mod I can't split up ammo for the sake of my team mates. I can share a save game if anyone wants.

**Comment by burner1024** [comment]
[Please do](https://github.com/BGforgeNet/Fallout2_Restoration_Project#reporting-issues).
What do you do, what do you expect to happen, and what actually happens?

**Comment by Njawl** [comment]
When I try to give some ammo by bartering I can only give the whole stack. When I try to divide I get the error sound when I press done. I also notices that most of my ammo can't be split. Limited to the stack size? 
[SLOT06.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4370341/SLOT06.zip)

Perhaps I should open a new topic for this. Vault City patrols don't seem to attack enemies in a random encounter if the patrols are bringing dogs with them.

**Comment by burner1024** [comment]
Errr... it was always limited by stack size. Do you want to give ammo 1 by 1? I don't think it ever worked that way in F2. If you have other information, please share.

**Comment by Njawl** [comment]
I see. It's a bit inconvinient when you don't have too much. I'll try to find out what amount I can give away. I imagine it works if you split a stack of 100 or something like that.

**Comment by burner1024** [comment]
It should.
