### ISSUE TITLE
Boxing suggestions

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#38]
I've been having fun in the ring but I have also had some troubles with it. There doesn't seem to be a way to tap out. I was thinking if perhaps there was someone you could talk to such as the announcer or a referee. There's also the possibility of simply pressing the end combat button. I understand that what I'm asking is more than a bug fix and might be hard to implement and none of this may be implemented due to limitations to the combat system. There's one thing that might work nonetheless. Having an object like a bell you can use or hit. If hit it would work similarly to a knockout and you always crit it for that effect. Take it as post-apocalypse understanding of "being saved by the bell".

There is a sense of humour in that you die in the ring nonetheless.

**Comment by burner1024** [comment]
Sorry, there's no indication it was ever intended to work this way, and as such it's out of RP's scope.
It shouldn't be to hard to implement this as a separate mod, though.
