### ISSUE TITLE
Doctors offering to heal companions seems random

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#39]
Would it fall within the scope of the RP to have this option among all doctor? I don't see a reason why you can't ask any doctor to patch up your crew.

**Comment by burner1024** [comment]
Please be more specific. I'm not sure what exactly you're talking about.

**Comment by Njawl** [comment]
Well, you can heal yourself and your companians at some doctors, while others only yourself. You see this through talking to them

**Comment by burner1024** [comment]
Which doctors? Can you provide saves?

**Comment by Njawl** [comment]
Most doctor's don't give you that option. The doc in San Francisco is one example.

**Comment by burner1024** [comment]
I think it could be RP material, but I'll need the full list of doctors with names and their behaviour and corresponding saves for all of them to make a decision and _maybe_ implement it.

**Comment by burner1024** [comment]
Not enough info.

**Comment by Njawl** [comment]
It seems only the doc in Redding and the outskirts of Vault City offers to heal your followers

**Comment by giathai** [comment]
No, Broken Hills' doctor also offer to heal your companions also.
