### ISSUE TITLE
The Dragon's men skill test crash

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#40]
The game likes to crash when you fight The Dragon's men in the ring in San Francisco. Here's the error message:
![Fallout 2](https://user-images.githubusercontent.com/62523089/77854879-2cbd1b00-71ed-11ea-8714-d8702e688dce.png)

**Comment by burner1024** [comment]
Please follow the [instruction](https://github.com/BGforgeNet/Fallout2_Restoration_Project#reporting-issues).

**Comment by Njawl** [comment]
I'm trying to enable debug but the debug commands are not in ddraw.ini. I also couldn't find those for for sound in fallout2.cfg so I added them manually. I assume something isn't right

**Comment by burner1024** [comment]
Have you got debug.log? That's what's important.

**Comment by burner1024** [comment]
Not enough info.
