### ISSUE TITLE
Sheng and Wong xp reward

### ISSUE THREAD

**Issue by giathai** [BGforgeNet/Fallout2_Restoration_Project#41]
SF's Abandonded House

Dr Sheng have you deliver the sentient-infused seed sample to Dr Wong.
Now, if you dont warn Dr Wong about that seed (having asked the question --Why change of heart) you have a measly 200xp and one superstim (-5 karma is neither here or there, one bandit). 
And if you warn him, you have 200xp and nothing (10 karma is neither here or there, two bandits). 
What? Is that a subtle-as-a-hammer suggestion to mess up Shi research?

I dont mind the none too subtle suggestion, but I do mind the beggar's charity of 200xp. Chosen One do a lot of work, and some good will, and he get a 200xp?

Please set them all to 2000xp at least. A player who arrive at SF, explore the central area full of monsters, explore the EPA to get the seed... all of that require a 2k xp at least~

**Comment by burner1024** [comment]
I share your sentiment, but I don't see any indication that it's not what killap intended. And I try to limit quest changes to veritable bugs, to avoid scope creep.
