### ISSUE TITLE
Vault Village placement in the main story flow

### ISSUE THREAD

**Issue by giathai** [BGforgeNet/Fallout2_Restoration_Project#42]
Recommend a Quest editting: Vault Village.

Currently Vault village seems to be accessible only AFTER you return from NCR (recon the route from VC to NCR).

It's most illogical, since VV is between VC and GECKO. And VV push the active introduction of Brain, the Mole rat. Which there is nothing to link it with the NCR trip.

Moreover, its xp is a bit out of sync with a post-NCR character. Too little, too late. And 4 Assault Rifle + 1 shotgun would be easy to acquire due to hoarding from that long trip. Let alone its major character, JOE, at that time would be, almost always, out on the tomblike field patch instead of inside Cassidy bar (since we most likely acquire that char and close the bar already). Also, its location make it a bit too silly. VC-VV-GECKO

If it's accessible from start, it would be more useful and logical.

EVERYTHING would be solved by push it earlier.

**Comment by burner1024** [comment]
Basically, same as #41.
