### ISSUE TITLE
Добавить set_self к use_obj_on_obj функциям.

### ISSUE THREAD

**Issue by FakelsHub** [BGforgeNet/Fallout2_Restoration_Project#44]
В диалогах где без выхода из диалога используется конструкция `use_obj_on_obj(obj, dude_obj)` нужно добавить пред ними два `set_self(dude_obj)`
Ванильная функция не предназначена для такого использования во время диалога, т.к. после выхода из диалога нпс пойдет к гг применять предмет(ы), но гг может отойти с гекса и функция не использует предмет.
В общем по ситуации смотри, я чекнул вот список.
```
ecravpty.ssl
nhmyron.ssl
dcrebecc.ssl
dcfranki.ssl
abhank.ssl
```

**Comment by burner1024** [comment]
Эх, не люблю я файлообменники. Ну [вот](http://wdfiles.ru/j11e).
Не знаю, чего у тебя не качается, у меня клон за пару минут проходит.

**Comment by FakelsHub** [comment]
А сколько размер у репы?, вчера пробывал, качает медленно да еще и размер не показывает.
сегодня тоже час прошел 150 мб скачало.

**Comment by burner1024** [comment]
На диске порядка полутора Гб (но качает по идее сжатое, трафик должен быть меньше)

**Comment by FakelsHub** [comment]
Я изменил issue.

**Comment by burner1024** [comment]
> Ванильная функция не предназначена для такого использования во время диалога, т.к. после выхода из диалога нпс пойдет к гг применять предмет(ы), но гг может отойти с гекса и функция не использует предмет.

Погляжу.
> а что обязательно после использовать set_self(0) я что-то про такое не слышал, или это ты так для безопасности добавил?

[Документация](https://sfall.bgforge.net/objects-and-scripts/#set_self) так говорит:
> Calling self_obj(0) will also revert self_obj to original value. It is recommended to call this after each use of set_self in normal scripts in order to avoid unforeseen side effects.
