### ISSUE TITLE
Skeeter skip out of requiring 3step plasma transformer?

### ISSUE THREAD

**Issue by giathai** [BGforgeNet/Fallout2_Restoration_Project#45]
Skeeter just plumb forget to ask me for a 3stepthingy. Possibly a misstep somewhere.

Problem is, I can not get the thing from Jimmy like in the old day (because you guys seem to set requirement in his dialog), so we can not get this quest self activated then self fulfilled.

Can you check Skeeter dialog line to set the requirement again? I think it is the extra, additional, requirement that was added later that cause this quest to not activating.

We just need Skeeter to ask for help from PC as long as this quest wasnt completed.

**Comment by burner1024** [comment]
I need a save, a step by step guide to reproduce the issue, and to know what you do expect to happen and what actualy happens.

**Comment by giathai** [comment]
Okay, this will take a long time because I pass the beginning of Gecko waaaay too long. A few weeks more.

**Comment by burner1024** [comment]
OK, feel free to reopen with more details.
