### ISSUE TITLE
Brother Samuel Disappearing Line

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#47]
The drunken munk in the Abbey in charge of the graveyard have a line you can't ask if you don't mention it right away. You need to have talked with his friend in New Reno first. The line is about brother Tully

[SLOT24.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4517193/SLOT24.zip)

**Comment by burner1024** [comment]
This is what, RP 2.3.3?

**Comment by Njawl** [comment]
Yeah

**Comment by burner1024** [comment]
Save crashes on load, must be not vanilla RP.
Also, it's in Modoc, not Abbey.

**Comment by Njawl** [comment]
![bilde](https://user-images.githubusercontent.com/62523089/80390364-9db72780-88ac-11ea-866d-09ca371640b7.png)
Only thing I can think of is that I forgot I had left debug on in fallout2.cfg including the sound one before remembering to switch it off.
The Modoc save was the closest to that point and it had the benefit of visiting the Abbey for the first time

**Comment by burner1024** [comment]
did you update sfall, by chance?

**Comment by Njawl** [comment]
I didn't

**Comment by burner1024** [comment]
Can't load, can't reproduce.

**Comment by Njawl** [comment]
[SLOT65.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4551981/SLOT65.zip)
Try this one. I saved it right next to Brother Samuel as well

**Comment by burner1024** [comment]
It crashes too:
```
Error: Can't fopen proto!

Error: Can't fopen proto!

Error: Can't fopen proto!

Error: Can't fopen proto!

Error: Can't fopen proto!
Error reading objects while loading map.
```
You sure that you don't have any other mods or customizations, used any editors?

**Comment by Njawl** [comment]
Nothing at all. I chose the guy with long hair but that came with the game/RP.

**Comment by Njawl** [comment]
Only thing I can think of now is to post pictures. It just shows however that a conversation option disappears when you go back to the initial conversation options after talking about something else.

**Comment by burner1024** [comment]
let's try that

**Comment by Njawl** [comment]
Good news. While the option does disappear like I said, if you exit the conversation and talk with him again the option is back again. In a sense this is a light bug.
![bilde](https://user-images.githubusercontent.com/62523089/80616285-059e7700-8a41-11ea-8e30-657f8c60782f.png)
![bilde](https://user-images.githubusercontent.com/62523089/80616312-0e8f4880-8a41-11ea-9ad1-e6144d19cfe3.png)
![bilde](https://user-images.githubusercontent.com/62523089/80616374-2070eb80-8a41-11ea-8a5e-de84e1b4e2b9.png)

**Comment by burner1024** [comment]
It's all good then.
