### ISSUE TITLE
Loss of Karma Selling Myron to Slavery

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#50]
I don't know. It seems like the definition of karma to me.

**Comment by burner1024** [comment]
Sorry, I don't understand what do you mean. The template is there for a reason.

**Comment by Njawl** [comment]
Sure, but I think Myron should be an exemption. He don't care about their lives on his hands so it's fitting to hand him over to slavers for a taste of his own medicine.
I've tried to bring him to justice elsewhere but the option doesn't appear among law enforcers.

**Comment by burner1024** [comment]
There's no evidence it's a bug.
And two wrongs don't make it right.

**Comment by Njawl** [comment]
Never said it was a bug. It's the best option besides killing him. The game doesn't give much room to make it right it seems

**Comment by Njawl** [comment]
I would like to add you get positive karma from killing him. It's somewhat inconsistend depending on how you look at it.

**Comment by burner1024** [comment]
> Never said it was a bug.

Only bugs and restorations belong in RP repo.
