### ISSUE TITLE
Should Charisma Module Be Endurance?

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#51]
Playing the game I was a bit puzzled why there wasn't any endurance modules. This was made clear since it was not on the list of options when you ask the AI down at the Brotherhood of Steel.
Should the charisma module have been an endurance module? Is it possible this was a mistake during development? The idea of having your charisma improved by a machine, while it may not be impossible it still boggles the mind on how that would work. Not only that having it improved may change your personality so the whole thing is questionable.
Not only that you would think the BoS would want to make better soldiers so stamina should be a higher priority than charisma.

Another bit I propose is to add another module instead of replacing the charisma module. Being that RP fills in missing content this seems to fit. There's no module to be found in the EPA building either and the modules tend to appear in pre-war installations.

**Comment by burner1024** [comment]
No evidence that it's either a bug or in scope of "restoration".
