### ISSUE TITLE
Followers Unable to Target More Than One Enemy

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#52]
It may not be a bug but seeing your followers have more action points to spend after killing an enemy leaves you wanting for more. Any thoughts on making this a possibility?

**Comment by burner1024** [comment]
There's is a template for issues, please follow the template.
In any case, this is in no way a restoration, and as such doesn't belong in RP repo.

**Comment by Njawl** [comment]
How do you explain the party orders addon then?

**Comment by burner1024** [comment]
> How do you explain the party orders addon then?

It's been added by killap.

> Also there's only a template for bugs.

Yes, because RP is pretty much complete.

**Comment by Njawl** [comment]
Alright but you're making unofficial releases and there's little harm in making improvements not straying far from the spirit of his work. You have already been open to consider things that aren't bugs that I have suggested. Have you considered making separate patches, one including changes on top of bug fixes?

Say, how do one know what's in line with restoration? Did the devs reveal what was not included or is it visible by looking through the game files and reading between the lines?

**Comment by burner1024** [comment]
> Have you considered making separate patches, one including changes on top of bug fixes?

No.

> Say, how do one know what's in line with restoration? Did the devs reveal what was not included or is it visible by looking through the game files and reading between the lines?

Probably, but this question is not about the issue at hand specifically, and doesn't belong here too.
