### ISSUE TITLE
Spanish translation error

### ISSUE THREAD

**Issue by GDRFunk** [BGforgeNet/Fallout2_Restoration_Project#53]
Using the latest release of RPU (v12) and his spanish localization, there's a several error, the game is not displaying correctly the spanish accent (tildes). In this image we can appreciate the error instead of "buen día" it says "buen d(weird char)a".
![image](https://user-images.githubusercontent.com/64866788/81110366-746c4c00-8ee9-11ea-8a26-ee897203d4f2.png)

**Comment by burner1024** [comment]
Any other mods installed?
Please attach your `fallout2.cfg` and a screenshot of `mods` directory.

**Comment by GDRFunk** [comment]
> Any other mods installed?
> Please attach your `fallout2.cfg` and a screenshot of `mods` directory listing.

No, only this. 

[fallout2.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4583483/fallout2.zip)
![image](https://user-images.githubusercontent.com/64866788/81113288-fa8a9180-8eed-11ea-9197-dad97483e99f.png)

**Comment by burner1024** [comment]
[font1.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4583577/font1.zip)
Try unzipping this into data directory.

**Comment by GDRFunk** [comment]
![image](https://user-images.githubusercontent.com/64866788/81116415-4ee44000-8ef3-11ea-9f71-7a6fc58d0806.png)
Worked. Thanks, if there's future errors i will report

**Comment by burner1024** [comment]
fixed in #35, actually
