### ISSUE TITLE
rpu_v13.exe fails to install

### ISSUE THREAD

**Issue by YaarPodshipnik** [BGforgeNet/Fallout2_Restoration_Project#54]
**Describe the bug**
The rpu_v13.exe installer fails to install with message:
> The drive or UNC share you selected does not exist or is not accessible. Please select another
The installer never asks about install location.

**To Reproduce**
1. Run the installer
2. Press "Next" button until you get to last screen
3. Press "Install", get the error

**Expected behavior**
- installer asks for destination location
- installer completes successfully

**Actual behavior**
- installer did not ask for destination location
- installer failed with the message provided above.

**Savegame**
N/A

**Screenshots**
Installer steps:
![image](https://user-images.githubusercontent.com/3943250/81703835-ff5ac280-9464-11ea-9d3c-35be3baf0683.png)
![image](https://user-images.githubusercontent.com/3943250/81703848-041f7680-9465-11ea-80cc-fa1d58b360c5.png)
![image](https://user-images.githubusercontent.com/3943250/81703865-0a155780-9465-11ea-9cd5-4a0e6844c9db.png)
![image](https://user-images.githubusercontent.com/3943250/81703893-14375600-9465-11ea-8f9a-52ff33ded65a.png)

**Environment**
- v13
- Windows 10 Pro, 10.0.18363

**Comment by burner1024** [comment]
It's a latest addition... apparently InnoSetup is acting up. Try v14.

**Comment by YaarPodshipnik** [comment]
rpu_v14.exe is even worse. It still doesn't ask for destination, but when I click install, it starts putting stuff to c:\windows

According to [this](https://jrsoftware.org/ishelp/index.php?topic=https://jrsoftware.org/ishelp/index.php?topic=setup_createappdir), having `CreateAppDir=no`
will prevent the destination dialog from showing up.

Maybe also add the below to see which dir it will got to?
```
AlwaysShowDirOnReadyPage=yes
```

Sorry for no pull request with those changes and just a comment.

**Comment by burner1024** [comment]
Sorry about that... the options interact in a non-obvious way. Inno also picks up old registry settings, which is why I haven't noticed this in the first place.

**Comment by YaarPodshipnik** [comment]
No worries! Inno docs I linked seriously lack proper cross references.

**Comment by burner1024** [comment]
I re-uploaded v14, it _should_ work now.

**Comment by YaarPodshipnik** [comment]
Works fine now, thanks!
