### ISSUE TITLE
VATS Hit Percentage Math

### ISSUE THREAD

**Issue by mav91** [BGforgeNet/Fallout2_Restoration_Project#55]
Windows 10 - playing the FRP through Steam - I installed the HD mod before FRP, installed FRP directly to my Steam installation folder of F2 (fresh install from Steam, I uninstalled then reinstalled).

Everything is working fine, except for the VATS hit percentages for guns, unarmed, melee weapons, anything I try.

Two issues:

1. I can have 95% hit percentage when attacking an enemy, yet still miss an unreasonable number of shots or hits. The math must be wrong or some kind of bug in the code.
2. On lower hit percentages, like 50% or 60%, I am still missing a stupid number of shots compared to the original game. I just finished Fallout 2 this week before installing the FRP and the hit percentages seem terrible in comparison to the original. For instance in Fallout 2 my original Steam download I was able to land grenade tosses at 12% in several instances, and the starting cave section I completed with no issue using the Chitsa preset character who has terrible strength and is a bad fighter. On the FRP I made a custom char with 5 str and struggled to hit way more.
3. I have 120% small guns skill at level 6, so I should be able to be seeing 75%-90% on headshots for enemies that are not too far away (3-5 move tiles away) yet I'm often seeing 30% hit rate, again this appears to be using dodgy math.

My strength is set to 5 and I am primarily using small guns (10mm pistol, desert eagle) neither of which exceed my strength, so that can't be the issue, and as I said above the bug is the same with unnarmed or melee weapons.

Any ideas how this can be fixed or where in the code I can modify this?

**Comment by burner1024** [comment]
Well, feel free to re-open if you find any conclusive evidence that something's off.
