### ISSUE TITLE
About Kaga's HP

### ISSUE THREAD

**Issue by NovaRain** [BGforgeNet/Fallout2_Restoration_Project#57]
Not really an issue. Currently Kaga's HP is kinda inconsistent in each encounter due to his varied SPECIAL stats:
1. Tribal: 333 (base 33 + bonus 300)
2. Leather: 338 (base 38 + bonus 300)
3. Metal: 333 (base 33 + bonus 300)
4. Combat: 335 (base 35 + bonus 300)
5. APA, final: 441 (base 41 + bonus 400)

Maybe he was supposed to have 300/400 as total HP but killap or someone in charge of proto edits didn't get it right? Because there was an example of the bugged 0000493.pro in old RP 2.3.3 with both "base" (useless because the game re-calculates base values for derived stats on load) and "bonus" set to 400 (whoever edited the proto probably used hex editing instead of GUI editors), which caused crashes in some cases.

**Comment by burner1024** [comment]
333 seems to be the recurring value, so if I had to choose one, that would probably be it.

**Comment by NovaRain** [comment]
> 
> 
> 333 seems to be the recurring value, so if I had to choose one, that would probably be it.

Hmm, given that the final boss has 999 HP, making a special enemy 333 HP seems a reasonable choice.
Don't know if his 5th was supposed to have 800 (from the incorrect proto setup in old RP) or 400 HP.

**Comment by burner1024** [comment]
Hardly, I think. I don't particularly like him being "special", I think RP has enough of that. It just seems a more or less consistent value.
As far as I remember, he wouldn't even have full HP in the last instance, only max would be upped to 800, current would stay at 400 or something.
What do you use to work with protos? It seems that ProtoManager still [doesn't support](https://github.com/FakelsHub/F2_ProtoManager/issues/10) AutoSearchPath.

**Comment by NovaRain** [comment]
> Hardly, I think. I don't particularly like him being "special", I think RP has enough of that. It just seems a more or less consistent value. As far as I remember, he wouldn't even have full HP in the last instance, only max would be upped to 800, current would stay at 400 or something.

His HP in final stage was displayed like "800/441", and first hit would cause the game to reset the incorrect current HP value.
In some cases the incorrect HP would crash the game when the player with Awareness perk hovers the targeting cursor on him, but of course that's been fixed in RPU.

> What do you use to work with protos? It seems that ProtoManager still doesn't support AutoSearchPath.

Both Proto Manager and Cubik's critter editor (it has a couple of convenient UI features so I spent some time setting it up for quick viewing critter stats), but that's because I'm still using old layout (i.e. use extracted RPU files to overwrite existing ones). Sometimes I just use a hex editor.

**Comment by burner1024** [comment]
Huh, I just realized I don't know where inventory is saved for the critters.
In the last stage he isn't actually wearing PA, he just gets its DR/DT stats, right? But those stats don't include strength. If we up base strength, that changes HP, and if we don't, he'll do worse in melee.

**Comment by NovaRain** [comment]
His stages are like other critters with built-in armor stats, and he already has 10 ST in the last stage. If you want him do better in melee, you might just give him some bonus melee damage.

**Comment by burner1024** [comment]
I just want consistent stats and HP... Does eqiupping armor actually change anything for critters? It could be done with a script.

**Comment by NovaRain** [comment]
> 
> 
> I just want consistent stats and HP... Does eqiupping armor actually change anything for critters? It could be done with a script.

Since you're going to edit his protos for consistent stats/HP, maybe just manually give him more base strength in his final stage, like how the current protos set up.

**Comment by burner1024** [comment]
Right... give more strength but drop base HP so total matches the rest. I don't know what I was thinking. Will do that.

**Comment by NovaRain** [comment]
> 
> 
> Right... give more strength but drop base HP so total matches the rest. I don't know what I was thinking. Will do that.

I think you mean "bonus HP" because the base values of derived stats are recalculated in game.

**Comment by burner1024** [comment]
Right, and I suppose his other stats are better equalized too? They are all over the place, going both up and down from stage to stage.

**Comment by NovaRain** [comment]
> 
> 
> Right, and I suppose his other stats are better equalized too? They are all over the place, going both up and down from stage to stage.

Yes, I think it's better to equalize his stats at least for 1st~4th stages, maybe give him a slight boost in his final stage.

**Comment by burner1024** [comment]
Ok, I went with
7/6/8/4/6/8/6 - first 4 stages
10/8/8/4/7/9/6 - final stage
