### ISSUE TITLE
Chemmie recipe change:  First Aid Kit.

### ISSUE THREAD

**Issue by giathai** [BGforgeNet/Fallout2_Restoration_Project#58]
Recommend a Chemmie recipe change:

First Aid Kit.

It's pretty useful as it can be ingredient for making: doctor bag, buffout, mentats, radx.

Its recipe is ridiculous expensive with  Stimpak, empty hypo, Poison antidote, rad away. ESPECIALLY the radaway thing, considering its price is more than the kit anyway. And FAK is not used to reduce rads, so this inclusion is plain weird.

I suggest to change the Radaway thing into Booze (using alcohol to cleanse the tool, clean the wound).

**Comment by burner1024** [comment]
That actually makes sense, although the same logic would apply to the antidote, I guess. And I'm not sure whether Booze is distilled enough to make a good desinfectant, maybe a Rot Gut instead.
@novarain what do you think?

**Comment by NovaRain** [comment]
From in-game description Rot Gut seems to be a better choice than Booze. But if we're going to change that for First Aid Kit, we should change all Booze in Chemmie recipes as well for consistency.
As for Booze, there's a description from _Fallout 2 Official Strategies & Secrets_: "Booze is a **distilled product of high alcohol content** ..." (I also checked my copy) so I think Booze should work just fine.

**Comment by giathai** [comment]
It also has significance in context.

When people hear it's booze using for disinfectant, they dont react much.
When people hear it's Rot Gut using for disinfectant, they react quite strong. Because rotgut has the literary context of being bad quality even with high alcohol grade.

For gaming significance: booze has 1 weight, Rotgut has none. So rotgut is much better as -PER chem. Meanwhile we dont store much booze for that, because it's heavy. Chemmie provide a legit way to deal with the stock of booze we have collected throughout the game.

So I urge Booze instead of Rot Gut.

**Comment by burner1024** [comment]
> As for Booze, there's a description from Fallout 2 Official Strategies & Secrets: "Booze is a distilled product of high alcohol content ..."

All hard beverages are distilled, but as you might've heard in the light of recent events, 40% (whisky, vodka, etc = booze) don't really cut it. It has to be at least 60%. And rotgut is ~80% (double effect in-game), so I figured that's more sensible. Actually, the recipe can be 2 booze vs 1 rotgut, whatever the player has, it's really only amount of alcohol that matters.

> When people hear it's Rot Gut using for disinfectant, they react quite strong. Because rotgut has the literary context of being bad quality even with high alcohol grade.

Mmm, no they don't and it's not?

> For gaming significance: booze has 1 weight, Rotgut has none.

Yeah, about that, actually no weight might be something to be fixed.

> But if we're going to change that for First Aid Kit, we should change all Booze in Chemmie recipes as well for consistency.

@giathai please check other recipes for that.

**Comment by giathai** [comment]
2 bottle of booze also can work~ Seriously, I have way too much booze around that single bottle doesnt reduce much.

**Comment by burner1024** [comment]
I glanced over other recipes... in fact most of them don't make much sense. Not to blame whoever made them up, of course, there's a quite limited selection of items in F2. However, it makes me a bit reluctant. It's all pretty random anyway.

**Comment by giathai** [comment]
Then only fix the issue with First Aid kit/booze~

**Comment by burner1024** [comment]
The answer is no.
- Limiting changes to FA kit is just a random change to a random recipe. All recipes should be treated the same.
- A compromise could be to make recipes configurable via an ini. I might accept such a pull request, however I'm not interested in working on it myself.
