### ISSUE TITLE
highlighting items problem

### ISSUE THREAD

**Issue by nsklaus** [BGforgeNet/Fallout2_Restoration_Project#59]
**Describe the bug**
highlighting items doesn't work for me.
i tried to modify ddraw.ini to change ToggleItemHighlightsKey=42 (left shift) to 54 (right shift)
but they did not work. neither 42 nor 54

**To Reproduce**
press shift key: nothing happens

**Expected behavior**
pressing shift key should highlight items

**Actual behavior**
no highlight 

**Savegame**
rats cave in klamath
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4943639/SLOT04.zip)

**Screenshots**
no highlight, so nothing to show

**Environment**
- RPU version: rpu_16
- other mods are installed : unofficialFO2patch.exe from killap's site (i do not know if this was needed or not)
running with wine 5.12, on arch based linux.

everything else seems to work, including high resolutions but i cannot figure how to have item highlight working.

**Comment by burner1024** [comment]
> unofficialFO2patch.exe from killap's site (i do not know if this was needed or not)

It's not.

Put [this](https://github.com/phobos2077/sfall/blob/master/artifacts/mods/gl_highlighting.int) into `data/scripts`. And [this](https://github.com/phobos2077/sfall/blob/master/artifacts/config_files/sfall-mods.ini) into main dir.

**Comment by nsklaus** [comment]
@burner1024 
thanks for the quick reply. unfortunately it did not work.
i can confirm both files you linked were missing from my installation, i added them where you told me. 
i can confirm shift key works for running. i also see sfall option screen for selecting resolution. by the way it says: graphic mode: 2
as a quick test i dropped a pair of boots i had in my inventory, in front of me and i pressed shift, still no highlight.
maybe something else is still missing ?

my install went like this: 
install fallout
install unofficialFO2patch.exe (i know now it wasn't necessary. tested game started fine)
install original killap restoration patch (game failled to run, complaining about wmareainit or something)
re-installed unaofficialFO2patch (game could be started again)
installed RP_V16 (game started correctly this time with your restoration project instead of killap's)

![Screenshot_2020-07-19_15-02-50](https://user-images.githubusercontent.com/6810861/87875443-7fefef00-c9d1-11ea-8c1e-48d80bdb02af.png)
![Screenshot_2020-07-19_15-04-29](https://user-images.githubusercontent.com/6810861/87875444-81211c00-c9d1-11ea-80dc-aa2dee008a60.png)

**Comment by burner1024** [comment]
how do you run F2? full cmd.

**Comment by nsklaus** [comment]
from fallout2 directory, just with: "wine ./fallout2HR.exe", like this:
```
kmbp: Fallout 2
$ wine ./fallout2HR.exe 
002c:fixme:winediag:__wine_start_process Wine Staging 5.12 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:err:vulkan:wine_vk_init Failed to load vulkan library
00b4:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
kmbp: Fallout 2
$ 
```
this snippet was full run: start game, load save, test shift (for highlight, which did not work), and then quit game.

**Comment by burner1024** [comment]
you need to pass dll overrides: `WINEDLLOVERRIDES='ddraw.dll=n,b'`

**Comment by nsklaus** [comment]
when i do that, there is some things happening:
i see sfall being mentionned on fallout2 title screen, bottom right corner, whereas before it wasn't.
but then the game has become unbearingly slow, just moving the pointer is a struggle.
for testing purposes when i finally reach load game screen, the game crash upon entering the world.
i attach error output, and screenshot of fallout title screen.
[error.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4943840/error.txt)
![Screenshot_2020-07-19_15-04-29](https://user-images.githubusercontent.com/6810861/87877312-d95e1b00-c9dd-11ea-8cba-541fc3be757d.png)
![sfall](https://user-images.githubusercontent.com/6810861/87877313-d9f6b180-c9dd-11ea-8d5b-6bfeb58cad06.png)

**Comment by burner1024** [comment]
Current sfall is 4.2.x, 3.3 is what RP 2.3.3 used. Yes, you better start anew.

**Comment by nsklaus** [comment]
while waiting for your reply i went ahead and deleted my wine prefix (rm -fr .wine/)
and installed fallout2 and rp_v16 only.
when this was finished i copied over the files you linked earlier:
sfall-mods.ini in fallout2 root directory
gl-highlighting.int in data/Scripts (i had to create the Scripts directory it didn't exists)
finally i copied my saves over, and started fallout2. game started fine, but i still don't have highlight upon pressing shift.
and there is no mention of sfall on fallout title screen.  that is, unless i pass dll override ddraw.dll=n,b. but if i do game is slowing to a crawl. and yes sfall gets mentioned, but it still say version 3.2

here is full log (both install of fallout2 and rp_v16 and running/quiting the game, with and without the dll override)
[wine-fallout2.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4943882/wine-fallout2.txt)

**Comment by burner1024** [comment]
1. You always need dll override. It's a prerequisite for running RPU.
2. Slowing down is another issue, let's not clutter. One issue per problem. However, I think you can try disabling CSMT: `winetricks csmt=off`.
3. Please attach your ddraw.dll and ddraw.ini. And show full listing of F2 dir. (just `ls`).

**Comment by nsklaus** [comment]
doing winetricks csmt=off made the game to start normaly (no more speed issue, pointer moving normally again and all).
i made the dll override as you said it was necessary, and i could see mention of sfall 3.2 in bottom corner.
when i loaded the game from my save, it did not crash immediately, but the screen stayed black. all i could see was the hud area on bottom of screen. then i pressed some key and it crashed. i include log, dir listing and dll as per reqested.

[ddraw.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4943943/ddraw.zip)
[wine-fallout2-1.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4943952/wine-fallout2-1.txt)

**Comment by burner1024** [comment]
Apparently you still have old sfall (which is what causing the crash now). Not sure why that happens.
I would try using a 32 bit wine prefix. (to create, `WINEARCH=win32 wineboot`, then proceed with installation normally).

**Comment by nsklaus** [comment]
i'm trying to create the 32bit wine prefix now. thanks for the directions.
as for sfall, all i can say is that i only installed fallout2 from gog and rp_v16.

**Comment by nsklaus** [comment]
ok, i went ahead and downloaded sfall 4.6.2 from [https://sourceforge.net/projects/sfall/files/sfall/sfall_4.2.6.7z/download](sourceforge)
i extracted it, and copied all its content into my fallout2 root directory (overwriting previous files).
and now on title screen is say: sfall 4.6.2.
game starts fine, saves load fine, and i have items highlighting working.
no speed problem, everything seems fine, i go play a few minutes more to see how it behave.
is it possible files in rp_v16 contains outdated version of sfall ?
i noticed when overwriting previous files that there was sizes differences.

**Comment by burner1024** [comment]
It doesn't. You can extract it yourself to verify.

**Comment by nsklaus** [comment]
maybe i don't have the correct version of rp_v16 ?
mine is like this:
```
$ ls -al  ~/Downloads/game_tempo/fallout/rpu_v16.exe 
-rw-r--r-- 1 klaus klaus 711034938 14 juil. 16:59 /home/klaus/Downloads/game_tempo/fallout/rpu_v16.exe
```

**Comment by burner1024** [comment]
3.2 comes with GoG installer. But for some reason, on your machine, RPU installer doesn't overwrite it with newer version like it should (and like it does on mine). I thought it might've to do with x32/x64 thing, but now I tried a 64 bit prefix, and it still does overwrite the dll correctly.

There's only one v16. Like I said, you can unpack it yourself with, say, [innounp](http://innounp.sourceforge.net/) and check the files inside.

What you can try (probably in a separate wine prefix, to avoid touching your game which is now working fine) is to set up everything anew, but with [logging](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline&anchor=LOG2) enabled. Maybe that'll shed some light.

**Comment by nsklaus** [comment]
ah that explains it.. at least partialy. those sfall 3.2 couldn't have come from nowhere. now i know it comes from gog package..ok.

well, my distro is a bit exotic, it's a non-systemd flavor of arch linux. maybe there's bits of wine left relying on some systemd process and since it's not there at all, that part gets dropped ? i have no idea, just blind guessing here.
in any cases, many thanks for the explanations and the help getting fallout2 to behave on my system!

if you want to test things more, to find out root cause of this, and you think i might be of some use, please let me know.
meanwhile i have a radioactive wasteland to .. clean and pacify :)

**Comment by burner1024** [comment]
> maybe there's bits of wine left relying on some systemd process and since it's not there at all, that part gets dropped 

I don't know. The next step would be to provide innosetup log. How to get it, I outlined in the previous message.

**Comment by nsklaus** [comment]
first i need to install innosetup-6.0.5.exe and then run:
```
wine gog-fallout2-setup.exe /log "bleh1.txt"
wine rp_v16.exe /log "bleh2.txt" 
```
in a new wine prefix,
is that what you're saying ? the syntax i put above looks alright ?

**Comment by burner1024** [comment]
You don't need to install innosetup.
Just rpu log is enough (make sure to provide the prefix)
```
WINEPREFIX=test wine gog-fallout2-setup.exe
WINEPREFIX=test wine rp_v16.exe /log="bleh2.txt" 
```

**Comment by nsklaus** [comment]
alright, i've created a new wine prefix with `WINEARCH=win32 wineboot`
i installed gog-fallout2, and then `wine rp_v16.exe /log="bleh2.txt" `
i didn't try to run it, because we did that a lot earlier i thought it wasn't necessary.
i didn't copy over the files the sfall-mods.ini and the gl-highlighting.int either.
please let me now if you need thoses steps too.

here is full log:
[wine-fallout2-4.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4944512/wine-fallout2-4.txt)

and here's rp_v16 log:
[bleh2.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4944508/bleh2.txt)

**Comment by burner1024** [comment]
Hmm, it says
```log
2020-07-19 21:40:37.468   -- File entry --
2020-07-19 21:40:37.470   Dest filename: C:\Games\Fallout2\ddraw.dll
2020-07-19 21:40:37.470   Time stamp of our file: 2020-05-20 23:06:36.000
2020-07-19 21:40:37.470   Installing the file.
2020-07-19 21:40:37.593   Successfully installed the file.
2020-07-19 21:40:37.593   -- File entry --
2020-07-19 21:40:37.595   Dest filename: C:\Games\Fallout2\ddraw.ini
2020-07-19 21:40:37.595   Time stamp of our file: 2020-07-02 17:11:22.000
2020-07-19 21:40:37.595   Installing the file.
2020-07-19 21:40:37.603   Successfully installed the file.
```

Can you verify whether they are old or new versions?

**Comment by nsklaus** [comment]
compared to the version i have found in sfall 4.6.2 i downloaed at sourceforge:

the ones i get after plain install of both gog-fallout2 and rpu_v16.exe:
```
$ ll ddraw.dll ddraw.ini 
-rwxrwxrwx 1 klaus klaus 384K 25 août   2015 ddraw.dll
-rwxrwxrwx 1 klaus klaus  16K 25 août   2015 ddraw.ini
```

the ones i get after manually install sfall 4.6.2 on top of gog-fallout2 + rpu_v16.exe:
```
$ ll ddraw.dll ddraw.ini 
-rw-r--r-- 1 klaus klaus 668K  3 juil. 15:38 ddraw.dll
-rw-r--r-- 1 klaus klaus  38K 19 juil. 19:00 ddraw.ini
```

**Comment by burner1024** [comment]
Well, I'm at a loss. The log reports installing them correctly. Inno even has `ignoreversion` and `overwritereadonly` flags set, which enables it to always overwrite the files. If you get any new idea or info, feel free to comment and I'll reopen. But for now, I don't know what else can be done or checked.

**Comment by nsklaus** [comment]
i can make a video/screencast of the whole install if you need.

**Comment by burner1024** [comment]
Unfortunately, that won't help.
