### ISSUE TITLE
Party Orders installation info

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Restoration_Project#6]
Please add to the notes that Party Orders Mod v1.3 requires moving "party_orders.ini" from mods dir  to main game directory as "party_op.ini".

**Comment by burner1024** [comment]
It shouldn't, and I pushed a new version to fix it.
Party Orders issues should go to [their own repo](https://github.com/BGforgeNet/Fallout2-Party-Orders).
