### ISSUE TITLE
lighting and fog of war 

### ISSUE THREAD

**Issue by nsklaus** [BGforgeNet/Fallout2_Restoration_Project#60]
**Describe the bug**
this is not a bug but rather a feature suggestion.
i was in a cave near klamath fighting rats for hours, even days apparently. and at some point i got outside without finishing the big rat monster. i thought i'd see first what's outside, maybe rest a little and fill the inventory with what i could find before getting back to the cave to finish the boss. and, when i got outside it was night time. it was a lot more darker than in the cave. if i wanted to see better around me the cave was the place to go back to. and that is a bit weird to have a supposed dark cave full of mutants rats being more brightful than the night outside. so here i wanted to suggest if it is possible to add fog of war in suposed dark places, and possibly making them at least as dark as the night outside. i do not know if you accept suggestions for new features here or not, but i thought i might try to ask and see how it goes. sorry if this was not appropriate.

**To Reproduce**
1. Go to some dark dark place 
2. see how clear and brightful it is compared to the night time outside

**Expected behavior**
i expected dark places without source of light to be, well.. dark.

**Actual behavior**
dark place was a lot brighter than night time outside. it was like sunny day inside that dark cave

**Screenshots**
the cave, without light sources
![darkcave](https://user-images.githubusercontent.com/6810861/87884396-67ea9080-ca0e-11ea-8b73-a05463f9ba73.png)

outside, night time
![outside](https://user-images.githubusercontent.com/6810861/87884399-691bbd80-ca0e-11ea-9b2b-420c1ccac86c.png)

**Comment by burner1024** [comment]
Gonna need a save.

**Comment by nsklaus** [comment]
here are the two saves:

in the dark cave, in front of the ladder to outside:
[darkcave.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4944636/darkcave.zip)

outside, night time (i waited 3hours for the night to come)
[outside.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4944637/outside.zip)

**Comment by burner1024** [comment]
Error on load, both. If you continued the game you started earlier without dll overrides, might have to do with that.

**Comment by nsklaus** [comment]
ok, i will create a new game, and go to klamath dark cave. now that i use dll override and the game's item highlight works and everything seems fine and all. then i'll report back. but,
from all the videos i've seen of the game, and previous session i had, even in a virutalized windowxp, this is always like that. caves are always as bright as would a sunny day outside. its like if the original dev team forgot that step of making light (or rather darkness) ambiance in "dungeons".

**Comment by burner1024** [comment]
Arroyo temple should be pretty dark. And RP specifically makes caves darker than in original, so much that I even had to add a [tweak](https://github.com/BGforgeNet/FO2tweaks#light-level) to tone it down. What you see is either a glitch in your game, or something's wrong in that particular cave.

**Comment by nsklaus** [comment]
just as i thought, from a new game, i made a speedrun to klamath dark cave, and it's as bright as day inside. a little moody lighting work would do marvels for the atmosphere. in comparison, arroyo temple was a little darker. there was brasiers and flames as source of light. in the entrance of the klamath cave there's also a few brasiers but not many. and it's a lot brighter. my bet is that many underground places and other supposed "dark places" just don't have any lighting effect applied.

**Comment by burner1024** [comment]
new save?

**Comment by nsklaus** [comment]
sorry, here it is:
[SLOT08.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/4944750/SLOT08.zip)

complete new game, speedrun to klamath cave, no shadows, cave evenly bright from every angle and space. i no light difference at all.

**Comment by burner1024** [comment]
I can't load a single one of your saves. Something's off. See if you can try them elsewhere, or maybe someone try them for you.
To be clear, the lighting should be and is dark on my machine:

![Captura de pantalla de 2020-07-20 06-07-34](https://user-images.githubusercontent.com/1279852/87887450-891fa100-ca4f-11ea-93e2-897c9f775986.png)

**Comment by nsklaus** [comment]
and you got the two big brasiers in front of the door, while i don't have them.
something is definitely wrong.  i'll try with fallout2 vanilla, and if it's the same i'll try under windowsxp virtualized.
maybe it's just wine-staging 5.1x ?

**Comment by burner1024** [comment]
I'm also on wine 5.12.

**Comment by burner1024** [comment]
Man... are you installing F2 and RPU into different directories?!

**Comment by nsklaus** [comment]
no i don't. it would seems a strange idea, i'd be surprised if you told i had to.

**Comment by burner1024** [comment]
That's not what the log from the other issue says, though:
```
2020-07-19 21:40:36.659   RestartManager found no applications using one of our files.
2020-07-19 21:40:36.700   Starting the installation process.
2020-07-19 21:40:36.710   Creating directory: C:\Games
2020-07-19 21:40:36.711   Creating directory: C:\Games\Fallout2
2020-07-19 21:40:36.712   Creating directory: C:\Games\Fallout2\backup
2020-07-19 21:40:36.712   Creating directory: C:\Games\Fallout2\backup\rpu
```

**Comment by nsklaus** [comment]
ok, let's suppose i clicked next, next , next a bit too fast while installing rpu.
it's possible, although unlikely. i will verify.

**Comment by nsklaus** [comment]
ok.. it seems i did.
it's a bit strange, since the installer asks only one time about the path and i've always selected fallout2 root directory.
but i must admit there actualy is a directory c:\Games\ which contains some fallout2 files. this is a fact. you are correct.
i copied them over my fallout install and now i can confirm the lighting problems are gone. so it seems i did something stupid without noticing. well.. my apologies for the time lost on this.

**Comment by burner1024** [comment]
It's a default and only path. There's no smart logic, it's just a pre-filled string.
