### ISSUE TITLE
Sfall-mods.ini left out by design? I just love to play with CombatControl

### ISSUE THREAD

**Issue by Myrthian** [BGforgeNet/Fallout2_Restoration_Project#61]
After having played Fallout 1 with Fallout et tu I don't want to play Fallout without CombatControl anymore, because the companions are just too stupid during combat if left to their own devices.

By default it seems parts of Sfall are being used, but not the Sfall-mod.ini for the CombatControl.

Is that by design?

**Comment by burner1024** [comment]
It's included in the next version.
