### ISSUE TITLE
Is the installation path missing a blank on purpose?

### ISSUE THREAD

**Issue by Myrthian** [BGforgeNet/Fallout2_Restoration_Project#62]
The default path of the installer is _C:\Games\Fallout2_ and if I wanted to start the game with the Fallout2.exe I will get the error "Couldn't find/load text fonts" - but if copy&paste the content on top of my Fallout 2 installation everything works fine, as I see the RPU version in the bottom right.

**Comment by burner1024** [comment]
yes
