### ISSUE TITLE
Stop the Brahmin raids quest bug

### ISSUE THREAD

**Issue by gterror** [BGforgeNet/Fallout2_Restoration_Project#64]
Having the problem of turning that quest in to Felix, after seeing the deathclaws, dialogue says that the job is not done. Using the latest rpu version
[SLOT21.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5240818/SLOT21.zip)
[SLOT22.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5240821/SLOT22.zip)

**Comment by burner1024** [comment]
Please make the zips actual zips , not rars renamed to zips (in future).

I cannot reproduce. In my game, after seeing the deathclaws, the quest is completed and turned in normally. (I do see that in your second save it's not completed). Are you sure that you've actually seen them and didn't leave the area too early? Try a couple more times, see if you can reproduce it.

**Comment by gterror** [comment]
I noticed that when the deathclaws appear, my character disappears for a sec, and when the deathclaws starts moving, it will appear again.

**Comment by burner1024** [comment]
> I noticed that when the deathclaws appear, my character disappears for a sec, and when the deathclaws starts moving, it will appear again.

OK, but that doesn't have anything to do with issue reproducibility.
