### ISSUE TITLE
info regarding MASTER.DAT patching

### ISSUE THREAD

**Issue by liPillON** [BGforgeNet/Fallout2_Restoration_Project#65]
Hi devs, I have no bugs to report, just a simple question about the installation procedure.

The original RP by killap's required the MASTER.DAT file to be patched. 
Without doing so, users would not have been able to create savegames.

Is this still the case for your new RP updated fork?
I would say no, judging by the installation instructions published here on github.

If so, it should be safe to install RPU on top of a clean humongous F2 install - correct?
Thank you!

**Comment by burner1024** [comment]
1. There's no patching necessary (thanks to newer sfall). RPU is entirely self-sufficient.
2. Questions are better asked on the [forum](https://forums.bgforge.net/viewforum.php?f=39).
