### ISSUE TITLE
Cat Jules level 5 proto typo

### ISSUE THREAD

**Issue by klipp556** [BGforgeNet/Fallout2_Restoration_Project#66]
Cat Jules's level 5 proto has an error regarding its Unarmed and Melee values.

Cat Jules currently has the following Unarmed & Melee skill value as he levels up:
Level 1: 55
Level 2: 65
Level 3: 75
Level 4: 85
Level 5: 80  <---this value obviously doesn't make sense

All of Cat Jules's combat skills grow by 10 each level so I have to imagine his level 5's Unarmed & Melee skill value was intended to be 95

![level 3](https://user-images.githubusercontent.com/75360549/100847439-75e10100-3445-11eb-9c06-d300d1196134.JPG)
![level 4](https://user-images.githubusercontent.com/75360549/100847457-7c6f7880-3445-11eb-8815-2f84a8b664be.JPG)
![level 5](https://user-images.githubusercontent.com/75360549/100847475-7ed1d280-3445-11eb-8ff4-97ab78a8af79.JPG)

Loving the mod btw, keep up the good work! :-)

**Comment by burner1024** [comment]
I think you're right.
