### ISSUE TITLE
No total compatibility with Fallout 2 Weapons Redone

### ISSUE THREAD

**Issue by Wickez** [BGforgeNet/Fallout2_Restoration_Project#67]
Howdey.

The old RP had a total compatibility with the swell mod of the [Weapons Redone](https://nma-fallout.com/resources/fallout-2-weapons-redone.72/updates). This is no longer the case with the Updated Restoration Project; the installer for the F2WR crashes when the option for the revamped Random Encounters gets selected; all other options work as intended, except this one, but it's important for it to get installed with the other (previous) selections to not needlessly weaken NPCs in several random encounters.

**Comment by NovaRain** [comment]
I think it's F2WR that needs to be updated/fixed because it might be too old to recognize the newer data structure which RPU uses.
Or you can try to extract the worldmap.txt from rpu.dat and put it in `Data\data\` first before running F2WR installer.

**Comment by burner1024** [comment]
Yes, you're going to have to get to Magnus about that.
Alternatively, it has manual installation instructions.

**Comment by Wickez** [comment]
Eyo, I managed to install it by unpacking RPU.DAT, as suggested, then going
through with the bundled F2WP installer. Cheerio.

śr., 23 gru 2020 o 00:33 burner1024 <notifications@github.com> napisał(a):

**Comment by lvhoang1** [comment]
So aside from that, can you confirm if this is ok to install Weapons Redone on top of RPU? 

I really like the changes to energy weapons, melee, and thrown range. But I'm kind of scared of incompatibility or bugs because they both touch the Armor Piercing in a different way.

**Comment by burner1024** [comment]
I didn't test, or ever used F2WR.
But if it works with RP 2.3.3, I'm 99% sure it'll work with RPU as well (although you may need to perform manual installation as described in F2WR readme).
For more auhoritative information, it's better to contact Magnus, the author of F2WR.

**Comment by Wickez** [comment]
> 
> 
> So aside from that, can you confirm if this is ok to install Weapons Redone on top of RPU?
> 
> I really like the changes to energy weapons, melee, and thrown range. But I'm kind of scared of incompatibility or bugs because they both touch the Armor Piercing in a different way.

Like I wrote above, it went smoothly with RPU, but I had to unpack RPU.DAT first and move the unpacked files into X:\Fallout 2 RPU\Data\Data\ directory before I ran the mod's installer.

No bugs detected on the front of weapons damage, armor piercing, and stuff; all works as intended by Magnus in F2WR.

P.S. Set "High DPI Scaling" to "Application" on F2WR installer if it's giving you troubles at launch.
