### ISSUE TITLE
Issues with Lenny Refreshing to his base model on each map change..

### ISSUE THREAD

**Issue by gustarballs1983** [BGforgeNet/Fallout2_Restoration_Project#68]
**Describe the bug**
A clear and concise description of what the bug is. (Also see the [instruction](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/reporting.md))

**To Reproduce**
1. Set Lenny armor appearance changes in npcarmor.ini
2. play the game, Recruit Lenny, equip him with an armor which he's sepose to change .frm to.
3. Armor changes to desired .frm
4. change map by any means (ladders, manholes, exit grids)
5. Lenny is back to base model! and a need to de-equip and re-equip armor is needed, in order to change back to corresponding armor animation .frm
6. Loading a save game with given bug resets the armor appearance to what's set in npcarmor.ini (need to change map to witness the bug)

**Expected behavior**
After equipping Lenny with an armor specified for him in npcarmor.ini, the change should stay there and persist until de-equipping that armor, or switchng to a different one.

**Actual behavior**
What actually happened.
Armor animation appearance for Lenny, after equipping armor,which i specified in npcarmor.ini , get's reverted to base animation appearance. on going to different map. (Note. Loading a savegame sets the correct armor animation from npcarmor.ini one has to go to a different map ie. exit to worldmap and click on the same spot agin for example for lenny to get back to his base model)
this animation reset is really annying, I'd really like the vibe of the power armored crew wrecking havoc and lenny base model kind of breaks it)
**Savegame**
Attach a savegame.
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5742403/SLOT04.zip)

**Screenshots**

**Environment**
- UPU version: v18
- If sfall was updated: yes from 4.2.8 to 4.2.8.1 (.dll only [left the default ddraw.ini cause no need t change]
- If any other mods are installed - fo2tweaks. gl_stealcheat.int (from modderpack), gltschardev2.int (also modderspack), GL_Rapid_Perks.int and RapidPerks.ini (from NMA's guy called Nirran straight from his modsite),
- If any cheats/trainers were used - 
- only custom hex edited Character file loaded during character creation. Hex edited all SPECIAL to 10 Skills to 300% all except steal skill and character age to 37 since in game customizator can only set to 35, however engine accepts values up to 99 just fine. all this in that custom char.cgd loaded during character creation.
-  aquired more perks than usual thanks to Nirran's GL_Rapid_Perks.int. massive party thanks to fo2tweaks, 
- ton of stuff in inventory thanks to sfall's:
- CritterInvSizeLimitMode=5
- CritterInvSizeLimit=2000000000 
- ALL partyNPC from EPA were aquired due to the old savegame trick:
- aquire ERSI put it in a container somewhere, and exit beyond map save file (usually a desk on the level with Mr.Chemmie) and I exit EPA and save to the desert. Next I exit game to desktop and copy all EPA save files from the catalogue of my last save to a different location.Next I launch Fo2RPU load that save go to EPA to take ERSI, exit EPA go to desert, save and exit to destop. copy EPA save files which were previously backed up, and replace the newer ones from my last save with the backed up ones. enter game, go to EPA and get a second ERSI cannister. Third ERSI cannister is done the same way. It is important to recover Sgt.Cat Jules as a last subject from the cryo-chamber not as first, otherwise One won't be able to get all 3 of those NPCs.
- other than that no external program was used no-Vad's, no-Falche2 and no-trainers.

other notable files I've modified:
[npcarmor.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5742416/npcarmor.zip)
[ddraw.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5742417/ddraw.zip)
[Fallout2.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5742418/Fallout2.zip)
[rpu.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5742419/rpu.zip)

notes:
I think the Lenny animation refresh is somehow tied to Lenny's script or other script that handles the setting in rpu.ini because for example Dex is also usually not present in npcarmor.ini, I've added him as well, and haven't noticed any abnormal behaviour with Dex (he's currently using power armor, and stays in power armor animation as expected)
Please do tell me if it's just a matter of leaving Lenny with the RP ( ghoul-redskin) animation as default, for the issue to go away, or is it something that needs to be done via script fix. 
I actually took Lenny's original model, because it can use SMG and it can run. Rifle animations is not super bad but until power armor, he can't use any decent ones, as his STR 4 and low small guns skill is a bummer, so the only option is to give him a burst weapon, and early on, only 10mmSMG does the job well. Besides it's not that one get's enaugh rifles with burst option early on. even the end game is harsh for burst rifle only users, as lenny's small guns skill prevents him from using gauss weaponry. 
no-Running can be quickly taken care of, as simple armor change to robes, power armor or advanced power armor, all have running animations, si if only Lenny stayed in the armor animation he is set to use everything would be fine, although he does not which is a big bummer, especially when using red-skin ghoul animation which does not have running.

**Comment by burner1024** [comment]
Yes, I don't want to duplicate instructions, so they won't get out of sync. The link has a special note mentioning that it leads to UPU repo. If you have a suggestion for making it clearer, feel free to share it. Maybe I should put it into a separate repo altogether.

**Comment by burner1024** [comment]
Also, the report is very detailed, thank you. If only they were all like this.
It's nothing to do with your edits, it's a script thing. I think NPC armor wasn't bundled yet at the time I wrote it, so I didn't take it into account.
Basically, the whole altering looks procedure needs to be skipped when Lenny is in one of those armors. Please remind me, it's just PA, APA and BK robes, or there's more?

**Comment by gustarballs1983** [comment]
Sorry for such a long delay.. i got carried away by xmas, and one stubborn family member that despite lockdown wanted to visit me anyways. so i had to attend to him, as guests in home should be treated nicely..

Anyways.. I've attached a personally modified "npcarmor.ini" that I've used to my bug report. No whacky stuff, Lenny only changes appearance to stuff that covers all bodyparts completely. (namely the default animations) a.k.a "Robes" "Power" and "AdvPower". I don't know what "BK robes" mean. In lenny settings I repeated the default values set as default for all listed NPCs. this armors are:
purple robes animation= Robes& Bridgekeeper's Robes
Power Armor animation= Power Armor& Hardned Power Armor
Advanced Power Armor animation = Advanced Power Armor & Advanced Power Armor Mk. II.
no unrealistic stupidity such as Lenny suddenly changeing to human animation like leathers, metal,combat armor aimations.
Only "within reason" armor animations for lenny are used, mainly for visual experience. Possibly, if set to use new Lenny "rifleghoul" animation settings, animation change will also enable Lenny to run instead of gimping & lagging behind.

ALSO: I've found a minor annoying bug in armor mod for Marcus, where when toying with the armor in Marcus's inventory with ControlCombat=2 in sfall-mods.ini during combad mode, could turn out Marcus script thinking He has the armor on, but actually it would be taken off. This leads to Marcus beeing unable to reequip the armor back agin, as inventory management doesn't allow Marcus to equip anything in armor slot at all, and the dialogue armor management bugs out as the script *thinks* the armor is on, but can't take it off nor put it on (the option to take off armor is there but after mentioned bug it doesn't do jack shit).
If You're interested I'll write a more detailed report on this one. The problem with screenshots about this one, is that Marcus's armor does not have inventory icon set, so it is invisible to the player, (however takes up Marcus's armor slot, and creates an invisible inventory item when taken off) so visualizing that may prove to be difficult.

**Comment by burner1024** [comment]
BK robes = brigdekeeper robes.
And right, there's also normal robes. Forgot about those.

NPCarmor being configurable makes it somewhat more complicated.
Try the attached script.
[gl_k_lenny_look.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5744303/gl_k_lenny_look.int.zip)

**Comment by gustarballs1983** [comment]
Ok so it seemes this new script did the trick. Lenny now sticks to armor animation all the time. haven't tested anything besides power armor yet, but I guess it works. as for Fo2tweaks i prefer an backup of an older version where brightness is fixed by adding Night Vision from the start, instead of screwing around with % brightness. I tried the % brightness once and after picking night vision, and suddenly something buged out, and the game has becone dark as if it was in-game night time during like 11AM, and haven't changed until i started a new game, without that crapped version.
