### ISSUE TITLE
NCR -> Redding brahmin drive, cant collect pay/do more than one run

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#69]
**Describe the bug**
A detailed description by Darek is here : https://www.nma-fallout.com/threads/redding-caravans-bug.181693/#post-4247011 and the rest of the thread has some more info (including a save)

The NCR->Redding brahmin drive appears to be bugged, The NPC that is supposed to pay you permanently deletes himself if you leave the redding map and come back, which prevents you from forever collecting your pay. If you go back to Duppo, he will say that a caravan run is available, but Hal never shows up outside of Westin's ranch. This also blocks you from entering the casino.

**To Reproduce**
1. Do the NCR->Redding brahmin drive.
2. Leave the map and come back, Hal will be gone and you cant collect your pay.
3. If you go back to Duppo, he will tell you theres another caravan run, but Hal never shows up outside of Westin's ranch so you can never go on another run
4. You cant get into the casino either

**Expected behavior**
The NPC that is supposed to pay you shouldnt delete himself permanently from the map as that prevents you from collecting your pay. It also bugs the caravan completion.

Duppo probably should be able to offer you another caravan run as he states he will have more in a few more months. If he tells you to be outside of westin's ranch, then Hal should show up so you can go on another run, but he never does.

You should be able to enter the casino as well rather than being blocked by the caravan dialog.

This is all done with Killap's patch but I saw that this bug wasnt mentioned in your changelog.

**Comment by burner1024** [comment]
1. This is UP or RP?
2. > This is all done with Killap's patch but I saw that this bug wasnt mentioned in your changelog.
  I'm not sure what do you mean. Are you saying it's fixed in killap's patch? All fixes are included, and changelogs are separate.

**Comment by Question2** [comment]
This was with RP 2.3.3. I will try getting a save of this.

**Comment by Question2** [comment]
Alright, I managed to get another save of the problem happening with v18 RPU.

Heres how I did it : 

1. Do NCR->Redding brahmin drive.
2. Leave the mining camp map and then come back. The guy who is supposed to pay you for the brahmin drive will delete himself from the map as per Darek's explanation due to an error in the script. Its probably supposed to make him invisible, not delete him.
3. Go back to Duppo and ask him for more work, then do another NCR->Reddigng brahmin drive.
4. Since the paymaster in the redding mining camp has permanently deleted himself from the map, he does not show up to pay you. This will prevent you from doing anymore brahmin drives in the future.

Slot02 is right before doing the brahmin drive.

Slot03 is after arriving in Redding and getting paid.

Slot04 is before starting the 2nd brahmin drive, once you arrive in the mining camp, you will see that the paymaster is missing.

[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760706/SLOT03.zip)
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760707/SLOT04.zip)
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760708/SLOT02.zip)

**Comment by Question2** [comment]
I took a look at the script and this appears to be the main problem : 

`procedure checkLoadConditions begin
   if (not cattle_drive(CATTLE_FINISHED) and cattle_drive(CATTLE_ON1)) then begin
      set_obj_visibility(self_obj, OBJ_VIS);
      set_local_var(LVAR_Vis, 1);
      dialogue_system_enter;
   end else if (cattle_drive(CATTLE_FINISHED)) then begin
      **destroy_object(self_obj);**
   end else begin
      set_obj_visibility(self_obj, OBJ_INVIS);
      set_local_var(LVAR_Vis, 0);
   end
end`

**Comment by burner1024** [comment]
Cool, feel free to submit a pull.

**Comment by burner1024** [comment]
I went through NMA thread. There are differing opinions. It seems that Hal's drive is supposed to be one-time thing, but the devs planned to have him repeatable at some point, which indicates the that the bug is having an option for the second caravan in the first place.
On the other hand, it's RP's task to restore cut content, so it kind of matches the scope.
Probably the most true fix would be to disable second run in UP and restore it in RP.
But I really don't want to maintain 2 separate versions, and the repeatable caravan is really very minor. So I think it'd be alright to let the paymaster appear in both, with option to actually restore Hal in Redding, should some code that.
