### ISSUE TITLE
NPC Armor Mod Missing FRMs

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Restoration_Project#7]
In V5 version:
rpu-install.sh sweeps gl_ammomod.int and gl_npcarmor.int into backup folder. 
And something is wrong with FIDs in npcarmor.ini like there are missing.
I had to copy npc armor files (data/art/critters) from killap RP like NMSULJ* NMSUCA* NMSUMA* NMSUPA* NMSULA* for Sulik to make it works.

**Comment by burner1024** [comment]
Please, one problem per issue.
You're right on both accounts. I pushed a new version.
