### ISSUE TITLE
Sierra army depot : buggy terminals

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#70]
**Describe the bug**

This is with killap's 2.3.3 patch.

I noticed that activating the alarms via the security terminals on each level does not seem to do anything. There are no alarms and the security bots do not move.

For example, in the attached save, using the terminal to activate the alarm on level 1 does nothing.

Note that this is after I have talked to Skynet and he said he was resetting security on levels 1-3. I am not sure if this makes a difference.

I looked in the scripts and noticed that the terminals seem to do this : 

`set_map_var(MVAR_Security_Level_1,1); // Seraph's Fix.  Original Code: set_global_var(MVAR_Security_Level_1,1);`

But the klaxons and bots are not tied to mvar_security_level, so by itself, so it does nothing.

In order to get the klaxons and bots to activate, you need to set this : 

`set_global_var(GVAR_SIERRA_BASE_SECURITY,SIERRA_SECURITY_ON);`

At this point, if security is activated on a specific level, the bots on that level will become active.

So to fix this, you need to make the terminals set the security to be on/off as well or nothing happens.

The klaxons are supposed to stop when the security is turned off as well, but they do not appear to do so. They are permanently active. I looked in the wsklaxon script but i cant see the problem...

[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5758246/SLOT04.zip)

**To Reproduce**
1. Use security terminals on each level
2. Activate the alarm
3. Nothing appears to happen

Edit : I will be editing the terminals myself, i will upload the scripts here when its done. Still dont know whats wrong with the klaxons not turning off though.

**Comment by Question2** [comment]
Okay i see the problem with the klaxons not turning off. 

For some reason, set_global_var(GVAR_SIERRA_BASE_SECURITY, SIERRA_SECURITY_OFF); doesnt actually set it to off. Not sure why, but when i checked the gvar with f12se, it was still set to 1.

Setting it to 0 instead seems to work though.

**Comment by Question2** [comment]
Doing some testing with the klaxons, im getting some strange results. It seems that the klaxons slowly turn themselves off, but only at a rate of one every 30 seconds or so. Not sure why this is doing this when turning the alarm on instantly makes all klaxons update to the flashing lights version.

**Comment by Question2** [comment]
Did more testing, if i activate the alarm, save, load the save game, then turn the alarm off, it works correctly. All the klaxons will instantly turn themselves off with no issues.

If i activate the alarm, then turn it off, it bugs out. At this point, saving and loading the save game will cause the klaxons to dissapear and other oddities.

What is this, an engine bug?

**Comment by burner1024** [comment]
1. I can reproduce the turning on the alarm doing nothing.
2. In my case, the klaxons just never turn off.
3. I can't reproduce the disappearing.

The whole system is a mess. Need to understand why did they use individual MVARs for security level and `GVAR_SIERRA_BASE_SECURITY` and in addition to that `GVAR_SIERRA_BASE_ALERT`.

**Comment by burner1024** [comment]
```
$ scripts_src/maps/depolva.ssl:   if ( (dude_elevation == 1) and (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) and (map_var(MVAR_Free_Bots) != 0) and (map_var(MVAR_Robot_Activation) == 0) ) then begin
scripts_src/headers/global.h:#define GVAR_SIERRA_BASE_SECURITY            (154)
scripts_src/sierra/wsklaxon.ssl:   if ((global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) and (local_var(LVAR_Once) == 0)) then begin
scripts_src/sierra/wsklaxon.ssl:   if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) then begin
scripts_src/sierra/wsklaxon.ssl:   end else if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_OFF) then begin
scripts_src/sierra/wiscrtdr.ssl:   if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) then begin
scripts_src/sierra/wcscbot2.ssl:   if ((global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_OFF) or
scripts_src/sierra/wcscbot2.ssl:   else if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) then begin
scripts_src/sierra/wcscbot2.ssl:   if ((global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) and (local_var(LVAR_Active) == 0)) then begin
scripts_src/sierra/wcsecbot.ssl:   if ((global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_OFF) or
scripts_src/sierra/wcsecbot.ssl:   else if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) then begin
scripts_src/sierra/wcsecbot.ssl:   if ((global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_ON) and (local_var(LVAR_Active) == 0)) then begin
```

`GVAR_SIERRA_BASE_SECURITY` is used:
1. for klaxons
2. in bot scripts in combination with MVAR level checks to attack the party
3. for activation of some horrible repair bay code that was further mutilated by killap for RP.

It is only ever turned off from Skynet terminal or assembled brainbot dialog.

**Comment by burner1024** [comment]
`GVAR_SIERRA_BASE_ALERT` is only set, but never checked anywhere. It can be removed.

**Comment by burner1024** [comment]
There's also `GVAR_SIERRA_BASE_ENEMY`, which has something to do with "Evil Skynet", and doesn't look 100% good, too.

Anyway, to summarize:
1. Other terminals do enable `GVAR_SIERRA_BASE_SECURITY` in addition to MVARs, so it looks like a bug.
2. Other terminals do no disable `GVAR_SIERRA_BASE_SECURITY`, so there's no evidence that klaxons not disabling is a bug.
3. It is not clear why there are GVARs in addition to MVARs in the first place.
4. The code is extremely confusing and frail. I wouldn't be surprised if they did actually intend for repair booth to work, they just _couldn't do it_.
5. I'll let the first terminal enable the alert properly and do some cleanup, but no further changes until someone figures out how it all actualy works.

**Comment by Question2** [comment]
Looking at the comments, it seems that the vanilla uses gvars only while the RP wanted to use mvars to specify the alert status on each floor and have the terminals enable/disable security on their respective floors only.

However, it seems that they didnt realise that the bots and klaxons are tied to GVAR_SIERRA_BASE_SECURITY, so setting the MVAR by itself does nothing.

The easiest way to fix this is simply to have each terminal set GVAR_SIERRA_BASE_SECURITY on/off when the player chooses to turn the alarm on/off. This will correctly cause the bots to go hostile instead of nothing happening.

Another strange part is the security terminal on level 3. You can disable the forcefields on level 1 and 2 via terminals, but there is no option to do it on level 3 because using the terminal causes you to talk to skynet. Its not clear if this is a bug, but i think it would make sense for the forcefields on level 3 to be disabled if you agree to help skynet and it would also be consistent with what happens on level 1 and 2.

**Comment by Question2** [comment]
As for the klaxons, they are supposed to turn off because they are tied to the security level in wsklaxon : 

`else if (global_var(GVAR_SIERRA_BASE_SECURITY) == SIERRA_SECURITY_OFF) then begin 
       if (obj_pid(self_obj) == PID_NS_FLASHING_LIGHT) then begin
           item:=create_object_sid(PID_NS_LIGHT,tile_num(self_obj),elevation(self_obj),SCRIPT_WSKLAXON);
           destroy_object(self_obj);
       end
       else if (obj_pid(self_obj) == PID_EW_FLASHING_LIGHT) then begin
           item:=create_object_sid(PID_EW_LIGHT,tile_num(self_obj),elevation(self_obj),SCRIPT_WSKLAXON);
           destroy_object(self_obj);
       end
   end`

When I tested it, it was doing this inconsistently. If I activated the security, all the klaxons will start flashing. BUT if i tried to turn it off, nothing would happen. At this point, if i saved and loaded the game, all the flashing klaxons would be deleted from the map.

On the other hand, if i activated the security, saved, loaded THEN turned the alarm off, all of them would instantly turn off as expected.

I will try testing it again to be sure.

**Comment by Question2** [comment]
OK tested the klaxons again.

![image](https://user-images.githubusercontent.com/1191378/103460033-192b7b80-4d4e-11eb-8375-7f85109a930c.png)

Here, i had just turned the alarm on, then turned it off. The secret walls have closed because GVAR_SIERRA_BASE_SECURITY is correctly set to off, but the klaxons are still flashing.

To be more specific, this is what I did : 

1.Used the terminal and turned the alarm on.
2.Exited dialog
3.Used the terminal and turned the alarm off

![image](https://user-images.githubusercontent.com/1191378/103460053-437d3900-4d4e-11eb-8f0f-e8472332724d.png)

I then saved and loaded. At this point, all the klaxons had vanished from the walls.

**Comment by Question2** [comment]
Okay ive fixed the following terminals:

Level 1 security terminal
Level 2 security terminal

Turning the alarm on/off will now set the GVAR for security level which will turn the bots/klaxons on and off.


[WSTERM1B.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760443/WSTERM1B.zip)

For the level 3 terminals, i have also made a small change : Agreeing to help skynet will disable the forcefields on level 3, similar to what you can do with the level 1 and 2 terminals.

**Comment by Question2** [comment]
[WISCRTDR.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760456/WISCRTDR.zip)

Ive also made the secret doors in skynet's room activate if the security is activated on level 3, as otherwise the bots inside the room remain trapped in it forever and just run around inside the secret room.

**Comment by burner1024** [comment]
1. I am not convinced. Need a second opinion. @NovaRain, what do you think?
2. I think klaxons are supposed to work the same way in both UP and RP, especially considering that RP [changelog](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/48c0aaef437841ccfc7fec1eaac215e1a910aa77/docs/rp-new_content.txt#L95) doesn't mention anything about them.
3. Whether this get accepted or not, it'd be better if you make a fork and a pull, to review changes more easily.

**Comment by NovaRain** [comment]
I agree the terminals on level 1 and 2 should really activate/disable the alarm (lights and bots). I'd vote no for extra changes on level 3.

**Comment by Question2** [comment]
Not sure what you mean by klaxons working the same way in both UP and RP...did you try replicating what I did to make the klaxons dissapear?

How do you make a fork and pull?

**Comment by Question2** [comment]
> 
> 
> I agree the terminals on level 1 and 2 should really activate/disable the alarm (lights and bots). I'd vote no for extra changes on level 3.

Main issue with level 3 is that the bots remain trapped in the secret room and are stuck inside, even though they are hostile to the player. They just run around inside.

This is a bug that killap added by the way, because killap made the secret doors open only if you make skynet an enemy. In vanilla, the secret doors open if the security is activated.

Theres no reason to keep the bots locked up in the secret room once the player has triggered the security.

**Comment by burner1024** [comment]
> How do you make a fork and pull?
[1](https://opensource.com/article/19/7/create-pull-request-github#comments), [2](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

> Not sure what you mean by klaxons working the same way in both UP and RP...did you try replicating what I did to make the klaxons dissapear?

I couldn't reproduce it in RPU.
I'm referring to this 
> it seems that the vanilla uses gvars only while the RP wanted to use mvars to specify the alert status on each floor and have the terminals enable/disable security on their respective floors only.

**Comment by burner1024** [comment]
> This is a bug that killap added by the way, because killap made the secret doors open on level 3 only if you make skynet an enemy. In vanilla, the secret doors open if the security is activated (for any reason).

I think this change should be reverted, yes.
Basically, the only things mentioned in RP changelog about Sierra are repair booth and trip wire. Otherwise, the location should work the same and scripts synced between UP and RP where possible.

**Comment by burner1024** [comment]
1. Many actors and actions can enable `GVAR_SIERRA_BASE_SECURITY`, but only Skynet can disable it. It makes sense and always been like that.
2. The purpose of klaxons is to indicate `GVAR_SIERRA_BASE_SECURITY` state to the player. Not the MVAR state. MVAR is pretty visible from robots shooting you in the face.
3. Therefore, terminals will turn on both. They will turn off MVAR, but not GVAR.
4. Secbots should no longer display floats when not active.
5. Level 3 secret door should release the bots when level security MVAR is set.
6. Anything else will have to be handled in separate issues, with savegames and steps to reproduce.
