### ISSUE TITLE
EPA : Moving Mr Handy causes massive stuttering when it is visible on screen

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#71]
![image](https://user-images.githubusercontent.com/1191378/103455923-3bac9d00-4d2c-11eb-9411-3e3cb2f7b5ae.png)

That mr handy looks like its trying to move left and right constantly and everytime it is visible on the screen, it causes massive stuttering and i can barely move. There is still some stuttering if it is not visible on the screen but it is not nearly as bad.

Using v18 of RPU with sfall v4.2.8.

[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760132/SLOT03.zip)

**Comment by Question2** [comment]
Nevermind, the installer didnt clear the script folder for some reason so its still using the old 2.3.3 scripts.

**Comment by burner1024** [comment]
Check logs in `backup` dir. It's supposed to clear them.

**Comment by Question2** [comment]
`
D:\GOG Games\Fallout 2>set "bdir=backup\rpu" 

D:\GOG Games\Fallout 2>set "scripts_dir=data\scripts" 

D:\GOG Games\Fallout 2>if not exist backup\rpu mkdir backup\rpu 

D:\GOG Games\Fallout 2>if exist patch000.dat (move patch000.dat backup\rpu\ ) 

D:\GOG Games\Fallout 2>move /y data backup\rpu\ 
Access is denied.

D:\GOG Games\Fallout 2>mkdir data\sound 
A subdirectory or file data\sound already exists.

D:\GOG Games\Fallout 2>move /y backup\rpu\data\savegame data\ 
The system cannot find the file specified.

D:\GOG Games\Fallout 2>move /y backup\rpu\data\*.txt data\ 
A duplicate file name exists, or the file
cannot be found.

D:\GOG Games\Fallout 2>move /y backup\rpu\data\*.gcd data\ 
A duplicate file name exists, or the file
cannot be found.

D:\GOG Games\Fallout 2>move /y backup\rpu\data\sound\music data\sound\ 
The system cannot find the file specified.

D:\GOG Games\Fallout 2>set appearances=hfr00s00,hfr00s01,hfr00s02,hmr00s00,hmr00s01,hmr00s02 

D:\GOG Games\Fallout 2>for %a in (hfr00s00 hfr00s01 hfr00s02 hmr00s00 hmr00s01 hmr00s02) do (if exist appearance\%a (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\%a backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hfr00s00 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hfr00s00 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hfr00s01 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hfr00s01 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hfr00s02 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hfr00s02 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hmr00s00 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hmr00s00 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hmr00s01 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hmr00s01 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>(if exist appearance\hmr00s02 (
if not exist backup\rpu\appearance mkdir backup\rpu\appearance  
 move appearance\hmr00s02 backup\rpu\appearance\ 
) ) 

D:\GOG Games\Fallout 2>mkdir data\scripts 
A subdirectory or file data\scripts already exists.

D:\GOG Games\Fallout 2>move /y gl_ammomod.int data\scripts\ 
        1 file(s) moved.

D:\GOG Games\Fallout 2>move /y gl_highlighting.int data\scripts\ 
        1 file(s) moved.

D:\GOG Games\Fallout 2>move /y gl_partycontrol.int data\scripts\ 
        1 file(s) moved.

D:\GOG Games\Fallout 2>initool.exe s fallout2.cfg sound music_path1 data\sound\music\  1>tmp.cfg 

D:\GOG Games\Fallout 2>initool.exe s tmp.cfg sound music_path2 sound\music\  1>tmp2.cfg 

D:\GOG Games\Fallout 2>del /s backup\rpu\fallout2.cfg 
Deleted file - D:\GOG Games\Fallout 2\backup\rpu\fallout2.cfg

D:\GOG Games\Fallout 2>move /y fallout2.cfg backup\rpu\ 
        1 file(s) moved.

D:\GOG Games\Fallout 2>del /s tmp.cfg initool.exe camlrt.dll 
Deleted file - D:\GOG Games\Fallout 2\tmp.cfg
Deleted file - D:\GOG Games\Fallout 2\initool.exe
Deleted file - D:\GOG Games\Fallout 2\camlrt.dll

D:\GOG Games\Fallout 2>move /y tmp2.cfg fallout2.cfg 
        1 file(s) moved.

D:\GOG Games\Fallout 2>del /s rpu-install.sh rpu-install.bat rpu-install.command 
Deleted file - D:\GOG Games\Fallout 2\rpu-install.sh
Deleted file - D:\GOG Games\Fallout 2\rpu-install.bat
Deleted file - D:\GOG Games\Fallout 2\rpu-install.command
The batch file cannot be found.
`

**Comment by Question2** [comment]
@burner1024  : I just ran the exe again and noticed that after the installation, i had somehow ended up with a script folder full of files. They were not there before i ran the exe.

[log.txt](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760394/log.txt)

**Comment by burner1024** [comment]
```
D:\GOG Games\Fallout 2>move /y data backup\rpu\ 
Access is denied.
```
I suppose that's where everything started to fall apart.
Check permissions on the directories.
