### ISSUE TITLE
v18 EPA : Sentry bots do not equip their weapons and just punch the player

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#73]
Using v18 RPU with sfall v4.2.8.

The sentry bots in the EPA do not equip their miniguns/rocket launchers and simply punch the player if attacked (which doesn't do much damage), effectively making them free exp. Just attack the sentry bots in the save if you want to see it.

[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760330/SLOT03.zip)

**Comment by NovaRain** [comment]
AFAIK robots in EPA don't have any weapon in their inventory.

**Comment by Question2** [comment]
I'm confused about that too because when I checked the robots in the sierra depot via BIS mapper, they have no weapons in their inventory yet can clearly equip and use them.

Maybe they get their weapons via a script when combat starts? I noticed the EPA ones have no scripts.

**Comment by burner1024** [comment]
Yes, sierra bots create their weapons via script.
EPA bots have scripts, but they are very simple.
Unless there's evidence it's a bug, I'm not inclined to make changes. Feel free to add info if you find any.

**Comment by Question2** [comment]
Im confused, are you saying that its intentional that EPA bots have no weapons? Whats the name of their script? I dont see them as having any scripts when i open the EPA maps in the BIS Mapper.

Its extremely weird for them to have no weapons, they are supposed to be security bots.

**Comment by burner1024** [comment]
I'm saying I don't really see a reason why not.
The script I see is epac21.

**Comment by Question2** [comment]
Well, the reasons that I see are ;

-Consistency, if players see a security bot, they expect it to be armed unless its clear that these bots are "special" in some way (and theres no such indication for EPA bots)

-No weapons = free xp for the player since all they can do is punch the player, and theres no reason to give the player free xp xp here

I had a look at the sierra security bots script and the setup parts seem pretty simple so i can add it to the epac21 and upload it here when im done. But where do we get the RPU source scripts?

**Comment by burner1024** [comment]
> But where do we get the RPU source scripts?

Right in this [repo](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/scripts_src), of course.

If someone who participated in EPA design would confirm that it's an oversight, that'd be good enough for me.

**Comment by burner1024** [comment]
On the second thought, yes, probably it's one of many oversigths. I agree that they need some weapons.

**Comment by Question2** [comment]
Theres no mention of the sentry bots in dialog except that the security hologram wants you to help him get control over the security bots again.

I downloaded the source scripts from github and tried compiling epac21.ssl, but now i keep getting this error : 

![image](https://user-images.githubusercontent.com/1191378/103938132-bc243100-5164-11eb-91a8-d5bc9c8545e3.png)

Every script from the RPU source that i open in the script editor is now complaining that it cannot parse define.h, although i can clearly see define.h in the header folder.

Am I supposed to do something extra to get the source scripts working? Strangely, im not getting this problem with the 2.3.3 source scripts.

If I double click on the error message to try and open upu.h, it gives me this error message : 

![image](https://user-images.githubusercontent.com/1191378/103938555-6439fa00-5165-11eb-8879-fa06916368ce.png)

I dont understand why its trying to open upu.h from the header folder, because i can clearly see it in the defines folder.

Do you happen to have discord by the way?

**Comment by burner1024** [comment]
BGforge discord is [here](https://discord.gg/4Yqfggm).

**Comment by burner1024** [comment]
- Added weapons and repair to EPA bots. Many of them were missing scripts, added those too.
- Didn't test, no save before entering EPA.
- It'd be good to reduce xp given for killing disarmed (repair) robots, but I'm not sure how to make it count and display in the normal combat xp pool.
