### ISSUE TITLE
v18 : default ddraw.ini causes RP to complain that you have overwritten RP's ddraw.ini file

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#74]
The ddraw.ini included in the installation file is missing this part : 

```
;Ensure that the RP ddraw.ini file is being used
ModifiedIni=42
```
Without this part, the game constantly displays a red warning text ingame saying that the RP ddraw.ini has been overwritten and warning you to revert the ddraw.ini.

**Comment by burner1024** [comment]
RPU doesn't check this. It's a leftover from RP, and if you have it, it means that something's wrong with update.

**Comment by Question2** [comment]
What do you mean by something's wrong with update? How do i check what is causing it?

**Comment by burner1024** [comment]
Definitely. I think you shared your log in the other issue, and there was something about permissions.
