### ISSUE TITLE
v18 : 5th Kaga encounter has incorrect hp?

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#75]
Using v18 RPU with sfall v4.2.8.

![image](https://user-images.githubusercontent.com/1191378/103480137-66baed80-4e0d-11eb-8cd8-6b7a140563d1.png)

I had the first kaga encounter near klamath, and i didnt get anymore till i got the 5th kaga encounter near san francisco. For some reason, Kaga has 800/441 hp. Im pretty sure he isnt supposed to have 800/441 hp.

Not sure how this is supposed to work but i suspect that skipping kaga encounters might have caused it.

Slot01 is in san francisco before the encounter, slot02 is at the start of the encounter.

[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5761660/SLOT01.zip)

[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5761663/SLOT02.zip)

If I damage Kaga, his hp resets to 441/441 (so he takes no damage from the first attack). After saving and loading in combat, I noticed that Kaga's hp reset to 800/800 (this is what you will see if you load slot02).

**Comment by burner1024** [comment]
I believe it ought to be fixed in #57.
Seeing that your upgrade didn't go well, I suggest that you make a fresh RPU installation and transfer the saves manually.
Maybe I should forbid direct upgrade.

**Comment by Question2** [comment]
Right, i did a fresh installation and that seems to have worked. Must have been a leftover critter proto file.
