### ISSUE TITLE
v18 : Kaga gear and xp are inconsistent

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#78]
Taken from v18's worldmap.txt : 

```
[Encounter: KAGA2]
type_00=pid:16777706, Item:10(wielded), Script:832
position=Surrounding

[Encounter: KAGA3]
type_00=pid:16777707, Item:242(wielded), Script:833
position=Surrounding

[Encounter: KAGA4]
type_00=pid:16777708, Item:12(wielded), Script:834
position=Surrounding

```
**Kaga 2** : The script gives him a 14mm pistol and makes him wield it, but the worldmap.txt gives him a hunting rifle and makes him wield it. The hunting rifle takes priority. What exactly is he supposed to use?

```
      check_restock_item(PID_14MM_PISTOL, 1, 1, 100)
      check_restock_item(PID_14MM_AP, 2, 2, 100)
      check_restock_item(PID_ASSAULT_RIFLE, 1, 1, 100)
      check_restock_item(PID_BOTTLE_CAPS, 250, 250, 100)

      wield_obj_critter(self_obj,self_item(PID_14MM_PISTOL));
```

Kaga 2 occurs near Modoc at levels 4+, I think giving him a hunting rifle would make more sense because the 14mm pistol is supposed to be a mid game weapon that starts showing up around new reno (and is way too powerful at Modoc when used with ammo mods). And why does he have an assault rifle? It looks like the assault rifle was meant for kaga 3 so im guessing that someone did a bad copy and paste here.

**Kaga 3** : The script gives him an assault rifle and makes him wield it, but worldmap.txt gives him a combat shotgun which takes priority. He shows up near the vault city raiders so an assault rifle probably makes more sense here. 

Edit : On second thought, I think it would be better to give him a FN FAL or something a bit better, the assault rifle isn't very threatening at this point because the player will have metal armor.

```
      check_restock_item(PID_ASSAULT_RIFLE, 1, 1, 100)
      check_restock_item(PID_5MM_JHP, 2, 2, 100)
      check_restock_item(PID_BOTTLE_CAPS, 500, 500, 100)

      wield_obj_critter(self_obj,self_item(PID_ASSAULT_RIFLE));
```

Kaga 4 : Has a minigun + laser rifle, but the script makes him use the minigun and he will never use the laser rifle unless he runs out of ammo (extremely unlikely since a level 12+ player around NCR wont survive the minigun for that long). The laser rifle doesnt make sense either considering he has low energy weapons skill.

Another issue is that the xp is inconsistent. Kaga 1 and 2 rewards 100 xp, but kaga 3 rewards 95 xp. And IMHO, the amount of xp rewarded is far too little for killing a boss character with 333 hp. I would suggest 500 / 750 / 1000 / 1250 / 1500 xp. His skill levels are also extremely high so he pretty much has 95% hit chance all the time.

**Comment by burner1024** [comment]
> What exactly is he supposed to use?

I have no idea.

> And why does he have an assault rifle? 

I have no idea.

I agree with most of your points, except FN FAL. My general rule is that balance should allow for no-reload playstyle. And a point blank burst from assault rifle is quite unleasant even in metal armor.
As for laser rifle, maybe give him something melee instead, as a backup.

**Comment by burner1024** [comment]
I went with 300/600/900/1200/1500 for xp and replaced the laser rifle with a super cattle prod.
Mostly this will be unseen anyway, since it's hard to kill him in first 4 encounters.
