### ISSUE TITLE
v18 RPU : Den slavers in random encounter cannot use their weapons

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#80]
I'm not sure which random encounter this is supposed to be...The encounter was called "bunch of slavers attempting to enslave some people" near the den. The slavers all have clubs and crowbars in their inventories but cannot wield them.

```
Encounter Difficulty Mod: -20WorldMap: Giving Player [45] Experience For Catching Rnd Encounter!
wmSetupRandomEncounter: Scenery Type: normal
wmSetupCritterObjs: typeIdx: 43, Formation: surrounding
wmSetupRndNextTileNum:TileNum: 21493
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 5 on Slaver: Critter Fid: 16777260
wmSetupRndNextTileNum:TileNum: 20099
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 5 on Slaver: Critter Fid: 16777260
wmSetupRndNextTileNum:TileNum: 17899
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 5 on Slaver: Critter Fid: 16777260
wmSetupRndNextTileNum:TileNum: 17286
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 20 on Slaver: Critter Fid: 16777252
wmSetupRndNextTileNum:TileNum: 18477
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 20 on Slaver: Critter Fid: 16777252
wmSetupRndNextTileNum:TileNum: 19678
inven_wield failed!  ERROR ERROR ERROR!
ERROR: wmSetupCritterObjs: Inven Wield Failed: 20 on Slaver: Critter Fid: 16777252
wmSetupCritterObjs: typeIdx: 44, Formation: surrounding
wmSetupRndNextTileNum:TileNum: 17291
wmSetupRndNextTileNum:TileNum: 18283
wmSetupRndNextTileNum:TileNum: 19274
wmSetupRndNextTileNum:TileNum: 19885
wmSetupRndNextTileNum:TileNum: 20899
wmSetupRndNextTileNum:TileNum: 18095
```
The encounter has a bunch of slavers and slaves on one team and a bunch of people including kids on the other team (the game just displays "you see nothing out of the ordinary" when i look at them). The strange part is that i cant see this encounter in RPU's worldmap.txt. The critter IDs 16777260 and 16777252 are not used in that file at all (im assuming fid means the proto ID). The slavers look like regular slavers though, the ones with the proto IDs : 16777433 and 16777434.

This is the only slaver encounter with clubs/crowbars, but it has no slaves (and this encounter does have slaves) : 

```
[Encounter: DEN_Slave_Run]
type_00=ratio:50%, pid:16777433, Item:5(wielded), Item:(0-10)41, Script:627                    ; Male Slaver w/ Club
type_01=ratio:50%, pid:16777434, Item:20(wielded), Item:(0-10)41, Script:627                   ; Female Slaver w/ Crowbar
position=Surrounding
```

[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5792101/SLOT10.zip)

**Comment by NovaRain** [comment]
Many critters don't have the "club" weapon animation, just change them to have knife for female and spear for male.

**Comment by Question2** [comment]
Looks like fid isnt equal to proto id. I guess theres something else that spawns those slavers in a combination of other critters to create the "slavers trying to enslave some people" encounter, but i dont know how that works.

**Comment by burner1024** [comment]
![Captura de pantalla de 2021-01-21 23-23-46](https://user-images.githubusercontent.com/1279852/105379859-da4b6000-5c3f-11eb-871a-61fe79b04689.png)
![Captura de pantalla de 2021-01-21 23-24-35](https://user-images.githubusercontent.com/1279852/105379863-dae3f680-5c3f-11eb-800e-15da911a0fc0.png)

The dude is just a regular bald dude, isn't he? I think it can be copied from hero appearance. The gal will have to be switched to knife.

**Comment by Lexx2k** [comment]
The hero appearance bald head dude has green pants. This critter has brown pants. So killing the club-wielders will now result in an odd graphic flip.

My autism took over and I created the missing animation files. 
https://nma-fallout.com/threads/new-animations-2.188707/page-100#post-4432729

**Comment by burner1024** [comment]
Must be a Murphy's law or something: "no matter your release policies, schedules and anything else, a bug will come up the day after release".
Added, thanks.

**Comment by Lexx2k** [comment]
I've only seen this because I went through the changelog after the new release. :>
