### ISSUE TITLE
Soft lock in the Church gang war fights are The Den if Lara dies

### ISSUE THREAD

**Issue by mathguilla** [BGforgeNet/Fallout2_Restoration_Project#81]
**RPU V18 - sfall 4.2.8.1 - Playing on a Mac using Porting Kit **

Hi everyone, 

There is a issue with the Church attack in The Den if Lara dies during the attack.
When the combat is over, there is an automatic dialog line opening.  I responded the line 1 'Let me heal first...' and normally there should be a response from Lara.  The issue is that if she's dead, this is what happen (see picture, and please disregard the highlighting which is not related to the issue).

![Capture d’écran 2021-01-09 à 16 34 22](https://user-images.githubusercontent.com/45603936/104113774-bee06c80-52b1-11eb-8709-8d6a7c318fcb.png)

The game was soft locked and I couldn't open any menu.  I had to Alt-F4 it.

It is tricky to replicate the bug since we cannot save during the fight. So to replicate one need to start the fight and let Lara die... Please find my save game before the fight here.

[SLOT05.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5792176/SLOT05.zip)

Best,
Mathieu

**Comment by burner1024** [comment]
It's indeed tricky to reproduce, but you can save in combat.
I don't see any obvious issue in the scripts. Please share a save where she's close to death. And enable [debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/debug.md), maybe it'll clarify something.
