### ISSUE TITLE
Myron's guards do not correctly check if the player is a mordino made man

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#84]
In NCMYRGRD.ssl, line 194 (talk_p_proc) : 

```
end else if ( (myron_permission) or (myron_date) ) then begin
         start_dialog_at_node(Node031); // this node will check if you are a mordino made man
      end else begin
         start_dialog_at_node(Node018); // this node does not check if you are a mordino made man
```

The made man check is only made in node031, but the only way to get to node031 is if you already have permission to see myron or if you are pretending to be a prostitute from the cat's paw (i think the RP adds a way to get miss kitty to send you there). 

So what happens if the player is a mordino made man is that the guard skips to node018 and he doesn't recognize that they are a mordino made man.

Simple fix, change line 194 to : 

```
 end else if ( (myron_permission) or (myron_date) or ( (self_family == dude_family) ) )  then begin
```

When you talk to the guard, he recognizes that you are a mordino made man and responds correctly.

**Comment by burner1024** [comment]
I agree.

**Comment by burner1024** [comment]
But saves are needed for testing.

**Comment by burner1024** [comment]
the msg does say "MADE MAN OR PERMISSION", so I guess it should be fixed, yes.
