### ISSUE TITLE
Abbey : Bookshelf has a skill book that is impossible to obtain

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#86]
![image](https://user-images.githubusercontent.com/1191378/104238087-0d4d6100-5494-11eb-8bb7-43b135018c8f.png)

That bookshelf has a outdoorsman skillbook but it is impossible to obtain it because it has the abbook.ssl script attached to it, which is only meant to be used with empty bookshelves in the abbey. It shouldnt have that script attached.

**Comment by Question2** [comment]
Another way of fixing it is to add this to the abbook.ssl script : 

```
procedure use_p_proc begin
 if (inven_count(self_obj) == 0) then begin
    script_overrides;
    display_mstr(102);
 end
end
```

So you can take stuff from the containers without the script blocking it.

**Comment by burner1024** [comment]
Script solution looks good to me, thanks.
