### ISSUE TITLE
Getting addicted too fast and sometimes not running

### ISSUE THREAD

**Issue by Fasciana** [BGforgeNet/Fallout2_Restoration_Project#90]
Hello guys.

I am playing F2 for many years now. And I always used the RP 2.3.3 yesterday I found out about your project.

I make clean new installation of fallout 2 classic english from gog. After that I directly installed your v.18 release.

Everything works quite well. But there are two issues I never had before. They just occur with v18 installed. With the normal fallout 2 and the standard RP v2.3.3 I never had these issues.

1. First I always using chemresist and all the years I'm playing I never got addicted ever since. But with your mod I just trink on beer maybe two and I'm already addicted. Same with other stuff. There must be an issue.

2.  I have turned on "always running" but sometimes, e.g. if a shelf is close let's say 1-8 squares than pretty often my character is just slowly walking its way over there. In F2 and RP v2.3.3 I never had that issue, too.

Both things are very annoying maybe you can fix this in a next release. Thx for the great work I really love it.

**Comment by burner1024** [comment]
Savegame, video?

**Comment by Fasciana** [comment]
Addiction issue:
Seems to be a bug. Tried it again, but I couldn't reproduce it.

Since it only happened in The Den I will try it there again. Later this evening.

Slow walking at short distances persists further. But I don't know to help solving this. Cause I can't give any further information on this. Do you still need a savegame?

**Comment by burner1024** [comment]
I think memory is playing tricks on you. The PC would always walk to the object if it was closer that 4 hexes.
I [requested](https://github.com/phobos2077/sfall/issues/46) an option in sfall to alleviate this 5 years ago, and it was [added](https://github.com/phobos2077/sfall/blob/51864eaf6ad98730b74c2eabffdce5efbc968d20/artifacts/ddraw.ini#L674).
Try using that. If you still have issues, let me know.
