### ISSUE TITLE
Gecko Power plant don't showing repair routine necessary to fixing the plant

### ISSUE THREAD

**Issue by Fasciana** [BGforgeNet/Fallout2_Restoration_Project#91]
When trying to repair the Gecko Power Plant, the procedure for the repair is missing. Means you don't get any clue which are the right steps to take in order to be able to repair it. Before I hacked into the poseidon network. I was leaving the conversation and know I can't reconnect to the network, After that i tried to repair the plant. (don't have save game from before)

Go to plant and try to fix it.

Robot goes through the routine, though you know what to do, but that is missing now.

actual build (v18) of rp
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6006098/SLOT02.zip)

![image](https://user-images.githubusercontent.com/79270167/108427324-46b87f80-723d-11eb-9946-d304957b4409.png)

**1. Edit**
Well it is still possible to fix the plant but for someone who hasn't played it before, there is now chance to solve this because there no more clues on which steps to take,

**Comment by burner1024** [comment]
What kind of clue?
Do you mean that the robot no longer does the routine?

**Comment by Fasciana** [comment]
Yes, I remember, that the robot did show the routine, so you get a clue, where to send it during repair process.

I consider, since you ask this, that this was changed, am I right?

**Comment by burner1024** [comment]
I don't really remember the robot doing anything on its own. It's brain is fried, isn't it?
Robot's script is pretty much the same.
I'm going to need some evidence showing it ever worked differently.

**Comment by Fasciana** [comment]
He burner.

It's been a while since I played FO2 the last time, but you were able to send him on the route which shows, which points to go. And after what's there was a text describing the main steps. I took the screenshot (see my reply) and at there usually is the procedure listet. But it isn't there as you can see.

But maybe my mind is playing tricks on me. I've got pretty less time and all the time have left, I'm doing the translation of the RP, Fallout Tweaks, Fallout 1 Fix and so into Germany.

I've I got time I'm going to tested it with vanilla version of Fallout 2 - the one from GOG.

Would this be a help to you?

**Comment by burner1024** [comment]
The text is here https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/text/english/dialog/gsterm.msg
I don't see anything describing the order of steps, nor the option to send the robot. Do you?

Here's UP version: https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/dialog/gsterm.msg

If you could find the corresponding lines in vanilla GoG version, or provide a save demonstrating it, it would help, yes.

**Comment by Fasciana** [comment]
I'm on it.

I starte a new game with the gog vanilla game. I'm already in gecko, unfortunately something crossed my plans, and I can't go on now. But this evening I have time and then I look it up.

**Comment by Fasciana** [comment]
Hi.

It seems, that there is bug. You were right, there was now script for the robot moving showing the right spots do repair the plant. But there was a written clue where the procedure was written down. But even in the vanilla installation it's missing. I talked to a friend of mine who played a lot of Fallout 2. And he also says that there was a written clue with right order of the spots the robot must go.

 I got to pictures.

![part1](https://user-images.githubusercontent.com/79270167/109431781-86832200-7a08-11eb-9a76-abadb0027a50.png)

As you can see the highlighted line says he wants to look up the procedure but if you click on it you only get this:
![part2](https://user-images.githubusercontent.com/79270167/109431835-b7fbed80-7a08-11eb-95c1-a3b508309840.png)

As I wrote earlier, my friend says that there was a written instruction in the second picture. It seems that there is a bug with vanilla version. Unfortunately, I don't have any other versions left of Fallout 2 except the one I'm using.

I did a save before I used the computer at the plant. Maybe you have another version and can check it out with my saved file. Since it is vanilla version of the game the save game should work.

[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6057878/SLOT01.zip)

Kind regards

**Comment by burner1024** [comment]
I also only have access to GoG version, so unfortunately can't check elsewhere.
To summarize:
- I have no idea what's this issue about. AFAIR the robot never showed the procedure, and there were no clues in the dialog.
- The only clue that I do remember is that the parts are named after planets, and that's their order.
- I don't see any traces of the info in either dialog file or the script.

Maybe you've played another mod that did have some extra info.

So, closing for now. If any new info comes to light, will reconsider.

**Comment by Fasciana** [comment]
No mods, just the vanilla version or the rp(u) nothing else. 

If I come across another version or got new clues I'll report back.
