### ISSUE TITLE
Many parts of the German translation are wrong or in Russian letters

### ISSUE THREAD

**Issue by Fasciana** [BGforgeNet/Fallout2_Restoration_Project#92]
**Describe the bug**
Some main parts of the German translation are wrong. Is there a possibility to redo the translation over at https://tra.bgforge.net/projects/fallout/rp/de/ ? 

If so, is there also a possibility that I do not have to go through all of the thousands lines of translation? Instead, I just want to directly pick the corresponding files containing the wrong lines. (I hope you understand what I mean.)

**To Reproduce**
Install German translation activate it, see the mistakes.

**Expected behavior**
Showing the correct translation, not russian letters or other stuff.

**Savegame**
Needs to be attached.

**Screenshots/debug logs**
I marked the mistakes at the screenshot.

![screenshot](https://user-images.githubusercontent.com/79270167/109506844-643be380-7a9e-11eb-8973-3d9ae03d5e1e.png)

**Environment (please complete the following information):**
latest build from yesterday, no other mods

**Additional context**
nothing more to add

**Comment by egornovivan** [comment]
The text seems to be fine 
![изображение](https://user-images.githubusercontent.com/60801856/109509612-e0482280-7ac2-11eb-8f3c-2efc0f34d191.png)

**Comment by Fasciana** [comment]
Yeah I see!

But it's displayed this way
![screenshot2](https://user-images.githubusercontent.com/79270167/109510323-250f9180-7aa2-11eb-9fb8-5b47c6d6f7b5.png)


Furthermore, there other words containing ö, ß, ü, and so on. But they are displayed correctly. As you can see at my first screenshot. There the word Fähigkeiten is written as intended with the small ä at the second position in the word.

That's the strange thing if all words containing the German "Umlaute" like ä,ö.ü and ß would be wrong, it would make sense but this way it's just strange! Because just some words are wrong and in Russian letters! I really don't understand this.

Any clues?

**Comment by egornovivan** [comment]
This is really strange 
![изображение](https://user-images.githubusercontent.com/60801856/109512241-b5ab9900-7ac5-11eb-97d1-620b486bcddf.png)

**Comment by Fasciana** [comment]
Definitely

**Comment by Fasciana** [comment]
The English version is affected also!

![screenshot3](https://user-images.githubusercontent.com/79270167/109513651-a0bf0d80-7aa5-11eb-8324-12dddb0f712a.png)


Might it be because I used the lastest build from yesterday? This one: https://github.com/BGforgeNet/Fallout2_Restoration_Project/actions/runs/608432310 ?

**Comment by burner1024** [comment]
Hmm, which file specifically did you use?

**Comment by Fasciana** [comment]
This one:

https://github.com/BGforgeNet/Fallout2_Restoration_Project/actions/runs/608432310 ,the rpu.exe. I installed it and left it to English. After firing up the game I remember to test the German translation. That's why I downloaded the translation.zip from the same link - to be up to date.

**Comment by burner1024** [comment]
Screenshot of mods dir, please.

**Comment by Fasciana** [comment]
Wait screenshot it is coming

**Comment by Fasciana** [comment]
![screenshot4](https://user-images.githubusercontent.com/79270167/109514595-7c176580-7aa6-11eb-9c85-9d9c9266cbe3.png)

I wanted to add, that I didn't changed everything else, except the apparel of Lenny, I switched it to 0 in the rpu.ini

**Comment by burner1024** [comment]
Right, as I thought.
You must have only one translation dat in the dir. Otherwise they'll mess each other up.

**Comment by Fasciana** [comment]
I'm such a stupid!!!

I missed the following in the hurry:

"Download rpu_v*_translations.zip from the latest release page. Extract the archive, copy only the desired language dat file into mods subdirectory." I looked it up right after your last reply!

I'm really sorry for this. I have missed it in the hurry.

But why are they messing each other up, since they are diffrent files?

**Comment by Fasciana** [comment]
Thx for your help

**Comment by burner1024** [comment]
Because the engine only supports text localization. Language directories only contain text.
There are other assets: fonts, graphics, etc that are localized to some degree or other in various translation packages. They are "global".
So when you add multiple dats, these assets override vanilla and each other here and there (since various bits are localized in some packages and not others). In the end you see the amalgam of them all.

No problem, keep up good work with translating!

**Comment by Fasciana** [comment]
Thx for your extended reply, I appreciate it.

Yeah translation needs some finetune, it's a lot of work. Some parts a translate pretty decent but others are, let's say, more freely translate. I guess that I'm done with the rpu translation during this week. lately at the beginning of next week - but no guarantee.

When viewing the massage file which contains the lines, is it some possible to instantly see whether the line belongs to the player or not? I am finding it pretty hard to figure it out when looking up the message files, it's really time consuming and annyoing because the translations much longer this way.

**Comment by burner1024** [comment]
I assume you saw the link to the message file in the bottom right?
![Captura de pantalla de 2021-03-01 22-33-17](https://user-images.githubusercontent.com/1279852/109519864-38405280-7ade-11eb-8147-fcd59fe72a80.png)

There is no better clue that the msg file.
Although in fact the same lines can be used by both PC or NPC, and even in different dialogs. (I don't know if that actually happens, but it's a possibility).

For disccusing the translations, [forum](https://forums.bgforge.net/viewforum.php?f=9) is a better place.
