### ISSUE TITLE
Dialogue Window doesn't close even after saving and loading again

### ISSUE THREAD

**Issue by Fasciana** [BGforgeNet/Fallout2_Restoration_Project#93]
**Describe the bug**
Left Arroyo and was underway to Klamath, on my way I got an encounter with some nomads. I said I want to barter and since then the following dialogue windows is shown, also you can play as usual. Even so I couldn't barter, and I couldn't hit talk bottom again. I'm using the fallout tweaks of you, the actual one.

Edit:
Evan reloading the game, with this dialogue saved before didn't help.

**To Reproduce**
I couldn't reproduce it, but I got the save game.

**Expected behavior**
Closing the dialogue

**Savegame**
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6071470/SLOT02.zip)

**Screenshots/debug logs**
![screenshot](https://user-images.githubusercontent.com/79270167/109708324-89624c00-7b9b-11eb-8fcf-b70ab6e6cd55.png)

**Environment (please complete the following information):**
RPU from today and the translation of today

**Additional context**
no

**Comment by Fasciana** [comment]
Im trying to disable the fallout tweaks maybe this caused it. Will report back

**Comment by Fasciana** [comment]
Restarting the complete game removed the box!

Just reloading the saved game, didn't removed the dialogue box, so I'm guessing it's a memory issue in connection with corrupted code?

**Comment by burner1024** [comment]
Ok, finally got it resolved. It's nothing to do with FO2tweaks.
Some changes in build system caused certain scripts fail to build silently, so they weren't making it into final package.
If you download the latest `rpu.dat` and find the nomads encounter again, it should be working normally.

**Comment by Fasciana** [comment]
Thx will give it a try in a few minutes

**Comment by Fasciana** [comment]
I searched my fingers wound!

Please help me, I can't find the rpu.dat in the code. I also used the search option, but I just can't find it! Where can I find it then?

Do you mean a new build from the actions section?

**Comment by burner1024** [comment]
yes, actions

**Comment by Fasciana** [comment]
> yes, actions

Okay. Thx again.

Just a little hind from me, though I don't know, if you know it. The lastest release from today seems not to have the fix included because when unziped and the setup started it says last updated/changed 02.03.2021. 

But when opening the release from yesterday, the one called "build", setup says last updated/changed at 04.03.2021. I wonder why the latest build has an earlier change date than the one from yesterday.

I just want to let you know in case that something went wrong.
