### ISSUE TITLE
Smiley melted away in toxic caverns

### ISSUE THREAD

**Issue by Fasciana** [BGforgeNet/Fallout2_Restoration_Project#96]
**Describe the bug**
Smiley got hit multiple times by the radiated liquids within the cave and melted away!  I tried it a few times now but there is now chance to get him out alive.

**To Reproduce**
Latest build from yesterday. Just go to the cave and get Smiley

**Expected behavior**
Smiley not taking damage from the radiated liquids.

**Savegame**
If necessary, I'll upload it

**Screenshots/debug logs**
![screenshot1png](https://user-images.githubusercontent.com/79270167/110173602-2244d180-7dff-11eb-8ecc-4d571cbb1dfe.png)

**Environment (please complete the following information):**
Latest RPU from yesterday

**Additional context**
 Any other usefull info?

**Comment by burner1024** [comment]
You got a save before talking to him?

**Comment by Fasciana** [comment]
> You got a save before talking to him?

No. But when I entered the cave. Will this do?

Then here it is:
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6093401/SLOT01.zip)

**Comment by burner1024** [comment]
You have no rubber boots. Let me guess, you stole his pair?

**Comment by Fasciana** [comment]
> You have no rubber boots. Let me guess, you stole his pair?

No, I take the pair from the locker at the entrance of the cave.

I restarted the game, this time Smiley made it without any damage, but my boots are just gone! And now I'm taking all the damage.

Could it be that there was a scripting error, that maybe my boots were gone but the game did a wrong check and acts like Smiley lost his boots instead? Just a guess

**Comment by burner1024** [comment]
Boots melt randomly.
It's quite normal for Smiley to die if you don't take care about him and wander the goo too much.

**Comment by Fasciana** [comment]
> Boots melt randomly.
> It's quite normal for Smiley to die if you don't take care about him and wander the goo too much.

Well he took the hits directly after he left the room he was hiding in. It was as if didn't ever where boots. I played the game about 100 times and that never ever happens before, same to me. The boots melted away at first contact when I reloaded the game.

There is also an issue with the brahmin mutilation. There is no option to talk to Mrs Bruckner about the clues and one can't make up the rebranded cows in the cattle of the Dunton brothers.

**Comment by burner1024** [comment]
>  I reloaded the saved game 4 times and it was always the same. It stopped when I restarted the game, so I think there is more about it, than just the regular melting boots.

When you can reproduce it, attach a save.

Other problems should go into their own issues.
