### ISSUE TITLE
Masticator fight in New Reno

### ISSUE THREAD

**Issue by xsarq** [BGforgeNet/Fallout2_Restoration_Project#97]
### What happened

I Fought Masticator on hard difficulty. I Score knockout by critically hitting in eyes or head, combat ends then its automatically restarts again like nothing happened. 

### What you expected to happen

I Score knockout, battle ends then ive got success screen. 

### Screenshot

https://imgur.com/a/G3vzKF6

### Savegame

Attached.

[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6175792/SLOT01.zip)

Also this is being played on Revison 18 with SFALL updated manually since i couldn't get item highlisting working through SFALL provided by you (shift wasn't working), installed on polish copy of Fallout 2 with polish rp translation project on. (Yeah thats a lot of things that could mess this up I know lol)

**Comment by burner1024** [comment]
Save crashes on loading. Please attach your ddraw.dll and ddraw.ini.

**Comment by xsarq** [comment]
Here:
[ddraw.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6177639/ddraw.zip)

**Comment by burner1024** [comment]
The crash is my own misconfiguration, nvm.
It's hard to score a knockout, though.
What does the message log say? I don't know Polish.

**Comment by xsarq** [comment]
https://youtu.be/UGiehhqNJmQ

At around 0:30 I'm scoring KO, combat ends for one turn, then combat starts again and he's standing again like he didn't just get KO. Cheater!

**Comment by FakelsHub** [comment]
Проверьте данную ситуацию с более старыми sfall версии 4.0/3.8 есть сомнения что это следствия изменения кода для AI.

**Comment by burner1024** [comment]
I can confirm the bug.
But RPU crashes on game launch then using sfall 4.0, so can't test with it.
`ncprzftr.ssl` has seen very [little changes](https://github.com/BGforgeNet/Fallout2_Restoration_Project/commits/master/scripts_src/newreno/ncprzftr.ssl) since RP. When testing on RP (default sfall 3.3) with new script, it works properly.
@novarain

**Comment by NovaRain** [comment]
It's the same in original RP 2.3.3. The issue is due to the fix for combat not ending automatically when there are no hostile critters in 4.1.9, if you test 4.1.8.1 the scenario should work correctly. I guess maybe the fix is a bit too aggressive or there's an oversight in the script only got triggered by the change (similar to the case of ending slide playback on the oil rig before)

**Comment by burner1024** [comment]
> It's the same in original RP 2.3.3

Hmm, for me it's not.

**Comment by NovaRain** [comment]
> 
> 
> > It's the same in original RP 2.3.3
> 
> Hmm, for me it's not.

I mean with newer sfall the fight with Masticator is bugged.

**Comment by burner1024** [comment]
Oh, I see.

**Comment by FakelsHub** [comment]
из вашего обсуждения не совсем понятно на кокой версии это работает? на 4.1.8 работает?
или это проблема PR?

**Comment by NovaRain** [comment]
> 
> 
> из вашего обсуждения не совсем понятно на какой версии это работает, на 4.1.8 работает?
> или это проблема RP?

The last version works fine is 4.1.8(.1), starting from 4.1.9 the fight with Masticator doesn't end if the player only knocks him out. Now the only way to win is killing him.

**Comment by FakelsHub** [comment]
_Why is it so incompetent to write scripts that then become buggy._

**Comment by NovaRain** [comment]
> _Why is it so incompetent to write scripts that then become buggy._

I'm not sure if the issue is due to sfall or hidden bug/faulty logic in the script, I was just doing tests.

**Comment by FakelsHub** [comment]
> Setting a "boxer got knocked out" variable in damage_p_proc and checking the variable in critter_p_proc might work.

This is the right decision.

I'm still dealing with two hacks that led to this bug.
> // Fix for combat not ending automatically when there are no hostile critters
> // Fix crash or animation glitch of the critter in combat when an explosion from explosives

**Comment by NovaRain** [comment]
> I'm still dealing with two hacks that led to this bug.
>
> > // Fix crash or animation glitch of the critter in combat when an explosion from explosives

Huh? That's one of the causes? I thought it's the 'NPC became a container' fix.

**Comment by NovaRain** [comment]
Here are my fix attempts: [ncprzftr_fixes_nr.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6219033/ncprzftr_fixes_nr.zip)
Tested in my game and it worked. I utilized the newer `combat_data` function to specifically check the "knocked out" flag.
One uses an extra LVAR to for the additional checks along with `is_critter_prone(self_obj)`, and the other is running the player win macro directly like the disqualified check.

**Comment by burner1024** [comment]
Thanks, I think direct check is cleaner? Added it.

**Comment by FakelsHub** [comment]
> EDIT: If I lower his endurance from 10 to 9, or set `KnockoutTime=40` in the ini, the scenario works as it should, at 

can default to a minimum of 6 seconds (36), as one round of combat increases the total time for 5 seconds.

**Comment by FakelsHub** [comment]
На самомделе вся эта связка скриптов написана очень глючно. Например при проигрыше игрока когда рефери объявляет победителя боксер инициализирует бой и атакует игрока, а если у игрока осталось мало хп то боксер его может и убить там же вне боя. :-)
И еще несколько косметических глюков уловил, когда тестировал это.
В общем очень глючная реализация боксерских боев.

**Comment by NovaRain** [comment]
> 
> 
> > EDIT: If I lower his endurance from 10 to 9, or set `KnockoutTime=40` in the ini, the scenario works as it should, at
> 
> can set default to a minimum of 6 seconds (36), as one round of combat increases the total time for 5 seconds.

Is the issue because with the fixes the wake up event (after 5 sec by default calculation) runs slightly earlier before critter_p_proc/combat_p_proc (run after each round, also 5 sec)?

**Comment by FakelsHub** [comment]
> Thanks, I think direct check is cleaner? Added

Не верное исправление. Проверка дожна быть в скрипте игрка, а в скрипте только установка переменной того что боксер накаутирован.

**Comment by FakelsHub** [comment]
> Is the issue because with the fixes the wake up event (after 5 sec by default calculation) runs slightly earlier than critter_p_proc/combat_p_proc (run after each round, also 5 sec)?

Да флаг снимается до combat_p_proc в конце раунда.
[Pc turn]->[npc turn]->[ end round +5sec run events ]->...  here 
[Pc turn]->[npc turn]->[ end round +5sec  ]->[ pc turn] ->[run enents]->...  was

**Comment by NovaRain** [comment]
> Yes, the flag is removed before the dude combat_p_proc at the end of the round.

By "run events" you mean the damage_event (clear knocked out flag if timer is up) in queue?
So it took at least one round for knocked out critters to wake up even with EN 10, but now they can wake up right after the same round they got knocked out?

**Comment by FakelsHub** [comment]
Once again I will depict the scheme
`[pc]->[npc1 knocked skip turn]->[npc2]->[end round +5sec]->[run events]->[pc or npc] ...`
it was
`[pc]->[npc1 knocked skip turn]->[npc2]->[end round +5sec]->[pc or npc]->[run events]->[npc] ...`

**Comment by FakelsHub** [comment]
Сan try to align the chain, main thing is that the events are executed before the NPC turns.
`[pc]->[npc1 knocked]->[npc2]->[end round +5sec]->[pc]->[run events]->[npc1] ->[npc2] ...`

**Comment by burner1024** [comment]
> Не верное исправление. Проверка дожна быть в скрипте игрока, а в скрипте боксера только установка переменной того что боксер накаутирован.

Почему? Все остальные проверки же в скрипте боксера.

> В общем очень глючная реализация боксерских боев.

Это да, ну так такого же полно и во всех остальных скриптах, так что чинится по мере возможности. Если есть желание - исправляй.

**Comment by FakelsHub** [comment]
>  Почему? Все остальные проверки же в скрипте боксера.

Там как раз все страховочные проверки (как я понял), или их наляпили лижбы были.
Самая основная в скрите dude без нее не идет проверка нокаута при переходе хода.

> Если есть желание - исправляй.

Не, у меня в sfall/движке полно дел.

Совет: когда игрок находится в боксерском бою, у напарниках в combat_p_proc  ставишь функцию ovveride_script и тогда они будут пропускать ход, а не искать как напасть на боксера.

**Comment by burner1024** [comment]
I really don't want to dive into this further now. Maybe later, if additional reports come in.
For the time being, I think NovaRain's version will do.
