### ISSUE TITLE
Syntax mistakes in translated .msg files

### ISSUE THREAD

**Issue by wipe2238** [BGforgeNet/Fallout2_Restoration_Project#99]
While testing more strict .msg scanner, i went thru RP and found two kinds of format errors. Not 100% sure if that can lead to problems, but as i already have report anyway... :]

First part is dead simple - `{{` used instead of `{`
```
{281}{}{{[J�t za n�]}
--------^ bracket not allowed here [data\text\czech\dialog\ncangbis.msg:41]
{249}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncfluffe.msg:32]
{328}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncfluffe.msg:75]
{348}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncfluffe.msg:88]
{260}{}{{Kdy� se na m� pod�v�, taju jako sn�h.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:86]
{290}{}{{Kdy� se na m� pod�v�, taju jako sn�h.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:116]
{403}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:229]
{591}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:417]
{754}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:580]
{985}{}{{Minulej tejden jsem nakopala Julese do koul�.}
--------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:811]
{1159}{}{{Minulej tejden jsem nakopala Julese do koul�.}
---------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:985]
{1332}{}{{Minulej tejden jsem nakopala Julese do koul�.}
---------^ bracket not allowed here [data\text\czech\dialog\ncprosti.msg:1158]
{403}{}{{Nie jestem zainteresowany. Dr Sheng - tw�j problem. Ty i ca�a reszta Shi spokojnie mo�ecie sobie z nim poradzi�.}
--------^ bracket not allowed here [data\text\polish\dialog\fcdrwong.msg:118]
{422}{}{{Nie jestem zainteresowany. Dr Sheng - tw�j problem. Ty i ca�a reszta Shi spokojnie mo�ecie sobie z nim poradzi�.}
--------^ bracket not allowed here [data\text\polish\dialog\fcdrwong.msg:123]
{129}{}{{De nada. E quanto aos meus amigos??}
--------^ bracket not allowed here [data\text\portuguese\dialog\vcandy.msg:30]
{135}{}{{Vamos com isso, ent�o. Eu s� vou prender o ol'Doctor aqui... esticar os suspens�rios e firmar os presilhas...}
--------^ bracket not allowed here [data\text\portuguese\dialog\vcandy.msg:36]
{180}{}{{Vamos com isso, ent�o. Eu s� vou prender o ol'Doctor aqui... esticar os suspens�rios e firmar os presilhas...}
--------^ bracket not allowed here [data\text\portuguese\dialog\vcandy.msg:81]
{337}{}{{Vamos com isso, ent�o. Eu s� vou prender o ol'Doctor aqui... esticar os suspens�rios e firmar os presilhas...}
--------^ bracket not allowed here [data\text\portuguese\dialog\vcandy.msg:238]
{150}{}{{Bueno, est� justo� �Oye!, De todos modos, �qui�n eres t�?}
--------^ bracket not allowed here [data\text\spanish\dialog\gczamok.msg:18]
{270}{}{{Est� bien. Puedes entrar.}
--------^ bracket not allowed here [data\text\spanish\dialog\gczamok.msg:48]
{150}{}{{Bueno, est� justo� �Oye!, De todos modos, �qui�n eres t�?}
--------^ bracket not allowed here [data\text\spanish\dialog_female\gczamok.msg:18]
{270}{}{{Est� bien. Puedes entrar.}
--------^ bracket not allowed here [data\text\spanish\dialog_female\gczamok.msg:48]
```

Second part contains multiline errors.
Faulty line is missing last `}`, next line contains only message id part, and another line is a correct entry with same id.

Full example:
```
{109}{}{Vault? Die einzige Vault die ich kenn ist in der Stadt. Verdammt großes Teil, kannste kaum verfehlen.)
{110}
{110}{}{Was hast du für Drinks auf Lager?}
```

```
{110}
^ bracket not allowed here (multiline) [data\text\german\dialog\vcmacrae.msg:11]
{401}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\gcbrain.msg:138]
{192}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\kcsmiley.msg:43]
{211}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\kcsmiley.msg:52]
{184}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\mcfarrel.msg:34]
{167}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\mcmiria.msg:19]
{165}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\mcrose.msg:22]
{237}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\ncmcgee.msg:22]
{386}
^ bracket not allowed here (multiline) [data\text\portuguese\dialog\ncrenesc.msg:114]
```

**Comment by burner1024** [comment]
Hm.
1. Is it actually not allowed? It seems that it's just [translated](https://tra.bgforge.net/translate/fallout/rp/cs/?checksum=&offset=&q=J%C3%ADt+za+n%C3%AD&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=#nearby) that way for some reason. And I checked translation source, it's the same there.
  Looks like a typo caused by manual translation. (Which is a reason to use the system...)
2. The second one is definitely a [typo](https://tra.bgforge.net/translate/fallout/rp/de/?checksum=&offset=&q=Die+einzige+Vault+die+ich+kenn+ist+in+der+Stadt&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=). Again, loaded from original translation, caused by manual typos.

Is this the full log of your checker?

**Comment by wipe2238** [comment]
> Is it actually not allowed?

Truth told, i'm never sure when it comes to .msg files what _really_ is illegal and what's not :S Fact that MSG format is very poorly described doesn't help either... But as single mistake in MSG can lead to crash (fresh example [here](https://github.com/fedprod/Fo1in2/commit/2bbef67feb9fb46330ebbf0c0ca00c31cdec10a6#diff-14ed05d2c40a09da0c26c12cc40fc9b6b4001805a2fc6905a1b5bf67e0dbc2e1L975)) it's more of "better safe than sorry" than anything else.

> Is this the full log of your checker?

I've cut parts which which are known to be non-issue, and falls into "cleaning up" category (enforcing usage of `#` for **any** text outside of `{}{}{}`, which isn't even needed from engine point of view).

**Comment by burner1024** [comment]
Ok, thanks. I'll clean it up.

**Comment by burner1024** [comment]
I've corrected the lines. Just to be sure, though, could you tell where to get the checker and how to run it?

(Also, if you have any tests/scanners for other files or game resources, please let me know, I'll see what else can be integrated into CI.
On my part, I have some rudimentary [tests](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/extra/tests) for LVARs and script names.)

**Comment by wipe2238** [comment]
> could you tell where to get the checker and how to run it?

[Source](https://github.com/wipe2238/ScanMsg/), with [binary-mirror](https://github.com/rotators/Fo1in2/tree/master/Tools/ScanMsg/) in FO1@2 repo. It simply looks for all `*.msg` in current dir and all subdirectories. Alternatively, you can run `exe path\to\check` but it might be little buggy, i'll get to that when i find time.

As for output, it prints all errors to console as well as to `ScanMsg.log` to make CI integration [bit easier](https://github.com/rotators/Fo1in2/blob/9ca02433ae5d4036c700c26a91b93b63d2e70087/.github/workflows/text.yml#L28-L38) (log exists = errors found, no log/log deleted = no known errors). App is very strict to "comments" right now (allows only `#`), but i'm going to add option to tolerate `;` and `//` shortly.

> any tests/scanners for other files or game resources

We make them as we go, so there's only ReDefine/ScanMsg (for now?).
From misc stuff, one of players made us [ini merger](https://gitlab.com/jalt-gl/mergeini.awk/) which we use to [automagically](https://github.com/rotators/Fo1in2/blob/9ca02433ae5d4036c700c26a91b93b63d2e70087/.github/workflows/schedule.yml#L364) merge sfall's ddraw.ini with [our settings](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/ddraw.fo1in2.ini). Small thing, but saves time when updating sfall, so yay.

**Comment by burner1024** [comment]
> [Source](https://github.com/wipe2238/ScanMsg/), with [binary-mirror](https://github.com/rotators/Fo1in2/tree/master/Tools/ScanMsg/) in FO1@2 repo. It simply looks for all `*.msg` in current dir and all subdirectories. Alternatively, you can run `exe path\to\check` but it might be little buggy, i'll get to that when i find time.

Thanks. Crashes under wine, though, so I guess it'll have to wait.

> From misc stuff, one of players made us [ini merger](https://gitlab.com/jalt-gl/mergeini.awk/) which we use to [automagically](https://github.com/rotators/Fo1in2/blob/9ca02433ae5d4036c700c26a91b93b63d2e70087/.github/workflows/schedule.yml#L364) merge sfall's ddraw.ini with [our settings](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/ddraw.fo1in2.ini). Small thing, but saves time when updating sfall, so yay.

Holy crap, that's some impressive wheel reinvention. I just use [crudini](https://github.com/pixelb/crudini).

**Comment by wipe2238** [comment]
> Holy crap, that's some impressive wheel reinvention

Oh well, what's done is done ;)

> Crashes under wine, though, so I guess it'll have to wait.

OK, so i added .NET5 project plus some Linux-specific guards (directory on disk mounted as read-only, missing read permissions for .msg, some path issues); while everything was tested with `dotnet`, fixes should allow to run whole thing via `wine`/`mono` as well.
Pick your poison.

From new stuff, i added duplication check for message id 0; it's not ignored by engine as i though, and should be checked as everything else (see https://pastebin.com/SiZLNjQM) plus `--relaxed` switch to allow non-`#` comments (and maybe

- `dotnet run --project ScanMsg/ScanMsg.NET5.csproj`
  `wine ScanMsg.exe`
  check files in current dir and subdirs
- `dotnet run --project ScanMsg/ScanMsg.NET5.csproj -- --relaxed`
  `wine ScanMsg.exe --relaxed`
  check files in current dir and subdirs, allow `//` and `;` comments
- `dotnet run --project ScanMsg/ScanMsg.NET5.csproj -- path/to/dir/`
  `wine ScanMsg.exe path/to/dir/`
  check files in `path/to/dir/` and subdirs
- `dotnet run --project ScanMsg/ScanMsg.NET5.csproj -- path/to/dir/ --relaxed`
  `wine ScanMsg.exe path/to/dir/ --relaxed`
  check files in `path/to/dir/` and subdirs, allow `//` and `;` comments

(PS: `dotnet run` includes compilation)

https://docs.microsoft.com/en-us/dotnet/core/install/linux

**Comment by burner1024** [comment]
Cool, how about exit codes? It seems it always returns 0.

**Comment by burner1024** [comment]
I'll try to integrate into CI, thanks!
